ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Reimbursement_Claims__c/Reimbursement_Claims__c.object-meta.xml
<CustomObject>
    <label>Reimbursement Claim</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Reimbursement_Claims__c/fields/Internal_Status__c.field-meta.xml
<CustomField>
    <fullName>Internal_Status__c</fullName>
    <description>Status of a reimbursement claim for internal use.</description>
    <label>Internal Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted For Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Sent To IMT</fullName>
            </value>
            <value>
                <fullName>Approved and Check Processed</fullName>
            </value>
            <value>
                <fullName>New Preapproval Request</fullName>
            </value>
            <value>
                <fullName>Waiting for Information</fullName>
            </value>
            <value>
                <fullName>Submitted for Preapproval</fullName>
            </value>
            <value>
                <fullName>Preapproval Rejected</fullName>
            </value>
            <value>
                <fullName>Preapproval Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Repository/Claims/force-app/main/default/classes/icTestReimbursementTriggerHandler.cls
@isTest
public class icTestReimbursementTriggerHandler {
    
    static testmethod void test_handleApprovementValidation(){
        
        Reimbursement_Claims__c newOne = new Reimbursement_Claims__c(Internal_Status__c = 'Approved');
        Reimbursement_Claims__c oldOne = new Reimbursement_Claims__c(Internal_Status__c = 'NotApproved');
        
    	icReimbursementTriggerHandler.IClass approvalValidationHandler = (icReimbursementTriggerHandler.IClass) icObjectFactory.GetSingletonInstance('icReimbursementTriggerHandler');
        
		Test.startTest();
        approvalValidationHandler.handleApprovementValidation(newOne, oldOne);
        
        Reimbursement_Claims__c testClaim = new Reimbursement_Claims__c();
        insert testClaim;
        update testClaim;
        Test.stopTest();
        
    }

}