ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Reimbursement_Claims__c/Reimbursement_Claims__c.object-meta.xml
<CustomObject>
    <label>Reimbursement Claim</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Reimbursement_Claims__c/fields/Internal_Status__c.field-meta.xml
<CustomField>
    <fullName>Internal_Status__c</fullName>
    <description>Status of a reimbursement claim for internal use.</description>
    <label>Internal Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted For Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Sent To IMT</fullName>
            </value>
            <value>
                <fullName>Approved and Check Processed</fullName>
            </value>
            <value>
                <fullName>New Preapproval Request</fullName>
            </value>
            <value>
                <fullName>Waiting for Information</fullName>
            </value>
            <value>
                <fullName>Submitted for Preapproval</fullName>
            </value>
            <value>
                <fullName>Preapproval Rejected</fullName>
            </value>
            <value>
                <fullName>Preapproval Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Reimbursement_Claims__c/fields/Net_Claim_Amount__c.field-meta.xml
<CustomField>
    <fullName>Net_Claim_Amount__c</fullName>
    <description>Amount Entered by Loyalty Admin at the time of Approval. This is the Amount that will be reimbursed to the Contractor.</description>
    <label>Net Reimbursable Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/icReimbursementTriggerHandler.cls
public class icReimbursementTriggerHandler implements icIClass{
    
     public Object GetInstance() {
        return new Impl();
    }

    public Interface IClass {
	
		void handleApprovementValidation(Reimbursement_Claims__c newReimbursement, Reimbursement_Claims__c oldReimbursement);
    }


    public class Impl implements IClass {
        
         public void handleApprovementValidation(Reimbursement_Claims__c newReimbursement, Reimbursement_Claims__c oldReimbursement){

			if(oldReimbursement.Internal_Status__c != 'Approved' && newReimbursement.Internal_Status__c == 'Approved' && newReimbursement.Net_Claim_Amount__c == null) {
            	newReimbursement.addError('TO APPROVE THIS CLAIM, PLEASE ENTER APPROVED AMOUNT ON CLAIM IN THE NET REIMBURSABLE AMOUNT.');
        	}

        }
        
    }


}