ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Building_Location.recordType-meta.xml
<RecordType>
    <fullName>Building_Location</fullName>
    <active>true</active>
    <description>Used to represent the location where a product is installed</description>
    <label>Building Location</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Contractor.recordType-meta.xml
<RecordType>
    <fullName>Contractor</fullName>
    <active>true</active>
    <label>Contractor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/US_Contractor.recordType-meta.xml
<RecordType>
    <fullName>US_Contractor</fullName>
    <active>true</active>
    <description>Contractor located in the US</description>
    <label>US Contractor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/US_Distributor.recordType-meta.xml
<RecordType>
    <fullName>US_Distributor</fullName>
    <active>true</active>
    <description>Distributors located in the US</description>
    <label>US Distributor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/Bidder__c.object-meta.xml
<CustomObject>
    <description>This object is a junction object between Opportinity, Account and Account, where Account references are of record type US Distributor  and record type US Contractor.</description>
    <label>Bidder</label>
    <nameField>
        <displayFormat>Bid-{000000}</displayFormat>
        <label>Bidder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Contractor_Account__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the Contractorfield must be of type Contractor or  type US Contractor.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bidders (Contractor)</relationshipLabel>
    <relationshipName>Opportunity_Distributor_Contractor</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Distributor_Account__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the Distributor field must be of type Distributor or  type US Distributor.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Distributor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bidders (Distributor)</relationshipLabel>
    <relationshipName>Opportunity_Distributor_Contractor1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Opportunity Record Type should be US Sales Bid</errorMessage>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Sales Bid</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bidders</relationshipLabel>
    <relationshipName>Opportunity_Distributor_Contractor</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/icTestUSSalesGeneratePDF_Email.cls
/**
 * Created by Anil Mannem (Incloud) on 25-Aug-2020
 */
@isTest
public with sharing class icTestUSSalesGeneratePDF_Email {
    static Id buildingLocationRecordTypeId;
    static Id distributorRecordTypeId;
    static Id contractorRecordTypeId;
    static Account testContractor;
    static Account testDistributor;
    static Opportunity testOpportunity;
    static Opportunity testOpportunity1;
    static User currentUser;

    static void CreateTestData(){
        currentUser = TestFactory.createUser('Unit', 'Test', 'sysAdminUsr@iko.com', 'sysAdminUsr@iko.com', 'System Administrator',
                'CEO', 'tsAdmU', 'GMT', 'en_US', 'UTF-8', 'en_US', 'United States', null, true);
        System.runAs(currentUser){
            buildingLocationRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Building_Location').getRecordTypeId();
            distributorRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('US_Distributor').getRecordTypeId();
            contractorRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('US_Contractor').getRecordTypeId();
            
            Account testBuildingLocation = new Account();
            testBuildingLocation.Name = ' Test Building Location';
            testBuildingLocation.RecordTypeId = buildingLocationRecordTypeId;
            insert testBuildingLocation;
            testOpportunity = icTestHelperDataCreator.generateOpportunityByRecordType('US Sales Bid', testBuildingLocation.Id);
            testOpportunity.Quote_Approved__c = true;
            insert testOpportunity;
            
            Account testBuildingLocation1 = new Account();
            testBuildingLocation1.Name = ' Test Building Location 1';
            testBuildingLocation1.RecordTypeId = buildingLocationRecordTypeId;
            insert testBuildingLocation1;
            testOpportunity1 = icTestHelperDataCreator.generateOpportunityByRecordType('US Sales Bid', testBuildingLocation1.Id);
            insert testOpportunity1;
    
            testDistributor = new Account();
            testDistributor.Name = 'Test Distributor';
            testDistributor.RecordTypeId = distributorRecordTypeId;
            insert testDistributor;
    
            testContractor = new Account();
            testContractor.Name = 'Test Contrator';
            testContractor.RecordTypeId = contractorRecordTypeId;
            insert testContractor;
        }
    }
    
    static testMethod void test_generatePDF_With_Contractor_and_Quote_Approved(){       
        CreateTestData();
        System.runAs(currentUser){
            // With Contractor and Quote Approved
            Bidder__c newBidder = new Bidder__c(Opportunity__c = testOpportunity.Id, Distributor_Account__c = testDistributor.Id, Contractor_Account__c = testContractor.Id);
            insert newBidder;
            Test.startTest();
            icUSSalesGeneratePDF_Email.generatePDFandEmail(newBidder.Id);
            Test.stopTest();            
        }
    }

    static testMethod void test_generatePDF_Without_Contractor_and_Quote_Approved(){       
        CreateTestData();
        System.runAs(currentUser){
            // Without Contractor and Quote Approved
            Bidder__c newBidder1 = new Bidder__c(Opportunity__c = testOpportunity.Id, Distributor_Account__c = testDistributor.Id);
            insert newBidder1;
            Test.startTest();
            icUSSalesGeneratePDF_Email.generatePDFandEmail(newBidder1.Id);
            Test.stopTest();
        }
    }

    static testMethod void test_generatePDF_Without_Contractor_and_Quote_not_Approved(){
        Test.startTest();
        CreateTestData();
        System.runAs(currentUser){
            // Without Contractor and Quote not Approved
            Bidder__c newBidder2 = new Bidder__c(Opportunity__c = testOpportunity1.Id, Distributor_Account__c = testDistributor.Id);
            insert newBidder2;
            icUSSalesGeneratePDF_Email.generatePDFandEmail(newBidder2.Id);
            Test.stopTest();
        }
    }
}