ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Contractor.recordType-meta.xml
<RecordType>
    <fullName>Contractor</fullName>
    <active>true</active>
    <label>Contractor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/Contractor_Invoice__c.object-meta.xml
<CustomObject>
    <label>Uploaded Invoice</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Uploaded Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>IKOPRO Contractor, IKOPRO Contractor HA OK</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Uploaded Invoices</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Uploaded_Files_Long__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_Files_Long__c</fullName>
    <label>Uploaded Files</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Rebate Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>IKOPRO Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/fields/Invoice_Year__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Year__c</fullName>
    <externalId>true</externalId>
    <label>Invoice Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/icTestREPOInvoice.cls
/**
 * Created by Andrea Pissinis on 2018-09-12.
 */
@isTest
public with sharing class icTestREPOInvoice {

    public static testMethod void test_getAllInvoicesByAccountIdAndDate(){

        icRepoInvoice.IClass repository = (icRepoInvoice.IClass) icObjectFactory.GetSingletonInstance('icRepoInvoice');

        Account contractor = icTestHelperUtility.generateContractorAccount();
        insert contractor;

        Invoice__c i = new Invoice__c();

        i.Contractor__c = contractor.Id;
        i.Invoice_Year__c = '2011';

        insert i;

        repository.getAllInvoicesByAccountIdAndDate(contractor.Id,'2011');

    }

    public static testMethod void test_getAllInvoicesByAccountIdsAndRebateYear() {
        icRepoInvoice.IClass repository = (icRepoInvoice.IClass) icObjectFactory.GetSingletonInstance('icRepoInvoice');

        List<Invoice__c> result = repository.getAllInvoicesByAccountIdsAndRebateYear(new List<String> {'test'}, '2019');
    }

    public static testMethod void test_getUploadedInvoiceById() {
        icRepoInvoice.IClass repository = (icRepoInvoice.IClass) icObjectFactory.GetSingletonInstance('icRepoInvoice');

        List<Contractor_Invoice__c> result = repository.getUploadedInvoiceById(new List<String> {'test'});
    }

    public static testMethod void test_updateInvoices() {
        icRepoInvoice.IClass repository = (icRepoInvoice.IClass) icObjectFactory.GetSingletonInstance('icRepoInvoice');

        Contractor_Invoice__c newUploadedInvoice = new Contractor_Invoice__c(Uploaded_Files_Long__c = 'test');
        insert newUploadedInvoice;

        newUploadedInvoice.Uploaded_Files_Long__c = 'test,test';
        repository.updateInvoices(new List<Contractor_Invoice__c> {newUploadedInvoice});
    }

}