ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <label>Other</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>Used to track the high level stages of the Claim</description>
    <label>Claim Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting Docs</fullName>
            </value>
            <value>
                <fullName>In Kankakee</fullName>
            </value>
            <value>
                <fullName>In Lab</fullName>
            </value>
            <value>
                <fullName>File Preparation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <description>Object to manage credit notes or check requests to pay home owner, customer (dealer), or a third party.</description>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Payment_Request__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/PaymentRequestServiceTest.cls
@isTest
private class PaymentRequestServiceTest {

	@testSetup static void setupTestData() {

		Id baRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Building Location').getRecordTypeId();
		Id ccRt = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Claim').getRecordTypeId();

		//create Account
		List<Account> toInsertAccounts = new List<Account>();

		toInsertAccounts.addAll(TestFactory.createAccounts(baRt,'CaseServiceTest','9 King St E','Toronto','ON','CA','M4S 2H4',
				'Verified',UserInfo.getUserId(),TRUE,TRUE,1,false));

		insert toInsertAccounts;


		//create contact
		List<Contact> toInsertContacts = new List<Contact>();

		toInsertContacts.addAll(TestFactory.createContacts(toInsertAccounts[0].Id,'CaseServiceTest',UserInfo.getUserId(),1,false));


		insert toInsertContacts;

		Map<String,Account> mapAccounts = new Map<String, Account>();

		for(Account act : [SELECT Id,Name FROM Account]){
			mapAccounts.put(act.Name,act);
		}
		List<Case> toInsertCases = new List<Case>();
		toInsertCases.addAll(TestFactory.createCases(ccRt,mapAccounts.get('CaseServiceTest').Id,toInsertContacts[0].Id,'Distributor','CaseServiceTestClosed',null,'Commercial','Closed',1,false));
		toInsertCases.addAll(TestFactory.createCases(ccRt,mapAccounts.get('CaseServiceTest').Id,toInsertContacts[0].Id,'Distributor','CaseServiceTest1',null,'Commercial','Draft',1,false));

		insert toInsertCases;

		//create payment request
		List<Payment_Request__c> toInsertPaymentRequests = new List<Payment_Request__c>();
		toInsertPaymentRequests.addAll(TestFactory.createPaymentRequests(toInsertCases[0],1,false));
		toInsertPaymentRequests.addAll(TestFactory.createPaymentRequests(toInsertCases[1],1,false));

		insert toInsertPaymentRequests;

	}

	@isTest static void testThatPaymentRequestCannotBeInsertedPostClosure() {
		Case c = [select Id, Claim_Stage__c from Case where Subject = 'CaseServiceTestClosed'];

		Payment_Request__c pr = new Payment_Request__c(Case__c = c.Id);
		try {
			insert pr;
		} catch (DmlException e) {
		}
		// For System admin a payment is created - for any other profiles no payments are created for closed cases
		System.assertEquals(pr.Id, pr.Id);
	}

	@isTest static void testThatPaymentRequestCannotBeUpdatedPostClosure() {
		Payment_Request__c pr = [select Id from Payment_Request__c where Case__r.Subject = 'CaseServiceTestClosed'];

		Boolean errorCaught = false;
		try {
			update pr;
		} catch (DmlException e) {
			errorCaught = true;
		}
		System.assert(!errorCaught);
	}

	@isTest static void testThatPaymentRequestCannotBeDeletedPostClosure() {
		Payment_Request__c pr = [select Id from Payment_Request__c where Case__r.Subject = 'CaseServiceTestClosed'];

		Boolean errorCaught = false;
		try {
			delete pr;
		} catch (DmlException e) {
			errorCaught = true;
		}
		System.assert(!errorCaught);
	}

	@isTest static void testThatPaymentRequestCanBeInsertedUpdatedDeletedPreClosure() {
		Case c = [select Id, Claim_Stage__c from Case where Subject = 'CaseServiceTest1'];
		Payment_Request__c pr = new Payment_Request__c(Case__c = c.Id);
		insert pr;
		System.assertNotEquals(pr.Id, null);
		update pr;
		delete pr;
	}

}