ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>Used to track the high level stages of the Claim</description>
    <label>Claim Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting Docs</fullName>
            </value>
            <value>
                <fullName>In Kankakee</fullName>
            </value>
            <value>
                <fullName>In Lab</fullName>
            </value>
            <value>
                <fullName>File Preparation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/Lab_Sample__c.object-meta.xml
<CustomObject>
    <label>Lab Sample</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Samples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A link to the Claim this lab sample is related to. Lab Samples with no links to a Claim have been received but not properly connected to a cliam.</description>
    <inlineHelpText>The Claim this Lab Sample relates to.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Lab Samples</relationshipLabel>
    <relationshipName>Lab_Samples</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>https://ikoussfsc.atlassian.net/browse/CLAIMSV2-358
Claims Stage</description>
    <formula>TEXT(Case__r.Claim_Stage__c)</formula>
    <inlineHelpText>Claims Stage</inlineHelpText>
    <label>Claim Stage</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Eligible_for_Approval_submission__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Approval_submission__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CLAIMS - 574. This field is populated by the LabTestResultTrigger only when all related LabTest Results are either in Completed or Not Required Status. This field will be used in the entry criteria for the LabSample approval process</description>
    <inlineHelpText>Signifies if Lab Sample is eligible for approval submission based on whether all related Lab Test Results are either in Completed or Not Required Status</inlineHelpText>
    <label>(Deprecated) Eligible for Approval</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <inlineHelpText>Used to generate the Sample Number; indicates the next record in the sequence for Country/Sector</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Test__c/Lab_Test__c.object-meta.xml
<CustomObject>
    <label>Lab Test</label>
    <nameField>
        <label>Lab Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Test__c/fields/Test_Description__c.field-meta.xml
<CustomField>
    <fullName>Test_Description__c</fullName>
    <label>Test Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Test__c/fields/Test_Reason__c.field-meta.xml
<CustomField>
    <fullName>Test_Reason__c</fullName>
    <label>Test Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Claim_Type_Reason</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Test_Result__c/Lab_Test_Result__c.object-meta.xml
<CustomObject>
    <description>This is to record lab test results for the Lab Sample.</description>
    <label>Lab Test Result</label>
    <nameField>
        <displayFormat>LTR-{0000000000}</displayFormat>
        <label>Lab Test Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Test Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Test_Result__c/fields/Lab_Sample__c.field-meta.xml
<CustomField>
    <fullName>Lab_Sample__c</fullName>
    <description>this is the lab sample that is tested.</description>
    <label>Lab Sample</label>
    <referenceTo>Lab_Sample__c</referenceTo>
    <relationshipLabel>Lab Test Results</relationshipLabel>
    <relationshipName>Lab_Test_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Test_Result__c/fields/Lab_Test__c.field-meta.xml
<CustomField>
    <fullName>Lab_Test__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This is the lab test that is to be run for the lab sample.</description>
    <label>Lab Test</label>
    <referenceTo>Lab_Test__c</referenceTo>
    <relationshipLabel>Lab Test Results</relationshipLabel>
    <relationshipName>Lab_Test_Results</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Test_Result__c/fields/Test_Result__c.field-meta.xml
<CustomField>
    <fullName>Test_Result__c</fullName>
    <description>This is the test result recorded by the lab tech</description>
    <label>Test Result</label>
    <length>131070</length>
    <type>Html</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Test_Result__c/fields/Test_Status__c.field-meta.xml
<CustomField>
    <fullName>Test_Status__c</fullName>
    <description>This is to indicate the progress of the lab test for the lab samples.</description>
    <label>Test Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/LabSampleTestResultServiceTest.cls
@isTest
private class LabSampleTestResultServiceTest {
	
	@testSetup static void setupTestData() {
		initTestData();
        insertLabTestResults();
	}


    private static void initTestData(){
        Id baRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Building Location').getRecordTypeId();
        Id ccRt = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Claim').getRecordTypeId();
        List<Account> toInsertAccounts = new List<Account>();

        toInsertAccounts.addAll(TestFactory.createAccounts(baRt,'CaseServiceTest','9 King St E','Toronto','ON','CA','M4S 2H4',
                'Verified',UserInfo.getUserId(),TRUE,TRUE,1,false));
        insert toInsertAccounts;
        
        //create contact
        List<Contact> con = TestFactory.createContacts(toInsertAccounts[0].Id,'LabSampleTapeCodeServiceTest',UserInfo.getUserId(),1,false);
        insert con;
        
        //create Cases
        List<Case> toInsertCases = new List<Case>();

        toInsertCases.addAll(TestFactory.createCases(ccRt,toInsertAccounts[0].Id,con[0].Id,'Owner','LabSampleTapeCodeServiceTest',null,'Commercial',null,1,false));
        toInsertCases.addAll(TestFactory.createCases(ccRt,toInsertAccounts[0].Id,con[0].Id,'Distributor',null,null,'Commercial',null,5,false));
        toInsertCases[1].Subject='CaseServiceTestClosed';
        toInsertCases[1].Claim_Stage__c='Closed';
        
        toInsertCases[2].Subject='CaseServiceTest1';
        
        toInsertCases[3].Subject='CaseServiceTest2';
        
        toInsertCases[4].Subject='CaseServiceTest3';
        
        toInsertCases[5].Subject='CaseServiceTest4';
        Insert toInsertCases;
        System.debug('toInsertCases: '+ toInsertCases);
        
        List<Lab_Sample__c> toInsertLabSamples = new List<Lab_Sample__c>();
        toInsertLabSamples.addAll(TestFactory.createLabSamples(toInsertCases[1], 5, false));
        toInsertLabSamples[1].Case__c=toInsertCases[2].Id;
        toInsertLabSamples[2].Case__c=toInsertCases[3].Id;
        toInsertLabSamples[3].Case__c=toInsertCases[4].Id;
        toInsertLabSamples[4].Case__c=toInsertCases[5].Id;
        Insert toInsertLabSamples;
        List<Lab_Sample__c> verifyLabSamples = [Select Case__r.Subject from Lab_Sample__c ];
        System.debug('verifyLabSamples[0]: '+verifyLabSamples[0].Case__r.Subject);
        
        List<Lab_Test__c> toInsertLabTests = new List<Lab_Test__c>();
        toInsertLabTests.addAll(TestFactory.createLabTests('Blistering', 'alpha', 1, false));   
        toInsertLabTests.addAll(TestFactory.createLabTests('Blistering', 'beta', 1, false)); 
        Insert toInsertLabTests;
    }
    
	@future
    static void insertLabTestResults(){
        List<Lab_Sample__c> labSamples = [select Id, Case__r.Subject from Lab_Sample__c ];
        System.debug('labSamples: '+labSamples.size());
        List<Lab_Test__c> labTests = [Select Id, Test_Reason__c, Test_Description__c from Lab_Test__c];
        List<Lab_Test_Result__c> toInsertLabTestResults = new List<Lab_Test_Result__c>();
        toInsertLabTestResults.addAll(TestFactory.createlabTestResults(labSamples[1], labTests[0], 1, false));
        toInsertLabTestResults.addAll(TestFactory.createlabTestResults(labSamples[2], labTests[1], 1, false));
        toInsertLabTestResults.addAll(TestFactory.createlabTestResults(labSamples[3], labTests[1], 1, false));
        toInsertLabTestResults.addAll(TestFactory.createlabTestResults(labSamples[4], labTests[0], 1, false));
        Insert toInsertLabTestResults;
    }    
	@isTest static void testThatLabTestResultCannotBeInsertedPostClosure() {
        System.debug('All sample results: '+[Select Count(Id) from Lab_Sample__c]);
		Lab_Sample__c ls 			= [select Id, Case__c from Lab_Sample__c where Case__r.Subject = 'CaseServiceTestClosed'];
		Case c = [Select Id, Claim_Stage__c from Case where Id = :ls.Case__c LIMIT 1];
        c.Claim_Stage__c='Closed';
        Update c;
        
		Lab_Test_Result__c lstc 	= new Lab_Test_Result__c(Lab_Sample__c = ls.Id);
		try {
			insert lstc;
		} catch(DmlException e) { }
		System.assertEquals(lstc.Id, null);
	}

	@isTest static void testThatLabTestResultCannotBeUpdatedPostClosure() {
        
        Lab_Test_Result__c lstc = [Select Id,Lab_Sample__c from Lab_Test_Result__c where Lab_Sample__r.Case__r.Subject = 'CaseServiceTest3' LIMIT 1];
		//Lab_Sample__c ls 			= [select Id, Case__c from Lab_Sample__c where Case__r.Subject = 'CaseServiceTestClosed'];
		Case c = [Select Id, Claim_Stage__c from Case where Subject = 'CaseServiceTest3' LIMIT 1];
        c.Claim_Stage__c='Closed';
        Update c;
        Test.startTest();
		Boolean errorCaught = false;
		try {
			update lstc;
		} catch(DmlException e) { 
			errorCaught = true;
		}
		System.assert(errorCaught);
        Test.stopTest();
	}

	@isTest static void testThatLabTestResultCannotBeDeletedPostClosure() {
		Lab_Test_Result__c lstc = [select Id from Lab_Test_Result__c where Lab_Sample__r.Case__r.Subject = 'CaseServiceTest2'];
		Case c = [Select Id, Claim_Stage__c from Case where Subject = 'CaseServiceTest2' LIMIT 1];
        c.Claim_Stage__c='Closed';
        Update c;
        
		Boolean errorCaught 		= false;
		try {
			delete lstc;
		} catch(DmlException e) { 
			errorCaught 			= true;
		}
		System.assert(errorCaught);
	}

	@isTest static void testThatLabTestResultCanBeInsertedUpdatedDeletedPreClosure() {
		Case c 			= [select Id, Claim_Stage__c from Case where Subject = 'CaseServiceTest1'];

		Lab_Test__c lt1 	= [select Id from Lab_Test__c where Test_Reason__c = 'Blistering' limit 1];

		Test.startTest();
		Lab_Sample__c ls	= new Lab_Sample__c(Case__c = c.Id);
		insert ls;

		Lab_Test_Result__c lstc 	= new Lab_Test_Result__c(Lab_Sample__c = ls.Id, Lab_Test__c = lt1.Id);
		insert lstc;

		System.assertNotEquals(lstc.Id, null);

		update lstc;
		delete lstc;
		Test.stopTest();
	}

	@isTest static void testUpdateStatusAccordingToTestResult_UpdateTestStatusWhenTestResultIsBlank_TestStatusUpdatedToNew(){

		Case c 	= [SELECT Id, Claim_Stage__c FROM Case WHERE Subject = 'CaseServiceTest1'];

		Lab_Test__c lt1 = [SELECT Id FROM Lab_Test__c WHERE Test_Reason__c = 'Blistering' LIMIT 1];


		Test.startTest();
		Lab_Sample__c ls = new Lab_Sample__c(Case__c = c.Id);
		insert ls;

		Lab_Test_Result__c lstc = new Lab_Test_Result__c(Lab_Sample__c = ls.Id, Lab_Test__c = lt1.Id,Test_Result__c = '');
		insert lstc;
		Test.stopTest();


		Lab_Test_Result__c expectedTestResult = [SELECT Test_Status__c FROM Lab_Test_Result__c WHERE Id = :lstc.Id];

		//assert
		System.assertEquals(expectedTestResult.Test_Status__c,'New');
	}

	@isTest static void testUpdateStatusAccordingToTestResult_UpdateTestStatusWhenTestResultIsNotBlank_TestStatusUpdatedToCompleted(){

		Case c 	= [SELECT Id, Claim_Stage__c FROM Case WHERE Subject = 'CaseServiceTest1'];

		Lab_Test__c lt1 = [SELECT Id FROM Lab_Test__c WHERE Test_Reason__c = 'Blistering' LIMIT 1];

		Test.startTest();
		Lab_Sample__c ls = new Lab_Sample__c(Case__c = c.Id);
		insert ls;

		Lab_Test_Result__c lstc = new Lab_Test_Result__c(Lab_Sample__c = ls.Id, Lab_Test__c = lt1.Id,Test_Status__c = 'New');
		insert lstc;

		lstc.Test_Result__c = 'Test Result';
		update lstc;
		Test.stopTest();


		Lab_Test_Result__c expectedTestResult = [SELECT Test_Status__c FROM Lab_Test_Result__c WHERE Id = :lstc.Id];

		//assert
		System.assertEquals(expectedTestResult.Test_Status__c,'Completed');
	}

	@isTest
	public static void testCountCompletedAndNotRequiredTestResultsForLabSample_checkEligibleForApprovalOnLabSample_OnInsertNotCompleted(){
		Case c 	= [SELECT Id, Claim_Stage__c FROM Case WHERE Subject = 'CaseServiceTest1'];

		Lab_Test__c lt1 = [SELECT Id FROM Lab_Test__c WHERE Test_Reason__c = 'Blistering' LIMIT 1];

		Test.startTest();
		Lab_Sample__c ls = new Lab_Sample__c(Sequence_Number__c = 1111111,Case__c = c.Id);
		insert ls;

		Lab_Test_Result__c lstc = new Lab_Test_Result__c(Lab_Sample__c = ls.Id, Lab_Test__c = lt1.Id,Test_Status__c = 'New');
		insert lstc;
		Test.stopTest();

		ls = [SELECT Eligible_for_Approval_submission__c FROM Lab_Sample__c WHERE Sequence_Number__c = 1111111];

		System.assert(!ls.Eligible_for_Approval_submission__c);
	}

	@isTest
	public static void testCountCompletedAndNotRequiredTestResultsForLabSample_checkEligibleForApprovalOnLabSample_OnInsertCompleted(){
		Case c 	= [SELECT Id, Claim_Stage__c FROM Case WHERE Subject = 'CaseServiceTest1'];

		Lab_Test__c lt1 = [SELECT Id FROM Lab_Test__c WHERE Test_Reason__c = 'Blistering' LIMIT 1];

		Test.startTest();
		Lab_Sample__c ls = new Lab_Sample__c(Sequence_Number__c = 1111111,Case__c = c.Id);
		insert ls;

		Lab_Test_Result__c lstc = new Lab_Test_Result__c(Lab_Sample__c = ls.Id, Lab_Test__c = lt1.Id,Test_Status__c = 'Completed');
		insert lstc;
		Test.stopTest();

		ls = [SELECT Eligible_for_Approval_submission__c FROM Lab_Sample__c WHERE Sequence_Number__c = 1111111];

		System.assert(ls.Eligible_for_Approval_submission__c);
	}

	@isTest
	public static void testCountCompletedAndNotRequiredTestResultsForLabSample_checkEligibleForApprovalOnLabSample_OnUpdateNotRequired(){
		Case c 	= [SELECT Id, Claim_Stage__c FROM Case WHERE Subject = 'CaseServiceTest1'];

		Lab_Test__c lt1 = [SELECT Id FROM Lab_Test__c WHERE Test_Reason__c = 'Blistering' LIMIT 1];

		Test.startTest();
		Lab_Sample__c ls = new Lab_Sample__c(Sequence_Number__c = 1111111,Case__c = c.Id);
		insert ls;

		Lab_Test_Result__c lstc = new Lab_Test_Result__c(Lab_Sample__c = ls.Id, Lab_Test__c = lt1.Id,Test_Status__c = 'Completed');
		insert lstc;

		lstc.Test_Status__c = 'Not Required';
		update lstc;
		Test.stopTest();

		ls = [SELECT Eligible_for_Approval_submission__c FROM Lab_Sample__c WHERE Sequence_Number__c = 1111111];

		System.assert(ls.Eligible_for_Approval_submission__c);
	}

	@isTest
	public static void testCountCompletedAndNotRequiredTestResultsForLabSample_checkEligibleForApprovalOnLabSample_OnUpdateNotCompleted(){
		Case c 	= [SELECT Id, Claim_Stage__c FROM Case WHERE Subject = 'CaseServiceTest1'];

		Lab_Test__c lt1 = [SELECT Id FROM Lab_Test__c WHERE Test_Reason__c = 'Blistering' LIMIT 1];

		Test.startTest();
		Lab_Sample__c ls = new Lab_Sample__c(Sequence_Number__c = 1111111,Case__c = c.Id);
		insert ls;

		Lab_Test_Result__c lstc = new Lab_Test_Result__c(Lab_Sample__c = ls.Id, Lab_Test__c = lt1.Id,Test_Status__c = 'New');
		insert lstc;

		lstc.Test_Status__c = 'In Progress';
		update lstc;
		Test.stopTest();

		ls = [SELECT Eligible_for_Approval_submission__c FROM Lab_Sample__c WHERE Sequence_Number__c = 1111111];

		System.assert(!ls.Eligible_for_Approval_submission__c);
	}

	@isTest
	public static void testCountCompletedAndNotRequiredTestResultsForLabSample_checkEligibleForApprovalOnLabSample_OnDeleteNotCompleted(){
		Case c 	= [SELECT Id, Claim_Stage__c FROM Case WHERE Subject = 'CaseServiceTest1'];

		Lab_Test__c lt1 = [SELECT Id FROM Lab_Test__c WHERE Test_Reason__c = 'Blistering' LIMIT 1];

		Test.startTest();
		Lab_Sample__c ls = new Lab_Sample__c(Sequence_Number__c = 1111111,Case__c = c.Id);
		insert ls;

		Lab_Test_Result__c lstc = new Lab_Test_Result__c(Lab_Sample__c = ls.Id, Lab_Test__c = lt1.Id,Test_Status__c = 'New');
		insert lstc;

		Lab_Test_Result__c lstc1 = new Lab_Test_Result__c(Lab_Sample__c = ls.Id, Lab_Test__c = lt1.Id,Test_Status__c = 'Completed');
		insert lstc1;

		delete lstc1;
		Test.stopTest();

		ls = [SELECT Eligible_for_Approval_submission__c FROM Lab_Sample__c WHERE Sequence_Number__c = 1111111];

		System.assert(!ls.Eligible_for_Approval_submission__c);
	}

	@isTest
	public static void testCountCompletedAndNotRequiredTestResultsForLabSample_checkEligibleForApprovalOnLabSample_OnDeleteCompleted(){
		Case c 	= [SELECT Id, Claim_Stage__c FROM Case WHERE Subject = 'CaseServiceTest1'];

		Lab_Test__c lt1 = [SELECT Id FROM Lab_Test__c WHERE Test_Reason__c = 'Blistering' LIMIT 1];

		Test.startTest();
		Lab_Sample__c ls = new Lab_Sample__c(Sequence_Number__c = 1111111,Case__c = c.Id);
		insert ls;

		Lab_Test_Result__c lstc = new Lab_Test_Result__c(Lab_Sample__c = ls.Id, Lab_Test__c = lt1.Id,Test_Status__c = 'New');
		insert lstc;

		Lab_Test_Result__c lstc1 = new Lab_Test_Result__c(Lab_Sample__c = ls.Id, Lab_Test__c = lt1.Id,Test_Status__c = 'Completed');
		insert lstc1;

		delete lstc;
		Test.stopTest();

		ls = [SELECT Eligible_for_Approval_submission__c FROM Lab_Sample__c WHERE Sequence_Number__c = 1111111];

		System.assert(ls.Eligible_for_Approval_submission__c);
	}
}