ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/Lab_Sample__c.object-meta.xml
<CustomObject>
    <label>Lab Sample</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Samples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A link to the Claim this lab sample is related to. Lab Samples with no links to a Claim have been received but not properly connected to a cliam.</description>
    <inlineHelpText>The Claim this Lab Sample relates to.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Lab Samples</relationshipLabel>
    <relationshipName>Lab_Samples</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/PRM_Comment__c/PRM_Comment__c.object-meta.xml
<CustomObject>
    <description>https://ikoussfsc.atlassian.net/browse/CLAIMSV2-66
Capture the Plant Reporting Module (PRM) comments by Plant Team.</description>
    <label>PRM Comment</label>
    <nameField>
        <displayFormat>PRMComment-{00000}</displayFormat>
        <label>PRM Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRM Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/PRM_Comment__c/fields/Lab_Sample__c.field-meta.xml
<CustomField>
    <fullName>Lab_Sample__c</fullName>
    <description>https://ikoussfsc.atlassian.net/browse/CLAIMSV2-66
Master Details Relationship with Lab Sample</description>
    <inlineHelpText>Link PRM Comment to Lab Sample</inlineHelpText>
    <label>Lab Sample</label>
    <referenceTo>Lab_Sample__c</referenceTo>
    <relationshipLabel>PRM Comments</relationshipLabel>
    <relationshipName>PRM_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/PRM_Comment__c/fields/Plant_Manager__c.field-meta.xml
<CustomField>
    <fullName>Plant_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CLAIMS - 626. Populated with Plant Manager&apos;s user id to be used in approval proces</description>
    <label>Plant Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PRM_Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/PRM_Comment__c/fields/PRM_Approval_Submitter__c.field-meta.xml
<CustomField>
    <fullName>PRM_Approval_Submitter__c</fullName>
    <description>CLAIMS - 626. Populated by the initial actions of the PRM Approval process</description>
    <label>PRM Approval Submitter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/PRMCommentServiceTest.cls
@isTest
public class PRMCommentServiceTest {
private static void createUsers(){

        List<User> toInsertUsers = new List<User>();

            toInsertUsers.add(TestFactory.createUser('Unit','Tests','plantMgr@iko.com','plantMgr@iko.com','Plant Manager',
                    'Plant','plant','GMT','en_US','UTF-8','en_US',null,null,false));        

        insert toInsertUsers;

    }
    
    @testSetup static void setupTestData(){
        Id baRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Building Location').getRecordTypeId();
        Id ccRt = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Claim').getRecordTypeId();
        
        List<Account> a = TestFactory.createAccounts(baRt,'CaseServiceTest','9 King St E','Toronto','ON','CA','M4S 2H4','Verified',UserInfo.getUserId(),TRUE,TRUE,1,true);
        List<Contact> con = TestFactory.createContacts(a[0].Id,'CaseServiceTest',UserInfo.getUserId(),1,true);
        
        List<Case> cases = TestFactory.createCases(ccRt,a[0].Id,con[0].Id,'Distributor','CaseServiceTest',null,'Commercial','Draft',1,true);
        TestFactory.createClaimTypes(cases[0],1,true);
     	TestFactory.createLabSamples(cases[0],1,true);
    }
    
    @isTest
    public static void testPopulateAssigneeForPlantManagerApproval(){
       createUsers();
        User runningUser = [SELECT Id, Profile.Name FROM User WHERE UserName = 'plantMgr@iko.com'];
        Lab_Sample__c ls = [SELECT Id FROM Lab_Sample__c WHERE Case__r.Subject = 'CaseServiceTest'];  
        
        Test.startTest();
        System.runAs(runningUser){
            PRM_Comment__c prmComment = new PRM_Comment__c(Lab_Sample__c = ls.Id);
            insert prmComment;
            
            prmComment.PRM_Approval_Submitter__c = 'Plant Manager';
            update prmComment;
        }      
        Test.stopTest();
        
        PRM_Comment__c prmCommentResult = [SELECT Id,Plant_Manager__c FROM PRM_Comment__c WHERE Lab_Sample__c = :ls.Id];
        System.assertEquals(runningUser.Id, prmCommentResult.Plant_Manager__c);
        
    }
}