ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/All_Claim_Photos_Attached__c.field-meta.xml
<CustomField>
    <fullName>All_Claim_Photos_Attached__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that all photos required for the Claim are attached</description>
    <inlineHelpText>By checking this, you are confirming that all necessary photos for submitting this claim are attached to the Case</inlineHelpText>
    <label>All Claim Photos Attached?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Distributor for a Residential or Commercial Claim</description>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Residential Account, Distributor, US Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Legacy_Claim_Account__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Distributor Cases</relationshipLabel>
    <relationshipName>DistributorCases</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Job_In_Progress__c.field-meta.xml
<CustomField>
    <fullName>Job_In_Progress__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Used to indicate that this claim is for a Job In Progress, to aid in setting priority</inlineHelpText>
    <label>Job In Progress</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Leaking__c.field-meta.xml
<CustomField>
    <fullName>Leaking__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates that this is related to a leaking issue, and will be used for prioritization</inlineHelpText>
    <label>Leaking?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product related to the Residential/Commercial Claim</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Is_Legacy__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Product2.Sectors_Text__c</field>
            <operation>contains</operation>
            <valueField>$Source.Sector__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Samples_Collected__c.field-meta.xml
<CustomField>
    <fullName>Samples_Collected__c</fullName>
    <description>Used to indicate if Samples were collected for a Claim; using a Yes/No picklist instead of Boolean to make this field required</description>
    <label>Samples Collected?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Type_of_Structure__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Structure__c</fullName>
    <inlineHelpText>Type of Structure/Building where the product is installed</inlineHelpText>
    <label>Type of Structure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Barn</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Garage</fullName>
            </value>
            <value>
                <fullName>Manufact Home</fullName>
            </value>
            <value>
                <fullName>Multi-Unit</fullName>
            </value>
            <value>
                <fullName>Residence</fullName>
            </value>
            <value>
                <fullName>Shed</fullName>
            </value>
            <value>
                <fullName>(none)</fullName>
                <isActive>false</isActive>
                <label>(none)</label>
            </value>
            <value>
                <fullName>Residence Shed</fullName>
                <isActive>false</isActive>
                <label>Residence Shed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/Claim_Type__c.object-meta.xml
<CustomObject>
    <description>Used to capture the Primary and Secondary reason for the Claim Case</description>
    <label>Claim Type</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Claim Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icTestRepoCase.cls
/**
 * Created by Anil Mannem (Incloud) on 28-July-2020
 */
@isTest
public with sharing class icTestRepoCase {

    static void setupTestData() {
        Id baRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Building Location').getRecordTypeId();
        Id ccRt = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Claim').getRecordTypeId();
        Id daRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Distributor').getRecordTypeId();

        //create Account
        // Order of Parameters
        // recordTypeId, accountName, bStreet, bCity, bStateCode, bCountryCode, bPostalCode, AddVerifiedStatus, ownerId, Boolean nmVerificationStatus, Boolean actVerifiedStatus, numOfAccounts, isInsert
        List<Account> toInsertAccounts = new List<Account>();
		
        toInsertAccounts.addAll(TestFactory.createAccounts(baRt, 'CaseServiceTest', '9 King St E', 'Toronto', 'ON', 'CA', 'M4S 2H4',
                'Verified', UserInfo.getUserId(), TRUE, TRUE, 1, false));
        toInsertAccounts.addAll(TestFactory.createAccounts(daRt, 'Slalom Distribution', '8 King St E', 'Toronto', 'ON', 'CA', 'M4S 2H4',
                'Verified', UserInfo.getUserId(), TRUE, TRUE, 1, false));
        toInsertAccounts.addAll(TestFactory.createAccounts(daRt, 'CaseServiceTestNewYork', '9 King St E', 'New York', 'NY', 'US', '99899',
                'Verified', UserInfo.getUserId(), TRUE, TRUE, 1, false));
        toInsertAccounts.addAll(TestFactory.createAccounts(baRt, 'CaseServiceTestQuebec', '9 King St E', 'Montreal', 'QC', 'CA', 'M4S 2H4',
                'Verified', UserInfo.getUserId(), TRUE, TRUE, 1, false));
        toInsertAccounts.addAll(TestFactory.createAccounts(baRt, 'CaseServiceTestQuebec2', '69 King St E', 'Montreal', 'QC', 'CA', 'M4S 2H4',
                'Verified', UserInfo.getUserId(), TRUE, TRUE, 1, false));
        toInsertAccounts.addAll(TestFactory.createAccounts(baRt, 'ClaimNumber', '19 King St E', 'Toronto', 'ON', 'CA', 'M4S 2H4',
                'Verified', UserInfo.getUserId(), TRUE, TRUE, 1, false));
        toInsertAccounts.addAll(TestFactory.createAccounts(baRt, 'CaseServiceTestWashington', '9 King St E', 'Seattle', 'WA', 'US', '12111',
                'Verified', UserInfo.getUserId(), TRUE, TRUE, 1, false));

        insert toInsertAccounts;

        //create contact
        List<Contact> toInsertContacts = new List<Contact>();

        toInsertContacts.addAll(TestFactory.createContacts(toInsertAccounts[0].Id, 'CaseServiceTest', UserInfo.getUserId(), 1, false));
        toInsertContacts.addAll(TestFactory.createContacts(toInsertAccounts[1].Id, 'CaseServiceTestAccount', UserInfo.getUserId(), 1, false));
        toInsertContacts.addAll(TestFactory.createContacts(toInsertAccounts[0].Id, 'CaseServiceTestForQueue', UserInfo.getUserId(), 1, false));

        insert toInsertContacts;

        Map<String, Account> mapAccounts = new Map<String, Account>();

        for (Account act : [SELECT Id,Name FROM Account]) {
            mapAccounts.put(act.Name, act);
        }

        //create products
        List<Product2> toInsertProducts = new List<Product2>();
        toInsertProducts.addAll(TestFactory.createProducts('IkoSampleProduct', TRUE, 'IkoSampleProduct', 'US;CA;Commercial;Blair', null, 1, false));

        insert toInsertProducts;

        //create Cases
        List<Case> toInsertCases = new List<Case>();

        toInsertCases.addAll(TestFactory.createCases(ccRt, mapAccounts.get('CaseServiceTest').Id, toInsertContacts[0].Id, 'Distributor', 'CaseServiceTestClosed', null, 'Commercial', 'Closed', 1, false));
        toInsertCases.addAll(TestFactory.createCases(ccRt, mapAccounts.get('CaseServiceTest').Id, toInsertContacts[0].Id, 'Distributor', 'CaseServiceTest', null, 'Commercial', 'Draft', 1, false));
        toInsertCases.addAll(TestFactory.createCases(ccRt, mapAccounts.get('CaseServiceTest').Id, toInsertContacts[0].Id, 'Distributor', 'CaseServiceTest1', null, 'Commercial', 'Draft', 1, false));
        toInsertCases.addAll(TestFactory.createCases(ccRt, mapAccounts.get('CaseServiceTestNewYork').Id, toInsertContacts[0].Id, 'Distributor', 'CaseServiceNewYork', date.newInstance(2006, 5, 5), 'Commercial', 'Draft', 1, false));
        toInsertCases.addAll(TestFactory.createCases(ccRt, mapAccounts.get('CaseServiceTestQuebec').Id, toInsertContacts[0].Id, 'Distributor', 'CaseServiceQuebec', date.newInstance(2006, 5, 5), 'Commercial', 'Draft', 1, false));
        toInsertCases.addAll(TestFactory.createCases(ccRt, mapAccounts.get('CaseServiceTestQuebec2').Id, toInsertContacts[0].Id, 'Distributor', 'CaseServiceQuebec2', date.newInstance(2016, 5, 5), 'Commercial', 'Draft', 1, false));

        toInsertCases.addAll(TestFactory.createCases(ccRt, mapAccounts.get('CaseServiceTestWashington').Id, toInsertContacts[0].Id, 'Distributor', 'CaseServiceWashington', date.newInstance(2006, 5, 5), 'US', 'Draft', 1, false));

        List<Case> c1 = TestFactory.createCases(ccRt, mapAccounts.get('ClaimNumber').Id, toInsertContacts[0].Id, 'Owner', 'ClaimNumberCase', null, 'CA', null, 1, false);
        c1[0].Job_In_Progress__c = TRUE;
        c1[0].Leaking__c = TRUE;
        toInsertCases.addAll(c1);

        List<Case> c2 = TestFactory.createCases(ccRt, mapAccounts.get('CaseServiceTest').Id, toInsertContacts[0].Id, 'Distributor', 'CaseServiceTest2', null, 'Commercial', 'Draft', 1, false);

        c2[0].Origin = 'Owner';
        c2[0].Samples_Collected__c = 'Not Required';
        c2[0].All_Claim_Photos_Attached__c = true;
        c2[0].Distributor__c = mapAccounts.get('Slalom Distribution').Id;
        c2[0].Product__c = toInsertProducts[0].Id;
        c2[0].Type_Of_Structure__c = 'Barn';
        c2[0].OwnerId = UserInfo.getUserId();

        Database.DMLOptions dmo = new Database.DMLOptions();
        dmo.assignmentRuleHeader.useDefaultRule = true;
        c2[0].setOptions(dmo);

        toInsertCases.addAll(c2);

        List<Case> c3 = TestFactory.createCases(ccRt, mapAccounts.get('CaseServiceTest').Id, toInsertContacts[0].Id, 'Owner', 'CaseServiceTestSubmitted', null, 'US', 'Draft', 1, false);
        c3[0].Samples_Collected__c = 'Not Required';
        c3[0].All_Claim_Photos_Attached__c = TRUE;
        c3[0].Product__c = toInsertProducts[0].Id;
        c3[0].Type_of_Structure__c = 'Barn';
        toInsertCases.addAll(c3);

        insert toInsertCases;

        //create Claim type
        List<Claim_Type__c> toInsertClaimTypes = new List<Claim_Type__c>();
        toInsertClaimTypes.addAll(TestFactory.createClaimTypes(toInsertCases[0], 1, false));
        toInsertClaimTypes.addAll(TestFactory.createClaimTypes(toInsertCases[1], 1, false));
        toInsertClaimTypes.addAll(TestFactory.createClaimTypes(toInsertCases[2], 1, false));
        toInsertClaimTypes.addAll(TestFactory.createClaimTypes(toInsertCases[3], 1, false));
        toInsertClaimTypes.addAll(TestFactory.createClaimTypes(toInsertCases[4], 1, false));
        toInsertClaimTypes.addAll(TestFactory.createClaimTypes(toInsertCases[5], 1, false));
        toInsertClaimTypes.addAll(TestFactory.createClaimTypes(toInsertCases[6], 1, false));
        toInsertClaimTypes.addAll(TestFactory.createClaimTypes(toInsertCases[7], 1, false));
        toInsertClaimTypes.addAll(TestFactory.createClaimTypes(toInsertCases[8], 1, false));
        toInsertClaimTypes.addAll(TestFactory.createClaimTypes(toInsertCases[9], 1, false));

        insert toInsertClaimTypes;
    }

	/**
	 * Ticket ClaimsV2-931
	 * By Anil Mannem (Incloud) on 28-July-2020
	 */
    @isTest
    static void testGetCaseById () {
        icRepoCase.IClass repository = (icRepoCase.IClass) icObjectFactory.GetSingletonInstance('icRepoCase');
        setupTestData();
        List<Case> caseList = repository.getCaseById(new Set<String>{''});
    }
}