ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/All_Claim_Photos_Attached__c.field-meta.xml
<CustomField>
    <fullName>All_Claim_Photos_Attached__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that all photos required for the Claim are attached</description>
    <inlineHelpText>By checking this, you are confirming that all necessary photos for submitting this claim are attached to the Case</inlineHelpText>
    <label>All Claim Photos Attached?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Distributor for a Residential or Commercial Claim</description>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Residential Account, Distributor, US Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Legacy_Claim_Account__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Distributor Cases</relationshipLabel>
    <relationshipName>DistributorCases</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product related to the Residential/Commercial Claim</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Is_Legacy__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Product2.Sectors_Text__c</field>
            <operation>contains</operation>
            <valueField>$Source.Sector__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Samples_Collected__c.field-meta.xml
<CustomField>
    <fullName>Samples_Collected__c</fullName>
    <description>Used to indicate if Samples were collected for a Claim; using a Yes/No picklist instead of Boolean to make this field required</description>
    <label>Samples Collected?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Type_of_Structure__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Structure__c</fullName>
    <inlineHelpText>Type of Structure/Building where the product is installed</inlineHelpText>
    <label>Type of Structure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Barn</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Garage</fullName>
            </value>
            <value>
                <fullName>Manufact Home</fullName>
            </value>
            <value>
                <fullName>Multi-Unit</fullName>
            </value>
            <value>
                <fullName>Residence</fullName>
            </value>
            <value>
                <fullName>Shed</fullName>
            </value>
            <value>
                <fullName>(none)</fullName>
                <isActive>false</isActive>
                <label>(none)</label>
            </value>
            <value>
                <fullName>Residence Shed</fullName>
                <isActive>false</isActive>
                <label>Residence Shed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/Contractor_Invoice__c.object-meta.xml
<CustomObject>
    <label>Uploaded Invoice</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Uploaded Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <label>Distributor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Uploaded_Files_Long__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_Files_Long__c</fullName>
    <label>Uploaded Files</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icTesthandlerContentVersion.cls
/**
 * Created by Anil Mannem on 27-Aug-2020.
 */

@isTest
public with sharing class icTesthandlerContentVersion {

    @isTest
    public static void testOnAfterInsert(){
        Test.startTest();
	    Contractor_Invoice__c newUploadedInvoice = new Contractor_Invoice__c(Uploaded_Files_Long__c = 'test');
        insert newUploadedInvoice;
        
        ContentVersion testVersion = new ContentVersion();
        testVersion.Title = 'Test';
        testVersion.PathOnClient = 'test.jpg';
        testVersion.VersionData = Blob.valueOf('test content Data');
        testVersion.IsMajorVersion = true;
        testVersion.FirstPublishLocationId = newUploadedInvoice.Id;
        insert testVersion;
        
        testVersion.Title = 'TestUpdate';
        update testVersion;
        
        Test.stopTest();
    }

    @isTest(SeeAllData=true)
    public static void testOnBeforeUpdate(){
        Test.startTest();
	    
        Profile p = [SELECT Id FROM Profile WHERE Name='CARS Sales Rep'];
        User u = new User(Alias = 'standt', Email='testuser@iko.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles',
         UserName='testuser@iko.com');
 
        System.runAs(u) {
            Id baRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Building Location').getRecordTypeId();
            Id ccRt = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Claim').getRecordTypeId();
            Id daRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Distributor').getRecordTypeId();
    
            //create Account
            // Order of Parameters
            // recordTypeId, accountName, bStreet, bCity, bStateCode, bCountryCode, bPostalCode, AddVerifiedStatus, ownerId, Boolean nmVerificationStatus, Boolean actVerifiedStatus, numOfAccounts, isInsert
            List<Account> toInsertAccounts = new List<Account>();		
            toInsertAccounts.addAll(TestFactory.createAccounts(baRt, 'CaseServiceTest', '9 King St E', 'Toronto', 'ON', 'CA', 'M4S 2H4',
                    'Verified', UserInfo.getUserId(), TRUE, TRUE, 1, false));
            toInsertAccounts.addAll(TestFactory.createAccounts(daRt, 'Slalom Distribution', '8 King St E', 'Toronto', 'ON', 'CA', 'M4S 2H4',
                'Verified', UserInfo.getUserId(), TRUE, TRUE, 1, false));
        	insert toInsertAccounts;
    
            //create contact
            List<Contact> toInsertContacts = new List<Contact>();
            toInsertContacts.addAll(TestFactory.createContacts(toInsertAccounts[0].Id, 'CaseServiceTest', UserInfo.getUserId(), 1, false));
            insert toInsertContacts;
            Map<String, Account> mapAccounts = new Map<String, Account>();
            for (Account act : [SELECT Id,Name FROM Account]) {
                mapAccounts.put(act.Name, act);
            }
            //create products
            List<Product2> toInsertProducts = new List<Product2>();
            toInsertProducts.addAll(TestFactory.createProducts('IkoSampleProduct', TRUE, 'IkoSampleProduct', 'US;CA;Commercial;Blair', null, 1, false));
            insert toInsertProducts;

            //create Cases
            List<Case> toInsertCases = new List<Case>();
            toInsertCases.addAll(TestFactory.createCases(ccRt, mapAccounts.get('CaseServiceTest').Id, toInsertContacts[0].Id, 'Distributor', 'CaseServiceTestClosed', null, 'Commercial', 'Draft', 1, false));
            toInsertCases[0].Origin = 'Owner';
			toInsertCases[0].Samples_Collected__c = 'Not Required';
            toInsertCases[0].All_Claim_Photos_Attached__c = true;
            toInsertCases[0].Distributor__c = mapAccounts.get('Slalom Distribution').Id;
            toInsertCases[0].Product__c = toInsertProducts[0].Id;
            toInsertCases[0].Type_Of_Structure__c = 'Barn';
            toInsertCases[0].OwnerId = UserInfo.getUserId();
            insert toInsertCases;

            ContentVersion testVersion = new ContentVersion();
            testVersion.Title = 'Test';
            testVersion.PathOnClient = 'test.jpg';
            testVersion.VersionData = Blob.valueOf('test content Data');
            testVersion.IsMajorVersion = true;
            testVersion.FirstPublishLocationId = toInsertCases[0].Id;
            insert testVersion;                
        }
        Test.stopTest();
        
    }
}