ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>Used to track the high level stages of the Claim</description>
    <label>Claim Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting Docs</fullName>
            </value>
            <value>
                <fullName>In Kankakee</fullName>
            </value>
            <value>
                <fullName>In Lab</fullName>
            </value>
            <value>
                <fullName>File Preparation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Sub_Stage__c</fullName>
    <label>Claim Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Claim_Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting POP</fullName>
            </value>
            <value>
                <fullName>POP Received</fullName>
            </value>
            <value>
                <fullName>Additional POP Required</fullName>
            </value>
            <value>
                <fullName>Initial review</fullName>
            </value>
            <value>
                <fullName>HOIS sent</fullName>
            </value>
            <value>
                <fullName>Awaiting HOIS</fullName>
            </value>
            <value>
                <fullName>Awaiting Samples</fullName>
            </value>
            <value>
                <fullName>Samples Received</fullName>
            </value>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Data Entry</fullName>
            </value>
            <value>
                <fullName>Info Required</fullName>
            </value>
            <value>
                <fullName>Info Requested</fullName>
            </value>
            <value>
                <fullName>Goodwill review</fullName>
            </value>
            <value>
                <fullName>In review</fullName>
            </value>
            <value>
                <fullName>Release Pending</fullName>
            </value>
            <value>
                <fullName>Waiting for Invoice</fullName>
            </value>
            <value>
                <fullName>Check/Credit Requested</fullName>
            </value>
            <value>
                <fullName>Check/Credit Approved</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Goodwill Requested</fullName>
            </value>
            <value>
                <fullName>Goodwill Rejected</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Samples Sent to Lab</fullName>
            </value>
            <value>
                <fullName>Dealer Invoice Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/Claim_Type__c.object-meta.xml
<CustomObject>
    <description>Used to capture the Primary and Secondary reason for the Claim Case</description>
    <label>Claim Type</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Claim Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Related Claim Case</description>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Case must be a Residential or Commercial Claim</errorMessage>
        <filterItems>
            <field>Case.RecordType.Name</field>
            <operation>contains</operation>
            <value>Claim</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Claim Types</relationshipLabel>
    <relationshipName>Claim_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/Lab_Sample__c.object-meta.xml
<CustomObject>
    <label>Lab Sample</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Samples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A link to the Claim this lab sample is related to. Lab Samples with no links to a Claim have been received but not properly connected to a cliam.</description>
    <inlineHelpText>The Claim this Lab Sample relates to.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Lab Samples</relationshipLabel>
    <relationshipName>Lab_Samples</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>https://ikoussfsc.atlassian.net/browse/CLAIMSV2-358
Claims Stage</description>
    <formula>TEXT(Case__r.Claim_Stage__c)</formula>
    <inlineHelpText>Claims Stage</inlineHelpText>
    <label>Claim Stage</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Claim_Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Sub_Stage__c</fullName>
    <description>https://ikoussfsc.atlassian.net/browse/CLAIMSV2-358
Claim Sub Stage</description>
    <formula>Text( Case__r.Claim_Sub_Stage__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Claim Sub Stage</inlineHelpText>
    <label>Claim Sub Stage</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample_Tape_Code__c/Lab_Sample_Tape_Code__c.object-meta.xml
<CustomObject>
    <description>This allows users to associate the tape codes with the lab samples</description>
    <label>Sample Description</label>
    <nameField>
        <displayFormat>LSTC - {000000000}</displayFormat>
        <label>Lab Sample Tape Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample_Tape_Code__c/fields/Lab_Sample__c.field-meta.xml
<CustomField>
    <fullName>Lab_Sample__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the lab sample the record is related to</description>
    <label>Lab Sample</label>
    <referenceTo>Lab_Sample__c</referenceTo>
    <relationshipName>Lab_Sample_Tape_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Settlement_Condition__c/Settlement_Condition__c.object-meta.xml
<CustomObject>
    <description>Used to capture Settlement Conditions against a Claim Case</description>
    <label>Settlement Condition</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Settlement Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Settlement_Condition__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Settlement Condition to be leveraged in offer letters</description>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Commercial Claim, Residential Claim</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Settlement Conditions</relationshipLabel>
    <relationshipName>Settlement_Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Settlement_Condition__c/fields/Condition_Template__c.field-meta.xml
<CustomField>
    <fullName>Condition_Template__c</fullName>
    <description>Used to select default text of condition</description>
    <label>Condition Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Ventilation must be upgraded....</fullName>
            </value>
            <value>
                <fullName>2. Extended downspouts to direct....</fullName>
            </value>
            <value>
                <fullName>3. Soffit ventilation must be cleared...</fullName>
            </value>
            <value>
                <fullName>4. Deck must be repaired...</fullName>
            </value>
            <value>
                <fullName>5. New shingles must be installed ...</fullName>
            </value>
            <value>
                <fullName>Free entry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Repository/Claims/force-app/main/default/classes/SettlementConditionServiceTest.cls
@isTest
private class SettlementConditionServiceTest {

    private static void getNonSysAdminUser(){
        TestFactory.createUser('UnitClaim', 'TestsClaim', 'claimsManagerUsr@iko.com', 'claimsManagerUsr@iko.com', 'Claims Manager',
                'Claims Manager', 'tclu', 'GMT', 'en_US', 'UTF-8', 'en_US', 'United States', null, true);
    }

    @testSetup static void setupTestData() {

        Id baRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Building Location').getRecordTypeId();
        Id ccRt = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Claim').getRecordTypeId();

        //create Account
        List<Account> toInsertAccounts = new List<Account>();

        toInsertAccounts.addAll(TestFactory.createAccounts(baRt,'CaseServiceTest','9 King St E','Toronto','ON','CA','M4S 2H4',
                'Verified',UserInfo.getUserId(),TRUE,TRUE,1,false));

        insert toInsertAccounts;


        //create contact
        List<Contact> toInsertContacts = new List<Contact>();

        toInsertContacts.addAll(TestFactory.createContacts(toInsertAccounts[0].Id,'CaseServiceTest',UserInfo.getUserId(),1,false));

        insert toInsertContacts;

        Map<String,Account> mapAccounts = new Map<String, Account>();

        for(Account act : [SELECT Id,Name FROM Account]){
            mapAccounts.put(act.Name,act);
        }


        //create Cases
        List<Case> toInsertCases = new List<Case>();
        toInsertCases.addAll(TestFactory.createCases(ccRt,mapAccounts.get('CaseServiceTest').Id,toInsertContacts[0].Id,'Distributor','CaseServiceTestClosed',null,'Commercial','Closed',1,false));
        toInsertCases.addAll(TestFactory.createCases(ccRt,mapAccounts.get('CaseServiceTest').Id,toInsertContacts[0].Id,'Distributor','CaseServiceTest1',null,'Commercial','Draft',1,false));

        toInsertCases.addAll(TestFactory.createCases(ccRt,mapAccounts.get('CaseServiceTest').Id,toInsertContacts[0].Id,'Distributor','CaseServiceTest1Copy',null,'Commercial','Draft',1,false));

        List<Case> cases = TestFactory.createCases(ccRt,mapAccounts.get('CaseServiceTest').Id,toInsertContacts[0].Id,'Distributor','CaseServiceTestWithInApprovalClaim',null,'Commercial','Assessment',1,false);
        cases[0].Claim_Sub_Stage__c = 'In Approval';
        toInsertCases.addAll(cases);

        insert toInsertCases;

        Lab_Sample__c ls = new Lab_Sample__c(Case__c = toInsertCases[2].Id);
        insert ls;

        Lab_Sample_Tape_Code__c lstc = new Lab_Sample_Tape_Code__c(Lab_Sample__c = ls.Id);
        insert lstc;

        Settlement_Condition__c sc = new Settlement_Condition__c(Case__c = toInsertCases[2].Id, Condition_Template__c = '1. Ventilation must be upgraded....');
        Settlement_Condition__c ct1 = new Settlement_Condition__c(Case__c = toInsertCases[0].Id, Condition_Template__c = '1. Ventilation must be upgraded....');
        insert new List<Settlement_Condition__c>{
            sc,ct1
        };

        Claim_Type__c ct = new Claim_Type__c(Case__c = toInsertCases[2].Id);
        insert ct;

    }
    @isTest static void testThatSettlementConditionCannotBeInsertedPostClosure() {
        getNonSysAdminUser();
        Case c = [select Id, Claim_Stage__c from Case where Subject = 'CaseServiceTestClosed'];
        User u = [SELECT Id FROM User WHERE Username = 'claimsManagerUsr@iko.com'];
        Settlement_Condition__c ct = new Settlement_Condition__c(Case__c = c.Id);
        String error = '';
        Test.startTest();
        try {
            System.runAs(u){
                insert ct;
            }
        } catch (DmlException e) {
            error = e.getMessage();
        }
        Test.stopTest();
        System.assertEquals(ct.Id, ct.Id);
    }

    @isTest static void testThatSettlementConditionCannotBeInsertedWhenStatusNotClosed() {
        getNonSysAdminUser();
        Case c = [select Id, Claim_Stage__c from Case where Subject = 'CaseServiceTestWithInApprovalClaim'];
        User u = [SELECT Id FROM User WHERE Username = 'claimsManagerUsr@iko.com'];
        Settlement_Condition__c ct = new Settlement_Condition__c(Case__c = c.Id);
        String error = '';
        Test.startTest();
        try {
            System.runAs(u){
                insert ct;
            }
        } catch (DmlException e) {
            error = e.getMessage();
        }
        Test.stopTest();
        System.assertNotEquals(error,'');
    }

    @isTest static void testThatSettlementConditionCannotBeUpdatedPostClosure() {
        getNonSysAdminUser();
        Case c = [select Id, Claim_Stage__c from Case where Subject = 'CaseServiceTestClosed'];
        User u = [SELECT Id FROM User WHERE Username = 'claimsManagerUsr@iko.com'];
        Settlement_Condition__c ct = [select Id from Settlement_Condition__c where Case__r.Subject = 'CaseServiceTestClosed'];

        System.runAs(u){
            Test.startTest();
            Boolean errorCaught = false;
            try {
                update ct;
            } catch (DmlException e) {
                errorCaught = true;
            }
            Test.stopTest();
            System.assert(errorCaught);
        }

    }

    @isTest static void testThatSettlementConditionCanBeUpdatedBySysAdminPostClosure() {
        Settlement_Condition__c ct = [select Id from Settlement_Condition__c where Case__r.Subject = 'CaseServiceTestClosed'];
        Test.startTest();
        Boolean errorCaught = false;
        try {
                update ct;
        } catch (DmlException e) {
            errorCaught = true;
        }
        Test.stopTest();
        System.assert(!errorCaught);
    }

    @isTest static void testThatSettlementConditionCannotBeDeletedPostClosure() {
        getNonSysAdminUser();
        User u = [SELECT Id FROM User WHERE Username = 'claimsManagerUsr@iko.com'];
        Settlement_Condition__c ct = [select Id from Settlement_Condition__c where Case__r.Subject = 'CaseServiceTestClosed'];

        System.runAs(u){
            Test.startTest();
            Boolean errorCaught = false;
            try {
                delete ct;
            } catch (DmlException e) {
                errorCaught = true;
            }
            Test.stopTest();
            System.assert(errorCaught);
        }

    }

    @isTest static void testThatSettlementConditionCanBeInsertedUpdatedDeletedPreClosure() {
        Case c = [select Id, Claim_Stage__c from Case where Subject = 'CaseServiceTest1'];

        Test.startTest();
        Settlement_Condition__c ct = new Settlement_Condition__c(Case__c = c.Id);
        insert ct;

        System.assertNotEquals(ct.Id, null);

        update ct;

        delete ct;
        Test.stopTest();
    }


}