ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Legacy_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Legacy_External_ID__c</fullName>
    <description>This is to identify and retain the WCMS system reference ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>Legacy Claim Number from WCMS</inlineHelpText>
    <label>Legacy Claim Number</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/Lab_Sample__c.object-meta.xml
<CustomObject>
    <label>Lab Sample</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Samples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A link to the Claim this lab sample is related to. Lab Samples with no links to a Claim have been received but not properly connected to a cliam.</description>
    <inlineHelpText>The Claim this Lab Sample relates to.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Lab Samples</relationshipLabel>
    <relationshipName>Lab_Samples</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Case_Description__c.field-meta.xml
<CustomField>
    <fullName>Case_Description__c</fullName>
    <description>CLAIMS - 77. Field to hold the related case description</description>
    <inlineHelpText>Related Case&apos;s description</inlineHelpText>
    <label>Case Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Id of record from legacy (WCMS) system</inlineHelpText>
    <label>Legacy Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/UpdateLegacyLabSampleRecordsTest.cls
/**
 * Created by sinan.bunni on 2019-11-15.
 */
@IsTest
private class UpdateLegacyLabSampleRecordsTest {

    @TestSetup
    static void setup() {
        Id baRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Building Location').getRecordTypeId();
        Id ccRt = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Claim').getRecordTypeId();

        //create Account
        List<Account> toInsertAccounts = new List<Account>();
        toInsertAccounts.addAll(TestFactory.createAccounts(baRt, 'CaseServiceTest', '9 King St E', 'Toronto', 'ON', 'CA', 'M4S 2H4',
                'Verified', UserInfo.getUserId(), TRUE, TRUE, 1, false));
        insert toInsertAccounts;

        //create contact
        List<Contact> toInsertContacts = new List<Contact>();
        toInsertContacts.addAll(TestFactory.createContacts(toInsertAccounts[0].Id, 'CaseServiceTest', UserInfo.getUserId(), 1, false));
        insert toInsertContacts;
		
        Case testCase = new Case();
        testCase = TestFactory.createCases(ccRt, toInsertAccounts.get(0).Id, toInsertContacts[0].Id, 'Distributor',
                'CaseServiceTest', null, 'Commercial', 'Draft', 1, false).get(0);
        testCase.Legacy_External_ID__c = '11111';
        testCase.Description = 'testbatch';
        insert testCase;

        Lab_Sample__c labSample = new Lab_Sample__c(Legacy_Id__c = '11111', Case__c = testCase.Id);
        insert labSample;

    } // end setup

    private static testMethod void execute_ValidLegacyLabSample_PopulateCaseDescriptionField() {

        Test.startTest();
        Id batchId = Database.executeBatch(new UpdateLegacyLabSampleRecords());
        Test.stopTest();

        // assert the data
        Integer count = 0;
        for (Lab_Sample__c labSample : [SELECT Case_Description__c FROM Lab_Sample__c]) {
            if (labSample.Case_Description__c != NULL) {
                count++;
            }
        }

        // System.assertEquals(1, count, 'Expected 1 updated Lab Sample records.');

    }

} // end UpdateLegacyLabSampleRecordsTest class