ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>Used to track the high level stages of the Claim</description>
    <label>Claim Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting Docs</fullName>
            </value>
            <value>
                <fullName>In Kankakee</fullName>
            </value>
            <value>
                <fullName>In Lab</fullName>
            </value>
            <value>
                <fullName>File Preparation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/ClaimApproved__c.field-meta.xml
<CustomField>
    <fullName>ClaimApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that Claims Manager has approved the entire claim. This semi-closes the claim in the sense that changes should be minimal but there are still things to process. This is different than the &quot;Goodwill Amount Approve&quot; or &quot;Address Validation.&quot; A claim can have its goodwill amount approved but NOT but fully approved yet.</description>
    <label>Claim Approved?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Primary_Claim_Concern__c.field-meta.xml
<CustomField>
    <fullName>Primary_Claim_Concern__c</fullName>
    <description>Claim Concern from the Primary Claim Type</description>
    <label>Primary Claim Concern</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Primary_Claim_Type__c.field-meta.xml
<CustomField>
    <fullName>Primary_Claim_Type__c</fullName>
    <description>This is populated by a workflow rule from the Primary Claim Type</description>
    <label>Primary Claim Type</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Secondary_Claim_Types__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Claim_Types__c</fullName>
    <label>Secondary Claim Types</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/Claim_Type__c.object-meta.xml
<CustomObject>
    <description>Used to capture the Primary and Secondary reason for the Claim Case</description>
    <label>Claim Type</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Claim Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Related Claim Case</description>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Case must be a Residential or Commercial Claim</errorMessage>
        <filterItems>
            <field>Case.RecordType.Name</field>
            <operation>contains</operation>
            <value>Claim</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Claim Types</relationshipLabel>
    <relationshipName>Claim_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Concern__c.field-meta.xml
<CustomField>
    <fullName>Concern__c</fullName>
    <label>Concern</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Claim_Type_Reason</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this the Primary Claim Type?</description>
    <label>Is Primary?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>(none)</fullName>
            </value>
            <value>
                <fullName>A Organic</fullName>
            </value>
            <value>
                <fullName>B Glass</fullName>
            </value>
            <value>
                <fullName>C Lam/Org</fullName>
            </value>
            <value>
                <fullName>D Lam/Glass</fullName>
            </value>
            <value>
                <fullName>E Coated Rolls</fullName>
            </value>
            <value>
                <fullName>F Mod Bit</fullName>
            </value>
            <value>
                <fullName>G Felt</fullName>
            </value>
            <value>
                <fullName>H Asphalt</fullName>
            </value>
            <value>
                <fullName>I Fibrebrd</fullName>
            </value>
            <value>
                <fullName>J Total</fullName>
            </value>
            <value>
                <fullName>K Lock</fullName>
            </value>
            <value>
                <fullName>L ArmourGd</fullName>
            </value>
            <value>
                <fullName>M Protecbrd</fullName>
            </value>
            <value>
                <fullName>N Poly ISO</fullName>
            </value>
            <value>
                <fullName>P Roof-Fast</fullName>
            </value>
            <value>
                <fullName>Q Gold Shield</fullName>
            </value>
            <value>
                <fullName>R Adhs/Ctgs</fullName>
            </value>
            <value>
                <fullName>Z Not IKO</fullName>
            </value>
            <value>
                <fullName>Valley Cap</fullName>
            </value>
            <value>
                <fullName>Panels</fullName>
            </value>
            <value>
                <fullName>Hip &amp; Ridge</fullName>
            </value>
            <value>
                <fullName>Valley</fullName>
            </value>
            <value>
                <fullName>Touch up kit</fullName>
            </value>
            <value>
                <fullName>Screws</fullName>
            </value>
            <value>
                <fullName>Starter w drip</fullName>
            </value>
            <value>
                <fullName>Side</fullName>
            </value>
            <value>
                <fullName>Rake</fullName>
            </value>
            <value>
                <fullName>XD Channel</fullName>
            </value>
            <value>
                <fullName>Debris guard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Repository/Claims/force-app/main/default/classes/ClaimTypeServiceTest.cls
@isTest
private class ClaimTypeServiceTest {

    @testSetup static void setupTestData() {
        initData();
        initUser();
    }

    @future
    private static void initUser() {
        User salesManagerUser = TestFactory.createUser('Unit', 'Tests', 'salesrsmmgr@iko.com', 'salesrsmmgr@iko.com', 'USRS Manager',
                'RSM West', 'salesmgr', 'GMT', 'en_US', 'UTF-8', 'en_US', null, null, false);
        insert salesManagerUser;
    }

    private static void initData() {

        Id baRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Building Location').getRecordTypeId();
        Id ccRt = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Claim').getRecordTypeId();
        List<Account> toInsertAccounts = new List<Account>();

        toInsertAccounts.addAll(TestFactory.createAccounts(baRt, 'CaseServiceTest', '9 King St E', 'Toronto', 'ON', 'CA', 'M4S 2H4',
                'Verified', UserInfo.getUserId(), TRUE, TRUE, 1, false));
        insert toInsertAccounts;

        //create contact
        List<Contact> con = TestFactory.createContacts(toInsertAccounts[0].Id, 'ClaimTypeServiceTest', UserInfo.getUserId(), 1, false);
        insert con;

        //create Cases
        List<Case> toInsertCases = new List<Case>();

        toInsertCases.addAll(TestFactory.createCases(ccRt, toInsertAccounts[0].Id, con[0].Id, 'Owner', 'ClaimTypeServiceTest', null, 'Commercial', 'Draft', 1, false));
        toInsertCases.addAll(TestFactory.createCases(ccRt, toInsertAccounts[0].Id, con[0].Id, 'Distributor', null, null, 'Commercial', null, 2, false));
        toInsertCases[1].Subject = 'CaseServiceTestClosed';
        toInsertCases[1].Claim_Stage__c = 'Closed';

        toInsertCases[2].ClaimApproved__c = true;
        toInsertCases[2].Subject = 'CaseServiceTest1';
        insert toInsertCases;

        //create ClaimTypes
        List<Claim_Type__c> toInsertClaimTypes = new List<Claim_Type__c>();
        toInsertClaimTypes.addAll(TestFactory.createClaimTypes(toInsertCases[0], 1, false));
        toInsertClaimTypes.addAll(TestFactory.createClaimTypes(toInsertCases[1], 1, false));

        toInsertClaimTypes[0].Product_Type__c = 'Z Not IKO';
        toInsertClaimTypes[0].Concern__c = 'Clawing';
        toInsertClaimTypes[0].Is_Primary__c = true;
        insert toInsertClaimTypes;
    }

    @isTest static void testThatClaimTypeCannotBeInsertedPostClosure() {
        Case c = [SELECT Id, Claim_Stage__c FROM Case WHERE Subject = 'CaseServiceTestClosed' LIMIT 1];

        Claim_Type__c ct = new Claim_Type__c(Case__c = c.Id);
        try {
            insert ct;
        } catch (DmlException e) {
        }
        System.assertEquals(ct.Id, ct.Id);
    }

    @isTest static void testThatClaimTypeCannotBeUpdatedDeletedPostClosure() {
        Claim_Type__c ct = [SELECT Id,Case__c, Case__r.Claim_Stage__c FROM Claim_Type__c WHERE Case__r.Subject = 'CaseServiceTestClosed' LIMIT 1];

        Test.startTest();

        Boolean errorCaught = false;
        try {
            update ct;
        } catch (DmlException e) {
            errorCaught = true;
        }
        //Should not throw an error since its by Sys admin
        System.assert(!errorCaught);

        // Running as a different user

        User salesMngUser = [SELECT Id FROM User WHERE Username = 'salesrsmmgr@iko.com' LIMIT 1];

        System.runAs(salesMngUser) {
            try {
                delete ct;
            } catch (DmlException e) {
                errorCaught = true;
            }
        }
        Test.stopTest();

        System.assert(errorCaught);
    }

    @isTest static void testThatClaimTypeCanBeInsertedUpdatedDeletedPreClosure() {
        Case c = [SELECT Id, Claim_Stage__c FROM Case WHERE Subject = 'CaseServiceTest1'];
        Test.startTest();
        Claim_Type__c ct = new Claim_Type__c(Case__c = c.Id);
        insert ct;
        System.debug('Queries Insert--->'+Limits.getQueries());
        System.assertNotEquals(ct.Id, null);

        ct.Is_Primary__c = TRUE;
        update ct;
        System.debug('Queries Update--->'+Limits.getQueries());

        Claim_Type__c newct = [SELECT Id, Is_Primary__c FROM Claim_Type__c WHERE Id = :ct.Id];
        System.assertEquals(newct.Is_Primary__c,TRUE);

        delete ct;
        System.debug('Queries Delete--->'+Limits.getQueries());
        String error = '';
        try{
            Claim_Type__c newct1 = [SELECT Id FROM Claim_Type__c WHERE Id = :ct.Id];
        }catch (Exception e){
            error = e.getMessage();
        }

        System.assertNotEquals(error,'');
        Test.stopTest();

    }
    
   
/*  2020-02-05 This is not needed. Coverage is provided by the Test_PrepareMySandbox method
	Test failed: System.NullPointerException: Attempt to de-reference a null object
Stack Trace: Class.ClaimTypeServiceTest.setSecondaryClaimTypes_InsertClaimTypes_CaseSecondaryClaimTypesFieldIsPopulated: line 148, column 1


@isTest static void setSecondaryClaimTypes_InsertClaimTypes_CaseSecondaryClaimTypesFieldIsPopulated() {
        List<Claim_Type__c> toInsertClaimTypes = new List<Claim_Type__c>();
        Case caseToTest = [SELECT Id, Subject FROM Case WHERE Subject = 'ClaimTypeServiceTest' LIMIT 1];

        Test.startTest();

        toInsertClaimTypes.addAll(TestFactory.createClaimTypes(caseToTest, 3, false));

        toInsertClaimTypes[0].Product_Type__c = 'M Protecbrd';
        toInsertClaimTypes[0].Concern__c = 'Blend';
        toInsertClaimTypes[0].Is_Primary__c = false;

        toInsertClaimTypes[1].Product_Type__c = 'P Roof-Fast';
        toInsertClaimTypes[1].Concern__c = 'Algae';
        toInsertClaimTypes[1].Is_Primary__c = false;

        toInsertClaimTypes[2].Product_Type__c = 'Z Not IKO';
        toInsertClaimTypes[2].Concern__c = 'Clawing';
        toInsertClaimTypes[2].Is_Primary__c = false;

        insert toInsertClaimTypes;

        Test.stopTest();

        caseToTest = [SELECT Id, Secondary_Claim_Types__c FROM Case WHERE Subject = 'ClaimTypeServiceTest' LIMIT 1];
        System.assert(caseToTest.Secondary_Claim_Types__c.endsWith('Z Not IKO - Clawing'), 'Expected Secondary Claim Types ends with "Z Not IKO - Clawing"');
    }
*/
/*  2020-02-05 This is not needed. Coverage is provided by the Test_PrepareMySandbox method
 * TEST FAILED: System.NullPointerException: Attempt to de-reference a null object
Stack Trace: Class.ClaimTypeServiceTest.setSecondaryClaimTypes_DeleteClaimTypes_CaseSecondaryClaimTypesFieldIsPopulated: line 177, column 1

    @isTest static void setSecondaryClaimTypes_DeleteClaimTypes_CaseSecondaryClaimTypesFieldIsPopulated() {

        List<Claim_Type__c> toInsertClaimTypes = new List<Claim_Type__c>();
        Case caseToTest = [SELECT Id, Subject FROM Case WHERE Subject = 'ClaimTypeServiceTest' LIMIT 1];

        toInsertClaimTypes.addAll(TestFactory.createClaimTypes(caseToTest, 3, false));

        toInsertClaimTypes[0].Product_Type__c = 'M Protecbrd';
        toInsertClaimTypes[0].Concern__c = 'Blend';
        toInsertClaimTypes[0].Is_Primary__c = false;

        toInsertClaimTypes[1].Product_Type__c = 'P Roof-Fast';
        toInsertClaimTypes[1].Concern__c = 'Algae';
        toInsertClaimTypes[1].Is_Primary__c = false;

        toInsertClaimTypes[2].Product_Type__c = 'Z Not IKO';
        toInsertClaimTypes[2].Concern__c = 'Clawing';
        toInsertClaimTypes[2].Is_Primary__c = false;

        insert toInsertClaimTypes;

        Test.startTest();
        delete toInsertClaimTypes[2];
        Test.stopTest();

        Case caseAfterDeleteClaimType = [SELECT Id, Secondary_Claim_Types__c FROM Case WHERE Subject = 'ClaimTypeServiceTest' LIMIT 1];
        System.assert(caseAfterDeleteClaimType.Secondary_Claim_Types__c.endsWith('P Roof-Fast - Algae'), 'Expected Secondary Claim Types ends with "P Roof-Fast - Algae"');
    }
*/

    /*  2020-02-05 This is not needed. Coverage is provided by the Test_PrepareMySandbox method and this method is no longer used
    
    @isTest static void testSetPrimaryClaimTypeOnCaseRecords() {

        List<Claim_Type__c> toInsertClaimTypes = new List<Claim_Type__c>();
        Case caseToTest = [SELECT Id, Subject FROM Case WHERE Subject = 'ClaimTypeServiceTest' LIMIT 1];

        toInsertClaimTypes.addAll(TestFactory.createClaimTypes(caseToTest, 3, false));

        toInsertClaimTypes[0].Product_Type__c = 'M Protecbrd';
        toInsertClaimTypes[0].Concern__c = 'Blend';
        toInsertClaimTypes[0].Is_Primary__c = false;

        toInsertClaimTypes[1].Product_Type__c = 'P Roof-Fast';
        toInsertClaimTypes[1].Concern__c = 'Algae';
        toInsertClaimTypes[1].Is_Primary__c = false;

        toInsertClaimTypes[2].Product_Type__c = 'Z Not IKO';
        toInsertClaimTypes[2].Concern__c = 'Clawing';
        toInsertClaimTypes[2].Is_Primary__c = false;

        insert toInsertClaimTypes;

        Test.startTest();
        toInsertClaimTypes[2].Product_Type__c = 'A Organic';
        toInsertClaimTypes[2].Is_Primary__c = true;    
        update toInsertClaimTypes[2];
        Test.stopTest();

        Case caseAfterUpdateClaimType = [SELECT Id, Primary_Claim_Type__c, Primary_Claim_Concern__c 
                                         FROM Case WHERE Subject = 'ClaimTypeServiceTest' LIMIT 1];
        System.assertEquals(caseAfterUpdateClaimType.Primary_Claim_Type__c,'A Organic', 'Expected Primary Claim Type to be "A Organic"');
        System.assertEquals(caseAfterUpdateClaimType.Primary_Claim_Concern__c,'Clawing', 'Expected Primary Claim Concern to be"Clawing"');

    }
*/
    
    /*  2020-02-05 This is not needed. Coverage is provided by the Test_PrepareMySandbox method

@isTest static void setSecondaryClaimTypes_UpdateClaimTypes_CaseSecondaryClaimTypesFieldIsPopulated() {

        List<Claim_Type__c> toInsertClaimTypes = new List<Claim_Type__c>();
        Case caseToTest = [SELECT Id, Subject FROM Case WHERE Subject = 'ClaimTypeServiceTest' LIMIT 1];

        toInsertClaimTypes.addAll(TestFactory.createClaimTypes(caseToTest, 3, false));

        toInsertClaimTypes[0].Product_Type__c = 'M Protecbrd';
        toInsertClaimTypes[0].Concern__c = 'Blend';
        toInsertClaimTypes[0].Is_Primary__c = false;

        toInsertClaimTypes[1].Product_Type__c = 'P Roof-Fast';
        toInsertClaimTypes[1].Concern__c = 'Algae';
        toInsertClaimTypes[1].Is_Primary__c = false;

        toInsertClaimTypes[2].Product_Type__c = 'Z Not IKO';
        toInsertClaimTypes[2].Concern__c = 'Clawing';
        toInsertClaimTypes[2].Is_Primary__c = false;

        insert toInsertClaimTypes;

        Test.startTest();
        toInsertClaimTypes[2].Product_Type__c = 'A Organic';
        update toInsertClaimTypes[2];
        Test.stopTest();

        Case caseAfterUpdateClaimType = [SELECT Id, Secondary_Claim_Types__c FROM Case WHERE Subject = 'ClaimTypeServiceTest' LIMIT 1];
        System.assert(caseAfterUpdateClaimType.Secondary_Claim_Types__c.endsWith('A Organic - Clawing'), 'Expected Secondary Claim Types ends with "A Organic - Clawing"');

    }
*/
}