ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Bundle_Rate__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Rate__c</fullName>
    <defaultValue>20</defaultValue>
    <description>Rate we use for payouts for bundle value</description>
    <label>Bundle Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>Used to track the high level stages of the Claim</description>
    <label>Claim Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting Docs</fullName>
            </value>
            <value>
                <fullName>In Kankakee</fullName>
            </value>
            <value>
                <fullName>In Lab</fullName>
            </value>
            <value>
                <fullName>File Preparation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/ClaimApproved__c.field-meta.xml
<CustomField>
    <fullName>ClaimApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that Claims Manager has approved the entire claim. This semi-closes the claim in the sense that changes should be minimal but there are still things to process. This is different than the &quot;Goodwill Amount Approve&quot; or &quot;Address Validation.&quot; A claim can have its goodwill amount approved but NOT but fully approved yet.</description>
    <label>Claim Approved?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product related to the Residential/Commercial Claim</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Is_Legacy__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Product2.Sectors_Text__c</field>
            <operation>contains</operation>
            <valueField>$Source.Sector__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Total_Cost_of_Additional_Settlement_Item__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_of_Additional_Settlement_Item__c</fullName>
    <defaultValue>0</defaultValue>
    <description>CLAIMSV2 - 75. The field is populated from the Case Products by summing the total of multiplying the Case Product Quantity with the default Rate (20$)</description>
    <inlineHelpText>The field is populated from the Case Products by summing the total of multiplying the Case Product Quantity with the default Rate (20$)</inlineHelpText>
    <label>Total Cost of Additional Settlement Item</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/Claim_Type__c.object-meta.xml
<CustomObject>
    <description>Used to capture the Primary and Secondary reason for the Claim Case</description>
    <label>Claim Type</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Claim Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Related Claim Case</description>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Case must be a Residential or Commercial Claim</errorMessage>
        <filterItems>
            <field>Case.RecordType.Name</field>
            <operation>contains</operation>
            <value>Claim</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Claim Types</relationshipLabel>
    <relationshipName>Claim_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/Lab_Sample__c.object-meta.xml
<CustomObject>
    <label>Lab Sample</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Samples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A link to the Claim this lab sample is related to. Lab Samples with no links to a Claim have been received but not properly connected to a cliam.</description>
    <inlineHelpText>The Claim this Lab Sample relates to.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Lab Samples</relationshipLabel>
    <relationshipName>Lab_Samples</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>https://ikoussfsc.atlassian.net/browse/CLAIMSV2-358
Claims Stage</description>
    <formula>TEXT(Case__r.Claim_Stage__c)</formula>
    <inlineHelpText>Claims Stage</inlineHelpText>
    <label>Claim Stage</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample_Tape_Code__c/Lab_Sample_Tape_Code__c.object-meta.xml
<CustomObject>
    <description>This allows users to associate the tape codes with the lab samples</description>
    <label>Sample Description</label>
    <nameField>
        <displayFormat>LSTC - {000000000}</displayFormat>
        <label>Lab Sample Tape Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample_Tape_Code__c/fields/Lab_Sample__c.field-meta.xml
<CustomField>
    <fullName>Lab_Sample__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the lab sample the record is related to</description>
    <label>Lab Sample</label>
    <referenceTo>Lab_Sample__c</referenceTo>
    <relationshipName>Lab_Sample_Tape_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample_Tape_Code__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;&amp; Tape_Code__r.Product__r.Id,  Tape_Code__r.Product__r.Name  )</formula>
    <label>Product</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample_Tape_Code__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>This denotes the number of shingles included in the sample for the associated tape code</description>
    <label>Quantity</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Related_Product__c/Related_Product__c.object-meta.xml
<CustomObject>
    <description>This is an object that allows users to associate multiple products to a claims case and capture additional details for these products.</description>
    <label>Related Product</label>
    <nameField>
        <displayFormat>RP-{0000000000}</displayFormat>
        <label>Related Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Related_Product__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a parent field on this object. This is required.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Products</relationshipLabel>
    <relationshipName>Related_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Related_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Records the product related to the claim case.</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Product is either inactive or is a legacy product</errorMessage>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.Is_Legacy__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>Ensure that the selected product is neither inactive nor a legacy product</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Related Products</relationshipLabel>
    <relationshipName>Related_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Related_Product__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>This is the quantity of the product that is needed for the settlement.</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Settlement_Condition__c/Settlement_Condition__c.object-meta.xml
<CustomObject>
    <description>Used to capture Settlement Conditions against a Claim Case</description>
    <label>Settlement Condition</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Settlement Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Settlement_Condition__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Settlement Condition to be leveraged in offer letters</description>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Commercial Claim, Residential Claim</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Settlement Conditions</relationshipLabel>
    <relationshipName>Settlement_Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Settlement_Condition__c/fields/Condition_Template__c.field-meta.xml
<CustomField>
    <fullName>Condition_Template__c</fullName>
    <description>Used to select default text of condition</description>
    <label>Condition Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Ventilation must be upgraded....</fullName>
            </value>
            <value>
                <fullName>2. Extended downspouts to direct....</fullName>
            </value>
            <value>
                <fullName>3. Soffit ventilation must be cleared...</fullName>
            </value>
            <value>
                <fullName>4. Deck must be repaired...</fullName>
            </value>
            <value>
                <fullName>5. New shingles must be installed ...</fullName>
            </value>
            <value>
                <fullName>Free entry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/RelatedProductServiceTest.cls
@isTest
private class RelatedProductServiceTest {
	@future
    private static void createUsers(){
       List<User> toInsertUsers = new List<User>();
        toInsertUsers.add(TestFactory.createUser('Unit','Tests','salesrsmmgr@iko.com','salesrsmmgr@iko.com','USRS Manager',
                'RSM West','salesmgr','GMT','en_US','UTF-8','en_US',null,null,false));
        toInsertUsers.add(TestFactory.createUser('UnitClaim', 'TestsClaim', 'claimsManagerUsr@iko.com', 'claimsManagerUsr@iko.com', 'Claims Manager',
                'Claims Manager', 'tclu', 'GMT', 'en_US', 'UTF-8', 'en_US', 'United States', null, false));
        toInsertUsers.add(TestFactory.createUser('UnitClaim1','TestsClaim','sysAdminUsr@iko.com','sysAdminUsr@iko.com','System Administrator',
                'CEO','tsAdmU','GMT','en_US','UTF-8','en_US','United States',null,false));

        insert toInsertUsers;
       /* TestFactory.createUser('Unit','Tests','salesrsmmgr@iko.com','salesrsmmgr@iko.com','USRS Manager',
                'RSM West','salesmgr','GMT','en_US','UTF-8','en_US',null,null,true);*/
    }

    @testSetup static void setupTestData() {
		createUsers();
        Id baRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Building Location').getRecordTypeId();
        Id ccRt = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Claim').getRecordTypeId();

        //create Account
        List<Account> toInsertAccounts = new List<Account>();

        toInsertAccounts.addAll(TestFactory.createAccounts(baRt,'CaseServiceTest','9 King St E','Toronto','ON','CA','M4S 2H4',
                'Verified',UserInfo.getUserId(),TRUE,TRUE,1,false));

        insert toInsertAccounts;


        //create contact
        List<Contact> toInsertContacts = new List<Contact>();

        toInsertContacts.addAll(TestFactory.createContacts(toInsertAccounts[0].Id,'CaseServiceTest',UserInfo.getUserId(),1,false));

        insert toInsertContacts;

        Map<String,Account> mapAccounts = new Map<String, Account>();

        for(Account act : [SELECT Id,Name FROM Account]){
            mapAccounts.put(act.Name,act);
        }


        //create Cases
        List<Case> toInsertCases = new List<Case>();
        toInsertCases.addAll(TestFactory.createCases(ccRt,mapAccounts.get('CaseServiceTest').Id,toInsertContacts[0].Id,'Distributor','CaseServiceTestClosed',null,'Commercial','Closed',1,false));
        toInsertCases.addAll(TestFactory.createCases(ccRt,mapAccounts.get('CaseServiceTest').Id,toInsertContacts[0].Id,'Distributor','CaseServiceTest1',null,'Commercial','Draft',1,false));

        toInsertCases.addAll(TestFactory.createCases(ccRt,mapAccounts.get('CaseServiceTest').Id,toInsertContacts[0].Id,'Distributor','CaseServiceTestWithApprovedClaim',null,'Commercial','Draft',1,false));
		toInsertCases.addAll(TestFactory.createCases(ccRt,mapAccounts.get('CaseServiceTest').Id,toInsertContacts[0].Id,'Distributor','CaseServiceTestWithAssessmentStage',null,'Commercial','Assessment',1,false));
        //toInsertCases[3].ClaimApproved__c=true;
        insert toInsertCases;

        Lab_Sample__c ls = new Lab_Sample__c(Case__c = toInsertCases[2].Id);
        insert ls;
        Lab_Sample_Tape_Code__c lstc = new Lab_Sample_Tape_Code__c(Lab_Sample__c = ls.Id);
        insert lstc;

        Settlement_Condition__c sc = new Settlement_Condition__c(Case__c = toInsertCases[2].Id, Condition_Template__c = '1. Ventilation must be upgraded....');
        insert sc;

        Claim_Type__c ct = new Claim_Type__c(Case__c = toInsertCases[2].Id);
        insert ct;

        //create products
        List<Product2> toInsertProducts = new List<Product2>();
        toInsertProducts.addAll(TestFactory.createProducts('IkoSampleProduct',TRUE,'IkoSampleProduct','US;CA;Commercial;Blair',null,1,false));

        insert toInsertProducts;

        //create related products
        List<Related_Product__c> toInsertRelatedProducts = new List<Related_Product__c>();

        toInsertRelatedProducts.addAll(TestFactory.createRelatedProducts(toInsertCases[0],toInsertProducts[0],1,false));
        toInsertRelatedProducts.addAll(TestFactory.createRelatedProducts(toInsertCases[1],toInsertProducts[0],1,false));
        toInsertRelatedProducts.addAll(TestFactory.createRelatedProducts(toInsertCases[1],toInsertProducts[0],1,false));
        toInsertRelatedProducts.addAll(TestFactory.createRelatedProducts(toInsertCases[2],toInsertProducts[0],1,false));
		toInsertRelatedProducts.addAll(TestFactory.createRelatedProducts(toInsertCases[3],toInsertProducts[0],1,false));
        insert toInsertRelatedProducts;


    }

    @isTest static void testThatRelatedProductsCannotBeDeletedPostCaseApproval() {
        Case c1 = [select Id, ClaimApproved__c from Case where Subject = 'CaseServiceTest1'];
        Product2 prod = [SELECT Id FROM Product2 WHERE Name = 'IkoSampleProduct'];

        Related_Product__c relatedProduct = [SELECT Id FROM Related_Product__c WHERE Case__c = :c1.Id AND Product__c = :prod.Id LIMIT 1];
        Test.startTest();

        c1.ClaimApproved__c = true;
        update c1;


        Boolean deletionBlocked = false;
        try {
            delete relatedProduct;
        } catch (DmlException e) {
            deletionBlocked = true;
        }
        System.debug('@@@Queries-->'+Limits.getQueries());
        Test.stopTest();  
        System.assert(deletionBlocked);
    }

    @isTest static void testThatRelatedProductsCannotBeDeletedBeforeCaseApproval() {
        Case c1 = [select Id, ClaimApproved__c from Case where Subject = 'CaseServiceTest1'];
        Product2 prod = [SELECT Id FROM Product2 WHERE Name = 'IkoSampleProduct'];

        Related_Product__c relatedProduct = [SELECT Id FROM Related_Product__c WHERE Case__c = :c1.Id AND Product__c = :prod.Id LIMIT 1];

        Boolean deletionBlocked = false;
        try {
            delete relatedProduct;
        } catch (DmlException e) {
            deletionBlocked = true;
        }
        System.assertEquals(deletionBlocked, false);

    }

    @isTest static void testThatRelatedProductCannotBeInsertedPostClosure() {
        Case c1 = [SELECT Id, Claim_Stage__c FROM Case where Subject = 'CaseServiceTestClosed'];
        Product2 prod = [SELECT Id FROM Product2 WHERE Name = 'IkoSampleProduct'];

        Related_Product__c ct = [SELECT Id FROM Related_Product__c WHERE Case__c = :c1.Id AND Product__c = :prod.Id];

        try {
            insert ct;
        } catch (DmlException e) {
        }
        System.assertEquals(ct.Id, ct.Id);
    }

    @isTest static void testThatRelatedProductCannotBeUpdatedPostClosure() {
        
        Related_Product__c ct = [select Id from Related_Product__c where Case__r.Subject = 'CaseServiceTestClosed'];
        Boolean errorCaught = false;
        User salesMngUser = [SELECT Id FROM User WHERE Username = 'salesrsmmgr@iko.com' ];
        User sysAdmin = [SELECT Id FROM User WHERE Username = 'sysAdminUsr@iko.com' ];
        // Running as a Sales Mgr

        try {
            System.runAs(sysAdmin){
            update ct;
            }
        } catch (DmlException e) {
            errorCaught = true;
        }
        System.assert(!errorCaught);
        //Boolean errorCaught = false;
        // Running as a different user


        System.runAs(salesMngUser) {
            try {
                delete ct;
            } catch (DMLException e) {
                errorCaught = true;
            }
        }
        System.assert(errorCaught);
    }

    @isTest static void testThatRelatedProductCannotBeDeletedPostClosure() {
        //createUsers();
        Related_Product__c ct = [select Id from Related_Product__c where Case__r.Subject = 'CaseServiceTestClosed'];
        // Running as a System Administrator
        User sysAdmin = [SELECT Id FROM User WHERE Username = 'sysAdminUsr@iko.com' ];
        Boolean errorCaught = false;
        try {
            System.runAs(sysAdmin){
                delete ct;
            }
        } catch (DmlException e) {
            errorCaught = true;
        }
        System.assert(!errorCaught);

        // Running as a different user
         User salesMngUser = [SELECT Id FROM User WHERE Username = 'salesrsmmgr@iko.com' ];

        System.runAs(salesMngUser) {
            try {
                delete ct;
            } catch (DMLException e) {
                errorCaught = true;
            }
        }
        System.assert(errorCaught);

    }

    @isTest static void testThatRelatedProductCanBeInsertedUpdatedDeletedPreClosure() {
        Case c1 = [select Id, Claim_Stage__c from Case where Subject = 'CaseServiceTest1'];

        Product2 prod = [SELECT Id FROM Product2 WHERE Name = 'IkoSampleProduct'];

        Related_Product__c ct = [SELECT Id FROM Related_Product__c WHERE Case__c = :c1.Id AND Product__c = :prod.Id LIMIT 1];

        System.assertNotEquals(ct.Id, null);
        update ct;
        delete ct;
    }

    @isTest static void blockCreatedUpdateDelete_ApprovedCaseWithOpenClaimUponInsert_ThrowValidationError() {
        Test.startTest();
        Case c1 = [SELECT Id, Claim_Stage__c FROM Case WHERE Subject = 'CaseServiceTestWithApprovedClaim'];
        c1.ClaimApproved__c = TRUE;
        update c1;

        Boolean errorCaught = false;
        Related_Product__c ct = [SELECT Id FROM Related_Product__c WHERE Case__c = :c1.Id];

        
        try {
            insert ct;
        } catch (DmlException e) {
            errorCaught = true;
        }
        Test.stopTest();

        System.assert(errorCaught);
    }

    @isTest static void blockCreatedUpdateDelete_ApprovedCaseWithOpenClaimUponUpdate_ThrowValidationError() {
        Test.startTest();
        Case c1 = [SELECT Id, Claim_Stage__c FROM Case WHERE Subject = 'CaseServiceTestWithApprovedClaim'];
        c1.ClaimApproved__c = TRUE;
        update c1;

        Related_Product__c ct = [SELECT Id FROM Related_Product__c WHERE Case__c = :c1.Id];

        Boolean errorCaught = false;

        
        try {
            update ct;
        } catch (DmlException e) {
            errorCaught = true;
        }
        Test.stopTest();

        System.assertEquals(errorCaught, true, 'An error has caught and thrown to the user.');
    }

    @isTest static void blockCreatedUpdateDelete_ApprovedCaseWithOpenClaimUponDelete_ThrowValidationError() {
        Test.startTest();
        Case c1 = [SELECT Id, Claim_Stage__c FROM Case WHERE Subject = 'CaseServiceTestWithApprovedClaim'];
        c1.ClaimApproved__c = TRUE;
        update c1;

        Related_Product__c ct = [SELECT Id FROM Related_Product__c WHERE Case__c = :c1.Id];
        Boolean errorCaught = false;
        try {
            delete ct;
        } catch (Exception e) {
            errorCaught = true;
        }
        Test.stopTest();

        System.assertEquals(errorCaught, true, 'An error has caught and throw to the user.');
    }

    @isTest static void calculateTotalCostOfSettlementItemsOnRelatedCase_populateTotalCostOfSettlementItemsField_onUpdate(){
        List<Related_Product__c> ct = [SELECT Id,Quantity__c FROM Related_Product__c WHERE Case__r.Subject = 'CaseServiceTest1'];

        Test.startTest();
        ct[0].Quantity__c = 1;
        ct[1].Quantity__c = 2;
        update ct;
        Test.stopTest();

        Case c = [SELECT Total_Cost_of_Additional_Settlement_Item__c,Bundle_Rate__c FROM Case WHERE Subject = 'CaseServiceTest1'];

        System.assertEquals((3 * c.Bundle_Rate__c),c.Total_Cost_of_Additional_Settlement_Item__c);

    }

    @isTest static void calculateTotalCostOfSettlementItemsOnRelatedCase_populateTotalCostOfSettlementItemsField_onDelete(){
        List<Related_Product__c> ct = [SELECT Id,Quantity__c FROM Related_Product__c WHERE Case__r.Subject = 'CaseServiceTest1'];

        Test.startTest();
        ct[0].Quantity__c = 1;
        ct[1].Quantity__c = 2;
        update ct;

        Case c = [SELECT Total_Cost_of_Additional_Settlement_Item__c,Bundle_Rate__c FROM Case WHERE Subject = 'CaseServiceTest1'];
        System.assertEquals((3 * c.Bundle_Rate__c),c.Total_Cost_of_Additional_Settlement_Item__c);

        delete ct[1];
        Case c1 = [SELECT Total_Cost_of_Additional_Settlement_Item__c,Bundle_Rate__c FROM Case WHERE Subject = 'CaseServiceTest1'];
        System.assertEquals((1 * c1.Bundle_Rate__c),c1.Total_Cost_of_Additional_Settlement_Item__c);

        Test.stopTest();
    }

    @isTest static void calculateTotalCostOfSettlementItemsOnRelatedCase_populateTotalCostOfSettlementItemsField_onInsert(){

        Case c1 = [select Id from Case where Subject = 'CaseServiceTest1'];
        Product2 p = [SELECT Id FROM Product2 WHERE Name = 'IkoSampleProduct'];

        Related_Product__c rp = new Related_Product__c(Case__c = c1.Id,Product__c = p.id,Quantity__c = 1);

        Test.startTest();
        insert rp;
        Test.stopTest();

        Case c = [SELECT Total_Cost_of_Additional_Settlement_Item__c,Bundle_Rate__c FROM Case WHERE Subject = 'CaseServiceTest1'];

        System.assertEquals((1 * c.Bundle_Rate__c),c.Total_Cost_of_Additional_Settlement_Item__c);

    }
    
    @isTest static void testSuccessfulDeleteRelatedProduct(){
        User claimsMngUser = [SELECT Id FROM User WHERE Username = 'claimsManagerUsr@iko.com' LIMIT 1 ];
        Case caseToTest = [SELECT Id, Subject, Claim_Stage__c, AccountId, ContactId From Case Where Subject = 'CaseServiceTestClosed' Limit 1];
        //List<Case> caseToInsert = TestFactory.createCases(ccRt,caseToClone.AccountId,caseToClone.AccountId,'Distributor','CaseServiceTestDelete',null,'Commercial','Closed',1,false);
        //Insert caseToClose;
        
        
        Test.startTest();
        Related_Product__c relatedProductToTest= [Select Id, Case__c from Related_Product__c Where Case__c= :caseToTest.Id LIMIT 1];
        
        System.runAs(claimsMngUser){
            try{
                //relatedProductToTest.Quantity__c = 5;
        		delete relatedProductToTest;
            }
            catch(Exception e){
                System.debug('Exception Message: '+e.getMessage());
            }  
        }
        
        Test.stopTest();
        
        
    }
    
    @isTest static void testSuccessfulDeleteRelatedProductForApprovedCase(){
        Test.startTest();
        User claimsMngUser = [SELECT Id FROM User WHERE Username = 'claimsManagerUsr@iko.com' LIMIT 1 ];
        Case caseApprovedToTest = [SELECT Id, Subject, Claim_Stage__c, AccountId, ContactId From Case Where Subject = 'CaseServiceTestWithAssessmentStage' Limit 1];
        Related_Product__c relatedProductApprovedToTest= [Select Id, Case__c from Related_Product__c Where Case__c= :caseApprovedToTest.Id LIMIT 1];
        caseApprovedToTest.ClaimApproved__c=true;
        update caseApprovedToTest;
        System.runAs(claimsMngUser){
            try{
                //relatedProductToTest.Quantity__c = 5;
        		delete relatedProductApprovedToTest;
            }
            catch(Exception e){
                System.debug('Exception Message: '+e.getMessage());
            }  
        }
        Test.stopTest();
    }
}