ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <label>Other</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <label>Account ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Currency_Used__c.field-meta.xml
<CustomField>
    <fullName>Currency_Used__c</fullName>
    <label>Currency Used</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Transaction_Sources__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Sources__c</fullName>
    <inlineHelpText>For Coop adjustments, only select &quot;Loyalty Admins&quot; as Transaction Source.</inlineHelpText>
    <label>Sources</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Transaction_Sources</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debit</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Repository/Claims/force-app/main/default/classes/icTestRepoTransaction.cls
/**
 * Created by Francois Poirier on 2018-12-17.
 */

@isTest
public with sharing class icTestRepoTransaction {

    static icREPOTransaction.IClass transactionRepo = (icREPOTransaction.IClass) icObjectFactory.GetSingletonInstance('icREPOTransaction');

    @isTest
    static void testCreateTransaction(){

        Account newAccount = new Account();
        newAccount = icTestHelperUtility.generateOtherAccount();
        insert newAccount;

        Transaction__c testTransaction = new Transaction__c();
        testTransaction.Account_ID__c = newAccount.Id;
        testTransaction.Amount__c = 1;
        testTransaction.Currency_Used__c = 'USD';
        testTransaction.Transaction_Sources__c = 'Other';
        testTransaction.Transaction_Type__c = 'Debit';

        testTransaction = transactionRepo.createTransaction(testTransaction);

        system.assert(String.isNotBlank(testTransaction.id));

    }

    @isTest
    static void testCreateTransactions(){
        Account newAccount = new Account();
        newAccount = icTestHelperUtility.generateOtherAccount();
        insert newAccount;

        Transaction__c testTransaction = new Transaction__c();
        testTransaction.Account_ID__c = newAccount.Id;
        testTransaction.Amount__c = 1;
        testTransaction.Currency_Used__c = 'USD';
        testTransaction.Transaction_Sources__c = 'Other';
        testTransaction.Transaction_Type__c = 'Debit';

        List<Database.SaveResult> results = transactionRepo.createTransactions(new List<Transaction__c>{testTransaction});
    }

}