ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Contractor_Subscription__c/IKOPRO_Contractor_Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Subscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Contractor_Subscription__c/fields/Contractor_Account__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>IKOPRO Contractor, IKOPRO Contractor HA OK</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions1</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Contractor_Subscription__c/fields/Membership_ID__c.field-meta.xml
<CustomField>
    <fullName>Membership_ID__c</fullName>
    <inlineHelpText>Please provide the membership Identifier that was shared with you during sign-up (e.g. HomeAdvisor SP Account Number).</inlineHelpText>
    <label>Membership ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Contractor_Subscription__c/fields/SourceId__c.field-meta.xml
<CustomField>
    <fullName>SourceId__c</fullName>
    <label>SourceId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icRepoSubscription.cls
public with sharing class icRepoSubscription implements icIClass {

	public Object GetInstance() {
		return new Impl();
	}

	public Interface IClass {
		List<IKOPRO_Contractor_Subscription__c> getSubscriptionsByAccountIdAndRecordTypeId(String accountId, String recordTypeId);
		void createSubscription(IKOPRO_Contractor_Subscription__c subscription);
		void updateSubscription(IKOPRO_Contractor_Subscription__c subscription);
	}

	public class Impl implements IClass {
		
		public List<IKOPRO_Contractor_Subscription__c> getSubscriptionsByAccountIdAndRecordTypeId(String accountId, String recordTypeId) {
			return [SELECT Id, Name, Username__c, Membership_ID__c, Password__c, SourceId__c, Client_Secret__c FROM IKOPRO_Contractor_Subscription__c WHERE Contractor_Account__c =:accountId AND RecordTypeId =:recordTypeId];
		}

		public void createSubscription(IKOPRO_Contractor_Subscription__c subscription) {
			insert subscription;
		}

		public void updateSubscription(IKOPRO_Contractor_Subscription__c subscription) {
			update subscription;
		}
	}
}