ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/AntiTrustSetting__mdt/AntiTrustSetting__mdt.object-meta.xml
<CustomObject>
    <label>Anti-Trust Setting</label>
    <pluralLabel>Anti-Trust Settings</pluralLabel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/AntiTrustSetting__mdt/fields/BackgroundName__c.field-meta.xml
<CustomField>
    <fullName>BackgroundName__c</fullName>
    <description>Image name in static resource package</description>
    <inlineHelpText>Image name in static resource package</inlineHelpText>
    <label>Background Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/AntiTrustSetting__mdt/fields/EmailAttachmentName__c.field-meta.xml
<CustomField>
    <fullName>EmailAttachmentName__c</fullName>
    <defaultValue>&apos;Antitrust Certificate&apos;</defaultValue>
    <label>Email Attachment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/AntiTrustSetting__mdt/fields/EmailTemplateDeveloperName__c.field-meta.xml
<CustomField>
    <fullName>EmailTemplateDeveloperName__c</fullName>
    <description>Anit-Trust Completed Email Template Developer Name</description>
    <inlineHelpText>Anit-Trust Completed Email Template Developer Name</inlineHelpText>
    <label>Email Template Developer Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/AntiTrustSetting__mdt/fields/OrganizationWideEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>OrganizationWideEmailAddress__c</fullName>
    <label>Organization-Wide Email Address</label>
    <type>Email</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/IKOCertivicateUtils.cls
public class IKOCertivicateUtils {
   
    public static User getUserById(Id userId) {
        List<User> users = [ SELECT Id, Name, Profile.Name, Email 
                             FROM User
                             WHERE Id = :userId ];
        return users.isEmpty() ? null : users[0];
    }

    public static User getUserByContactId(Id contactId) {
        List<User> users = [ SELECT Id, Name, Profile.Name, ContactId, Email 
                             FROM User
                             WHERE ContactId = :contactId ];
        return users.isEmpty() ? null : users[0];
    }

    public static AntiTrustSetting__mdt getAntiTrustSettingByProfileName(String profileName) {
        List<AntiTrustSetting__mdt> antiTrustSettings = [ SELECT BackgroundName__c, ProfileName__c, EmailTemplateDeveloperName__c, 
                                                                 OrganizationWideEmailAddress__c, EmailAttachmentName__c
                                                          FROM AntiTrustSetting__mdt
                                                          WHERE ProfileName__c = :profileName ];
        return antiTrustSettings.isEmpty() ? null : antiTrustSettings[0];
    }

    public static OrgWideEmailAddress getOrgWideEmailAddressByEmailAddress(String emailAddress) {
        List<OrgWideEmailAddress> orgWideEmailAddress = [ SELECT Id
                                                          FROM OrgWideEmailAddress 
                                                          WHERE Address = :emailAddress ];
        return orgWideEmailAddress.isEmpty() ? null : orgWideEmailAddress[0];            
    }   

    public static EmailTemplate getEmailTemplateByDeveloperName(String developerName) {
        List<EmailTemplate> emailTemplates = [ SELECT Id, Subject, Body, HtmlValue
                                               FROM EmailTemplate 
                                               WHERE DeveloperName = :developerName ];
        return emailTemplates.isEmpty() ? null : emailTemplates[0];
    }

    public static redwing__Achievement_Assignment__c getAchievementAssignmentById(Id achievementAssignmentId) {
        return [ SELECT Id, redwing__User__c, redwing__User__r.ManagerId,  redwing__Contact__r.Owner.Id, redwing__Contact__c,
                        redwing__User__r.Contact.ReportsToId
                 FROM redwing__Achievement_Assignment__c
                 WHERE Id =: achievementAssignmentId ];
    }
}