ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/IKOPRO_Account_Payment__c.object-meta.xml
<CustomObject>
    <label>Contractor Payment</label>
    <nameField>
        <displayFormat>INV - {00000}</displayFormat>
        <label>PaymentID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contractor Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>IKOPRO Contractor</value>
        </filterItems>
        <filterItems>
            <field>Account.Name</field>
            <operation>equals</operation>
            <value>APPLICANTS</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Due_Amount__c.field-meta.xml
<CustomField>
    <fullName>Due_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Membership Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Paid_Date__c.field-meta.xml
<CustomField>
    <fullName>Paid_Date__c</fullName>
    <label>Paid Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <referenceTo>IKOPRO_Payment__c</referenceTo>
    <relationshipName>Account_Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Payment__c/IKOPRO_Payment__c.object-meta.xml
<CustomObject>
    <description>Object to manage payments related to membership fees. (junction object relates this one with Contractor Accounts)</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icTestRepoAccountPayment.cls
/**
 * Created by Francois Poirier on 2018-12-17.
 */

@isTest
public with sharing class icTestRepoAccountPayment {

    static icRepoAccountPayment.IClass accountPaymentRepo = (icRepoAccountPayment.IClass) icObjectFactory.GetSingletonInstance('icRepoAccountPayment');
    static Account testContractor {get; set;}
    static IKOPRO_Account_Payment__c testAccountPayment = new IKOPRO_Account_Payment__c();
    static String testId = '';

    @testSetup static void setup(){

        testContractor = icTestHelperUtility.generateContractorAccount();
        insert testContractor;

        IKOPRO_Payment__c testPayment = new IKOPRO_Payment__c();
        testPayment.Amount__c = 321;        
        insert testPayment;

        testAccountPayment.Payment__c = testPayment.Id;
        testAccountPayment.Due_Amount__c = 321;
        testAccountPayment.Contractor__c = testContractor.Id;
        testAccountPayment.Year__c = '2019';
        testAccountPayment.Paid_Date__c = Date.today();
        insert testAccountPayment;

    }


    @isTest
    static void testRepoAccountPayment(){
        testAccountPayment = [SELECT Id FROM IKOPRO_Account_Payment__c WHERE Due_Amount__c = 321 LIMIT 1];

        IKOPRO_Account_Payment__c accountPaymentFromRepo = new IKOPRO_Account_Payment__c();
        accountPaymentFromRepo = accountPaymentRepo.getAccountPaymentById(testAccountPayment.Id);
        system.assertEquals(testAccountPayment.Id, accountPaymentFromRepo.Id);

        testAccountPayment.Due_Amount__c = 456;
        accountPaymentFromRepo = accountPaymentRepo.updateAccountPayment(testAccountPayment);
        system.assertEquals(testAccountPayment.Due_Amount__c, accountPaymentFromRepo.Due_Amount__c);

    }

    @isTest
    static void test_getPaidAccountPaymentByYearAndContractorIds(){
        List<String> mockContractorIds = new List<String>();
        //mockContractorIds.add(testContractor.Id);

        List<IKOPRO_Account_Payment__c> listResult = accountPaymentRepo.getPaidAccountPaymentByYearAndContractorIds('2019', mockContractorIds);

    }
}