ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/IKOPRO_Account_Payment__c.object-meta.xml
<CustomObject>
    <label>Contractor Payment</label>
    <nameField>
        <displayFormat>INV - {00000}</displayFormat>
        <label>PaymentID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contractor Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>IKOPRO Contractor</value>
        </filterItems>
        <filterItems>
            <field>Account.Name</field>
            <operation>equals</operation>
            <value>APPLICANTS</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

Repository/Claims/force-app/main/default/classes/icLogicAccountPayment.cls
/**
 * Created by Francois Poirier on 2018-12-11.
 */

public without sharing class icLogicAccountPayment implements icIClass {

    public Object GetInstance() {
        return new Impl();
    }

    public Interface IClass {

        IKOPRO_Account_Payment__c getAccountPaymentById(Id accountPaymentId);
        List<IKOPRO_Account_Payment__c> getPaidAccountPaymentByYearAndContractorIds(String strYear, List<String> contractorIds);
        Map<String, IKOPRO_Account_Payment__c> getMapPaidRenewalByContractorId(List<IKOPRO_Account_Payment__c> payments);
        IKOPRO_Account_Payment__c updateAccountPayment(IKOPRO_Account_Payment__c accountPayment);

    }

    public class Impl implements IClass {

        private icRepoAccountPayment.IClass apRepo = (icRepoAccountPayment.IClass) icObjectFactory.GetSingletonInstance('icRepoAccountPayment');

        public IKOPRO_Account_Payment__c getAccountPaymentById(Id accountPaymentId){

            return apRepo.getAccountPaymentById(accountPaymentId);

        }

        public List<IKOPRO_Account_Payment__c> getPaidAccountPaymentByYearAndContractorIds(String strYear, List<String> contractorIds){
            return apRepo.getPaidAccountPaymentByYearAndContractorIds(strYear, contractorIds);
        }

        public Map<String, IKOPRO_Account_Payment__c> getMapPaidRenewalByContractorId(List<IKOPRO_Account_Payment__c> payments) {
            Map<String, IKOPRO_Account_Payment__c> returnMap = new Map<String, IKOPRO_Account_Payment__c>();

            for(IKOPRO_Account_Payment__c thisPayment : payments) {
                returnMap.put(thisPayment.Contractor__c, thisPayment);
            }

            return returnMap;
        }

        public IKOPRO_Account_Payment__c updateAccountPayment(IKOPRO_Account_Payment__c accountPayment){

            return apRepo.updateAccountPayment(accountPayment);

        }

    }


}