ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/IKOPRO_Account_Payment__c.object-meta.xml
<CustomObject>
    <label>Contractor Payment</label>
    <nameField>
        <displayFormat>INV - {00000}</displayFormat>
        <label>PaymentID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contractor Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to contractor applicant contact in order to store the payment record for the signup process payment. (payment info will be copied to the contractor account once that account is created).</description>
    <inlineHelpText>Lookup to contractor applicant contact in order to store the payment record for the signup process payment. (payment info will be copied to the contractor account once that account is created).</inlineHelpText>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Account_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>IKOPRO Contractor</value>
        </filterItems>
        <filterItems>
            <field>Account.Name</field>
            <operation>equals</operation>
            <value>APPLICANTS</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Contractor_Email__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Email__c</fullName>
    <label>Contractor Email</label>
    <type>Email</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <formula>IF(ISBLANK( Applicant__c ), 
IF(ISPICKVAL(Contractor__r.BillingCountryCode,&apos;CA&apos;), &quot;CAD&quot;, &quot;USD&quot;),

IF(Applicant__r.Country_Code_Applicant__c = &apos;CA&apos;, &quot;CAD&quot;, &quot;USD&quot;)
)</formula>
    <label>Currency</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Net_Membership_Fee__c.field-meta.xml
<CustomField>
    <fullName>Net_Membership_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Net Amount Due</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <label>Paid Amount</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Paid_Date__c.field-meta.xml
<CustomField>
    <fullName>Paid_Date__c</fullName>
    <label>Paid Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icRepoAccountPayment.cls
/**
 * Created by Francois Poirier on 2018-12-11.
 */

public without sharing class icRepoAccountPayment  implements icIClass {

    public Object GetInstance() {
        return new Impl();
    }

    public Interface IClass {

        IKOPRO_Account_Payment__c getAccountPaymentById(Id accountPaymentId);
        List<IKOPRO_Account_Payment__c> getPaidAccountPaymentByYearAndContractorIds(String strYear, List<String> contractorIds);
        IKOPRO_Account_Payment__c updateAccountPayment(IKOPRO_Account_Payment__c accountPayment);

    }

    public class Impl implements IClass {

        public IKOPRO_Account_Payment__c getAccountPaymentById(Id accountPaymentId){

            List<IKOPRO_Account_Payment__c> accountPayments = new List<IKOPRO_Account_Payment__c>();
            IKOPRO_Account_Payment__c retour = new IKOPRO_Account_Payment__c();

            accountPayments = [
                    SELECT  Id,
                            Contractor__c,
                            Contractor__r.Primary_Contact_FirstName_Applicant__pc,
                            Contractor__r.Primary_Contact_LastName_Applicant__pc,
                            Contractor__r.BillingStreet,
                            Contractor__r.BillingCity,
                            Contractor__r.BillingStateCode,
                            Contractor__r.BillingCountryCode,
                            Contractor__r.BillingPostalCode,
                            Applicant__c,
                            Applicant__r.Company_Street_Applicant__c,
                            Applicant__r.Company_City_Applicant__c,
                            Applicant__r.Zip_Postal_Code_Applicant__c,
                            Applicant__r.Company_State_Province_Code_Applicant__c,
                            Applicant__r.Country_Code_Applicant__c,
                            Contractor_Email__c,
                            Currency__c,
                            Name,
                            Net_Membership_Fee__c,
                            Paid_Amount__c,
                            Paid_Date__c,
                            Year__c
                    FROM    IKOPRO_Account_Payment__c
                    WHERE   Id =: accountPaymentId
            ];

            if(accountPayments.size()>0){
                retour = accountPayments[0];
            }

            return retour;

        }

        public List<IKOPRO_Account_Payment__c> getPaidAccountPaymentByYearAndContractorIds(String strYear, List<String> contractorIds) {
            return [SELECT Id
                            ,Contractor__c
                    FROM IKOPRO_Account_Payment__c
                    WHERE Year__c = :strYear
                    AND Contractor__c IN :contractorIds
                    AND Paid_Date__c != null];
        }

        public IKOPRO_Account_Payment__c updateAccountPayment(IKOPRO_Account_Payment__c accountPayment){

            update accountPayment;
            return accountPayment;

        }

    }
}