ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/IKOPRO_Account_Payment__c.object-meta.xml
<CustomObject>
    <label>Contractor Payment</label>
    <nameField>
        <displayFormat>INV - {00000}</displayFormat>
        <label>PaymentID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contractor Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to contractor applicant contact in order to store the payment record for the signup process payment. (payment info will be copied to the contractor account once that account is created).</description>
    <inlineHelpText>Lookup to contractor applicant contact in order to store the payment record for the signup process payment. (payment info will be copied to the contractor account once that account is created).</inlineHelpText>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Account_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>IKOPRO Contractor</value>
        </filterItems>
        <filterItems>
            <field>Account.Name</field>
            <operation>equals</operation>
            <value>APPLICANTS</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <label>Paid Amount</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Paid_Date__c.field-meta.xml
<CustomField>
    <fullName>Paid_Date__c</fullName>
    <label>Paid Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Payment_Source__c.field-meta.xml
<CustomField>
    <fullName>Payment_Source__c</fullName>
    <inlineHelpText>Values will come from Payment Gateway</inlineHelpText>
    <label>Payment Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Paypal</fullName>
            </value>
            <value>
                <fullName>Prozone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Payment_Transaction_Code__c.field-meta.xml
<CustomField>
    <fullName>Payment_Transaction_Code__c</fullName>
    <description>Value will come from Payment Gateway (in case of PayPal payment)</description>
    <label>Payment Transaction Code</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <label>Account ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Account_Payment__c.field-meta.xml
<CustomField>
    <fullName>Account_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>IKOPRO_Account_Payment__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Currency_Used__c.field-meta.xml
<CustomField>
    <fullName>Currency_Used__c</fullName>
    <label>Currency Used</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Transaction_JSON__c.field-meta.xml
<CustomField>
    <fullName>Transaction_JSON__c</fullName>
    <label>JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Transaction_reference__c.field-meta.xml
<CustomField>
    <fullName>Transaction_reference__c</fullName>
    <label>Transaction reference</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Transaction_Sources__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Sources__c</fullName>
    <inlineHelpText>For Coop adjustments, only select &quot;Loyalty Admins&quot; as Transaction Source.</inlineHelpText>
    <label>Sources</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Transaction_Sources</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debit</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Transaction_User__c.field-meta.xml
<CustomField>
    <fullName>Transaction_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/icCTRLPaypalVF.cls
/**
 * Created by Francois Poirier on 2018-12-04.
 */

public without sharing class icCTRLPaypalVF {

    public PaymentAddress thisPaymentAddress {get;set;}
    public String strPaymentDetails {get;set;}
    public Contact paymentContact {get;set;}
    public String sfPaymentId {get;set;}
    public String contactId {get;set;}
    //public String environment {get;set;}
    public IKOPRO_Account_Payment__c accountPayment {get;set;}
    public String locale {get;set;}

    private icLogicTransaction.IClass transactionLogic = (icLogicTransaction.IClass) icObjectFactory.GetSingletonInstance('icLogicTransaction');
    private icLogicAccountPayment.IClass apLogic = (icLogicAccountPayment.IClass) icObjectFactory.GetSingletonInstance('icLogicAccountPayment');
    private icLogicUser.IClass userLogic = (icLogicUser.IClass) icObjectFactory.GetSingletonInstance('icLogicUser');
    private icLogicContact.IClass contactLogic = (icLogicContact.IClass) icObjectFactory.GetSingletonInstance('icLogicContact');


    public icCTRLPaypalVF(){

        String environment;
        Boolean isSandbox = [SELECT isSandbox FROM Organization LIMIT 1].isSandbox;
        system.debug('isSandbox ====> ' + isSandbox);
        /*if(isSandbox){
            environment = 'sandbox';
        }
        else {
            environment = 'production';
        }*/
        locale = UserInfo.getLocale();
        sfPaymentId = ApexPages.currentPage().getParameters().get('paymentid');
        contactId = ApexPages.currentPage().getParameters().get('contactid');
        accountPayment = apLogic.getAccountPaymentById(sfPaymentId);
        paymentContact = contactLogic.getContactById(contactId);

        system.debug('account payment ===> ' + accountPayment);
        system.debug('payment contact ===> ' + paymentContact);

        if(accountPayment.Applicant__c != null) {
            thisPaymentAddress = new PaymentAddress(accountPayment.Applicant__r.Company_Street_Applicant__c, accountPayment.Applicant__r.Company_City_Applicant__c, accountPayment.Applicant__r.Zip_Postal_Code_Applicant__c, accountPayment.Applicant__r.Company_State_Province_Code_Applicant__c, accountPayment.Applicant__r.Country_Code_Applicant__c);
        } else {
            thisPaymentAddress = new PaymentAddress(accountPayment.Contractor__r.BillingStreet, accountPayment.Contractor__r.BillingCity, accountPayment.Contractor__r.BillingPostalCode, accountPayment.Contractor__r.BillingStateCode, accountPayment.Contractor__r.BillingCountryCode);
        }

    }

    public void savePayment(){

        try {

            System.debug('payment Details ===> ' + strPaymentDetails);

            strPaymentDetails = strPaymentDetails.replaceAll('currency', 'paymentcurrency');
            System.debug('payment Details ===> ' + strPaymentDetails);

            icDTOPaypalPaymentResponse dtoPaymentDetails = new icDTOPaypalPaymentResponse();

            dtoPaymentDetails = (icDTOPaypalPaymentResponse) JSON.deserialize(strPaymentDetails, icDTOPaypalPaymentResponse.class);

            system.debug('payment detaisl DTO ===> ' + dtoPaymentDetails);

            if(String.isNotBlank(dtoPaymentDetails.state)) {

                Transaction__c trans = new Transaction__c();
                Account acc = new Account();
                Double amount = 0;

                for (icDTOPaypalTransactionItem item : dtoPaymentDetails.transactions) {

                    amount += Double.valueOf(item.amount.total);

                }
                String paymentCurrency = 'USD';
                if(dtoPaymentDetails.transactions.size()>0){
                    paymentCurrency = dtoPaymentDetails.transactions[0].amount.paymentcurrency;
                }

                trans.Amount__c = amount;
                trans.Currency_Used__c = paymentCurrency;
                trans.Transaction_Date__c = Date.today();
                trans.Transaction_reference__c = dtoPaymentDetails.id;
                trans.Transaction_User__c = UserInfo.getUserId();
                trans.Account_ID__c = accountPayment.Contractor__c;
                trans.Transaction_Type__c = 'Credit';
                trans.Transaction_Sources__c = 'Paypal';
                trans.Account_Payment__c = accountPayment.Id;
                trans.Transaction_Status__c = dtoPaymentDetails.state;
                trans.Transaction_JSON__c = strPaymentDetails;
                transactionLogic.createTransaction(trans);

                if(dtoPaymentDetails.state == 'Approved') {
                    accountPayment.Paid_Amount__c = amount;
                    accountPayment.Paid_Date__c = Date.today();
                    accountPayment.Payment_Source__c = 'Paypal';
                    accountPayment.Payment_Transaction_Code__c = dtoPaymentDetails.id;
                    apLogic.updateAccountPayment(accountPayment);
                }
            }



        } catch (Exception ex)
        {
            icServiceErrorHandler.LogError('icCTRLPaypalVF', 'savePayment', ex.getStackTraceString(), ex.getMessage(), strPaymentDetails);
        }
    }

    public Contact getPaymentContact(){

        return paymentContact;

    }

    public IKOPRO_Account_Payment__c getAccountPayment(){
        return accountPayment;
    }

    public String getLocale(){
        return locale;
    }

    public class PaymentAddress {
        public String street {get;set;}
        public String city {get;set;}
        public String zipCode {get;set;}
        public String state {get;set;}
        public String country {get;set;}

        public PaymentAddress(String street, String city, String zipCode, String state, String country){
            this.street = street;
            this.city = city;
            this.zipCode = zipCode;
            this.state = state;
            this.country = country;
        }
    }
}