ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/IKOPRO_Account_Payment__c.object-meta.xml
<CustomObject>
    <label>Contractor Payment</label>
    <nameField>
        <displayFormat>INV - {00000}</displayFormat>
        <label>PaymentID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contractor Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Net_Membership_Fee__c.field-meta.xml
<CustomField>
    <fullName>Net_Membership_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Net Amount Due</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <label>Paid Amount</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icCTRLPaypal.cls
/**
 * Created by Francois Poirier on 2018-12-03.
 */

global with sharing class icCTRLPaypal {

    static icLogicAccountPayment.IClass logicAccountPayment = (icLogicAccountPayment.IClass) icObjectFactory.GetSingletonInstance('icLogicAccountPayment');

    @AuraEnabled
    global static Boolean getInvoicePaidStatus(String accountPaymentId){

        Boolean retour = false;

        IKOPRO_Account_Payment__c accountPayment = new IKOPRO_Account_Payment__c();

        accountPayment = logicAccountPayment.getAccountPaymentById(accountPaymentId);

        if (accountPayment.Net_Membership_Fee__c - accountPayment.Paid_Amount__c <= 0){

            retour = true;

        }

        return retour;

    }
}