ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/API_Configuration__mdt/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/API_Configuration__mdt/fields/Source_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Id__c</fullName>
    <label>Source Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CommunitySiteNameConfiguration__mdt/CommunitySiteNameConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>This metadata contains the information related to the Site Name Community and help to bind the value to the CommunityName global setvalue used in Calendar event and Whatshappening configuration.</description>
    <label>Community Site Name Configuration</label>
    <pluralLabel>Community Site Name Configurations</pluralLabel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CommunitySiteNameConfiguration__mdt/fields/CommunityName__c.field-meta.xml
<CustomField>
    <fullName>CommunityName__c</fullName>
    <description>This value must contains the information return by Site.getName() when the apex code is call from the Community site. This information should change from an org/sandbox to another.</description>
    <label>CommunityName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CommunitySiteNameConfiguration__mdt/fields/CommunityNameGlobalSetValue__c.field-meta.xml
<CustomField>
    <fullName>CommunityNameGlobalSetValue__c</fullName>
    <description>This value must match the API NAME Value of the corresponding Picklist list Item in the global value set named CommunityName</description>
    <label>CommunityNameGlobalSetValue</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Iko_Global_Configurations__mdt/Iko_Global_Configurations__mdt.object-meta.xml
<CustomObject>
    <label>Iko Global Configurations</label>
    <pluralLabel>Iko Global Configurations</pluralLabel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Iko_Global_Configurations__mdt/fields/Default_Vendor_Email__c.field-meta.xml
<CustomField>
    <fullName>Default_Vendor_Email__c</fullName>
    <label>Default Vendor Email</label>
    <type>Email</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Iko_Global_Configurations__mdt/fields/Vendor_Email_CA__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Email_CA__c</fullName>
    <label>Vendor Email CA</label>
    <type>Email</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Iko_Global_Configurations__mdt/fields/Vendor_Email_US__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Email_US__c</fullName>
    <label>Vendor Email US</label>
    <type>Email</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icRepoConfig.cls
public with sharing class icRepoConfig implements icIClass {

	public Object GetInstance(){
		return new Impl();
	}

	public interface IClass {
		API_Configuration__mdt getAPIConfigByName(String configName);
		Iko_Global_Configurations__mdt getIkoGlobalConfigByName(String configName);
		CommunitySiteNameConfiguration__mdt getCommunitySiteNameConfigByName(String configName);
	}

	public class Impl implements IClass {

		public API_Configuration__mdt getAPIConfigByName(String configName) {
			API_Configuration__mdt returnConfig;
			
			List<API_Configuration__mdt> returnConfigs = 
				[SELECT 	Id, 
							Label,
							Endpoint__c,
							Username__c,
							Password__c,
							Source_Id__c,
							Client_Secret__c,
							Client_Id__c,
							Token__c
				FROM API_Configuration__mdt
				WHERE DeveloperName =:configName];

			if(returnConfigs.size() > 0) {
				returnConfig = returnConfigs[0];
			}

			return returnConfig;
		}

		public Iko_Global_Configurations__mdt getIkoGlobalConfigByName(String configName) {
			Iko_Global_Configurations__mdt returnConfig;
			
			List<Iko_Global_Configurations__mdt> returnConfigs = 
				[SELECT 	Id, 
							Label,
							Default_Vendor_Email__c,
							Vendor_Email_CA__c,
							Vendor_Email_US__c
				FROM Iko_Global_Configurations__mdt
				WHERE DeveloperName =:configName];

			if(returnConfigs.size() > 0) {
				returnConfig = returnConfigs[0];
			}

			return returnConfig;
		}
		
		//Added for IKO-360 by Dominic Boivin on 06-10-2020
		public CommunitySiteNameConfiguration__mdt getCommunitySiteNameConfigByName(String configName) {
			CommunitySiteNameConfiguration__mdt returnConfig;
			
			List<CommunitySiteNameConfiguration__mdt> returnConfigs = 
				[SELECT 	Id, 
							Label,
							CommunityName__c,
							CommunityNameGlobalSetValue__c
							
				FROM CommunitySiteNameConfiguration__mdt
				WHERE DeveloperName =:configName];

			if(returnConfigs.size() > 0) {
				returnConfig = returnConfigs[0];
			}

			return returnConfig;
		}
	}
}