ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/EagleView_Report__c.object-meta.xml
<CustomObject>
    <label>EagleView Report</label>
    <nameField>
        <displayFormat>EVR-{0}</displayFormat>
        <label>EagleView Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EagleView Reports</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <externalId>true</externalId>
    <label>Order Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Report_Id__c.field-meta.xml
<CustomField>
    <fullName>Report_Id__c</fullName>
    <label>Report Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Created</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>In Process</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/SubStatus__c.field-meta.xml
<CustomField>
    <fullName>SubStatus__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>29</fullName>
                <label>AddressVerified</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Canceled By Client</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Card Rejected</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>CreditCard Failure</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Customer</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Customer Response</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Duplicate</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Need To ID</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>No ID</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>No Images</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Other</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Poor Images</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Process Started</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Ready To Send</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Report Type Change</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Sent</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Site Map</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>System</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Under Review</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Wrong House</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Sent_</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icRepoEagleViewReport.cls
public class icRepoEagleViewReport implements icIClass {

	public Object GetInstance() {
		return new Impl();
	}

	public Interface IClass {
		EagleView_Report__c getEagleViewReportById(String recordId);
		void createEagleViewReport(EagleView_Report__c newReport);
		void updateEagleViewReport(EagleView_Report__c updateReport);
		void deleteEagleViewReport(EagleView_Report__c deleteReport);
	}

	public class Impl implements IClass {

		public EagleView_Report__c getEagleViewReportById(String recordId) {
			return [SELECT Id, Order_Id__c, Report_Id__c, Status__c, SubStatus__c FROM EagleView_Report__c WHERE Id = :recordId];
		}

		public void createEagleViewReport(EagleView_Report__c newReport) {
			insert newReport;
		}

		public void updateEagleViewReport(EagleView_Report__c updateReport) {
			update updateReport;
		}

		public void deleteEagleViewReport(EagleView_Report__c deleteReport) {
			delete deleteReport;
		}
	}
}