ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/EagleView_Report__c.object-meta.xml
<CustomObject>
    <label>EagleView Report</label>
    <nameField>
        <displayFormat>EVR-{0}</displayFormat>
        <label>EagleView Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EagleView Reports</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Created</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>In Process</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/SubStatus__c.field-meta.xml
<CustomField>
    <fullName>SubStatus__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>29</fullName>
                <label>AddressVerified</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Canceled By Client</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Card Rejected</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>CreditCard Failure</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Customer</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Customer Response</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Duplicate</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Need To ID</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>No ID</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>No Images</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Other</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Poor Images</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Process Started</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Ready To Send</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Report Type Change</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Sent</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Site Map</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>System</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Under Review</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Wrong House</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Sent_</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icServiceEagleViewOrderStatusUpdate.cls
@RestResource(urlMapping='/evservice/OrderStatusUpdate')
global class icServiceEagleViewOrderStatusUpdate {

	//static icLogicHomeAdvisor.IClass haLogic = (icLogicHomeAdvisor.IClass) icObjectFactory.GetSingletonInstance('icLogicHomeAdvisor');	

	@HttpGet
	global static String doGet() {
		System.debug('--------- icServiceEagleViewOrderStatusUpdate doGet ---------');

		icLogicEagleViewReport.IClass evReportLogic = (icLogicEagleViewReport.IClass) icObjectFactory.GetSingletonInstance('icLogicEagleViewReport');

		try {
			Map<String, String> requestParams = RestContext.request.params;
			String statusId = requestParams.get('StatusId');
			String subStatusId = requestParams.get('SubStatusId');
			String sfRefId = requestParams.get('RefId');
			String evRefId = requestParams.get('ReportId');

			System.debug('statusId : ' + statusId);
			System.debug('subStatusId : ' + subStatusId);
			System.debug('sfRefId : ' + sfRefId);
			System.debug('evRefId : ' + evRefId);

			EagleView_Report__c updateReport = new EagleView_Report__c(Id = sfRefId
                ,Status__c = statusId
                ,SubStatus__c = subStatusId);
        	evReportLogic.updateEagleViewReport(updateReport);
		} catch (Exception ex) {
			icServiceErrorHandler.LogError('icServiceEagleViewOrderStatusUpdate', 'doGet', ex.getStackTraceString(), ex.getMessage(), '');
		}
		
		return 'Ok';
	}
}