ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/EagleView_Report__c.object-meta.xml
<CustomObject>
    <label>EagleView Report</label>
    <nameField>
        <displayFormat>EVR-{0}</displayFormat>
        <label>EagleView Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EagleView Reports</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EagleView Reports</relationshipLabel>
    <relationshipName>EagleView_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>EagleView Reports</relationshipLabel>
    <relationshipName>EagleView_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <externalId>true</externalId>
    <label>Order Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Report_Id__c.field-meta.xml
<CustomField>
    <fullName>Report_Id__c</fullName>
    <label>Report Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Contractor_Subscription__c/IKOPRO_Contractor_Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Subscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Repository/Claims/force-app/main/default/classes/icCTRLEagleview.cls
/**
* Created by Francois Poirier on 2018-06-20.
*/
global with sharing class icCTRLEagleview {

    static icBLeagleView.IClass evBL = (icBLeagleView.IClass) icObjectFactory.GetSingletonInstance('icBLeagleView');
    static icLogicUser.IClass logicUser = (icLogicUser.IClass) icObjectFactory.GetSingletonInstance('icLogicUser');
    static icLogicSubscription.IClass logicSubscription = (icLogicSubscription.IClass) icObjectFactory.GetSingletonInstance('icLogicSubscription');
    static icLogicEagleViewReport.IClass evReportLogic = (icLogicEagleViewReport.IClass) icObjectFactory.GetSingletonInstance('icLogicEagleViewReport');

    @AuraEnabled
    global static Boolean isCustomerSubscribed(){
        Boolean isCustomerSubscribed = false;

        String customerId = logicUser.getAccountIdFromPartnerUser(UserInfo.getUserId());
        List<IKOPRO_Contractor_Subscription__c> customerSubscriptions = logicSubscription.getEagleViewSubscriptionForCustomer(customerId);

        if(customerSubscriptions.size() == 1) {
            isCustomerSubscribed = true;
        }

        return isCustomerSubscribed;
    }

    @AuraEnabled
    global static Boolean isCommunity(String sPageURL){

       if (sPageURL.contains('lightning')){
           return false;
       }else return true;
    }

    @AuraEnabled
    global static List<icDTOEagleViewProduct> getAvailableProducts(){
        List<icDTOEagleViewProduct> returnAvailableProducts;
        
        String customerId = logicUser.getAccountIdFromPartnerUser(UserInfo.getUserId());
        List<IKOPRO_Contractor_Subscription__c> customerSubscriptions = logicSubscription.getEagleViewSubscriptionForCustomer(customerId);
        
        if(customerSubscriptions.size() == 1) {
            IKOPRO_Contractor_Subscription__c eagleViewSubsciption = customerSubscriptions[0];            
            returnAvailableProducts = evBL.getAvailableProducts();
        }

        return returnAvailableProducts;
    }

    @AuraEnabled
    global static icDTOEagleViewPlaceOrderResponse placeOrder(String strOrder){ 
        icDTOEagleViewPlaceOrderResponse placeOrderResponse = new icDTOEagleViewPlaceOrderResponse();

        try {
            String customerId = logicUser.getAccountIdFromPartnerUser(UserInfo.getUserId());
            List<IKOPRO_Contractor_Subscription__c> customerSubscriptions = logicSubscription.getEagleViewSubscriptionForCustomer(customerId);

            if(customerSubscriptions.size() == 1) {
                IKOPRO_Contractor_Subscription__c eagleViewSubsciption = customerSubscriptions[0];
                placeOrderResponse = evBL.placeOrder(strOrder, eagleViewSubsciption.Username__c);
            }            
        } catch (Exception ex ) {
            System.debug(ex.getMessage());
            String errorRef = icServiceErrorHandler.LogError('icCTRLEagleview', 'placeOrder', ex.getStackTraceString(), ex.getMessage(), strOrder);
            placeOrderResponse.message = Label.icAn_Exception_Occured_please_contact_IKO_for_assistance_with_this_reference_Id + errorRef;
        }

        return placeOrderResponse;
    }

    @AuraEnabled
    global static String createOrder(String orderDetailsJSON, String opportunityId){
        try {
            icDTOEagleViewOrderForm orderForm = (icDTOEagleViewOrderForm)JSON.deserialize(orderDetailsJSON, icDTOEagleViewOrderForm.Class);

            String customerId = logicUser.getAccountIdFromPartnerUser(UserInfo.getUserId());

            EagleView_Report__c newReport = evReportLogic.generateEagleViewReportFromOrderForm(orderForm);
            newReport.Account__c = customerId;
            newReport.Opportunity__c = opportunityId;

            evReportLogic.createEagleViewReport(newReport);
            return newReport.Id;
        } catch (Exception ex ) {
            System.debug(ex.getMessage());
            String errorRef = icServiceErrorHandler.LogError('icCTRLEagleview', 'createOrder', ex.getStackTraceString(), ex.getMessage(), orderDetailsJSON);
            return Label.icAn_Exception_Occured_please_contact_IKO_for_assistance_with_this_reference_Id + errorRef;
        }
    }

    @AuraEnabled
    global static String setOrderIds(String sfOrderId, String jsonOrderInfo){
        try {
            icDTOEagleViewPlaceOrderResponse orderInfo = (icDTOEagleViewPlaceOrderResponse)JSON.deserialize(jsonOrderInfo, icDTOEagleViewPlaceOrderResponse.Class);
            
            EagleView_Report__c updateReport = new EagleView_Report__c(Id = sfOrderId);
            if(orderInfo.OrderId == null) {
                evReportLogic.deleteEagleViewReport(updateReport);
            } else {
                updateReport.Order_Id__c = String.valueOf(orderInfo.OrderId);
                updateReport.Report_Id__c = String.valueOf(orderInfo.ReportIds[0]);
                evReportLogic.updateEagleViewReport(updateReport);
            }
            return Label.icSuccess;
        } catch (Exception ex ) {
            System.debug(ex.getMessage());
            String errorRef = icServiceErrorHandler.LogError('icCTRLEagleview', 'setOrderIds', ex.getStackTraceString(), ex.getMessage(), jsonOrderInfo);
            return Label.icAn_Exception_Occured_please_contact_IKO_for_assistance_with_this_reference_Id + errorRef;
        }
    }

    @AuraEnabled
    global static String cancelOrder(String recordId) {
        try {
            String returnResult = Label.icInternal_Error_Could_not_cancel_Order;
            EagleView_Report__c thisReport = evReportLogic.getEagleViewReportById(recordId);

            String customerId = logicUser.getAccountIdFromPartnerUser(UserInfo.getUserId());
            List<IKOPRO_Contractor_Subscription__c> customerSubscriptions = logicSubscription.getEagleViewSubscriptionForCustomer(customerId);

            if(customerSubscriptions.size() == 1) {
                IKOPRO_Contractor_Subscription__c eagleViewSubsciption = customerSubscriptions[0];            
                returnResult = evBL.cancelOrder(thisReport.Report_Id__c);
            }
            
            return returnResult;
        } catch (Exception ex ) {
            System.debug(ex.getMessage());
            String errorRef = icServiceErrorHandler.LogError('icCTRLEagleview', 'cancelOrder', ex.getStackTraceString(), ex.getMessage(), recordId);
            return Label.icAn_Exception_Occured_please_contact_IKO_for_assistance_with_this_reference_Id + errorRef;
        }
    }

    @AuraEnabled
    global static icDTOGenericResult subscribe(String eagleviewUsername, String eagleviewPassword) {
        icDTOGenericResult returnResult = new icDTOGenericResult();

        try {
            returnResult = evBL.grantUserOrderDelegation(eagleviewUsername, eagleviewPassword);

            System.debug('delegate result : ' + returnResult);

            if(returnResult.isSuccess) {
                String customerId = logicUser.getAccountIdFromPartnerUser(UserInfo.getUserId());
                List<IKOPRO_Contractor_Subscription__c> customerSubscriptions = logicSubscription.getEagleViewSubscriptionForCustomer(customerId);

                if(customerSubscriptions.size() == 1) {
                    IKOPRO_Contractor_Subscription__c eagleViewSubsciption = customerSubscriptions[0];
                    eagleViewSubsciption.Username__c = eagleviewUsername;
                    logicSubscription.updateEagleViewSubscription(eagleViewSubsciption);
                } else {
                    logicSubscription.createEagleViewSubscription(customerId, eagleviewUsername);
                }

                returnResult.message = Label.icYou_are_successfully_subscribed_to_EagleView;
            }
        } catch (Exception ex) {
            System.debug(ex.getMessage());
            String errorRef;
            errorRef = icServiceErrorHandler.LogError('icCTRLEagleview', 'subscribe', ex.getStackTraceString(), ex.getMessage(), eagleviewUsername);
            system.debug('errorRef ===> ' + errorRef);
            system.debug('returnResult ===> ' + returnResult);
            if(returnResult == null){
                returnResult = new icDTOGenericResult();
            }
            returnResult.message = Label.icAn_Exception_Occured_please_contact_IKO_for_assistance_with_this_reference_Id + errorRef;
            returnResult.isSuccess = false;            
        }

        System.debug('final result : ' + returnResult);
        
        return returnResult;
    }
}