ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/EagleView_Report__c.object-meta.xml
<CustomObject>
    <label>EagleView Report</label>
    <nameField>
        <displayFormat>EVR-{0}</displayFormat>
        <label>EagleView Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EagleView Reports</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EagleView Reports</relationshipLabel>
    <relationshipName>EagleView_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Changes_in_the_last_4_years__c.field-meta.xml
<CustomField>
    <fullName>Changes_in_the_last_4_years__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Changes in the last 4 years</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Download_Link__c.field-meta.xml
<CustomField>
    <fullName>Download_Link__c</fullName>
    <label>Download Link</label>
    <type>Url</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Measurement_Type__c.field-meta.xml
<CustomField>
    <fullName>Measurement_Type__c</fullName>
    <label>Measurement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>PrimaryPlusDetachedGarage</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>PrimaryStructureOnly</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>AllStructuresOnParcel</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>CommercialComplex</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Residential</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Commercial</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>MultiFamily</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Report_Id__c.field-meta.xml
<CustomField>
    <fullName>Report_Id__c</fullName>
    <label>Report Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Special_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Special_Instructions__c</fullName>
    <label>Special Instructions</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Created</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>In Process</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/SubStatus__c.field-meta.xml
<CustomField>
    <fullName>SubStatus__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>29</fullName>
                <label>AddressVerified</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Canceled By Client</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Card Rejected</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>CreditCard Failure</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Customer</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Customer Response</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Duplicate</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Need To ID</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>No ID</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>No Images</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Other</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Poor Images</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Process Started</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Ready To Send</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Report Type Change</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Sent</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Site Map</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>System</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Under Review</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Wrong House</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Sent_</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Contractor_Subscription__c/IKOPRO_Contractor_Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Subscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Contractor_Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Repository/Claims/force-app/main/default/classes/icLogicEagleViewReport.cls
public class icLogicEagleViewReport implements icIClass {

	public Object GetInstance() {
		return new Impl();
	}

	public Interface IClass {
		EagleView_Report__c generateEagleViewReportFromOrderForm(icDTOEagleViewOrderForm orderForm);
		EagleView_Report__c getEagleViewReportById(String recordId);
		void getEagleViewDownloadReportLink(EagleView_Report__c evReport);
		void createEagleViewReport(EagleView_Report__c newReport);
		void updateEagleViewReport(EagleView_Report__c updateReport);
		void deleteEagleViewReport(EagleView_Report__c deleteReport);
	}

	public class Impl implements IClass {

		icRepoEagleViewReport.IClass repo = (icRepoEagleViewReport.IClass) icObjectFactory.GetSingletonInstance('icRepoEagleViewReport');		

		public EagleView_Report__c generateEagleViewReportFromOrderForm(icDTOEagleViewOrderForm orderForm) {
			EagleView_Report__c returnEVReport = new EagleView_Report__c(Status__c = '1'
				,SubStatus__c = '1'
				,Street_Address__c = orderForm.streetAddress
				,City__c = orderForm.city
				,State_Province__c = orderForm.state
				,Zip_Postal_Code__c = orderForm.postalCode
				,Country__c = orderForm.country
				,Property_Type__c = String.valueOf(orderForm.propertyType)
				,Product__c = orderForm.product.name
				,Delivery__c = orderForm.delivery.name
				,Measurement_Type__c = String.valueOf(orderForm.measurementType)
				,Special_Instructions__c = orderForm.specialInstructions
				,Changes_in_the_last_4_years__c = orderForm.changesInLast4Years);
			return returnEVReport;
		}

		public EagleView_Report__c getEagleViewReportById(String recordId) {
			return repo.getEagleViewReportById(recordId);
		}

		public void getEagleViewDownloadReportLink(EagleView_Report__c evReport) {
			getDownloadLink(evReport.Id, evReport.Account__c, evReport.Report_Id__c);
		}

		public void createEagleViewReport(EagleView_Report__c newReport) {
			repo.createEagleViewReport(newReport);
		}

		public void updateEagleViewReport(EagleView_Report__c updateReport) {
			repo.updateEagleViewReport(updateReport);
		}

		public void deleteEagleViewReport(EagleView_Report__c deleteReport) {
			repo.deleteEagleViewReport(deleteReport);
		}
	}

	@future(callout=true)
	private static void getDownloadLink(String sfReportId, String accountId, String evReportId) {
		icBLeagleView.IClass evService = (icBLeagleView.IClass) icObjectFactory.GetSingletonInstance('icBLeagleView');
		icLogicSubscription.IClass logicSubscription = (icLogicSubscription.IClass) icObjectFactory.GetSingletonInstance('icLogicSubscription');
		icRepoEagleViewReport.IClass repo = (icRepoEagleViewReport.IClass) icObjectFactory.GetSingletonInstance('icRepoEagleViewReport');		

		List<IKOPRO_Contractor_Subscription__c> customerSubscriptions = logicSubscription.getEagleViewSubscriptionForCustomer(accountId);

		if(customerSubscriptions.size() == 1) {
			IKOPRO_Contractor_Subscription__c eagleViewSubsciption = customerSubscriptions[0];
			String reportDownalodLink = evService.getDownloadLink(evReportId);

			EagleView_Report__c updateReport = new EagleView_Report__c(Id = sfReportId, Download_Link__c = reportDownalodLink);
			repo.updateEagleViewReport(updateReport);
        }
    }
}