ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CommunitySiteNameConfiguration__mdt/CommunitySiteNameConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>This metadata contains the information related to the Site Name Community and help to bind the value to the CommunityName global setvalue used in Calendar event and Whatshappening configuration.</description>
    <label>Community Site Name Configuration</label>
    <pluralLabel>Community Site Name Configurations</pluralLabel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CommunitySiteNameConfiguration__mdt/fields/CommunityNameGlobalSetValue__c.field-meta.xml
<CustomField>
    <fullName>CommunityNameGlobalSetValue__c</fullName>
    <description>This value must match the API NAME Value of the corresponding Picklist list Item in the global value set named CommunityName</description>
    <label>CommunityNameGlobalSetValue</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/Contractor_Invoice__c.object-meta.xml
<CustomObject>
    <label>Uploaded Invoice</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Uploaded Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>IKOPRO Contractor, IKOPRO Contractor HA OK</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Uploaded Invoices</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/File_s_Attached__c.field-meta.xml
<CustomField>
    <fullName>File_s_Attached__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Ticked by flow when at least one FileID is captured.</description>
    <label>File(s) Attached</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <label>Date of Upload</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Rebate_Program_CA__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Program_CA__c</fullName>
    <label>Rebate Program (CA)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>REWARDSELEVATEDCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Rebate_Program_CRC_c__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Program_CRC_c__c</fullName>
    <label>Rebate_Program_CRC_c</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rebate_Program_CRC_c</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Rebate_Program_US__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Program_US__c</fullName>
    <label>Rebate Program (US)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2021BONUSREWARDS</fullName>
            </value>
            <value>
                <fullName>2018CONTRACTOR</fullName>
                <isActive>false</isActive>
                <label>2018CONTRACTOR</label>
            </value>
            <value>
                <fullName>2018PRO4-US</fullName>
                <isActive>false</isActive>
                <label>2018PRO4-US</label>
            </value>
            <value>
                <fullName>2019CONTRACTOR</fullName>
                <isActive>false</isActive>
                <label>2019CONTRACTOR</label>
            </value>
            <value>
                <fullName>2019PRO4-US</fullName>
                <isActive>false</isActive>
                <label>2019PRO4-US</label>
            </value>
            <value>
                <fullName>2019SPIFF</fullName>
                <isActive>false</isActive>
                <label>2019SPIFF</label>
            </value>
            <value>
                <fullName>2020BONUSREWARDSUS</fullName>
                <isActive>false</isActive>
                <label>2020BONUSREWARDSUS</label>
            </value>
            <value>
                <fullName>250WRAPREBATE2019</fullName>
                <isActive>false</isActive>
                <label>250WRAPREBATE2019</label>
            </value>
            <value>
                <fullName>500WRAPREBATE2019</fullName>
                <isActive>false</isActive>
                <label>500WRAPREBATE2019</label>
            </value>
            <value>
                <fullName>NOT A VALID CODE</fullName>
                <isActive>false</isActive>
                <label>NOT A VALID CODE</label>
            </value>
            <value>
                <fullName>SALUTEMILITARY2019</fullName>
                <isActive>false</isActive>
                <label>SALUTEMILITARY2019</label>
            </value>
            <value>
                <fullName>SALUTEMILITARY2019-D</fullName>
                <isActive>false</isActive>
                <label>SALUTEMILITARY2019-D</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Action Required</label>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Upload Failed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Ready for Upload</fullName>
            </value>
            <value>
                <fullName>DO NOT PAY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Uploaded_Files_Long__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_Files_Long__c</fullName>
    <label>Uploaded Files</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/User_Email__c.field-meta.xml
<CustomField>
    <fullName>User_Email__c</fullName>
    <label>User_Email</label>
    <type>Email</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/User_FirstName__c.field-meta.xml
<CustomField>
    <fullName>User_FirstName__c</fullName>
    <label>User_FirstName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/User_LastName__c.field-meta.xml
<CustomField>
    <fullName>User_LastName__c</fullName>
    <label>User_LastName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/User_Mobile__c.field-meta.xml
<CustomField>
    <fullName>User_Mobile__c</fullName>
    <label>User_Mobile</label>
    <type>Phone</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/User_Phone__c.field-meta.xml
<CustomField>
    <fullName>User_Phone__c</fullName>
    <label>User_Phone</label>
    <type>Phone</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/recordTypes/Uploaded_Invoice.recordType-meta.xml
<RecordType>
    <fullName>Uploaded_Invoice</fullName>
    <active>true</active>
    <label>Uploaded Invoice</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icLogicContractorInvoice.cls
/**
* Created by Francois Poirier on 2019-11-18.
*/

public with sharing class icLogicContractorInvoice implements icIClass {
    
    public Object GetInstance() {
        return new Impl();
    }
    
    public Interface IClass {
        
        void saveContractorInvoice(Contractor_Invoice__c invoice);
        Contractor_Invoice__c createNewContractorInvoiceFromProgram(String rebateProgram, Contractor_Invoice__c newInvoice);
        Contractor_Invoice__c createNewContractorInvoiceFromProgram(String rebateProgram);
        List<icDtoPickList> getRebatePrograms();
        
        Contractor_Invoice__c getContractorInvoiceById(Id contractorInvoiceId);
        void removeFileIdsFromContractInvoice(Id contractorInvoiceId,  List<String> fileIds);
        void deleteContractorInvoiceById(Id contractorInvoiceId);
    }
    
    public class Impl implements IClass {
        
        private icRepoContractorInvoice.IClass repoContractorInvoice = (icRepoContractorInvoice.IClass) icObjectFactory.GetSingletonInstance('icRepoContractorInvoice');
        private icLogicUser.IClass logicUser = (icLogicUser.IClass) icObjectFactory.GetSingletonInstance('icLogicUser');
        private icUtilSchema.IClass utilSchema = (icUtilSchema.IClass) icObjectFactory.GetSingletonInstance('icUtilSchema');
        private icLogicConfig.IClass logicConfig = (icLogicConfig.IClass) icObjectFactory.GetSingletonInstance('icLogicConfig');
        public void saveContractorInvoice(Contractor_Invoice__c invoice){
            
            
            Id uploadedRecordTypeId = Schema.SObjectType.Contractor_Invoice__c.getRecordTypeInfosByDeveloperName().get('Uploaded_Invoice').getRecordTypeId();
            invoice.Status__c = 'Uploaded';
            invoice.RecordTypeId = uploadedRecordTypeId;
            
            repoContractorInvoice.saveContractorInvoice(invoice);
            
        }
        
        public Contractor_Invoice__c createNewContractorInvoiceFromProgram(String rebateProgram){
            return createNewContractorInvoiceFromProgram(rebateProgram, new Contractor_Invoice__c());
        }
        
        public Contractor_Invoice__c createNewContractorInvoiceFromProgram(String rebateProgram, Contractor_Invoice__c newInvoice){
            //Contractor_Invoice__c newInvoice = new Contractor_Invoice__c();
            //TODO: remove hard coded id
            User currentUser = logicUser.getUserAndAccountFromPartnerUser(UserInfo.getUserId());
            
            
            //            User currentUser = logicUser.getUserAndAccountFromPartnerUser('0051F000002KbBkQAK');
            newInvoice.Contractor__c = currentUser.Contact.AccountId;
            
             String communityName;
            if(System.Test.isRunningTest()){
               communityName = icTestLogicContractorInvoice.siteName;
            }
            else{
               communityName = Site.getName();
                
            }
            CommunitySiteNameConfiguration__mdt communityConfig = logicConfig.getCommunitySiteNameConfigByName(communityName);
            if(communityConfig.CommunityNameGlobalSetValue__c == 'CRC_C'){
                newInvoice.Rebate_Program_CRC_c__c = rebateProgram;
            } else if(communityConfig.CommunityNameGlobalSetValue__c == 'IKOROOFPRO_C'){
                
                if(currentUser.Contact.Account.BillingCountry == 'Canada'){
                    newInvoice.Rebate_Program_CA__c = rebateProgram;
                }
                else {
                    newInvoice.Rebate_Program_US__c = rebateProgram;
                }
            }
                
            
            newInvoice.Invoice_Date__c = System.today();
            newInvoice.User_FirstName__c = currentUser.Contact.FirstName;
            newInvoice.User_LastName__c = currentUser.Contact.LastName;
            newInvoice.User_Email__c = currentUser.Contact.Email;
            newInvoice.User_Mobile__c = currentUser.Contact.MobilePhone;
            newInvoice.User_Phone__c = currentUser.Contact.Phone;
            
            repoContractorInvoice.saveContractorInvoice(newInvoice);
            newInvoice = getContractorInvoiceById(newInvoice.Id);
            
            return newInvoice;
        }
        
        public List<icDtoPickList> getRebatePrograms(){
            
            List<icDtoPickList> rebatePrograms = new List<icDtoPickList>();
            //TODO: remove hard coded Id
            
            String communityName;
            if(System.Test.isRunningTest()){
               communityName = icTestLogicContractorInvoice.siteName;
            }
            else{
               communityName = Site.getName();
                
            }
            CommunitySiteNameConfiguration__mdt communityConfig = logicConfig.getCommunitySiteNameConfigByName(communityName);
            
            if(communityConfig.CommunityNameGlobalSetValue__c == 'CRC_C')
            {
                rebatePrograms = utilSchema.getPickListValues('Contractor_Invoice__c', 'Rebate_Program_CRC_c__c');
            }
            else if(communityConfig.CommunityNameGlobalSetValue__c == 'IKOROOFPRO_C'){
                User currentUser = logicUser.getUserAndAccountFromPartnerUser(UserInfo.getUserId());
                //            User currentUser = logicUser.getUserAndAccountFromPartnerUser('0051F000002KbBkQAK');
                system.debug('currentUser.Contact.Account.BillingCountry ===> ' + currentUser.Contact.Account.BillingCountry);
                
                if(currentUser.Contact.Account.BillingCountry == 'Canada'){
                    rebatePrograms = utilSchema.getPickListValues('Contractor_Invoice__c', 'Rebate_Program_CA__c');
                }
                else{
                    rebatePrograms = utilSchema.getPickListValues('Contractor_Invoice__c', 'Rebate_Program_US__c');
                }
            }
            
            
            system.debug('rebate programs ====> ' + rebatePrograms);
            return rebatePrograms;
        }
        
        public Contractor_Invoice__c getContractorInvoiceById(Id contractorInvoiceId){
            
            return repoContractorInvoice.getContractorInvoiceById(contractorInvoiceId);
            
        }
        
        public void removeFileIdsFromContractInvoice(Id contractorInvoiceId, List<String> fileIds){
            
            List<Contractor_Invoice__c> contractInvoices = [SELECT Id, Uploaded_Files_Long__c FROM Contractor_Invoice__c WHERE ID = :contractorInvoiceId];
            List<String> documentIds = new List<String>();
            
            if(contractInvoices[0].Uploaded_Files_Long__c != null){
                for(String documentId : contractInvoices[0].Uploaded_Files_Long__c.split(',')){
                    if(String.isNotBlank(documentId) && !fileIds.contains(documentId.trim())){
                        documentIds.add(documentId);
                    }
                }
                if(documentIds.isEmpty()){
                    contractInvoices[0].Uploaded_Files_Long__c = '';
                    contractInvoices[0].File_s_Attached__c = false;
                }else{
                    contractInvoices[0].Uploaded_Files_Long__c = String.join(documentIds, ',');
                    contractInvoices[0].Uploaded_Files_Long__c += ',';
                    contractInvoices[0].File_s_Attached__c = true;
                }
                update contractInvoices;
            }
        }
        
        public void deleteContractorInvoiceById(Id contractorInvoiceId){
            
            List<Contractor_Invoice__c> contractInvoices = new List<Contractor_Invoice__c>();
            contractInvoices.add(new Contractor_Invoice__c(Id = contractorInvoiceId));
            DELETE contractInvoices;
        }
        
    }
    
}