ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CommunitySiteNameConfiguration__mdt/CommunitySiteNameConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>This metadata contains the information related to the Site Name Community and help to bind the value to the CommunityName global setvalue used in Calendar event and Whatshappening configuration.</description>
    <label>Community Site Name Configuration</label>
    <pluralLabel>Community Site Name Configurations</pluralLabel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CommunitySiteNameConfiguration__mdt/fields/CommunityNameGlobalSetValue__c.field-meta.xml
<CustomField>
    <fullName>CommunityNameGlobalSetValue__c</fullName>
    <description>This value must match the API NAME Value of the corresponding Picklist list Item in the global value set named CommunityName</description>
    <label>CommunityNameGlobalSetValue</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/What_s_Happening__c/What_s_Happening__c.object-meta.xml
<CustomObject>
    <description>This object contains content to generate quick view cards of current events and activities within the community.</description>
    <label>What&apos;s Happening</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>What&apos;s Happening</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icCtrlWhatsHappening.cls
global with sharing class icCtrlWhatsHappening {

	static icLogicWhatsHappening.IClass logicWhatsHappening = (icLogicWhatsHappening.IClass) icObjectFactory.GetSingletonInstance('icLogicWhatsHappening');
	static icLogicUser.IClass logicUser = (icLogicUser.IClass) icObjectFactory.GetSingletonInstance('icLogicUser');
    static icLogicConfig.IClass logicConfig = (icLogicConfig.IClass) icObjectFactory.GetSingletonInstance('icLogicConfig');

	@AuraEnabled
	global static icDTOWhatsHappeningResult getWhatsHappening() {
		icDTOWhatsHappeningResult returnResult = new icDTOWhatsHappeningResult();

		User thisUSerInfo = logicUser.getUserAndAccountFromPartnerUser(UserInfo.getUserId());
		
		//IKO-240 Get the community Name to filter the What's happening object.
		String communityName = Site.getName();
		CommunitySiteNameConfiguration__mdt communityConfig = logicConfig.getCommunitySiteNameConfigByName(communityName);
		system.debug('Community Name ===> ' + communityName);
		List<What_s_Happening__c> listWhatsHappening = logicWhatsHappening.getActiveWhatHappeningByLanguageAndCommunityName(thisUSerInfo.ROOFPRO_Portal_Language__c, communityConfig.CommunityNameGlobalSetValue__c);
        returnResult.content = logicWhatsHappening.getListDTOFromWhatHappening(listWhatsHappening);
		returnResult.theme = UserInfo.getUiThemeDisplayed();

		return returnResult;
	}
}