ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CommunitySiteNameConfiguration__mdt/CommunitySiteNameConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>This metadata contains the information related to the Site Name Community and help to bind the value to the CommunityName global setvalue used in Calendar event and Whatshappening configuration.</description>
    <label>Community Site Name Configuration</label>
    <pluralLabel>Community Site Name Configurations</pluralLabel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CommunitySiteNameConfiguration__mdt/fields/CommunityNameGlobalSetValue__c.field-meta.xml
<CustomField>
    <fullName>CommunityNameGlobalSetValue__c</fullName>
    <description>This value must match the API NAME Value of the corresponding Picklist list Item in the global value set named CommunityName</description>
    <label>CommunityNameGlobalSetValue</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/What_s_Happening__c/What_s_Happening__c.object-meta.xml
<CustomObject>
    <description>This object contains content to generate quick view cards of current events and activities within the community.</description>
    <label>What&apos;s Happening</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>What&apos;s Happening</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Repository/Claims/force-app/main/default/classes/icTestCtrlWhatsHappening.cls
@isTest
public with sharing class icTestCtrlWhatsHappening {

	public static testMethod void test_getWhatsHappening(){
		CommunitySiteNameConfiguration__mdt config = new CommunitySiteNameConfiguration__mdt();
        config.CommunityNameGlobalSetValue__c = 'IKOROOFPRO_C';

        icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicConfig', new icLogicConfigMock());
        icTestMockUtilities.Tracer.SetReturnValue('icLogicConfigMock', 'getCommunitySiteNameConfigByName', config);
        
		icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicUser', new icLogicUserMock());
		icTestMockUtilities.Tracer.SetReturnValue('icLogicUserMock', 'getUserAndAccountFromPartnerUser', new User());
		icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicWhatsHappening', new icLogicWhatsHappeningMock());
		icTestMockUtilities.Tracer.SetReturnValue('icLogicWhatsHappeningMock', 'getActiveWhatHappeningByLanguageAndCommunityName', new List<What_s_Happening__c>());
		icTestMockUtilities.Tracer.SetReturnValue('icLogicWhatsHappeningMock', 'getListDTOFromWhatHappening', new List<icDTOWhatsHappening>());

		icCtrlWhatsHappening.getWhatsHappening();
	}
}