ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Cleanup_Schedulables_Config__mdt/EU_Cleanup_Schedulables_Config__mdt.object-meta.xml
<CustomObject>
    <description>Used to define which objects, including children, should be cleaned up at what intervals.</description>
    <label>Cleanup Schedulables Config</label>
    <pluralLabel>Cleanup Schedulables Configs</pluralLabel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Cleanup_Schedulables_Config__mdt/fields/Maximum_Age__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Age__c</fullName>
    <description>The maximum age which an object may have before it will be cleaned up. To be defined in DAYS.</description>
    <inlineHelpText>The maximum age which an object may have before it will be cleaned up. To be defined in DAYS.</inlineHelpText>
    <label>Maximum Age</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Cleanup_Schedulables_Config__mdt/fields/Target_Object_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Object_Developer_Name__c</fullName>
    <description>The DEVELOPER NAME of the object which should be cleaned up.</description>
    <inlineHelpText>The DEVELOPER NAME of the object which should be cleaned up.</inlineHelpText>
    <label>Target Object Developer Name</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/EU_Open_Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>OI-{YYYY}-{0000000}</displayFormat>
        <label>Open Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Open_Invoice__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Invoice__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Invoice Paid</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/CleanupSchedulable_EuOpenInvoice.cls
/**
 * Created by Gerard van Kempen on 2019-12-18.
 * 2019 (C) 4C NV, Mechelen Belgium.
 * Last modified as part of project 'IKO SFDC'.
 */

global class CleanupSchedulable_EuOpenInvoice implements Schedulable {

    global static final String jobName = 'Cleanup (daily) - Closed EU_Open_Invoice__c';

    global void execute(SchedulableContext context) {
        this.run();
    }

    global static void schedule() {
        String cronExp = '0 40 3 * * ?';
        System.schedule(jobName, cronExp, (new CleanupSchedulable_EuOpenInvoice()));
    }

    global void run() {
        final Datetime today = Datetime.now();
        final List<EU_Cleanup_Schedulables_Config__mdt> configsList = [
                SELECT Target_Object_Developer_Name__c, Maximum_Age__c
                FROM EU_Cleanup_Schedulables_Config__mdt
                WHERE Target_Object_Developer_Name__c = :EU_Open_Invoice__c.class.getName()
        ];
        if(configsList.size() != 1) {
            System.debug(LoggingLevel.ERROR, 'could not load configuration for schedulable: configuration is missing or ambiguous');
            return;
        }
        final EU_Cleanup_Schedulables_Config__mdt config = configsList.get(0);
        Date maxDate = today.addDays(-((Integer)config.Maximum_Age__c)).date();

        if (System.Test.isRunningTest()) {
            // set date to tomorrow because we can't alter lastmodifieddate
            maxDate = today.addDays(1).date();
        }

        List<EU_Open_Invoice__c> invoicesToBeDeleted = [
                SELECT Id
                FROM EU_Open_Invoice__c
                WHERE EU_Open_Invoice__c = TRUE
                AND LastModifiedDate < :maxDate LIMIT 10000
        ];
        try {
            delete invoicesToBeDeleted;
        } catch(Exception e) {
            System.debug(LoggingLevel.ERROR, 'could not delete objects: DML returned an error');
            System.debug(LoggingLevel.ERROR, e);
        }
    }
}