ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Cleanup_Schedulables_Config__mdt/EU_Cleanup_Schedulables_Config__mdt.object-meta.xml
<CustomObject>
    <description>Used to define which objects, including children, should be cleaned up at what intervals.</description>
    <label>Cleanup Schedulables Config</label>
    <pluralLabel>Cleanup Schedulables Configs</pluralLabel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Cleanup_Schedulables_Config__mdt/fields/Maximum_Age__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Age__c</fullName>
    <description>The maximum age which an object may have before it will be cleaned up. To be defined in DAYS.</description>
    <inlineHelpText>The maximum age which an object may have before it will be cleaned up. To be defined in DAYS.</inlineHelpText>
    <label>Maximum Age</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Cleanup_Schedulables_Config__mdt/fields/Target_Object_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Object_Developer_Name__c</fullName>
    <description>The DEVELOPER NAME of the object which should be cleaned up.</description>
    <inlineHelpText>The DEVELOPER NAME of the object which should be cleaned up.</inlineHelpText>
    <label>Target Object Developer Name</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/EU_Price_Agreement__c.object-meta.xml
<CustomObject>
    <label>Price Header</label>
    <nameField>
        <displayFormat>PA-{YY}-{0000000}</displayFormat>
        <label>Price Header ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/EU_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>EU_Expiry_Date__c</fullName>
    <description>Rollup of the latest Expiry Date of the Price Lines</description>
    <label>Expiry Date</label>
    <summarizedField>EU_Price_Item__c.EU_Expiry_Date__c</summarizedField>
    <summaryForeignKey>EU_Price_Item__c.EU_Pricing_Agreement__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Item__c/EU_Price_Item__c.object-meta.xml
<CustomObject>
    <label>Price Line</label>
    <nameField>
        <displayFormat>PI-{YY}-{0000000}</displayFormat>
        <label>Price Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Item__c/fields/EU_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>EU_Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Item__c/fields/EU_Pricing_Agreement__c.field-meta.xml
<CustomField>
    <fullName>EU_Pricing_Agreement__c</fullName>
    <label>Price Header</label>
    <referenceTo>EU_Price_Agreement__c</referenceTo>
    <relationshipLabel>Price Lines</relationshipLabel>
    <relationshipName>Price_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/CleanupSchedulable_EuPricingAgreement.cls
/**
 * Created by Gerard van Kempen on 2019-12-24.
 * 2019 (C) 4C NV, Mechelen Belgium.
 * Last modified as part of project 'IKO SFDC'.
 */

public class CleanupSchedulable_EuPricingAgreement implements Schedulable {

    public static final String jobName = 'Cleanup (daily) - Expired EU_Price_Agreement__c';

    public void execute(SchedulableContext context) {
        this.run();
    }

    public static void schedule() {
        String cronExp = '0 0 3 * * ?';
        System.schedule(jobName, cronExp, (new CleanupSchedulable_EuPricingAgreement()));
    }

    private class IntTuple {
        public Integer field_0 = 0;
        public Integer field_1 = 0;
    }

    private void run() {
        final Datetime today = Datetime.now();
        final List<EU_Cleanup_Schedulables_Config__mdt> configsList = [
                SELECT Target_Object_Developer_Name__c, Maximum_Age__c
                FROM EU_Cleanup_Schedulables_Config__mdt
                WHERE Target_Object_Developer_Name__c = :EU_Price_Item__c.class.getName()
        ];
        if(configsList.size() != 1) {
            System.debug(LoggingLevel.ERROR, 'could not load configuration for schedulable: configuration is missing or ambiguous');
            return;
        }
        final EU_Cleanup_Schedulables_Config__mdt config = configsList.get(0);
        Date maxDate = today.addDays(-((Integer)config.Maximum_Age__c)).date();

        if (System.Test.isRunningTest()) {
            maxDate = today.addDays(-48).date();
        }

        List<EU_Price_Item__c> expiredPriceItems = [
                SELECT Id, EU_Pricing_Agreement__c, EU_Expiry_Date__c
                FROM EU_Price_Item__c
                WHERE EU_Expiry_Date__c < :maxDate
        ];

        Set<Id> priceAgreementsWithExpiredItemsIds = new Set<Id>();
        for(EU_Price_Item__c item : expiredPriceItems) {
            priceAgreementsWithExpiredItemsIds.add(item.EU_Pricing_Agreement__c);
        }

        try {
            delete expiredPriceItems;
        } catch(Exception e) {
            System.debug(LoggingLevel.ERROR, 'could not delete objects: DML returned an error');
            System.debug(LoggingLevel.ERROR, e);
        }


        List<EU_Price_Agreement__c> agreementsToCheckForHavingChildren = [
                SELECT Id, (SELECT Id FROM Price_Items__r)
                FROM EU_Price_Agreement__c
                WHERE Id IN :priceAgreementsWithExpiredItemsIds
        ];

        List<EU_Price_Agreement__c> agreementsWithoutChildren = new List<EU_Price_Agreement__c>();
        for(EU_Price_Agreement__c agreement : agreementsToCheckForHavingChildren) {
            if(agreement.Price_Items__r.isEmpty()) {
                agreementsWithoutChildren.add(agreement);
            }
        }

        try {
            delete agreementsWithoutChildren;
        } catch(Exception e) {
            System.debug(LoggingLevel.ERROR, 'could not delete objects: DML returned an error');
            System.debug(LoggingLevel.ERROR, e);
        }
    }
}