ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/PRM_Comment__c/PRM_Comment__c.object-meta.xml
<CustomObject>
    <description>https://ikoussfsc.atlassian.net/browse/CLAIMSV2-66
Capture the Plant Reporting Module (PRM) comments by Plant Team.</description>
    <label>PRM Comment</label>
    <nameField>
        <displayFormat>PRMComment-{00000}</displayFormat>
        <label>PRM Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRM Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/PRM_Comment__c/fields/Plant_Manager__c.field-meta.xml
<CustomField>
    <fullName>Plant_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CLAIMS - 626. Populated with Plant Manager&apos;s user id to be used in approval proces</description>
    <label>Plant Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PRM_Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/PRM_Comment__c/fields/PRM_Approval_Submitter__c.field-meta.xml
<CustomField>
    <fullName>PRM_Approval_Submitter__c</fullName>
    <description>CLAIMS - 626. Populated by the initial actions of the PRM Approval process</description>
    <label>PRM Approval Submitter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/PRMCommentsService.cls
public class PRMCommentsService {

    public static void populateAssigneeForPlantManagerApproval(List<PRM_Comment__c> newComments,Map<Id,PRM_Comment__c> mapOldComments){
        User runningUser = [SELECT Id, Profile.Name FROM User WHERE Id = :UserInfo.getUserId()];
        
        for(PRM_Comment__c eachPRMComment : newComments){
            if(mapOldComments.get(eachPRMComment.Id).PRM_Approval_Submitter__c == NULL && eachPRMComment.PRM_Approval_Submitter__c != NULL){              
                if(eachPRMComment.PRM_Approval_Submitter__c == 'Plant Manager'){
                   eachPRMComment.Plant_Manager__c = runningUser.Id;
                }
            }
        }
    }
}