ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Bundle_Rate__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Rate__c</fullName>
    <defaultValue>20</defaultValue>
    <description>Rate we use for payouts for bundle value</description>
    <label>Bundle Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>Used to track the high level stages of the Claim</description>
    <label>Claim Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting Docs</fullName>
            </value>
            <value>
                <fullName>In Kankakee</fullName>
            </value>
            <value>
                <fullName>In Lab</fullName>
            </value>
            <value>
                <fullName>File Preparation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Sub_Stage__c</fullName>
    <label>Claim Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Claim_Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting POP</fullName>
            </value>
            <value>
                <fullName>POP Received</fullName>
            </value>
            <value>
                <fullName>Additional POP Required</fullName>
            </value>
            <value>
                <fullName>Initial review</fullName>
            </value>
            <value>
                <fullName>HOIS sent</fullName>
            </value>
            <value>
                <fullName>Awaiting HOIS</fullName>
            </value>
            <value>
                <fullName>Awaiting Samples</fullName>
            </value>
            <value>
                <fullName>Samples Received</fullName>
            </value>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Data Entry</fullName>
            </value>
            <value>
                <fullName>Info Required</fullName>
            </value>
            <value>
                <fullName>Info Requested</fullName>
            </value>
            <value>
                <fullName>Goodwill review</fullName>
            </value>
            <value>
                <fullName>In review</fullName>
            </value>
            <value>
                <fullName>Release Pending</fullName>
            </value>
            <value>
                <fullName>Waiting for Invoice</fullName>
            </value>
            <value>
                <fullName>Check/Credit Requested</fullName>
            </value>
            <value>
                <fullName>Check/Credit Approved</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Goodwill Requested</fullName>
            </value>
            <value>
                <fullName>Goodwill Rejected</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Samples Sent to Lab</fullName>
            </value>
            <value>
                <fullName>Dealer Invoice Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/ClaimApproved__c.field-meta.xml
<CustomField>
    <fullName>ClaimApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that Claims Manager has approved the entire claim. This semi-closes the claim in the sense that changes should be minimal but there are still things to process. This is different than the &quot;Goodwill Amount Approve&quot; or &quot;Address Validation.&quot; A claim can have its goodwill amount approved but NOT but fully approved yet.</description>
    <label>Claim Approved?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Total_Cost_of_Additional_Settlement_Item__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_of_Additional_Settlement_Item__c</fullName>
    <defaultValue>0</defaultValue>
    <description>CLAIMSV2 - 75. The field is populated from the Case Products by summing the total of multiplying the Case Product Quantity with the default Rate (20$)</description>
    <inlineHelpText>The field is populated from the Case Products by summing the total of multiplying the Case Product Quantity with the default Rate (20$)</inlineHelpText>
    <label>Total Cost of Additional Settlement Item</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Related_Product__c/Related_Product__c.object-meta.xml
<CustomObject>
    <description>This is an object that allows users to associate multiple products to a claims case and capture additional details for these products.</description>
    <label>Related Product</label>
    <nameField>
        <displayFormat>RP-{0000000000}</displayFormat>
        <label>Related Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Related_Product__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a parent field on this object. This is required.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Products</relationshipLabel>
    <relationshipName>Related_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Related_Product__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>This is the quantity of the product that is needed for the settlement.</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/RelatedProductService.cls
public with sharing class RelatedProductService {

    public static void blockRecordDeletion(List<Related_Product__c> records) {
        Set<Id> caseIds = new Set<Id>();
        for (Related_Product__c relatedProduct : records) {
            caseIds.add(relatedProduct.Case__c);
        }

        Map<Id, Case> caseMap = new Map<Id, Case>([
                SELECT Id, ClaimApproved__c
                FROM Case
                WHERE Id IN :caseIds
        ]);

        if (caseMap.isEmpty()) {
            return;
        }

        for (Related_Product__c relatedProduct : records) {
            if (caseMap.get(relatedProduct.Case__c).ClaimApproved__c != NULL && caseMap.get(relatedProduct.Case__c).ClaimApproved__c) {
                relatedProduct.addError('Related Product cannot be deleted after the Case has been approved');
            }
        }
    }

    /*
        Block all updates for Case when the Claim_Stage__c is Closed, *unless* it is being re-opened
    */
    public static void blockCreatedUpdateDelete(List<Related_Product__c> records) {
        User runningUser = [SELECT Id, Profile.Name FROM User WHERE Id = :UserInfo.getUserId()];

        Map<Id, RecordType> claimRecordTypes = CaseService.getClaimRecordTypes();
        List<Id> caseIds = new List<Id>();

        for (Related_Product__c rp : records)
            caseIds.add(rp.Case__c);

        // SOQL query modified as part of US IWCN-723
        Map<Id, Case> caseMap = new Map<Id, Case>(
        [
                SELECT Id, RecordTypeId, Claim_Stage__c, ClaimApproved__c, Claim_Sub_Stage__c
                FROM Case
                WHERE Id IN :caseIds
                AND RecordTypeId IN :claimRecordTypes.keySet()
                AND (
                        Claim_Stage__c = 'Closed' OR
                        ClaimApproved__c = true OR
                        (Claim_Stage__c = 'Assessment' AND Claim_Sub_Stage__c = 'In Approval')
                )
        ]
        );

        if (caseMap.isEmpty())
            return;

        for (Related_Product__c rp : records) {
            Case caseRecord = caseMap.get(rp.Case__c);
            if (runningUser.Profile.Name != 'System Administrator') {
                if (caseRecord.Claim_Stage__c == 'Closed') {
                    rp.addError('Case Products cannot be modified for a closed case');
                } else {
                    rp.addERror('Case Products cannot be modified after submitting for approval');
                }
            }
        }
    }

    /*
        CLAIMS -75. Populate field on related case based on quantities of related products
    */
    public static void calculateTotalCostOfSettlementItemsOnRelatedCase(List<Related_Product__c> relatedProducts) {

        Id settlementTypeId = Schema.SObjectType.Related_Product__c.getRecordTypeInfosByName().get('Settlement Items').getRecordTypeId();
        Set<Id> relatedCaseIds = new Set<Id>();
        List<Case> casesToUpdate = new List<Case>();
        Map<Id, Case> casesByIds = new Map<Id, Case>();

        for (Related_Product__c eachRelatedProduct : relatedProducts) {
            if (eachRelatedProduct.Quantity__c != NULL && eachRelatedProduct.RecordTypeId == settlementTypeId) {
                relatedCaseIds.add(eachRelatedProduct.Case__c);
            }
        }


        if (relatedCaseIds.isEmpty()) {
            return;
        }


        List<Case> casesList = new List<Case>([
                SELECT Id,Total_Cost_of_Additional_Settlement_Item__c,Bundle_Rate__c
                FROM Case
                WHERE Id IN :relatedCaseIds
        ]);

        if (casesList.isEmpty()) {
            return;
        }

        //create map from List
        for (Case tCase : casesList) {
            casesByIds.put(tCase.Id, tCase);
        }

        List<AggregateResult> agr = [
                SELECT Case__c,SUM(Quantity__c) sumOfRelatedProducts
                FROM Related_Product__c
                WHERE Case__c IN :relatedCaseIds
                GROUP BY Case__c
        ];

        if (agr.isEmpty()) {
            for (Case thisCase : casesList) {
                thisCase.Total_Cost_of_Additional_Settlement_Item__c = 0.00;
                casesToUpdate.add(thisCase);
            }
        } else {
            for (AggregateResult eachRelatedProduct : agr) {
                Case thisCase = casesByIds.get((Id) eachRelatedProduct.get('Case__c'));
                thisCase.Total_Cost_of_Additional_Settlement_Item__c = Double.valueOf(eachRelatedProduct.get('sumOfRelatedProducts'))
                        * thisCase.Bundle_Rate__c;
                casesToUpdate.add(thisCase);
            }
        }

        update casesToUpdate;

    }
}