ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>Used to track the high level stages of the Claim</description>
    <label>Claim Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting Docs</fullName>
            </value>
            <value>
                <fullName>In Kankakee</fullName>
            </value>
            <value>
                <fullName>In Lab</fullName>
            </value>
            <value>
                <fullName>File Preparation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Installation_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Date__c</fullName>
    <description>Date of the product installation</description>
    <label>Installation Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Iron_Clad_Period_Years__c.field-meta.xml
<CustomField>
    <fullName>Iron_Clad_Period_Years__c</fullName>
    <description>To be populated through CaseService class invoked by CaseTrigger. This field displays how many years is the iron clad warranty valid for.  When a shingle is first installed it has an iron clad period where the warranty covers labour and material for the shingles.  Depending on when installed and type of product they will have different period length.  This first states what is that length.</description>
    <label>Iron Clad Period (Years)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <description>This field captures the language for the case. The documents generated for cases will be based on this language field.</description>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Operating_Languages</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Qualified__c.field-meta.xml
<CustomField>
    <fullName>Qualified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set manually by the Claims agent if the claim is determined to fit the criteria for the Organic Class Action settlement. This is also used to drive which template gets selected.</description>
    <inlineHelpText>Checked if the claim is determined by the Claim agent to fit the criteria of IKO&apos;s Organic shingle Class Action settlement.</inlineHelpText>
    <label>Qualified</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warranty_and_Claim_Sectors</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Settlement_Type__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Type__c</fullName>
    <description>Indicates what type of Settlement this will be, which will have downstream impact on calclulations</description>
    <label>Settlement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>Default</label>
            </value>
            <value>
                <fullName>Hand Seal</fullName>
            </value>
            <value>
                <fullName>Cash Settlement</fullName>
            </value>
            <value>
                <fullName>Cash Settlement - Material Only</fullName>
            </value>
            <value>
                <fullName>Goodwill</fullName>
            </value>
            <value>
                <fullName>Money or Material Offer</fullName>
            </value>
            <value>
                <fullName>Manual Calculation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/Test_Case_TriggerHandler.cls
@istest
public class Test_Case_TriggerHandler {

    @testsetup static void createTestData() {
        SandboxSetup.sandboxSetup();
    }


    @istest static void organicCrackingHandSealTest() {
        

        Test.startTest();
        Case myCase  = [SELECT Id FROM Case 
                        WHERE Account.Name = 'Art Gallery of Ontario' 
                        AND Sector__c = 'CA' 
                        LIMIT 1];
        	// Manipulate the case so the Template Selection trigger fires 
        	myCase.Claim_Stage__c = 'Assessment';
        	myCase.Settlement_Type__c = 'Hand Seal';
        	myCase.Qualified__c = true;
	        
        update myCase;
        	
        Test.stopTest();
    }

@istest static void organicCrackingCashSettlementTest() {
        
        Test.startTest();
    Case myCase  = [SELECT Id FROM Case WHERE Account.Name = 'Art Gallery of Ontario' AND Sector__c = 'CA' LIMIT 1];
        
        	// Manipulate the case so the Template Selection trigger fires 
        	myCase.Claim_Stage__c = 'Assessment';
        	myCase.Settlement_Type__c = 'Cash Settlement';
	        	update myCase;
    		// test for the PRM date, whatever that is
    		// 1997-06-01
    		// First we test before the PRM 
    		myCase.Settlement_Type__c = 'Default';
    		myCase.Installation_Date__c = Date.newInstance(1996, 6,1);
    			update myCase;
    
    		myCase.Installation_Date__c = System.today().addYears(-5);
    		myCase.Iron_Clad_Period_Years__c = 10;
    			update myCase;
    
    		myCase.Installation_Date__c = System.today().addYears(-15);
    		myCase.Iron_Clad_Period_Years__c = 10;
    			update myCase;
    		
        Test.stopTest();
    }

@istest static void organicCrackingCashSettlementMaterialOnlyTest() {
         
        Test.startTest();
    Case myCase  = [SELECT Id FROM Case WHERE Account.Name = 'Art Gallery of Ontario' AND Sector__c = 'CA' LIMIT 1];
       
        	// Manipulate the case so the Template Selection trigger fires 
        	myCase.Claim_Stage__c = 'Assessment';
        	myCase.Settlement_Type__c = 'Cash Settlement - Material Only';
	        	update myCase;
        Test.stopTest();
    }

@istest static void romProductTypeJ() {
        
        Test.startTest();
     Case myCase  = [SELECT Id FROM Case WHERE Account.Name = 'Royal Ontario Museum' AND Sector__c = 'CA' LIMIT 1];
       
        	// Manipulate the case so the Template Selection trigger fires 
        	myCase.Claim_Stage__c = 'Assessment';
        	myCase.Settlement_Type__c = 'Cash Settlement - Material Only';
	        	update myCase;
        Test.stopTest();
    }
    
// Test the Louvre for product type K
// Louvre Museum
@istest static void louvreProductTypeK() {
        
        Test.startTest();
    Case myCase  = [SELECT Id FROM Case WHERE Account.Name = 'Louvre Museum' AND Sector__c = 'CA' LIMIT 1];
        
        	// Manipulate the case so the Template Selection trigger fires 
        	myCase.Claim_Stage__c = 'Assessment';
        	myCase.Settlement_Type__c = 'Cash Settlement - Material Only';
			myCase.Qualified__c = true;
	        	update myCase;
        Test.stopTest();
    }
    
@istest static void organicCrackingGoodwillTest() {
        
        Test.startTest();
     Case myCase  = [SELECT Id FROM Case WHERE Account.Name = 'Art Gallery of Ontario' AND Sector__c = 'CA' LIMIT 1];
       
        	// Manipulate the case so the Template Selection trigger fires 
        	myCase.Claim_Stage__c = 'Assessment';
        	myCase.Settlement_Type__c = 'Goodwill';
	        	update myCase;
        Test.stopTest();
    }
    
    
@istest static void organicGranuleQuebecCanadaTest() {
        
        Test.startTest();
     Case myCase  = [SELECT Id FROM Case WHERE Account.Name = 'Quebec National Assembly' AND Account.BillingStateCode = 'QC' LIMIT 1];
       
        	// Manipulate the case so the Template Selection trigger fires 
        	myCase.Claim_Stage__c = 'Assessment';
        	myCase.Settlement_Type__c = 'Cash Settlement';
    		myCase.Qualified__c = true;
	        	update myCase;
        Test.stopTest();
    }

// Guggenheim is a glass claim with product type B
@istest static void guggenheimGlassClaim() {
        
        Test.startTest();
      Case myCase  = [SELECT Id FROM Case WHERE Account.Name = 'Guggenheim' LIMIT 1];
      
        	// Manipulate the case so the Template Selection trigger fires 
        	myCase.Claim_Stage__c = 'Assessment';
        	myCase.Settlement_Type__c = 'Cash Settlement';
	        	update myCase;
    
    		myCase.Settlement_Type__c = 'Money or Material Offer';
    			update myCase;
    
    		myCase.Settlement_Type__c = 'Manual Calculation';
    			update myCase;

    Test.stopTest();
    }

// Guggenheim is a glass claim with product type D
@istest static void bilbaoGuggenhimClaim() {
        
        Test.startTest();
    Case myCase  = [SELECT Id FROM Case WHERE Account.Name = 'Guggenheim Bilbao' LIMIT 1];
        
        	// Manipulate the case so the Template Selection trigger fires 
        	myCase.Claim_Stage__c = 'Assessment';
        	myCase.Settlement_Type__c = 'Cash Settlement';
	        	update myCase;
        Test.stopTest();
    }

    
    @istest static void usSectorYankeeStadium() {
        
        Test.startTest();
         Case myCase  = [SELECT Id FROM Case WHERE Account.Name = 'Yankee Stadium' AND Sector__c = 'US' LIMIT 1];
       
        	// Manipulate the case so the Template Selection trigger fires
        	myCase.Claim_Stage__c = 'Offered';
				update myCase;
        Test.stopTest();
    }


    @isTest static void testThatCaseTemplate_Organic_REG_CS_EN_CA()
    {
       
        Test.startTest();
         Case myCase  = [SELECT Id FROM Case WHERE Account.Name = 'Art Gallery of Ontario' AND Sector__c = 'CA' LIMIT 1];

        	// Manipulate the case so the Template Selection trigger fires 
        	myCase.Claim_Stage__c = 'Assessment';
        	myCase.Settlement_Type__c = 'Cash Settlement';
            myCase.Preferred_Language__c = 'English'; 
            myCase.Sector__c = 'CA';
            update myCase;
        	
        Test.stopTest();
    }

   
}