ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>Used to track the high level stages of the Claim</description>
    <label>Claim Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting Docs</fullName>
            </value>
            <value>
                <fullName>In Kankakee</fullName>
            </value>
            <value>
                <fullName>In Lab</fullName>
            </value>
            <value>
                <fullName>File Preparation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Conga_Iron_Clad_Period_Months__c.field-meta.xml
<CustomField>
    <fullName>Conga_Iron_Clad_Period_Months__c</fullName>
    <description>This field displays how many months is the iron clad warranty valid for. When a shingle is first installed it has an iron clad period where the warranty covers labour and material for the shingles. Depending on when installed and type of product they will have different period length. This first states what is that length. Derived from Iron Clad Period (Years) field.</description>
    <formula>Iron_Clad_Period_Years__c * 12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Iron Clad Period (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Installation_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Date__c</fullName>
    <description>Date of the product installation</description>
    <label>Installation Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Num_of_Months_Product_Used__c.field-meta.xml
<CustomField>
    <fullName>Num_of_Months_Product_Used__c</fullName>
    <description>Calculated # of months that the product has been used, based on Installation Date and Case Created Date</description>
    <formula>CEILING(
	(
		YEAR( Call_Received_Date__c ) *12 + MONTH(Call_Received_Date__c )
	) -
	(
	YEAR( Installation_Date__c )*12 + MONTH(Installation_Date__c )
	)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Calculated # of months that the product has been used, based on Installation Date and Case Created Date</inlineHelpText>
    <label># of Months Product Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <description>This field captures the language for the case. The documents generated for cases will be based on this language field.</description>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Operating_Languages</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product related to the Residential/Commercial Claim</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Is_Legacy__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Product2.Sectors_Text__c</field>
            <operation>contains</operation>
            <valueField>$Source.Sector__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Qualified__c.field-meta.xml
<CustomField>
    <fullName>Qualified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set manually by the Claims agent if the claim is determined to fit the criteria for the Organic Class Action settlement. This is also used to drive which template gets selected.</description>
    <inlineHelpText>Checked if the claim is determined by the Claim agent to fit the criteria of IKO&apos;s Organic shingle Class Action settlement.</inlineHelpText>
    <label>Qualified</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warranty_and_Claim_Sectors</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Settlement_Type__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Type__c</fullName>
    <description>Indicates what type of Settlement this will be, which will have downstream impact on calclulations</description>
    <label>Settlement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>Default</label>
            </value>
            <value>
                <fullName>Hand Seal</fullName>
            </value>
            <value>
                <fullName>Cash Settlement</fullName>
            </value>
            <value>
                <fullName>Cash Settlement - Material Only</fullName>
            </value>
            <value>
                <fullName>Goodwill</fullName>
            </value>
            <value>
                <fullName>Money or Material Offer</fullName>
            </value>
            <value>
                <fullName>Manual Calculation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Template_Name_Automatic_Generated__c.field-meta.xml
<CustomField>
    <fullName>Template_Name_Automatic_Generated__c</fullName>
    <label>Template Name (Automatic Generated)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <description>This field displays the unit of measure of the product.</description>
    <formula>TEXT( Product__r.Unit_of_Measure__c )</formula>
    <label>Unit of Measure</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/Claim_Type__c.object-meta.xml
<CustomObject>
    <description>Used to capture the Primary and Secondary reason for the Claim Case</description>
    <label>Claim Type</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Claim Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Related Claim Case</description>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Case must be a Residential or Commercial Claim</errorMessage>
        <filterItems>
            <field>Case.RecordType.Name</field>
            <operation>contains</operation>
            <value>Claim</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Claim Types</relationshipLabel>
    <relationshipName>Claim_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Concern__c.field-meta.xml
<CustomField>
    <fullName>Concern__c</fullName>
    <label>Concern</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Claim_Type_Reason</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this the Primary Claim Type?</description>
    <label>Is Primary?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>(none)</fullName>
            </value>
            <value>
                <fullName>A Organic</fullName>
            </value>
            <value>
                <fullName>B Glass</fullName>
            </value>
            <value>
                <fullName>C Lam/Org</fullName>
            </value>
            <value>
                <fullName>D Lam/Glass</fullName>
            </value>
            <value>
                <fullName>E Coated Rolls</fullName>
            </value>
            <value>
                <fullName>F Mod Bit</fullName>
            </value>
            <value>
                <fullName>G Felt</fullName>
            </value>
            <value>
                <fullName>H Asphalt</fullName>
            </value>
            <value>
                <fullName>I Fibrebrd</fullName>
            </value>
            <value>
                <fullName>J Total</fullName>
            </value>
            <value>
                <fullName>K Lock</fullName>
            </value>
            <value>
                <fullName>L ArmourGd</fullName>
            </value>
            <value>
                <fullName>M Protecbrd</fullName>
            </value>
            <value>
                <fullName>N Poly ISO</fullName>
            </value>
            <value>
                <fullName>P Roof-Fast</fullName>
            </value>
            <value>
                <fullName>Q Gold Shield</fullName>
            </value>
            <value>
                <fullName>R Adhs/Ctgs</fullName>
            </value>
            <value>
                <fullName>Z Not IKO</fullName>
            </value>
            <value>
                <fullName>Valley Cap</fullName>
            </value>
            <value>
                <fullName>Panels</fullName>
            </value>
            <value>
                <fullName>Hip &amp; Ridge</fullName>
            </value>
            <value>
                <fullName>Valley</fullName>
            </value>
            <value>
                <fullName>Touch up kit</fullName>
            </value>
            <value>
                <fullName>Screws</fullName>
            </value>
            <value>
                <fullName>Starter w drip</fullName>
            </value>
            <value>
                <fullName>Side</fullName>
            </value>
            <value>
                <fullName>Rake</fullName>
            </value>
            <value>
                <fullName>XD Channel</fullName>
            </value>
            <value>
                <fullName>Debris guard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/Case_TriggerHandler_Test.cls
@isTest
public class Case_TriggerHandler_Test {
	 @testSetup static void setupTestData() {
        initData();
        initUser();
    }

    @future
    private static void initUser() {
        User salesManagerUser = TestFactory.createUser('Unit', 'Tests', 'salesrsmmgr@iko.com', 'salesrsmmgr@iko.com', 'USRS Manager',
                'RSM West', 'salesmgr', 'GMT', 'en_US', 'UTF-8', 'en_US', null, null, false);
        insert salesManagerUser;
    }
    
    private static void initData() {

        Id baRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Building Location').getRecordTypeId();
        Id ccRt = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Claim').getRecordTypeId();
        List<Account> toInsertAccounts = new List<Account>();

        toInsertAccounts.addAll(TestFactory.createAccounts(baRt, 'AccountCA', '9 King St E', 'Toronto', 'ON', 'CA', 'M4S 2H4',
                'Verified', UserInfo.getUserId(), TRUE, TRUE, 1, false));
        //insert toInsertAccounts;

        toInsertAccounts.addAll(TestFactory.createAccounts(baRt, 'AccountQC', '9 King St E', 'Toronto', 'QC', 'CA', 'M4S 2H4',
                'Verified', UserInfo.getUserId(), TRUE, TRUE, 1, false));
        insert toInsertAccounts;
        
        Product2 p = new Product2(
        	Name = 'IKO CAMBRIDGE',
            Sectors__c = 'CA',
            Is_Legacy__c = false,
            Unit_of_Measure__c = 'BD'
        );
        insert p;
        
        
        //create contact
        List<Contact> con = TestFactory.createContacts(toInsertAccounts[0].Id, 'ClaimTypeServiceTest', UserInfo.getUserId(), 1, false);
        insert con;

        
    }
	 
    @isTest static void testThatCaseTemplate_ManualCalculation() {
        Test.startTest();
        Account caAccount = [select Id from Account where BillingCountryCode = :'CA' limit 1];
		Contact contact = [select Id from Contact limit 1];        
        Case c1 = new Case(
            Description = 'Residential Claim created by Test Case',
        	RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Residential Claim').getRecordTypeId(),
            Claim_Stage__c = 'Assessment',
            Settlement_Type__c = 'Manual Calculation',
            Preferred_Language__c = 'English', 
            AccountId = caAccount.Id,
            ContactId = contact.Id,
            Template_Name_Automatic_Generated__c = '',
            Sector__c = 'CA'
        );
        //system.debug('c1: ' + c1);
        insert c1;
        
        Claim_Type__c ct = new Claim_Type__c(
        	case__c = c1.Id,
            Concern__c = 'Clawing',
            Product_Type__c = 'B Glass',
            Is_Primary__c = true
        );
        insert ct;
        
        Case cCheck		= [select Id, Template_Name_Automatic_Generated__c from Case where Id = :c1.Id limit 1];
        //system.debug('c1: ' + c1);
        System.assertEquals( null, cCheck.Template_Name_Automatic_Generated__c );                                 
        Test.stopTest();
        
    }
    
    @isTest static void testThatCaseTemplate_Glass_REG_MMO_EN_CA() {
         Test.startTest();
        Account caAccount = [select Id from Account where BillingCountryCode = :'CA' limit 1];
		Contact contact = [select Id from Contact limit 1];        
        Case c1 = new Case(
            Description = 'Residential Claim created by Test Case',
        	RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Residential Claim').getRecordTypeId(),
            Claim_Stage__c = 'Assessment',
            Settlement_Type__c = 'Money or Material Offer',
            Preferred_Language__c = 'English', 
            AccountId = caAccount.Id,
            ContactId = contact.Id,
            Template_Name_Automatic_Generated__c = '',
            Sector__c = 'CA'
        );
        //system.debug('c1: ' + c1);
        insert c1;
        
        Claim_Type__c ct = new Claim_Type__c(
        	case__c = c1.Id,
            Concern__c = 'Clawing',
            Product_Type__c = 'B Glass',
            Is_Primary__c = true
        );
        insert ct;
        
        Case cCheck		= [select Id, Template_Name_Automatic_Generated__c from Case where Id = :c1.Id limit 1];
        //system.debug('c1: ' + c1);
        System.assertEquals( '1 - [Glass] Offer-Release [REG] [MMO] [IKO] [EN] [CA]', cCheck.Template_Name_Automatic_Generated__c );                                 
        Test.stopTest();
        
    }
    
    @isTest static void testThatCaseTemplate_Glass_REG_CS_EN_CA() {
         Test.startTest();
        Account caAccount = [select Id from Account where BillingCountryCode = :'CA' limit 1];
		Contact contact = [select Id from Contact limit 1];        
        Case c1 = new Case(
            Description = 'Residential Claim created by Test Case',
        	RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Residential Claim').getRecordTypeId(),
            Claim_Stage__c = 'Assessment',
            Settlement_Type__c = 'Cash Settlement',
            Preferred_Language__c = 'English', 
            AccountId = caAccount.Id,
            ContactId = contact.Id,
            Template_Name_Automatic_Generated__c = '',
            Sector__c = 'CA'
        );
        //system.debug('c1: ' + c1);
        insert c1;
        
        Claim_Type__c ct = new Claim_Type__c(
        	case__c = c1.Id,
            Concern__c = 'Clawing',
            Product_Type__c = 'B Glass',
            Is_Primary__c = true
        );
        insert ct;
        
        Case cCheck		= [select Id, Template_Name_Automatic_Generated__c from Case where Id = :c1.Id limit 1];
        //system.debug('c1: ' + c1);
        System.assertEquals( '1 - [Glass] Offer-Release [REG] [CS] [IKO] [EN] [CA]', cCheck.Template_Name_Automatic_Generated__c );                                 
        
        Test.stopTest();
    }
    
    @isTest static void testThatCaseTemplate_Glass_REG_CSMO_EN_QC() {
         Test.startTest();
        Account caAccount = [select Id from Account where BillingStateCode = :'QC' limit 1];
		Contact contact = [select Id from Contact limit 1];        
        Case c1 = new Case(
            Description = 'Residential Claim created by Test Case',
        	RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Residential Claim').getRecordTypeId(),
            Claim_Stage__c = 'Assessment',
            Settlement_Type__c = 'Cash Settlement - Material Only',
            Preferred_Language__c = 'English', 
            AccountId = caAccount.Id,
            ContactId = contact.Id,
            Template_Name_Automatic_Generated__c = '',
            Sector__c = 'CA'
        );
        //system.debug('c1: ' + c1);
        insert c1;
        
        Claim_Type__c ct = new Claim_Type__c(
        	case__c = c1.Id,
            Concern__c = 'Clawing',
            Product_Type__c = 'B Glass',
            Is_Primary__c = true
        );
        insert ct;
        
        Case cCheck		= [select Id, Template_Name_Automatic_Generated__c from Case where Id = :c1.Id limit 1];
        System.assertEquals( '1 - [Glass] Offer-Release [REG] [CSMO] [IKO] [EN] [QC]', cCheck.Template_Name_Automatic_Generated__c );  
    	Test.stopTest();
    }
    /*
    @isTest static void testThatCaseTemplate_Glass_REG_FR_FR_CA() {
        Account caAccount = [select Id from Account where BillingCountryCode = :'CA' limit 1];
		Contact contact = [select Id from Contact limit 1];        
        Case c1 = new Case(
            Description = 'Residential Claim created by Test Case',
        	RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Residential Claim').getRecordTypeId(),
            Claim_Stage__c = 'Assessment',
            Settlement_Type__c = 'Cash Settlement - Material Only',
            Preferred_Language__c = 'French', 
            Installation_Date__c = Date.valueOf('1998-06-01'),
            Num_of_Months_Product_Used__c = 6,
            Conga_Iron_Clad_Period_Months__c = 8,
            AccountId = caAccount.Id,
            ContactId = contact.Id,
            Template_Name_Automatic_Generated__c = '',
            Sector__c = 'CA'
        );
        //system.debug('c1: ' + c1);
        insert c1;
        
        Claim_Type__c ct = new Claim_Type__c(
        	case__c = c1.Id,
            Concern__c = 'Clawing',
            Product_Type__c = 'B Glass',
            Is_Primary__c = true
        );
        insert ct;
        
        Case cCheck		= [select Id, Template_Name_Automatic_Generated__c from Case where Id = :c1.Id limit 1];
        System.assertEquals( '1 - [Glass] Offer-Release [REG] [CSMO] [IKO] [EN] [QC]', cCheck.Template_Name_Automatic_Generated__c );  
    }
    */
    @isTest static void testThatCaseTemplate_Glass_REG_GW_FR_QC() {
         Test.startTest();
        Account caAccount = [select Id from Account where BillingStateCode = :'QC' limit 1];
        Contact contact = [select Id from Contact limit 1];        
        Case c1 = new Case(
            Description = 'Residential Claim created by Test Case',
        	RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Residential Claim').getRecordTypeId(),
            Claim_Stage__c = 'Assessment',
            Settlement_Type__c = 'Goodwill',
            Preferred_Language__c = 'Quebec French', 
            AccountId = caAccount.Id,
            ContactId = contact.Id,
            Template_Name_Automatic_Generated__c = '',
            Sector__c = 'CA'
        );
        //system.debug('c1: ' + c1);
        insert c1;
        
        Claim_Type__c ct = new Claim_Type__c(
        	case__c = c1.Id,
            Concern__c = 'Clawing',
            Product_Type__c = 'B Glass',
            Is_Primary__c = true
        );
        insert ct;
        
        Case cCheck		= [select Id, Template_Name_Automatic_Generated__c from Case where Id = :c1.Id limit 1];
        System.debug('template name = ' + cCheck.Template_Name_Automatic_Generated__c); 
        System.assertEquals( '1 - [Glass] Offer-Release [REG] [GW] [IKO] [FR] [QC]', cCheck.Template_Name_Automatic_Generated__c );  
    	Test.stopTest();
    }
    
    @isTest static void testThatCaseTemplate_Glass_REG_HS_EN_CA() {
         Test.startTest();
       Account caAccount = [select Id from Account where BillingCountryCode = :'CA' limit 1];
		Contact contact = [select Id from Contact limit 1];        
        Case c1 = new Case(
            Description = 'Residential Claim created by Test Case',
        	RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Residential Claim').getRecordTypeId(),
            Claim_Stage__c = 'Assessment',
            Settlement_Type__c = 'Hand Seal',
            Preferred_Language__c = 'English', 
            AccountId = caAccount.Id,
            ContactId = contact.Id,
            Template_Name_Automatic_Generated__c = '',
            Sector__c = 'CA'
        );
        //system.debug('c1: ' + c1);
        insert c1;
        
        Claim_Type__c ct = new Claim_Type__c(
        	case__c = c1.Id,
            Concern__c = 'Clawing',
            Product_Type__c = 'B Glass',
            Is_Primary__c = true
        );
        insert ct;
        
        Case cCheck		= [select Id, Template_Name_Automatic_Generated__c from Case where Id = :c1.Id limit 1];
        //system.debug('c1: ' + c1);
        System.assertEquals( '1 - [Glass] Offer-Release [REG] [HS] [IKO] [EN] [CA]', cCheck.Template_Name_Automatic_Generated__c );                                 
         Test.stopTest();
    }
    
    @isTest static void testThatCaseTemplate_Glass_REG_HSFM_EN_QC() {
         Test.startTest();
        Account caAccount = [select Id from Account where BillingStateCode = :'QC' limit 1];
		Contact contact = [select Id from Contact limit 1];        
        Case c1 = new Case(
            Description = 'Residential Claim created by Test Case',
        	RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Residential Claim').getRecordTypeId(),
            Claim_Stage__c = 'Assessment',
            Settlement_Type__c = 'Cash Settlement - Material Only',
            Preferred_Language__c = 'English', 
            AccountId = caAccount.Id,
            ContactId = contact.Id,
            Template_Name_Automatic_Generated__c = '',
            Sector__c = 'CA'
        );
        //system.debug('c1: ' + c1);
        insert c1;
        
        Claim_Type__c ct = new Claim_Type__c(
        	case__c = c1.Id,
            Concern__c = 'Fishmouthing',
            Product_Type__c = 'B Glass',
            Is_Primary__c = true
        );
        insert ct;
        
        Case cCheck		= [select Id, Template_Name_Automatic_Generated__c from Case where Id = :c1.Id limit 1];
        System.debug('Template name = ' + cCheck.Template_Name_Automatic_Generated__c );
        System.assertEquals( '1 - [Glass] Offer-Release [REG] [HS-FM] [IKO] [EN] [QC]', cCheck.Template_Name_Automatic_Generated__c );  
    	Test.stopTest();
    }
    /*
    @isTest static void testThatCaseTemplate_Glass_REG_PRM_FR_CA() {
                                   
         
    }
    */
    @isTest static void testThatCaseTemplate_Glass_REG_PRML_FR_QC() {
         Test.startTest();
        Account caAccount = [select Id from Account where BillingStateCode = :'QC' limit 1];
		Contact contact = [select Id from Contact limit 1];        
        Case c1 = new Case(
            Description = 'Residential Claim created by Test Case',
        	RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Residential Claim').getRecordTypeId(),
            Claim_Stage__c = 'Assessment',
            Settlement_Type__c = 'Default',
            Preferred_Language__c = 'Quebec French', 
            Installation_Date__c = Date.valueOf('1997-05-01'),
            AccountId = caAccount.Id,
            ContactId = contact.Id,
            Template_Name_Automatic_Generated__c = '',
            Sector__c = 'CA'
        );
        //system.debug('c1: ' + c1);
        insert c1;
        
        Claim_Type__c ct = new Claim_Type__c(
        	case__c = c1.Id,
            Concern__c = 'Clawing',
            Product_Type__c = 'B Glass',
            Is_Primary__c = true
        );
        insert ct;
        
        Case cCheck		= [select Id, Template_Name_Automatic_Generated__c from Case where Id = :c1.Id limit 1];
        //system.debug('c1: ' + c1);
        System.assertEquals( '1 - [Glass] Offer-Release [REG] [PRML] [IKO] [FR] [QC]', cCheck.Template_Name_Automatic_Generated__c );      
   		Test.stopTest();
    }
    
    @isTest static void testThatCaseTemplate_ORGANIC_CAC_CS_EN_CA() {
         Test.startTest();
        Account caAccount = [select Id from Account where BillingCountryCode = :'CA' limit 1];
		Contact contact = [select Id from Contact limit 1];        
        Product2 product = [select Id from Product2 limit 1];
        Case c1 = new Case(
            Description = 'Residential Claim created by Test Case',
        	RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Residential Claim').getRecordTypeId(),
            Claim_Stage__c = 'Assessment',
            Settlement_Type__c = 'Cash Settlement',
            Preferred_Language__c = 'English', 
            AccountId = caAccount.Id,
            ContactId = contact.Id,
            Template_Name_Automatic_Generated__c = '',
            Product__c = product.Id,
            Sector__c = 'CA'
        );
        system.debug('c1: ' + c1);
        insert c1;
        
        Claim_Type__c ct = new Claim_Type__c(
        	case__c = c1.Id,
            Concern__c = 'Cracking',
            Product_Type__c = 'A Organic',
            Is_Primary__c = true
        );
        insert ct;
                
        c1.Qualified__c = true;
        update c1;
        
        //Claim_Type__c claimtype = [select Id, Product_Type__c from Claim_Type__c where Id = : ct.Id limit 1];
        Case cCheck		= [select Id, Template_Name_Automatic_Generated__c from Case where Id = :c1.Id limit 1];
        System.assertEquals( '1 - [Org] Offer-Release [CAC] [CS] [IKO] [EN] [CA]', cCheck.Template_Name_Automatic_Generated__c );        
   		Test.stopTest();
    }
    
    @isTest static void testThatCaseTemplate_ORGANIC_CAG_CS_EN_CA() {
         Test.startTest();
        Account caAccount = [select Id from Account where BillingCountryCode = :'CA' limit 1];
		Contact contact = [select Id from Contact limit 1];        
        Product2 product = [select Id from Product2 limit 1];
        System.debug('product id is ' + product.Id);
        Case c1 = new Case(
            Description = 'Residential Claim created by Test Case',
        	RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Residential Claim').getRecordTypeId(),
            Claim_Stage__c = 'Assessment',
            Settlement_Type__c = 'Cash Settlement',
            Preferred_Language__c = 'English', 
            AccountId = caAccount.Id,
            ContactId = contact.Id,
            Template_Name_Automatic_Generated__c = '',
            Product__c = product.Id,
            Sector__c = 'CA'
        );
        system.debug('c1: ' + c1);
        insert c1;
        
        Claim_Type__c ct = new Claim_Type__c(
        	case__c = c1.Id,
            Concern__c = 'Granule Loss',
            Product_Type__c = 'A Organic',
            Is_Primary__c = true
        );
        insert ct;
                
        c1.Qualified__c = true;
        update c1;
        
        Case cCheck		= [select Id, Template_Name_Automatic_Generated__c from Case where Id = :c1.Id limit 1];
                
        System.assertEquals( '1 - [Org] Offer-Release [CAG] [CS] [IKO] [EN] [CA]', cCheck.Template_Name_Automatic_Generated__c );        
   		Test.stopTest();
    }
    
    
}