ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>Used to track the high level stages of the Claim</description>
    <label>Claim Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting Docs</fullName>
            </value>
            <value>
                <fullName>In Kankakee</fullName>
            </value>
            <value>
                <fullName>In Lab</fullName>
            </value>
            <value>
                <fullName>File Preparation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Sub_Stage__c</fullName>
    <label>Claim Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Claim_Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting POP</fullName>
            </value>
            <value>
                <fullName>POP Received</fullName>
            </value>
            <value>
                <fullName>Additional POP Required</fullName>
            </value>
            <value>
                <fullName>Initial review</fullName>
            </value>
            <value>
                <fullName>HOIS sent</fullName>
            </value>
            <value>
                <fullName>Awaiting HOIS</fullName>
            </value>
            <value>
                <fullName>Awaiting Samples</fullName>
            </value>
            <value>
                <fullName>Samples Received</fullName>
            </value>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Data Entry</fullName>
            </value>
            <value>
                <fullName>Info Required</fullName>
            </value>
            <value>
                <fullName>Info Requested</fullName>
            </value>
            <value>
                <fullName>Goodwill review</fullName>
            </value>
            <value>
                <fullName>In review</fullName>
            </value>
            <value>
                <fullName>Release Pending</fullName>
            </value>
            <value>
                <fullName>Waiting for Invoice</fullName>
            </value>
            <value>
                <fullName>Check/Credit Requested</fullName>
            </value>
            <value>
                <fullName>Check/Credit Approved</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Goodwill Requested</fullName>
            </value>
            <value>
                <fullName>Goodwill Rejected</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Samples Sent to Lab</fullName>
            </value>
            <value>
                <fullName>Dealer Invoice Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/ClaimApproved__c.field-meta.xml
<CustomField>
    <fullName>ClaimApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that Claims Manager has approved the entire claim. This semi-closes the claim in the sense that changes should be minimal but there are still things to process. This is different than the &quot;Goodwill Amount Approve&quot; or &quot;Address Validation.&quot; A claim can have its goodwill amount approved but NOT but fully approved yet.</description>
    <label>Claim Approved?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Tape_Code__c.field-meta.xml
<CustomField>
    <fullName>Tape_Code__c</fullName>
    <description>Sales, Claims and Lab uses this to record the product Tape Code</description>
    <label>Tape Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/Lab_Sample__c.object-meta.xml
<CustomObject>
    <label>Lab Sample</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Samples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A link to the Claim this lab sample is related to. Lab Samples with no links to a Claim have been received but not properly connected to a cliam.</description>
    <inlineHelpText>The Claim this Lab Sample relates to.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Lab Samples</relationshipLabel>
    <relationshipName>Lab_Samples</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Case_Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Case_Open_Date__c</fullName>
    <description>Used for list views</description>
    <formula>Case__r.CreatedDate</formula>
    <label>Case Open Date</label>
    <type>DateTime</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>https://ikoussfsc.atlassian.net/browse/CLAIMSV2-358
Claims Stage</description>
    <formula>TEXT(Case__r.Claim_Stage__c)</formula>
    <inlineHelpText>Claims Stage</inlineHelpText>
    <label>Claim Stage</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Claim_Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Sub_Stage__c</fullName>
    <description>https://ikoussfsc.atlassian.net/browse/CLAIMSV2-358
Claim Sub Stage</description>
    <formula>Text( Case__r.Claim_Sub_Stage__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Claim Sub Stage</inlineHelpText>
    <label>Claim Sub Stage</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/PRM__c.field-meta.xml
<CustomField>
    <fullName>PRM__c</fullName>
    <defaultValue>false</defaultValue>
    <description>https://ikoussfsc.atlassian.net/browse/CLAIMSV2-294
Indicates whether the Lab Sample should be reviewed by the Plant.</description>
    <inlineHelpText>Indicates whether the Lab Sample should be reviewed by the Plant.</inlineHelpText>
    <label>PRM</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Recent_Manufacture_Date__c.field-meta.xml
<CustomField>
    <fullName>Recent_Manufacture_Date__c</fullName>
    <description>https://ikoussfsc.atlassian.net/browse/CLAIMSV2-294
Capture the most recent manufacture date of the Lab Sample Tape Code</description>
    <inlineHelpText>Capture the most recent manufacture date of the Lab Sample Tape Code.</inlineHelpText>
    <label>Recent Manufacture Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample_Tape_Code__c/Lab_Sample_Tape_Code__c.object-meta.xml
<CustomObject>
    <description>This allows users to associate the tape codes with the lab samples</description>
    <label>Sample Description</label>
    <nameField>
        <displayFormat>LSTC - {000000000}</displayFormat>
        <label>Lab Sample Tape Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample_Tape_Code__c/fields/Lab_Sample__c.field-meta.xml
<CustomField>
    <fullName>Lab_Sample__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the lab sample the record is related to</description>
    <label>Lab Sample</label>
    <referenceTo>Lab_Sample__c</referenceTo>
    <relationshipName>Lab_Sample_Tape_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample_Tape_Code__c/fields/Manufacture_Date__c.field-meta.xml
<CustomField>
    <fullName>Manufacture_Date__c</fullName>
    <formula>TEXT( Tape_Code__r.Manufacture_Date__c)</formula>
    <label>Manufacture Date</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample_Tape_Code__c/fields/Tape_Code__c.field-meta.xml
<CustomField>
    <fullName>Tape_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the tape code that is associated with the lab sample</description>
    <label>Tape Code</label>
    <referenceTo>Tape_Code__c</referenceTo>
    <relationshipName>Lab_Sample_Tape_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tape_Code__c/Tape_Code__c.object-meta.xml
<CustomObject>
    <description>This records the tape code details for IKO products which helps with the claim and warranty process</description>
    <label>Tape Code</label>
    <nameField>
        <label>Tape Code Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tape Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tape_Code__c/fields/Manufacture_Date__c.field-meta.xml
<CustomField>
    <fullName>Manufacture_Date__c</fullName>
    <description>This is used to record the date of manufacture for the product for the tape code.</description>
    <label>Manufacture Date</label>
    <type>DateTime</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/LabSampleTapeCodeService.cls
public with sharing class LabSampleTapeCodeService {

    /*
        Block all updates for Case when the Claim_Stage__c is Closed, *unless* it is being re-opened
    */
    public static void blockCreatedUpdateDelete(List<Lab_Sample_Tape_Code__c> records) {
        Map<Id, RecordType> claimRecordTypes = CaseService.getClaimRecordTypes();
        List<Id> caseIds = new List<Id>();

        List<Id> labSampleIds = new List<Id>();

        for (Lab_Sample_Tape_Code__c record : records)
            labSampleIds.add(record.Lab_Sample__c);

        // SOQL query modified as part of US IWCN-723
        Map<Id, Lab_Sample__c> labSamplesMap = new Map<Id, Lab_Sample__c>(
        [
                SELECT Id, Case__r.RecordTypeId, Case__r.Claim_Stage__c, Case__r.Claim_Sub_Stage__c, Case__r.ClaimApproved__c
                FROM Lab_Sample__c
                WHERE Id IN :labSampleIds
                AND Case__r.RecordTypeId IN :claimRecordTypes.keySet()
                AND (
                        Case__r.Claim_Stage__c = 'Closed' OR
                        Case__r.ClaimApproved__c = true OR
                        (Case__r.Claim_Stage__c = 'Assessment' AND Case__r.Claim_Sub_Stage__c = 'In Approval')
                )
        ]
        );

        if (labSamplesMap.isEmpty()) {
            return;
        }

        for (Lab_Sample_Tape_Code__c record : records) {
            Lab_Sample__c labSampleRecord = labSamplesMap.get(record.Lab_Sample__c);
            if (labSampleRecord.Case__r.Claim_Stage__c == 'Closed') {
                record.addError('Lab Sample Tape Codes cannot be modified for a closed case');
            } else {
                record.addERror('Case Lab Samples cannot be modifed after submitting for approval');
            }
        }
    }

    /**
     * @description Populate the PRM field on the Lab Sample
     *
     * @param labSampleTapeCodeMap new Map of triggered Lab Sample Tape Code
     */
    public static void populateLabSamplePRMField(final Map<Id, Lab_Sample_Tape_Code__c> labSampleTapeCodeMap) {

        Set<Id> labSampleIds = new Set<Id>();
        for (Lab_Sample_Tape_Code__c labSampleTapeCode : labSampleTapeCodeMap.values()) {
            if (labSampleTapeCode.Lab_Sample__c != NULL && labSampleTapeCode.Tape_Code__c != NULL && labSampleTapeCode.Manufacture_Date__c != NULL) {
                labSampleIds.add(labSampleTapeCode.Lab_Sample__c);
            }
        }

        if (labSampleIds.isEmpty()) {
            return;
        }

        List<Lab_Sample__c> labSamples = [
                SELECT Id, Case_Open_Date__c, PRM__c
                FROM Lab_Sample__c
                WHERE Id IN :labSampleIds
        ];

        if (labSamples.isEmpty()) {
            return;
        }

        LabSampleService.populateLabSamplePRMField(labSamples, 'Sample_Description');

    } // end populateLabSamplePRMField method

    /**
     * @description populates the Sample Recent Manufacture Date on Lab Sample with the recent manufacture date
     *      of Lab Sample Tape Code
     *
     * @param labSampleTapeCodes new list of Sample Taple Code records
     */
    public static void populateLabSampleRecentManufactureDate(final List<Lab_Sample_Tape_Code__c> labSampleTapeCodes) {

        Set<Id> labSamplesIds = new Set<Id>();
        for (Lab_Sample_Tape_Code__c labSampleTapeCode : labSampleTapeCodes) {
            //&& labSampleTapeCode.Manufacture_Date__c != NULL
            if (labSampleTapeCode.Lab_Sample__c != NULL && labSampleTapeCode.Tape_Code__c != NULL) {
                labSamplesIds.add(labSampleTapeCode.Lab_Sample__c);
            }
        }

        if (labSamplesIds.isEmpty()) {
            return;
        }

        // this map contains all Lab Sample Ids with the most recent date of the Lab Sample Tape Code
        Map<Id, String> manufactureDateByLabSampleIds = new Map<Id, String>();
        List<Lab_Sample_Tape_Code__c> allLabSampleTapeCodes = [
                SELECT Id, Manufacture_Date__c, Lab_Sample__c
                FROM Lab_Sample_Tape_Code__c
                WHERE Lab_Sample__c IN :labSamplesIds AND
                (Manufacture_Date__c != 'Z' OR Manufacture_Date__c != NULL)
                ORDER BY Manufacture_Date__c DESC // Get the recent Manufacture Date
        ];

        if (allLabSampleTapeCodes.isEmpty()) {
            for (Id labSampleId : labSamplesIds) {
                manufactureDateByLabSampleIds.put(labSampleId, NULL);
            }
        } else {
            for (Lab_Sample_Tape_Code__c labSampleTapeCode : allLabSampleTapeCodes) {
                if (!manufactureDateByLabSampleIds.containsKey(labSampleTapeCode.Lab_Sample__c)) {
                    manufactureDateByLabSampleIds.put(labSampleTapeCode.Lab_Sample__c, labSampleTapeCode.Manufacture_Date__c);
                }
            }
        }

        if (manufactureDateByLabSampleIds.isEmpty()) {
            return;
        }

        Map<Id, Lab_Sample__c> toUpdate = new Map<Id, Lab_Sample__c>();
        for (Lab_Sample__c labSample : [SELECT Id, Recent_Manufacture_Date__c FROM Lab_Sample__c WHERE Id IN :manufactureDateByLabSampleIds.keySet()]) {
            String manufactureDate = manufactureDateByLabSampleIds.get(labSample.Id);
            if (manufactureDate != 'Z') {
                labSample.Recent_Manufacture_Date__c = manufactureDate == NULL ? NULL : Date.valueOf(manufactureDate);
                toUpdate.put(labSample.Id, labSample);
            }
        }

        if (toUpdate.isEmpty()) {
            return;
        }

        Database.update(toUpdate.values(), false);


    } // end populateLabSampleRecentManufactureDate method
}