ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>Used to track the high level stages of the Claim</description>
    <label>Claim Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting Docs</fullName>
            </value>
            <value>
                <fullName>In Kankakee</fullName>
            </value>
            <value>
                <fullName>In Lab</fullName>
            </value>
            <value>
                <fullName>File Preparation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Sub_Stage__c</fullName>
    <label>Claim Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Claim_Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting POP</fullName>
            </value>
            <value>
                <fullName>POP Received</fullName>
            </value>
            <value>
                <fullName>Additional POP Required</fullName>
            </value>
            <value>
                <fullName>Initial review</fullName>
            </value>
            <value>
                <fullName>HOIS sent</fullName>
            </value>
            <value>
                <fullName>Awaiting HOIS</fullName>
            </value>
            <value>
                <fullName>Awaiting Samples</fullName>
            </value>
            <value>
                <fullName>Samples Received</fullName>
            </value>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Data Entry</fullName>
            </value>
            <value>
                <fullName>Info Required</fullName>
            </value>
            <value>
                <fullName>Info Requested</fullName>
            </value>
            <value>
                <fullName>Goodwill review</fullName>
            </value>
            <value>
                <fullName>In review</fullName>
            </value>
            <value>
                <fullName>Release Pending</fullName>
            </value>
            <value>
                <fullName>Waiting for Invoice</fullName>
            </value>
            <value>
                <fullName>Check/Credit Requested</fullName>
            </value>
            <value>
                <fullName>Check/Credit Approved</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Goodwill Requested</fullName>
            </value>
            <value>
                <fullName>Goodwill Rejected</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Samples Sent to Lab</fullName>
            </value>
            <value>
                <fullName>Dealer Invoice Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claims_Config__c/Claims_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to store values for the Claims team app configurations</description>
    <label>Claims Config</label>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claims_Config__c/fields/SharinPix_Annotate_Permission_Id__c.field-meta.xml
<CustomField>
    <fullName>SharinPix_Annotate_Permission_Id__c</fullName>
    <inlineHelpText>Allows end user to upload images, annotate, crop, resize</inlineHelpText>
    <label>SharinPix Annotate Permission Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claims_Config__c/fields/SharinPix_Read_Only_Permission__c.field-meta.xml
<CustomField>
    <fullName>SharinPix_Read_Only_Permission__c</fullName>
    <inlineHelpText>Used in Lightning Pages to apply a read-only permission</inlineHelpText>
    <label>SharinPix Read Only Permission</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claims_Config__c/fields/SharinPix_Upload_Only_Permission__c.field-meta.xml
<CustomField>
    <fullName>SharinPix_Upload_Only_Permission__c</fullName>
    <inlineHelpText>For the SharinPix Permission where the Claims team can continue to upload images at any point of the process</inlineHelpText>
    <label>SharinPix Upload Only Permission</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/Lab_Sample__c.object-meta.xml
<CustomObject>
    <label>Lab Sample</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Samples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A link to the Claim this lab sample is related to. Lab Samples with no links to a Claim have been received but not properly connected to a cliam.</description>
    <inlineHelpText>The Claim this Lab Sample relates to.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Lab Samples</relationshipLabel>
    <relationshipName>Lab_Samples</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>https://ikoussfsc.atlassian.net/browse/CLAIMSV2-358
Claims Stage</description>
    <formula>TEXT(Case__r.Claim_Stage__c)</formula>
    <inlineHelpText>Claims Stage</inlineHelpText>
    <label>Claim Stage</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Claim_Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Sub_Stage__c</fullName>
    <description>https://ikoussfsc.atlassian.net/browse/CLAIMSV2-358
Claim Sub Stage</description>
    <formula>Text( Case__r.Claim_Sub_Stage__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Claim Sub Stage</inlineHelpText>
    <label>Claim Sub Stage</label>
    <type>Text</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/SharinPixPermissionsController.cls
/**
 * @description Sharinpix images controller based on the Logged in User profile and the Claim Stage and Sub Stage
 * @author Sinan Bunni
 * @date 16/09/2019
 */
public with sharing class SharinPixPermissionsController {

    private static final String EMPTY = '';
    private static final String CASEOBJECT = 'Case';
    private static final String LABSAMPLEOBJECT = 'Lab_Sample__c';

    private static String profileName {
        get {
            if (profileName == NULL) {
                profileName = [SELECT Id, Name FROM Profile WHERE Id = :UserInfo.getProfileId()].Name;
            }

            return profileName;
        }
        set;
    }

    /**
     * @description Security: Determine SharinPix permission set to apply to Case/ Lab Sample
     * Leverages the Claims_Config__c custom setting to determine the
     * appropriate permission id to return to the sharinPixWrapper component.
     * Returns the sharinPix permissions (annotate, read only or upload) based on
     * Claim Stage, Claim Sub Stage and logged in profile name
     *
     * @param recordId object Id passed in by the @see sharinPixWrapper lightning component
     * @param objectName object name passed in by the @see sharinPixWrapper lightning component
     *
     * @return String represents the sharingPix permissions Id
     */
    @AuraEnabled
    public static String getSharinPixPermissions(final Id recordId, final String objectName) {

        String sharinPixPermission = EMPTY;

        if (objectName == CASEOBJECT) {
            Case caseRecord = [
                    SELECT Id, Claim_Stage__c, Claim_Sub_Stage__c
                    FROM Case
                    WHERE Id = :recordId
            ];
            sharinPixPermission = getSharinPixPermissionId(caseRecord.Claim_Stage__c, caseRecord.Claim_Sub_Stage__c);
        } else if (objectName == LABSAMPLEOBJECT) {
            Lab_Sample__c labSample = [
                    SELECT Case__c, Case__r.Claim_Stage__c, Case__r.Claim_Sub_Stage__c
                    FROM Lab_Sample__c
                    WHERE Id = :recordId
                    LIMIT 1
            ];
            String claimStage = labSample.Case__r.Claim_Stage__c;
            String claimSubStage = labSample.Case__r.Claim_Sub_Stage__c;

            sharinPixPermission = getSharinPixPermissionId(claimStage, claimSubStage);
        }

        return sharinPixPermission;

    } // end getSharinPixPermissionId method

    /**
     * @description Get the CaseId associatd with the Lab Sample
     * @param labSampleId Lab Sample Id
     * @return parent CaseId to the Lab Sample record
     */
    @AuraEnabled
    public static String getCaseIdByLabSampleId(String labSampleId) {
        if (labSampleId == NULL) {
            return EMPTY;
        }

        return [SELECT Case__c FROM Lab_Sample__c WHERE Id = :labSampleId LIMIT 1].Case__c;
    } // end getCaseIdByLabSampleId method

    /**
     * @description Retrieve the SharinPix Permission Id
     *
     * @param recordId object Id passed in by the @see sharinPixWrapper lightning component
     * @param claimStage object name passed in by the @see sharinPixWrapper lightning component
     *
     * @return String resprests the sharingPix Permission Id
     */
    private static String getSharinPixPermissionId(final String claimStage, final String claimSubStage) {

        String sharinPixPermission = EMPTY;

        try {
            if (claimStage == 'Draft') {
                //ClaimsV2-1029 Nov 30, 2020 Vicki Tran..Plant users can only 'read' at 'Draft' stage
                if (profileName.contains('Plant')) {
                    sharinPixPermission = Claims_Config__c.getOrgDefaults().SharinPix_Read_Only_Permission__c;
                }
                else
                {
                	sharinPixPermission = Claims_Config__c.getOrgDefaults().SharinPix_Annotate_Permission_Id__c;
                }
            }

            if (claimStage == 'Submitted' || claimStage == 'Awaiting Docs' || claimStage == 'In Kankakee' ||
                    (claimStage == 'In Lab' && (claimSubStage != 'In Approval' || claimSubStage != 'Approved'))) {
                if (profileName.contains('Lab')) {
                    sharinPixPermission = Claims_Config__c.getOrgDefaults().SharinPix_Annotate_Permission_Id__c;
                } else if (profileName.contains('Claim')) {
                    sharinPixPermission = Claims_Config__c.getOrgDefaults().SharinPix_Upload_Only_Permission__c;
                } else {
                    sharinPixPermission = Claims_Config__c.getOrgDefaults().SharinPix_Read_Only_Permission__c;
                }
            }

            if (claimStage == 'File Preparation' || claimStage == 'Assessment' || claimStage == 'Offered' || claimStage == 'Payment' ||
                    (claimStage == 'In Lab' && (claimSubStage == 'In Approval' || claimSubStage == 'Approved'))) {
                if (profileName.contains('Claim')) {
                    sharinPixPermission = Claims_Config__c.getOrgDefaults().SharinPix_Upload_Only_Permission__c;
                } else {
                    sharinPixPermission = Claims_Config__c.getOrgDefaults().SharinPix_Read_Only_Permission__c;
                }
            }

            if (claimStage == 'Closed') {
                sharinPixPermission = Claims_Config__c.getOrgDefaults().SharinPix_Read_Only_Permission__c;
            }
        } catch (Exception exp) {
            System.debug('getSharinPixPermissionId: error = ' + exp.getMessage());
        }

        return sharinPixPermission;
    } // end getSharinPixPermissionId method

} // end SharinPixPermissionsController class