ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>Used to track the high level stages of the Claim</description>
    <label>Claim Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting Docs</fullName>
            </value>
            <value>
                <fullName>In Kankakee</fullName>
            </value>
            <value>
                <fullName>In Lab</fullName>
            </value>
            <value>
                <fullName>File Preparation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Sub_Stage__c</fullName>
    <label>Claim Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Claim_Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting POP</fullName>
            </value>
            <value>
                <fullName>POP Received</fullName>
            </value>
            <value>
                <fullName>Additional POP Required</fullName>
            </value>
            <value>
                <fullName>Initial review</fullName>
            </value>
            <value>
                <fullName>HOIS sent</fullName>
            </value>
            <value>
                <fullName>Awaiting HOIS</fullName>
            </value>
            <value>
                <fullName>Awaiting Samples</fullName>
            </value>
            <value>
                <fullName>Samples Received</fullName>
            </value>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Data Entry</fullName>
            </value>
            <value>
                <fullName>Info Required</fullName>
            </value>
            <value>
                <fullName>Info Requested</fullName>
            </value>
            <value>
                <fullName>Goodwill review</fullName>
            </value>
            <value>
                <fullName>In review</fullName>
            </value>
            <value>
                <fullName>Release Pending</fullName>
            </value>
            <value>
                <fullName>Waiting for Invoice</fullName>
            </value>
            <value>
                <fullName>Check/Credit Requested</fullName>
            </value>
            <value>
                <fullName>Check/Credit Approved</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Goodwill Requested</fullName>
            </value>
            <value>
                <fullName>Goodwill Rejected</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Samples Sent to Lab</fullName>
            </value>
            <value>
                <fullName>Dealer Invoice Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/ClaimApproved__c.field-meta.xml
<CustomField>
    <fullName>ClaimApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that Claims Manager has approved the entire claim. This semi-closes the claim in the sense that changes should be minimal but there are still things to process. This is different than the &quot;Goodwill Amount Approve&quot; or &quot;Address Validation.&quot; A claim can have its goodwill amount approved but NOT but fully approved yet.</description>
    <label>Claim Approved?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/Lab_Sample__c.object-meta.xml
<CustomObject>
    <label>Lab Sample</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Samples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A link to the Claim this lab sample is related to. Lab Samples with no links to a Claim have been received but not properly connected to a cliam.</description>
    <inlineHelpText>The Claim this Lab Sample relates to.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Lab Samples</relationshipLabel>
    <relationshipName>Lab_Samples</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>https://ikoussfsc.atlassian.net/browse/CLAIMSV2-358
Claims Stage</description>
    <formula>TEXT(Case__r.Claim_Stage__c)</formula>
    <inlineHelpText>Claims Stage</inlineHelpText>
    <label>Claim Stage</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Claim_Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Sub_Stage__c</fullName>
    <description>https://ikoussfsc.atlassian.net/browse/CLAIMSV2-358
Claim Sub Stage</description>
    <formula>Text( Case__r.Claim_Sub_Stage__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Claim Sub Stage</inlineHelpText>
    <label>Claim Sub Stage</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Eligible_for_Approval_submission__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Approval_submission__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CLAIMS - 574. This field is populated by the LabTestResultTrigger only when all related LabTest Results are either in Completed or Not Required Status. This field will be used in the entry criteria for the LabSample approval process</description>
    <inlineHelpText>Signifies if Lab Sample is eligible for approval submission based on whether all related Lab Test Results are either in Completed or Not Required Status</inlineHelpText>
    <label>(Deprecated) Eligible for Approval</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Test_Result__c/Lab_Test_Result__c.object-meta.xml
<CustomObject>
    <description>This is to record lab test results for the Lab Sample.</description>
    <label>Lab Test Result</label>
    <nameField>
        <displayFormat>LTR-{0000000000}</displayFormat>
        <label>Lab Test Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Test Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Test_Result__c/fields/Lab_Sample__c.field-meta.xml
<CustomField>
    <fullName>Lab_Sample__c</fullName>
    <description>this is the lab sample that is tested.</description>
    <label>Lab Sample</label>
    <referenceTo>Lab_Sample__c</referenceTo>
    <relationshipLabel>Lab Test Results</relationshipLabel>
    <relationshipName>Lab_Test_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Test_Result__c/fields/N_A__c.field-meta.xml
<CustomField>
    <fullName>N_A__c</fullName>
    <defaultValue>false</defaultValue>
    <description>2020-02-03 this is being removed. Allow Lab team to flag a test to skip a test added to the Lab Sample if no longer needed</description>
    <label>(deprecated) Not Applicable</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Test_Result__c/fields/Test_Result__c.field-meta.xml
<CustomField>
    <fullName>Test_Result__c</fullName>
    <description>This is the test result recorded by the lab tech</description>
    <label>Test Result</label>
    <length>131070</length>
    <type>Html</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Test_Result__c/fields/Test_Status__c.field-meta.xml
<CustomField>
    <fullName>Test_Status__c</fullName>
    <description>This is to indicate the progress of the lab test for the lab samples.</description>
    <label>Test Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/LabSampleTestResultService.cls
public with sharing class LabSampleTestResultService {
    /*
        Block all updates for Case when the Claim_Stage__c is Closed, *unless* it is being re-opened
    */
    public static void blockCreatedUpdateDelete(List<Lab_Test_Result__c> records) {
        User runningUser = [SELECT Id, Profile.Name FROM User WHERE Id = :UserInfo.getUserId()];
//
        Map<Id, RecordType> claimRecordTypes = CaseService.getClaimRecordTypes();
        List<Id> caseIds = new List<Id>();

        List<Id> labSampleIds = new List<Id>();

        for (Lab_Test_Result__c record : records) {
            labSampleIds.add(record.Lab_Sample__c);
        }

        // SOQL query modified as part of US IWCN-723
        Map<Id, Lab_Sample__c> labSamplesMap = new Map<Id, Lab_Sample__c>(
        [
                SELECT Id, Case__r.RecordTypeId, Case__r.Claim_Stage__c, Case__r.Claim_Sub_Stage__c, Case__r.ClaimApproved__c
                FROM Lab_Sample__c
                WHERE Id IN :labSampleIds
                AND Case__r.RecordTypeId IN :claimRecordTypes.keySet()
                AND (
                        Case__r.Claim_Stage__c = 'Closed' OR
                        Case__r.ClaimApproved__c = true OR
                        (Case__r.Claim_Stage__c = 'Assessment' AND Case__r.Claim_Sub_Stage__c = 'In Approval')
                )
        ]
        );
        if (labSamplesMap.isEmpty()) {
            return;
        }

        for (Lab_Test_Result__c record : records) {
            Lab_Sample__c labSampleRecord = labSamplesMap.get(record.Lab_Sample__c);
            System.debug('what is in labSampleRecord?'+labSampleRecord);
            if (labSampleRecord.Case__r.Claim_Stage__c == 'Closed' && runningUser.Profile.Name != 'System Administrator') {
                record.addError('Lab Sample Tape Codes cannot be modified for a closed case');
            } else {
                record.addError('Case Lab Samples cannot be modifed after submitting for approval');
            }
        }

    }

    /*
        CLAIMS -359
        Update Status field according to value in Test Result field
    */
    public static void updateOwnerIdAndStatusAccordingToTestResult(List<Lab_Test_Result__c> newLabTestResults) {

		//CLAIMS - 359
		if (newLabTestResults.isEmpty()) {
			return;
		}

        /* claimsV2-730 queue id is no longer assigned to owner Id due to the master detail relationship.
        List<QueueSobject> queueIds = [SELECT QueueId, Queue.Name, SobjectType FROM QueueSobject WHERE Queue.Name = 'Lab Test Queue'];
        if (queueIds.isEmpty()) {
            return;
        }
		*/
        for (Lab_Test_Result__c labTestResult : newLabTestResults) {
            //ClaimsV2-730 owner Id is not used anymore, master detail relationship.
          //  labTestResult.OwnerId = queueIds.get(0).QueueId;
            if (labTestResult.Test_Result__c != NULL &&
                    labTestResult.Test_Result__c != '' && labTestResult.Test_Status__c == 'New' //&&
                    //Condition for N/A added for CLAIMS - 514
                   /* !labTestResult.N_A__c*/) {
                labTestResult.Test_Status__c = 'Completed';
            } //else if - added for CLAIMS - 514
           /* else if(labTestResult.N_A__c){
                labTestResult.Test_Status__c = 'Not Required';
            }*/
        }
    }

    public static void countCompletedAndNotRequiredTestResultsForLabSample(List<Lab_Test_Result__c> newLabTestResults,
                                                                            Map<Id,Lab_Test_Result__c> oldLabTestResultMapByIds){

        Set<Id> labSampleIds = new Set<Id>();

        // For insert
        if(newLabTestResults!= NULL && oldLabTestResultMapByIds == NULL){
            for(Lab_Test_Result__c eachTestResult : newLabTestResults){
                labSampleIds.add(eachTestResult.Lab_Sample__c);
             }
        }
        //for delete
        else if(newLabTestResults == NULL && oldLabTestResultMapByIds != NULL){
            for(Lab_Test_Result__c eachTestResult : oldLabTestResultMapByIds.values()){
                labSampleIds.add(eachTestResult.Lab_Sample__c);
            }
        }
        //for update
        else{
            for(Lab_Test_Result__c eachTestResult : newLabTestResults){
                if(eachTestResult.Test_Status__c != oldLabTestResultMapByIds.get(eachTestResult.Id).Test_Status__c){
                    labSampleIds.add(eachTestResult.Lab_Sample__c);
                }
            }
        }

       if(labSampleIds.isEmpty()){
            return;
        }

        // retrieve LabSamples along with all related test results
        List<Lab_Sample__c> allSamplesWithRelatedResults = [SELECT Id,Eligible_for_Approval_submission__c,
                                                            (Select Id,Test_Status__c FROM Lab_Test_Results__r)
                                                            FROM Lab_Sample__c WHERE Id IN :labSampleIds];

        System.debug('@@@allSamplesWithRelatedResults--'+allSamplesWithRelatedResults);

        // retrieve test results which are 'Completed' or 'Not Required'
        AggregateResult[] groupedResult = [SELECT Lab_Sample__c,COUNT(Test_Status__c) FROM Lab_Test_Result__c
                                            WHERE (Lab_Sample__c IN :labSampleIds OR CreatedDate = TODAY) AND
                                            (Test_Status__c = 'Completed' OR Test_Status__c = 'Not Required') GROUP BY Lab_Sample__c];

        Map<Id,Integer> sequenceMap = new Map<Id, Integer>();
        for(AggregateResult agr : groupedResult){
            sequenceMap.put(String.valueOf(agr.get('Lab_Sample__c')),Integer.valueOf(agr.get('expr0')));
        }

        List<Lab_Sample__c> toUpdateLabSamples = new List<Lab_Sample__c>();

        for(Lab_Sample__c eachLabSample : allSamplesWithRelatedResults){

            Integer countOfEligibleTestResults = sequenceMap.get(eachLabSample.Id);

            System.debug('@@@countOfEligibleTestResults--'+countOfEligibleTestResults);
            System.debug('@@@eachLabSample.Lab_Test_Results__r.size()--'+eachLabSample.Lab_Test_Results__r.size());

            if(countOfEligibleTestResults == eachLabSample.Lab_Test_Results__r.size()){
                eachLabSample.Eligible_for_Approval_submission__c = TRUE;
                toUpdateLabSamples.add(eachLabSample);
            }else{
                eachLabSample.Eligible_for_Approval_submission__c = FALSE;
                toUpdateLabSamples.add(eachLabSample);
            }
        }

        if(!toUpdateLabSamples.isEmpty()){
            update toUpdateLabSamples;
        }

    }//countCompletedAndNotRequiredTestResultsForLabSample() end

}