ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>Used to track the high level stages of the Claim</description>
    <label>Claim Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting Docs</fullName>
            </value>
            <value>
                <fullName>In Kankakee</fullName>
            </value>
            <value>
                <fullName>In Lab</fullName>
            </value>
            <value>
                <fullName>File Preparation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Sub_Stage__c</fullName>
    <label>Claim Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Claim_Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting POP</fullName>
            </value>
            <value>
                <fullName>POP Received</fullName>
            </value>
            <value>
                <fullName>Additional POP Required</fullName>
            </value>
            <value>
                <fullName>Initial review</fullName>
            </value>
            <value>
                <fullName>HOIS sent</fullName>
            </value>
            <value>
                <fullName>Awaiting HOIS</fullName>
            </value>
            <value>
                <fullName>Awaiting Samples</fullName>
            </value>
            <value>
                <fullName>Samples Received</fullName>
            </value>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Data Entry</fullName>
            </value>
            <value>
                <fullName>Info Required</fullName>
            </value>
            <value>
                <fullName>Info Requested</fullName>
            </value>
            <value>
                <fullName>Goodwill review</fullName>
            </value>
            <value>
                <fullName>In review</fullName>
            </value>
            <value>
                <fullName>Release Pending</fullName>
            </value>
            <value>
                <fullName>Waiting for Invoice</fullName>
            </value>
            <value>
                <fullName>Check/Credit Requested</fullName>
            </value>
            <value>
                <fullName>Check/Credit Approved</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Goodwill Requested</fullName>
            </value>
            <value>
                <fullName>Goodwill Rejected</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Samples Sent to Lab</fullName>
            </value>
            <value>
                <fullName>Dealer Invoice Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/ClaimApproved__c.field-meta.xml
<CustomField>
    <fullName>ClaimApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that Claims Manager has approved the entire claim. This semi-closes the claim in the sense that changes should be minimal but there are still things to process. This is different than the &quot;Goodwill Amount Approve&quot; or &quot;Address Validation.&quot; A claim can have its goodwill amount approved but NOT but fully approved yet.</description>
    <label>Claim Approved?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Settlement_Condition__c/Settlement_Condition__c.object-meta.xml
<CustomObject>
    <description>Used to capture Settlement Conditions against a Claim Case</description>
    <label>Settlement Condition</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Settlement Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Settlement_Condition__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Settlement Condition to be leveraged in offer letters</description>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Commercial Claim, Residential Claim</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Settlement Conditions</relationshipLabel>
    <relationshipName>Settlement_Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/SettlementConditionService.cls
public with sharing class SettlementConditionService {

	/*
		Block all updates for Case when the Claim_Stage__c is Closed, *unless* it is being re-opened
	*/
	public static void blockCreatedUpdateDelete(List<Settlement_Condition__c> records) {
		User runningUser = [SELECT Id, Profile.Name FROM User WHERE Id = :UserInfo.getUserId()];

		Map<Id, RecordType> claimRecordTypes = CaseService.getClaimRecordTypes();
		List<Id> caseIds = new List<Id>();

		for (Settlement_Condition__c record : records)
			caseIds.add(record.Case__c);

		// SOQL query modified as part of US IWCN-723
		Map<Id, Case> caseMap = new Map<Id, Case>(
		[
				SELECT Id, RecordTypeId, Claim_Stage__c, ClaimApproved__c, Claim_Sub_Stage__c
				FROM Case
				WHERE Id IN :caseIds
				AND RecordTypeId IN :claimRecordTypes.keySet()
				AND
				(
						Claim_Stage__c = 'Closed' OR
						ClaimApproved__c = true OR
						(Claim_Stage__c = 'Assessment' AND Claim_Sub_Stage__c = 'In Approval')
				)
		]
		);

		if (caseMap.isEmpty()) {
			return;
		}

		for (Settlement_Condition__c record : records) {
			Case caseRecord = caseMap.get(record.Case__c);
			if (runningUser.Profile.Name != 'System Administrator') {
				if (caseRecord.Claim_Stage__c == 'Closed') {
					record.addError('Settlement Conditions cannot be modified for a closed case');
				} else {
					record.addERror('Case Settlement Condition cannot be modifed after submitting for approval');
				}
			}
		}
	}
}