ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Claim_Number__c</fullName>
    <description>Claim Number assigned to the Claim; should never change. By default, will be assigned the value from the Generated_Claim_Number__c formula field, but may be use other values (e.g. imported from WCMS system)</description>
    <externalId>true</externalId>
    <label>Claim Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>Used to track the high level stages of the Claim</description>
    <label>Claim Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting Docs</fullName>
            </value>
            <value>
                <fullName>In Kankakee</fullName>
            </value>
            <value>
                <fullName>In Lab</fullName>
            </value>
            <value>
                <fullName>File Preparation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icRepoCase.cls
/**
 * Created by Anil Mannem (Incloud) on 28-July-2020
 */
public class icRepoCase implements icIClass {

	public Object GetInstance() {
		return new Impl();
	}

	public Interface IClass {
		List<Case> getCaseById(Set<String> caseId);
	}

	public class Impl implements IClass {
		/** Ticket ClaimsV2-931
		 *  Added Repo to query Cases
		 *  By Anil Mannem (Incloud) on 28-July-2020
		 */
		public List<Case> getCaseById(Set<String> caseId) {
            return [SELECT  Id,
                            Claim_Number__c,
                            Claim_Stage__c
                    FROM Case
                    WHERE Id =:caseId];
		}
	}
}