ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>Used to track the high level stages of the Claim</description>
    <label>Claim Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting Docs</fullName>
            </value>
            <value>
                <fullName>In Kankakee</fullName>
            </value>
            <value>
                <fullName>In Lab</fullName>
            </value>
            <value>
                <fullName>File Preparation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Sub_Stage__c</fullName>
    <label>Claim Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Claim_Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting POP</fullName>
            </value>
            <value>
                <fullName>POP Received</fullName>
            </value>
            <value>
                <fullName>Additional POP Required</fullName>
            </value>
            <value>
                <fullName>Initial review</fullName>
            </value>
            <value>
                <fullName>HOIS sent</fullName>
            </value>
            <value>
                <fullName>Awaiting HOIS</fullName>
            </value>
            <value>
                <fullName>Awaiting Samples</fullName>
            </value>
            <value>
                <fullName>Samples Received</fullName>
            </value>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Data Entry</fullName>
            </value>
            <value>
                <fullName>Info Required</fullName>
            </value>
            <value>
                <fullName>Info Requested</fullName>
            </value>
            <value>
                <fullName>Goodwill review</fullName>
            </value>
            <value>
                <fullName>In review</fullName>
            </value>
            <value>
                <fullName>Release Pending</fullName>
            </value>
            <value>
                <fullName>Waiting for Invoice</fullName>
            </value>
            <value>
                <fullName>Check/Credit Requested</fullName>
            </value>
            <value>
                <fullName>Check/Credit Approved</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Goodwill Requested</fullName>
            </value>
            <value>
                <fullName>Goodwill Rejected</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Samples Sent to Lab</fullName>
            </value>
            <value>
                <fullName>Dealer Invoice Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/ClaimApproved__c.field-meta.xml
<CustomField>
    <fullName>ClaimApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that Claims Manager has approved the entire claim. This semi-closes the claim in the sense that changes should be minimal but there are still things to process. This is different than the &quot;Goodwill Amount Approve&quot; or &quot;Address Validation.&quot; A claim can have its goodwill amount approved but NOT but fully approved yet.</description>
    <label>Claim Approved?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Primary_Claim_Concern__c.field-meta.xml
<CustomField>
    <fullName>Primary_Claim_Concern__c</fullName>
    <description>Claim Concern from the Primary Claim Type</description>
    <label>Primary Claim Concern</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Primary_Claim_Type__c.field-meta.xml
<CustomField>
    <fullName>Primary_Claim_Type__c</fullName>
    <description>This is populated by a workflow rule from the Primary Claim Type</description>
    <label>Primary Claim Type</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Secondary_Claim_Types__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Claim_Types__c</fullName>
    <label>Secondary Claim Types</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/Claim_Type__c.object-meta.xml
<CustomObject>
    <description>Used to capture the Primary and Secondary reason for the Claim Case</description>
    <label>Claim Type</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Claim Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Related Claim Case</description>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Case must be a Residential or Commercial Claim</errorMessage>
        <filterItems>
            <field>Case.RecordType.Name</field>
            <operation>contains</operation>
            <value>Claim</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Claim Types</relationshipLabel>
    <relationshipName>Claim_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Concern__c.field-meta.xml
<CustomField>
    <fullName>Concern__c</fullName>
    <label>Concern</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Claim_Type_Reason</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this the Primary Claim Type?</description>
    <label>Is Primary?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>(none)</fullName>
            </value>
            <value>
                <fullName>A Organic</fullName>
            </value>
            <value>
                <fullName>B Glass</fullName>
            </value>
            <value>
                <fullName>C Lam/Org</fullName>
            </value>
            <value>
                <fullName>D Lam/Glass</fullName>
            </value>
            <value>
                <fullName>E Coated Rolls</fullName>
            </value>
            <value>
                <fullName>F Mod Bit</fullName>
            </value>
            <value>
                <fullName>G Felt</fullName>
            </value>
            <value>
                <fullName>H Asphalt</fullName>
            </value>
            <value>
                <fullName>I Fibrebrd</fullName>
            </value>
            <value>
                <fullName>J Total</fullName>
            </value>
            <value>
                <fullName>K Lock</fullName>
            </value>
            <value>
                <fullName>L ArmourGd</fullName>
            </value>
            <value>
                <fullName>M Protecbrd</fullName>
            </value>
            <value>
                <fullName>N Poly ISO</fullName>
            </value>
            <value>
                <fullName>P Roof-Fast</fullName>
            </value>
            <value>
                <fullName>Q Gold Shield</fullName>
            </value>
            <value>
                <fullName>R Adhs/Ctgs</fullName>
            </value>
            <value>
                <fullName>Z Not IKO</fullName>
            </value>
            <value>
                <fullName>Valley Cap</fullName>
            </value>
            <value>
                <fullName>Panels</fullName>
            </value>
            <value>
                <fullName>Hip &amp; Ridge</fullName>
            </value>
            <value>
                <fullName>Valley</fullName>
            </value>
            <value>
                <fullName>Touch up kit</fullName>
            </value>
            <value>
                <fullName>Screws</fullName>
            </value>
            <value>
                <fullName>Starter w drip</fullName>
            </value>
            <value>
                <fullName>Side</fullName>
            </value>
            <value>
                <fullName>Rake</fullName>
            </value>
            <value>
                <fullName>XD Channel</fullName>
            </value>
            <value>
                <fullName>Debris guard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/ClaimTypeService.cls
public with sharing class ClaimTypeService {

    /*
        Block all updates for Case when the Claim_Stage__c is Closed, *unless* it is being re-opened
    */
    public static void blockCreatedUpdateDelete(List<Claim_Type__c> records) {
        User runningUser = [SELECT Id, Profile.Name FROM User WHERE Id = :UserInfo.getUserId()];
        Map<Id, RecordType> claimRecordTypes = CaseService.getClaimRecordTypes();
        List<Id> caseIds = new List<Id>();

        for (Claim_Type__c rp : records)
            caseIds.add(rp.Case__c);

        // SOQL query modified as part of US IWCN-723
        Map<Id, Case> caseMap = new Map<Id, Case>(
        [
                SELECT Id, RecordTypeId, Claim_Stage__c, Claim_Sub_Stage__c, ClaimApproved__c
                FROM Case
                WHERE Id IN :caseIds
                AND RecordTypeId IN :claimRecordTypes.keySet()
                AND
                (
                        Claim_Stage__c = 'Closed' OR
                        ClaimApproved__c = true OR
                        (Claim_Stage__c = 'Assessment' AND Claim_Sub_Stage__c = 'In Approval')
                )
        ]
        );

        if (caseMap.isEmpty()) {
            return;
        }

        for (Claim_Type__c rp : records) {
            Case caseRecord = caseMap.get(rp.Case__c);
            if (runningUser.Profile.Name != 'System Administrator') {
                if (caseRecord.Claim_Stage__c == 'Closed') {
                    rp.addError('Claim Types cannot be modified for a closed case');
                } else {
                    rp.addERror('Case Claim Types cannot be modifed after submitting for approval');
                }
            }
        }
    }


    // If the claim type being inserted is _not_ primary, make sure there
    // is a primary claim type related to the claim. If there isn't, set
    // this one to the Primary Claim Type
    // End result: there will always one primary claim type
    public static void setPrimary(List<Claim_Type__c> records) {

		System.Debug('Setting Primary Claim Type');
        
        Set<Id> caseIds = new Set<Id>();
        Set<Id> claimTypeIds = new Set<Id>();
        
        for (Claim_Type__c c : records) {
            caseIds.add(c.Case__c);
            claimTypeIds.add(c.Id);
        }
        // Build a list of claim types related to these cases that ARE primary
        // We're going to use list size to figure out whether to make this one primary
        List<Claim_Type__c> isPrimary = new List<Claim_Type__c>([
                SELECT Id, Case__c, Is_Primary__c, Product_Type__c, Concern__c, Case__r.Claim_Stage__c, Case__r.ClaimApproved__c, Case__r.Claim_Sub_Stage__c
                FROM Claim_Type__c
                WHERE Case__c IN :caseIds
                AND Is_Primary__c = TRUE
        ]);

        // if (isPrimary.isEmpty()) {
        //    return;
        // }
        // Turn this into a map so we can can use Contains Key

        // Loop through records and see check to see if there's an existing primary match in the map
        // if the map doesn't contain anything related to the case, there is no primary claim type so
        // we should set this one to be it

        // This is going to store the list of things we need to set to not primary
        // we're using the set because we get a duplicate ID error when more than one
        // Primary is loaded. Sets don't have duplicates. The problem relates only
        // mass data loads and will not happen in the real world, but this helped
        List<Claim_Type__c> otherClaimTypes = new List<Claim_Type__c>();
        Set<Claim_Type__c> uniqueClaim = new Set<Claim_Type__c>();

        for (Claim_Type__c c : records) {

            // If the insert of update is set to primary, we set any
            // other primary claims to false and update those records
            if (c.Is_Primary__c == true) {
                for (Claim_Type__c ct : isPrimary) {
                    // we're going to skip this record
                    if (ct.Id != c.Id) {
                        ct.Is_Primary__c = false;
                        uniqueClaim.add(ct);
                    }
                }

            } else {
                // If the insert or update is set to NOT primary, we check to make sure
                // a primary claim type exists. If it doesn't, make it so.
                Map<Id, Claim_Type__c> primaryClaimsbyCaseId = new Map<Id, Claim_type__c>();
                for (Claim_Type__c ct : isPrimary) {
                    primaryClaimsbyCaseId.put(c.Case__c, c);
                }

                if (primaryClaimsbyCaseId.containsKey(c.Case__c) == false) {
                    c.Is_Primary__c = true;
                }
            }

        }

        // Fun deduplication trick: convert the list to a set, which contains no duplicates, then convert it back to
        otherClaimTypes.addAll(uniqueClaim);
        Database.update(otherClaimTypes, false);
    }
    
    // This is inappropriately named. It sets the Primary and the Secondary
    public static void setPrimaryAndSecondary(List<Claim_Type__c> newClaimTypes, Map<Id, Claim_Type__c> oldClaimTypesByIds) {
         // if(checkRecursive.runOnce()) {
        System.Debug('Setting Secondary Claim Types');
        
        List<Case> casesToUpdate = new List<Case>();

        Set<Id> caseIds = new Set<Id>();
        
		// 2020-02-04
		// This is needed to accomodate a delete, which means the OLD claimtype IDs would have this
		// but not the new
        if (oldClaimTypesByIds != NULL) {
            caseIds = caseIdsBeforeUpdate(newClaimTypes, oldClaimTypesByIds);
        } else {
            caseIds = caseIdsBeforeInsert(newClaimTypes);
        }

        // 2019-02-04
        // This should not be needed. If it's empty, nothing will happen
        // if (caseIds.isEmpty()) {
        //     return;
        // }
	
        System.Debug('Getting all Secondary Claim Types');
		// Gets a list of all the claim types related to all the cases
        /* 
         * Map<Id, Claim_Type__c> relatedClaimTypes = new Map<Id, Claim_Type__c> ([
                SELECT Id, Is_Primary__c, Case__c, Product_Type__c, Concern__c
                FROM Claim_Type__c
                WHERE Case__c IN :caseIds
        ]);
*/		
        list<Claim_Type__c> allRelatedClaimTypes = new list<Claim_Type__c>([SELECT Id, 
                                                                            Is_Primary__c, 
                                                                            Case__c, 
                                                                            Product_Type__c, 
                                                                            Concern__c
                                                                            FROM Claim_Type__c
                                                                            WHERE Case__c IN :caseIds
                                                                            ORDER BY Product_Type__c ASC]);

		System.Debug('Claim Types ' + allRelatedClaimTypes.size());

            if (allRelatedClaimTypes.isEmpty()) {
            // It is the last Claim Type record that was deleted
            // update the Case Secondary Claim Type to NULL
            for (Id caseId : caseIds) {
                Case c = new Case();
                	c.Id = caseId;
                    c.Primary_Claim_Type__c = null;
                    c.Primary_Claim_Concern__c = null;
                    c.Secondary_Claim_Types__c = null;
                casesToUpdate.add(c);
            }
        } else {

            for(Id caseId : caseIds) {
                Case c = new Case();
                	c.Id = caseId;
                	c.Secondary_Claim_Types__c = '';

				// loop through claim types
				// using a nested loop to first get a claim ID then to loop throgh a claim type
				// don't love this but...alternatives? Maps are unique by ID, so...
                for(Claim_Type__c ct : allRelatedClaimTypes) {
                    if(ct.Case__c == c.Id) {
                        if(ct.Is_Primary__c == true) {
                            System.Debug('Primary');
                            c.Primary_Claim_Type__c = ct.Product_Type__c;
                            c.Primary_Claim_Concern__c = ct.Concern__c;
                        } else {
                            c.Secondary_Claim_Types__c += ct.Product_Type__c + ' - ' + ct.Concern__c + ', ';
                            System.Debug('Secondary');
                        }
                    }
					
            }
                    // this just strips the final ', '
                    c.Secondary_Claim_Types__c = c.Secondary_Claim_Types__c.left(c.Secondary_Claim_Types__c.length() - 2);
            casesToUpdate.add(c);
            }
            /* 2020-02-02 I have no idea what the purpose of this is - Skooter
             * Map<Id, List<Claim_Type__c>> caseToClaimTypes = new Map<Id, List<Claim_Type__c>>();
            for (Claim_Type__c claimTypeRecord : relatedClaimTypes.values()) {
                if (!caseToClaimTypes.containsKey(claimTypeRecord.Case__c)) {
                    caseToClaimTypes.put(claimTypeRecord.Case__c, new List<Claim_Type__c>());
                }
                caseToClaimTypes.get(claimTypeRecord.Case__c).add(claimTypeRecord);
            }
			*/

            /*or (Id caseId : caseToClaimTypes.keySet()) {
                Case caseRecord = new Case(Id = caseId);
                caseRecord.Secondary_Claim_Types__c = '';
                for (Claim_Type__c claimType : caseToClaimTypes.get(caseId)) {
                    caseRecord.Secondary_Claim_Types__c += claimType.Product_Type__c + ' - ' + claimType.Concern__c + ',';
                }
                caseRecord.Secondary_Claim_Types__c = caseRecord.Secondary_Claim_Types__c.removeEnd(',');
                casesToUpdate.add(caseRecord);
            }*/
        }
		// 2020-01-29 This isn't needed. An update with an empty list just does nothing
        // if (!casesToUpdate.isEmpty()) {
            update casesToUpdate;
        // }
        // }
    }
    
    // 2020-01-29 I have no idea what the original ticket for this 
    // but Prashanth says it's CLAIMSV2-379
    // which is imposssible to read

    //Populate the primary type field on the case record when the claim type record is changed/added    
    // George's original description ^^^^^^^^^^^^^^^^^^^^

    public static void setPrimaryTypeOnCaseRecords(final List<Claim_Type__c> allClaimTypes) {
		
        // check to prevent recurs
        if(checkRecursive.runOnce()) {

        // Build a set of all the IDs of related cases
        Set<Id> caseIds = new Set<Id>();
			// Changed the variable name from newClaimTypes to allClaimTypes because that's more accurate
			// This is an after update as well, so the claimtype isn't new
            for (Claim_Type__c claimTypeRecord : allClaimTypes) {
                if(claimTypeRecord.Is_Primary__c)
                {
                    caseIds.add(claimTypeRecord.Case__c);
                }
            }
        	System.Debug('Set Size: ' + caseIds.size());
        
		// Get all the related cases and create a map
		// This means each case will appear only once
		// 2020-01-29 I believe this query is not needed at all. We already have all of the claimsIDs
        // Map<Id, Case> casesByCaseId = new Map<Id, Case>([SELECT Id, Primary_Claim_Type__c, Primary_Claim_Concern__c 
        //                                                 FROM Case WHERE Id =:caseIds]);
			// System.Debug('Map Size: ' + casesByCaseId.size());
        
        // Create a list to add cases to so we can do an update
        List<Case> casesToUpdate = new List<Case>();
		Set<Id> casesToUpdateIds = new Set<Id>();
        
        for (Claim_Type__c ct : allClaimTypes) {
            // This will never be null (it throws an error if it's missing)
            // it's also based on a query that's not needed
            	// Case c = casesByCaseId.get(claimTypeRecord.Case__c);
            	// if(c != null)

            // We only up date the case if the Claim Type is:
           	// - Primary
           	// - We haven't already updated it (because duplicate IDs aren't allowed in lists)
			if(ct.Is_Primary__c == true && casesToUpdateIds.contains(ct.Case__c) == false) {
                Case c = new Case();
                	c.Id = ct.Case__c;
                	c.Primary_Claim_Type__c = ct.Product_Type__c;
                	c.Primary_Claim_Concern__c = ct.Concern__c;
                casesToUpdate.add(c);
                // Add it to the set so we know we've already done this one
                // This means the _first_ primary inserted will be the one
                // that sets the case
                casesToUpdateIds.add(ct.Case__c);
            }
        }
        
        // This isn't needed. It won't run if the list is zero
        // if(casesToUpdate.size() > 0)
        // {
        	update casesToUpdate;    
        // }
        }
    }

    private static Set<Id> caseIdsBeforeInsert(final List<Claim_Type__c> newClaimTypes) {

        Set<Id> caseIds = new Set<Id>();

        for (Claim_Type__c claimTypeRecord : newClaimTypes) {
            caseIds.add(claimTypeRecord.Case__c);
        }

        return caseIds;
    } // end caseIdsBeforeInsert method

    private static Set<Id> caseIdsBeforeUpdate(final List<Claim_Type__c> newClaimTypes, final Map<Id, Claim_Type__c> oldClaimTypesByIds) {

        Set<Id> caseIds = new Set<Id>();

        for (Claim_Type__c claimTypeRecord : newClaimTypes) {
            String oldProductType = oldClaimTypesByIds.get(claimTypeRecord.Id).Product_Type__c;
            String oldConcern = oldClaimTypesByIds.get(claimTypeRecord.Id).Concern__c;
			Boolean isPrimary = oldClaimTypesByIds.get(claimTypeRecord.Id).Is_Primary__c;
            if (claimTypeRecord.Product_Type__c != oldProductType || claimTypeRecord.Concern__c != oldConcern || claimTypeRecord.Is_Primary__c != isPrimary ) {
                caseIds.add(claimTypeRecord.Case__c);
            }
        }

        return caseIds;

    } // end caseIdsBeforeUpdate method
    
    }