ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>Used to track the high level stages of the Claim</description>
    <label>Claim Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting Docs</fullName>
            </value>
            <value>
                <fullName>In Kankakee</fullName>
            </value>
            <value>
                <fullName>In Lab</fullName>
            </value>
            <value>
                <fullName>File Preparation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Sub_Stage__c</fullName>
    <label>Claim Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Claim_Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting POP</fullName>
            </value>
            <value>
                <fullName>POP Received</fullName>
            </value>
            <value>
                <fullName>Additional POP Required</fullName>
            </value>
            <value>
                <fullName>Initial review</fullName>
            </value>
            <value>
                <fullName>HOIS sent</fullName>
            </value>
            <value>
                <fullName>Awaiting HOIS</fullName>
            </value>
            <value>
                <fullName>Awaiting Samples</fullName>
            </value>
            <value>
                <fullName>Samples Received</fullName>
            </value>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Data Entry</fullName>
            </value>
            <value>
                <fullName>Info Required</fullName>
            </value>
            <value>
                <fullName>Info Requested</fullName>
            </value>
            <value>
                <fullName>Goodwill review</fullName>
            </value>
            <value>
                <fullName>In review</fullName>
            </value>
            <value>
                <fullName>Release Pending</fullName>
            </value>
            <value>
                <fullName>Waiting for Invoice</fullName>
            </value>
            <value>
                <fullName>Check/Credit Requested</fullName>
            </value>
            <value>
                <fullName>Check/Credit Approved</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Goodwill Requested</fullName>
            </value>
            <value>
                <fullName>Goodwill Rejected</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Samples Sent to Lab</fullName>
            </value>
            <value>
                <fullName>Dealer Invoice Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/ClaimApproved__c.field-meta.xml
<CustomField>
    <fullName>ClaimApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that Claims Manager has approved the entire claim. This semi-closes the claim in the sense that changes should be minimal but there are still things to process. This is different than the &quot;Goodwill Amount Approve&quot; or &quot;Address Validation.&quot; A claim can have its goodwill amount approved but NOT but fully approved yet.</description>
    <label>Claim Approved?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Installation_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Date__c</fullName>
    <description>Date of the product installation</description>
    <label>Installation Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Tape_Code__c.field-meta.xml
<CustomField>
    <fullName>Tape_Code__c</fullName>
    <description>Sales, Claims and Lab uses this to record the product Tape Code</description>
    <label>Tape Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/Claim_Type__c.object-meta.xml
<CustomObject>
    <description>Used to capture the Primary and Secondary reason for the Claim Case</description>
    <label>Claim Type</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Claim Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Related Claim Case</description>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Case must be a Residential or Commercial Claim</errorMessage>
        <filterItems>
            <field>Case.RecordType.Name</field>
            <operation>contains</operation>
            <value>Claim</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Claim Types</relationshipLabel>
    <relationshipName>Claim_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Concern__c.field-meta.xml
<CustomField>
    <fullName>Concern__c</fullName>
    <label>Concern</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Claim_Type_Reason</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this the Primary Claim Type?</description>
    <label>Is Primary?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>(none)</fullName>
            </value>
            <value>
                <fullName>A Organic</fullName>
            </value>
            <value>
                <fullName>B Glass</fullName>
            </value>
            <value>
                <fullName>C Lam/Org</fullName>
            </value>
            <value>
                <fullName>D Lam/Glass</fullName>
            </value>
            <value>
                <fullName>E Coated Rolls</fullName>
            </value>
            <value>
                <fullName>F Mod Bit</fullName>
            </value>
            <value>
                <fullName>G Felt</fullName>
            </value>
            <value>
                <fullName>H Asphalt</fullName>
            </value>
            <value>
                <fullName>I Fibrebrd</fullName>
            </value>
            <value>
                <fullName>J Total</fullName>
            </value>
            <value>
                <fullName>K Lock</fullName>
            </value>
            <value>
                <fullName>L ArmourGd</fullName>
            </value>
            <value>
                <fullName>M Protecbrd</fullName>
            </value>
            <value>
                <fullName>N Poly ISO</fullName>
            </value>
            <value>
                <fullName>P Roof-Fast</fullName>
            </value>
            <value>
                <fullName>Q Gold Shield</fullName>
            </value>
            <value>
                <fullName>R Adhs/Ctgs</fullName>
            </value>
            <value>
                <fullName>Z Not IKO</fullName>
            </value>
            <value>
                <fullName>Valley Cap</fullName>
            </value>
            <value>
                <fullName>Panels</fullName>
            </value>
            <value>
                <fullName>Hip &amp; Ridge</fullName>
            </value>
            <value>
                <fullName>Valley</fullName>
            </value>
            <value>
                <fullName>Touch up kit</fullName>
            </value>
            <value>
                <fullName>Screws</fullName>
            </value>
            <value>
                <fullName>Starter w drip</fullName>
            </value>
            <value>
                <fullName>Side</fullName>
            </value>
            <value>
                <fullName>Rake</fullName>
            </value>
            <value>
                <fullName>XD Channel</fullName>
            </value>
            <value>
                <fullName>Debris guard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/Lab_Sample__c.object-meta.xml
<CustomObject>
    <label>Lab Sample</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Samples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A link to the Claim this lab sample is related to. Lab Samples with no links to a Claim have been received but not properly connected to a cliam.</description>
    <inlineHelpText>The Claim this Lab Sample relates to.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Lab Samples</relationshipLabel>
    <relationshipName>Lab_Samples</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>https://ikoussfsc.atlassian.net/browse/CLAIMSV2-358
Claims Stage</description>
    <formula>TEXT(Case__r.Claim_Stage__c)</formula>
    <inlineHelpText>Claims Stage</inlineHelpText>
    <label>Claim Stage</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Claim_Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Sub_Stage__c</fullName>
    <description>https://ikoussfsc.atlassian.net/browse/CLAIMSV2-358
Claim Sub Stage</description>
    <formula>Text( Case__r.Claim_Sub_Stage__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Claim Sub Stage</inlineHelpText>
    <label>Claim Sub Stage</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/PRM__c.field-meta.xml
<CustomField>
    <fullName>PRM__c</fullName>
    <defaultValue>false</defaultValue>
    <description>https://ikoussfsc.atlassian.net/browse/CLAIMSV2-294
Indicates whether the Lab Sample should be reviewed by the Plant.</description>
    <inlineHelpText>Indicates whether the Lab Sample should be reviewed by the Plant.</inlineHelpText>
    <label>PRM</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample_Tape_Code__c/Lab_Sample_Tape_Code__c.object-meta.xml
<CustomObject>
    <description>This allows users to associate the tape codes with the lab samples</description>
    <label>Sample Description</label>
    <nameField>
        <displayFormat>LSTC - {000000000}</displayFormat>
        <label>Lab Sample Tape Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample_Tape_Code__c/fields/Lab_Sample__c.field-meta.xml
<CustomField>
    <fullName>Lab_Sample__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the lab sample the record is related to</description>
    <label>Lab Sample</label>
    <referenceTo>Lab_Sample__c</referenceTo>
    <relationshipName>Lab_Sample_Tape_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample_Tape_Code__c/fields/Manufacture_Date__c.field-meta.xml
<CustomField>
    <fullName>Manufacture_Date__c</fullName>
    <formula>TEXT( Tape_Code__r.Manufacture_Date__c)</formula>
    <label>Manufacture Date</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample_Tape_Code__c/fields/Tape_Code__c.field-meta.xml
<CustomField>
    <fullName>Tape_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the tape code that is associated with the lab sample</description>
    <label>Tape Code</label>
    <referenceTo>Tape_Code__c</referenceTo>
    <relationshipName>Lab_Sample_Tape_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/LabSampleTapeCodeServiceTest.cls
@isTest
private class LabSampleTapeCodeServiceTest {

    @testSetup static void setupTestData() {
        initTestData();
    }

    private static void initTestData(){
        Id baRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Building Location').getRecordTypeId();
        Id ccRt = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Claim').getRecordTypeId();
        List<Account> toInsertAccounts = new List<Account>();

        toInsertAccounts.addAll(TestFactory.createAccounts(baRt,'CaseServiceTest','9 King St E','Toronto','ON','CA','M4S 2H4',
                'Verified',UserInfo.getUserId(),TRUE,TRUE,1,false));
        insert toInsertAccounts;
        
        //create contact
        List<Contact> con = TestFactory.createContacts(toInsertAccounts[0].Id,'LabSampleTapeCodeServiceTest',UserInfo.getUserId(),1,false);
        insert con;
        
        //create Cases
        List<Case> toInsertCases = new List<Case>();

        toInsertCases.addAll(TestFactory.createCases(ccRt,toInsertAccounts[0].Id,con[0].Id,'Owner','LabSampleTapeCodeServiceTest',null,'Commercial',null,1,false));
        toInsertCases.addAll(TestFactory.createCases(ccRt,toInsertAccounts[0].Id,con[0].Id,'Distributor',null,null,'Commercial',null,5,false));
        toInsertCases[1].Subject='CaseServiceTestClosed';
        toInsertCases[1].Claim_Stage__c='Closed';
        
        toInsertCases[2].ClaimApproved__c=true;
        toInsertCases[2].Subject='CaseServiceTest1';
        
        toInsertCases[3].Subject='CaseServiceTest2';
        
        toInsertCases[4].Subject='CaseServiceTest3';
        
        toInsertCases[5].Subject='CaseServiceTest4';
        Insert toInsertCases;
        
        System.debug('toInsertCases: '+toInsertCases);
        //create ClaimTypes
        List<Claim_Type__c> toInsertClaimTypes = new List<Claim_Type__c>();
        toInsertClaimTypes.addAll(TestFactory.createClaimTypes(toInsertCases[0], 1, false));
        
                
        toInsertClaimTypes[0].Product_Type__c='Z Not IKO';
        toInsertClaimTypes[0].Concern__c='Clawing';
        toInsertClaimTypes[0].Is_Primary__c=true;
        Insert toInsertClaimTypes;
        
        List<Lab_Sample__c> toInsertLabSamples = new List<Lab_Sample__c>();
        toInsertLabSamples.addAll(TestFactory.createLabSamples(toInsertCases[1], 5, false));
        toInsertLabSamples[1].Case__c=toInsertCases[2].Id;
        toInsertLabSamples[2].Case__c=toInsertCases[3].Id;
        toInsertLabSamples[3].Case__c=toInsertCases[4].Id;
        toInsertLabSamples[4].Case__c=toInsertCases[5].Id;
        Insert toInsertLabSamples;
        
		insertLabSampleCodes();         
    }
    
    @future
    static void insertLabSampleCodes(){
        List<Lab_Sample__c> lstc = [select Id from Lab_Sample__c where Case__r.Subject in ('CaseServiceTest2', 'CaseServiceTest3', 'CaseServiceTest4')];
        List<Lab_Sample_Tape_Code__c> toInsertLabSamplesTapeCode = new List<Lab_Sample_Tape_Code__c>();
        toInsertLabSamplesTapeCode.addAll(TestFactory.createLabSampleTapCodes(lstc[0], 1, false));
        toInsertLabSamplesTapeCode.addAll(TestFactory.createLabSampleTapCodes(lstc[1], 1, false));
        toInsertLabSamplesTapeCode.addAll(TestFactory.createLabSampleTapCodes(lstc[2], 1, false));
        Insert toInsertLabSamplesTapeCode;
    }
    @isTest static void testThatLabSampleTapeCodeCannotBeInsertedPostClosure() {
        Lab_Sample__c ls = [select Id from Lab_Sample__c where Case__r.Subject = 'CaseServiceTestClosed' LIMIT 1];

        Test.startTest();
        Lab_Sample_Tape_Code__c lstc = new Lab_Sample_Tape_Code__c(Lab_Sample__c = ls.Id);
        try {
            insert lstc;
        } catch (DmlException e) {
            System.debug('Caught DML exception');
        }
        System.assertEquals(lstc.Id, null);
        Test.stopTest();
    }

    @isTest static void testThatLabSampleTapeCodeCannotBeUpdatedPostClosure() {
        Case caseToUpdate = [Select Id, Claim_Stage__c from Case Where Subject = 'CaseServiceTest2'];
        Lab_Sample_Tape_Code__c lstc = [select Id from Lab_Sample_Tape_Code__c where Lab_Sample__r.Case__r.Subject = 'CaseServiceTest2'];
        
        caseToUpdate.Claim_Stage__c='Closed';
        Update caseToUpdate;
        
        Boolean errorCaught = false;
		
        
        Test.startTest();
        try {
            update lstc;
        } catch (DmlException e) {
            errorCaught = true;
        }
        System.assert(errorCaught);
        Test.stopTest();

        
    }

    @isTest static void testThatLabSampleTapeCodeCannotBeDeletedPostClosure() {
        Case caseToUpdate = [Select Id, Claim_Stage__c from Case Where Subject = 'CaseServiceTest3'];
        Lab_Sample_Tape_Code__c lstc = [select Id from Lab_Sample_Tape_Code__c where Lab_Sample__r.Case__c = :caseToUpdate.Id];
        
        caseToUpdate.Claim_Stage__c='Closed';
        Update caseToUpdate;
        
        System.debug('caseToUpdate: '+caseToUpdate);
        
        Boolean errorCaught = false;

        Test.startTest();
        try {
            delete lstc;
        } catch (DmlException e) {
            errorCaught = true;
        }
        System.assert(errorCaught);
        Test.stopTest();

        
    }

    @isTest static void testThatLabSampleTapeCodeCanBeInsertedUpdatedDeletedPreClosure() {
        Case c = [select Id, Claim_Stage__c, Claim_Sub_Stage__c, ClaimApproved__c from Case where Subject = 'CaseServiceTest4'];
		        
        Test.startTest();
        Lab_Sample__c ls = new Lab_Sample__c(Case__c = c.Id);
        insert ls;
        Lab_Sample_Tape_Code__c lstc = new Lab_Sample_Tape_Code__c(Lab_Sample__c = ls.Id);
        insert lstc;
        System.assertNotEquals(lstc.Id, null);
        update lstc;
        delete lstc;
        Test.stopTest();
        
    }

    private static testMethod void populateLabSamplePRMField_CreateNewTapeCodeWithManufactureDateOneYearFromCaseCreateDate_LabSamplePRMIsChecked() {

        // Prepare the data
        Case caseRecord = [SELECT Id, Installation_Date__c,ClaimApproved__c, CreatedDate FROM Case WHERE Subject = 'CaseServiceTest1'];
        if (caseRecord.ClaimApproved__c){
            caseRecord.ClaimApproved__c=false;
        	update caseRecord;
        }
        
        
        Lab_Sample__c labSampleRecord = [SELECT Id ,PRM__c FROM Lab_Sample__c WHERE Case__c = :caseRecord.Id];

        // Test the data
        Test.startTest();
        Tape_Code__c tapeCodeRecord = new Tape_Code__c(
                Name = 'Manufacture Date within one year of Case Created Date',
                Manufacture_Date__c = Date.newInstance(caseRecord.CreatedDate.year(), caseRecord.CreatedDate.month() - 5, caseRecord.CreatedDate.day()));
        insert tapeCodeRecord;

        Lab_Sample_Tape_Code__c labSampleTapeCodeRecord = new Lab_Sample_Tape_Code__c(Lab_Sample__c = labSampleRecord.Id, Tape_Code__c = tapeCodeRecord.Id);
        insert labSampleTapeCodeRecord;
        
        labSampleRecord = [SELECT Id, PRM__c FROM Lab_Sample__c WHERE Id = :labSampleRecord.Id];
        System.assertEquals(true, labSampleRecord.PRM__c, 'Expected Lab Sample PRM field is checked as the Manufacture Date is within one year of the Case Created Date.');

        Test.stopTest();

        // Assert the data
        
    }

    private static testMethod void populateLabSamplePRMField_CreateNewTapeCodeWithManufactureDateTwoYearFromCaseCreateDate_LabSamplePRMIsUnchecked() {

        // Prepare the data
        Case caseRecord = [SELECT Id, Installation_Date__c,ClaimApproved__c, CreatedDate FROM Case WHERE Subject = 'CaseServiceTest1'];
        Lab_Sample__c labSampleRecord = [SELECT Id ,PRM__c FROM Lab_Sample__c WHERE Case__c = :caseRecord.Id];
		
        if (caseRecord.ClaimApproved__c){
            caseRecord.ClaimApproved__c=false;
        	update caseRecord;
        }
        // Test the data
        Test.startTest();
        Tape_Code__c tapeCodeRecord = new Tape_Code__c(
                Name = 'Manufacture Date within two years of Case Created Date',
                Manufacture_Date__c = Date.newInstance(caseRecord.CreatedDate.year() - 2, caseRecord.CreatedDate.month(), caseRecord.CreatedDate.day()));
        insert tapeCodeRecord;

        Lab_Sample_Tape_Code__c labSampleTapeCodeRecord = new Lab_Sample_Tape_Code__c(Lab_Sample__c = labSampleRecord.Id, Tape_Code__c = tapeCodeRecord.Id);
        insert labSampleTapeCodeRecord;
        Test.stopTest();

        // Assert the data
        labSampleRecord = [SELECT Id, PRM__c FROM Lab_Sample__c WHERE Id = :labSampleRecord.Id];
        System.assertEquals(false, labSampleRecord.PRM__c, 'Expected Lab Sample PRM field is unchecked as the Manufacture Date is within two year of the Case Created Date.');

    }

    private static testMethod  void populateLabSampleRecentManufactureDate_CreateNewTapeCodesWithDifferentManufatureDates_PopulateRecentManufactureDateWithRecentDate() {

        // Prepare the data
        Case caseRecord = [SELECT Id, Installation_Date__c,ClaimApproved__c, CreatedDate FROM Case WHERE Subject = 'CaseServiceTest1'];
        Lab_Sample__c labSampleRecord = [SELECT Id ,PRM__c FROM Lab_Sample__c WHERE Case__c = :caseRecord.Id];
		if (caseRecord.ClaimApproved__c){
            caseRecord.ClaimApproved__c=false;
        	update caseRecord;
        }
        // Test the data
        Test.startTest();
        Tape_Code__c tapeCodeRecord1 = new Tape_Code__c(
                Name = 'Manufacture Date within two years of Case Created Date',
                Manufacture_Date__c = Date.newInstance(caseRecord.CreatedDate.year() - 2, caseRecord.CreatedDate.month(), caseRecord.CreatedDate.day()));

        Tape_Code__c tapeCodeRecord2 = new Tape_Code__c(
                Name = 'Manufacture Date within two years of Case Created Date',
                Manufacture_Date__c = Date.newInstance(caseRecord.CreatedDate.year() - 1, caseRecord.CreatedDate.month(), caseRecord.CreatedDate.day()));

        insert new List<Tape_Code__c> { tapeCodeRecord1, tapeCodeRecord2 };

        Lab_Sample_Tape_Code__c labSampleTapeCodeRecord1 = new Lab_Sample_Tape_Code__c(Lab_Sample__c = labSampleRecord.Id, Tape_Code__c = tapeCodeRecord1.Id);
        Lab_Sample_Tape_Code__c labSampleTapeCodeRecord2 = new Lab_Sample_Tape_Code__c(Lab_Sample__c = labSampleRecord.Id, Tape_Code__c = tapeCodeRecord2.Id);
        System.debug('@@@ labSampleTapeCodeRecord1: ' + labSampleTapeCodeRecord1);
        System.debug('@@@ labSampleTapeCodeRecord2: ' + labSampleTapeCodeRecord2);

        insert new List<Lab_Sample_Tape_Code__c> { labSampleTapeCodeRecord1, labSampleTapeCodeRecord2 };
        Test.stopTest();

        // Assert the data
        labSampleRecord  = [SELECT Id, Recent_Manufacture_Date__c FROM Lab_Sample__c WHERE Id = :labSampleRecord.Id];
        System.debug('@@@ labSampleRecord: ' +  labSampleRecord);
        System.assert(labSampleRecord.Recent_Manufacture_Date__c != NULL, 'Expected Recent Manufacture date is recent manufacture date of the Lab Sample Tape Code record');

    }

}