ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Distributor for a Residential or Commercial Claim</description>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Residential Account, Distributor, US Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Legacy_Claim_Account__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Distributor Cases</relationshipLabel>
    <relationshipName>DistributorCases</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Distributor_Shared_With__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Shared_With__c</fullName>
    <defaultValue>&quot; &quot;</defaultValue>
    <description>Capture the name of the Role/ Group that the Parent Distributor to the Case is shared with.
It will be a comma separated text field that that will be used in the Case Sharing Rule to show/ hide the Cases that are In Litigation.
The Case Criteria based sharing rules will use this text in combination with the CONTAINS operator to match the Account Shared with Role/Group name with the Case Shared with Role/Group</description>
    <inlineHelpText>Capture the name of the Role/ Group that the Parent Distributor to the Case is shared with.</inlineHelpText>
    <label>Distributor Shared With</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/BatchCaseSharingFieldUpdates.cls
global with sharing class BatchCaseSharingFieldUpdates implements Database.Batchable<sObject>, Database.Stateful {

    global Set<Id> distributorIds{get;set;}
    global Map<Id, Set<Id>> userOrGroupIdsByAccountIds{get;set;}
    global Set<CaseSharingRulesUtility.AccountIdToUserOrGroupIdsWrapper> wrappers{get;set;}
    global Set<CaseSharingRulesUtility.AccountIdToGroupNameWrapper> groupWrappers{get;set;}

    global BatchCaseSharingFieldUpdates(Set<Id> distIds, Map<Id, Set<Id>> userOrGrpIdsByAcctIds, Set<CaseSharingRulesUtility.AccountIdToUserOrGroupIdsWrapper> wrp, Set<CaseSharingRulesUtility.AccountIdToGroupNameWrapper> grpWrappers) {
            this.distributorIds = distIds;
            this.userOrGroupIdsByAccountIds = userOrGrpIdsByAcctIds;
            this.wrappers = wrp;
            this.groupWrappers = grpWrappers;
    }

    global Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator([SELECT Id, Distributor__c, Distributor_Shared_With__c FROM Case WHERE Distributor__c IN : distributorIds]);
    }

    global void execute(Database.BatchableContext context, List<Case> caseScope) {

        system.debug('====> BatchCaseSharingFieldUpdates');
        List<Case> allCases = new List<Case>();
        for(case eachCase : caseScope){

            for (CaseSharingRulesUtility.AccountIdToGroupNameWrapper wrapper : groupWrappers) {
                if (eachCase.Distributor__c == wrapper.accountId) {
                    eachCase.Distributor_Shared_With__c = '';
                    eachCase.Distributor_Shared_With__c = wrapper.roleOrGroupByGroupString;
                }
            }
            allCases.add(eachCase);
        }

        if (!allCases.isEmpty()) {
            Database.update(allCases, false);
        }
    }

    global void finish(Database.BatchableContext context) {
    }

}