ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Legacy_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Legacy_External_ID__c</fullName>
    <description>This is to identify and retain the WCMS system reference ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>Legacy Claim Number from WCMS</inlineHelpText>
    <label>Legacy Claim Number</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/SYS_UserRole__c.field-meta.xml
<CustomField>
    <fullName>SYS_UserRole__c</fullName>
    <description>Case Created By User Role</description>
    <inlineHelpText>Case Created By User Role</inlineHelpText>
    <label>SYS_UserRole</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/UpdateLegacyCaseRecords.cls
global class UpdateLegacyCaseRecords implements Database.Batchable<sObject>{

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT ID, Legacy_External_ID__c, SYS_UserRole__c, CreatedBy.UserRole.Name FROM Case ' + 
            'WHERE Legacy_External_ID__c != NULL'
        );
    }
    global void execute(Database.BatchableContext bc, List<Case> records){
        // process each batch of records

        for (Case caseRecord : records) {
            caseRecord.SYS_UserRole__c = caseRecord.CreatedBy.UserRole.Name;
        }
        update records;
        
    } 
    
    global void finish(Database.BatchableContext bc){
    	// VOID
    }    
}