ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Primary_Claim_Concern__c.field-meta.xml
<CustomField>
    <fullName>Primary_Claim_Concern__c</fullName>
    <description>Claim Concern from the Primary Claim Type</description>
    <label>Primary Claim Concern</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Primary_Claim_Type__c.field-meta.xml
<CustomField>
    <fullName>Primary_Claim_Type__c</fullName>
    <description>This is populated by a workflow rule from the Primary Claim Type</description>
    <label>Primary Claim Type</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Secondary_Claim_Types__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Claim_Types__c</fullName>
    <label>Secondary Claim Types</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/Claim_Type__c.object-meta.xml
<CustomObject>
    <description>Used to capture the Primary and Secondary reason for the Claim Case</description>
    <label>Claim Type</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Claim Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Related Claim Case</description>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Case must be a Residential or Commercial Claim</errorMessage>
        <filterItems>
            <field>Case.RecordType.Name</field>
            <operation>contains</operation>
            <value>Claim</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Claim Types</relationshipLabel>
    <relationshipName>Claim_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Concern__c.field-meta.xml
<CustomField>
    <fullName>Concern__c</fullName>
    <label>Concern</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Claim_Type_Reason</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this the Primary Claim Type?</description>
    <label>Is Primary?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>(none)</fullName>
            </value>
            <value>
                <fullName>A Organic</fullName>
            </value>
            <value>
                <fullName>B Glass</fullName>
            </value>
            <value>
                <fullName>C Lam/Org</fullName>
            </value>
            <value>
                <fullName>D Lam/Glass</fullName>
            </value>
            <value>
                <fullName>E Coated Rolls</fullName>
            </value>
            <value>
                <fullName>F Mod Bit</fullName>
            </value>
            <value>
                <fullName>G Felt</fullName>
            </value>
            <value>
                <fullName>H Asphalt</fullName>
            </value>
            <value>
                <fullName>I Fibrebrd</fullName>
            </value>
            <value>
                <fullName>J Total</fullName>
            </value>
            <value>
                <fullName>K Lock</fullName>
            </value>
            <value>
                <fullName>L ArmourGd</fullName>
            </value>
            <value>
                <fullName>M Protecbrd</fullName>
            </value>
            <value>
                <fullName>N Poly ISO</fullName>
            </value>
            <value>
                <fullName>P Roof-Fast</fullName>
            </value>
            <value>
                <fullName>Q Gold Shield</fullName>
            </value>
            <value>
                <fullName>R Adhs/Ctgs</fullName>
            </value>
            <value>
                <fullName>Z Not IKO</fullName>
            </value>
            <value>
                <fullName>Valley Cap</fullName>
            </value>
            <value>
                <fullName>Panels</fullName>
            </value>
            <value>
                <fullName>Hip &amp; Ridge</fullName>
            </value>
            <value>
                <fullName>Valley</fullName>
            </value>
            <value>
                <fullName>Touch up kit</fullName>
            </value>
            <value>
                <fullName>Screws</fullName>
            </value>
            <value>
                <fullName>Starter w drip</fullName>
            </value>
            <value>
                <fullName>Side</fullName>
            </value>
            <value>
                <fullName>Rake</fullName>
            </value>
            <value>
                <fullName>XD Channel</fullName>
            </value>
            <value>
                <fullName>Debris guard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Repository/Claims/force-app/main/default/classes/ClaimType_TriggerHandler.cls
public class ClaimType_TriggerHandler {
    // This is inappropriately named. It sets the Primary and the Secondary
    public static void setPrimaryAndSecondary(List<Claim_Type__c> newClaimTypes, Map<Id, Claim_Type__c> oldClaimTypesByIds) {
         // if(checkRecursive.runOnce()) {
        System.Debug('Setting Secondary Claim Types');
        
        List<Case> casesToUpdate = new List<Case>();

        Set<Id> caseIds = new Set<Id>();
        
		// 2020-02-04
		// add the new claim types to the list
        for(Claim_Type__c ct : newClaimTypes) {
            caseIds.add(ct.Case__c);
        }
		// Convert the trigger old map to a list and iterate through it
		// sets are unique, so we don't have to do any deduplication here
        if(oldClaimTypesByIds != null) {
            for(Claim_Type__c ct : oldClaimTypesByIds.values()) {
    	        caseIds.add(ct.Case__c);
	    	    }
        	}

        System.Debug('Getting all The Claim Types');
		// Gets a list of all the claim types related to all the cases
        list<Claim_Type__c> allRelatedClaimTypes = new list<Claim_Type__c>([SELECT Id, 
                                                                            Is_Primary__c, 
                                                                            Case__c, 
                                                                            Product_Type__c, 
                                                                            Concern__c
                                                                            FROM Claim_Type__c
                                                                            WHERE Case__c IN :caseIds
                                                                            ORDER BY Product_Type__c ASC]);

		System.Debug('Claim Types ' + allRelatedClaimTypes.size());

			// Loop through all our CaseIds. Start by clearing the current values in the fields
            for(Id caseId : caseIds) {
                Case c = new Case();
                	c.Id = caseId;
                	c.Primary_Claim_Concern__c = '';
                	c.Primary_Claim_Type__c = '';
                	c.Secondary_Claim_Types__c = '';

				// loop through claim types
				// using a nested loop to first get a claim ID then to loop throgh a claim type
				// don't love this but...alternatives? Maps are unique by ID, so...
                for(Claim_Type__c ct : allRelatedClaimTypes) {
                    if(ct.Case__c == c.Id) {
                        if(ct.Is_Primary__c == true) {
                            System.Debug('Primary');
                            c.Primary_Claim_Type__c = ct.Product_Type__c;
                            c.Primary_Claim_Concern__c = ct.Concern__c;
                        } else {
                            c.Secondary_Claim_Types__c += ct.Product_Type__c + ' - ' + ct.Concern__c + ', ';
                            System.Debug('Secondary');
                        }
                    }
					
            }
                // this just strips the final ', '
                c.Secondary_Claim_Types__c = c.Secondary_Claim_Types__c.left(c.Secondary_Claim_Types__c.length() - 2);

            casesToUpdate.add(c);
            }
        
            update casesToUpdate;
    }

}