ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/intelEmailCommercial__mdt/intelEmailCommercial__mdt.object-meta.xml
<CustomObject>
    <label>intelEmailCommercial</label>
    <pluralLabel>intelEmailResidentials</pluralLabel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/intelEmailRecordType__mdt/intelEmailRecordType__mdt.object-meta.xml
<CustomObject>
    <label>intelEmailRecordType</label>
    <pluralLabel>intelEmailRecordTypes</pluralLabel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/intelEmailRecordType__mdt/fields/RecordTypeId__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>RecordTypeId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/intelEmailResidential__mdt/intelEmailResidential__mdt.object-meta.xml
<CustomObject>
    <label>intelEmailResidential</label>
    <pluralLabel>intelEmailResidential</pluralLabel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report__c/Intelligence_Report__c.object-meta.xml
<CustomObject>
    <label>Intelligence Report</label>
    <nameField>
        <displayFormat>Intel-{000}</displayFormat>
        <label>Intelligence Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intelligence Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3-Tabs</fullName>
            </value>
            <value>
                <fullName>Hi and Ridge</fullName>
            </value>
            <value>
                <fullName>Ice &amp; Water</fullName>
            </value>
            <value>
                <fullName>Laminates</fullName>
            </value>
            <value>
                <fullName>Leading Edge</fullName>
            </value>
            <value>
                <fullName>Underlayment</fullName>
            </value>
            <value>
                <fullName>Adhesives/Primers</fullName>
            </value>
            <value>
                <fullName>AquaBarrier</fullName>
            </value>
            <value>
                <fullName>Asphalt</fullName>
            </value>
            <value>
                <fullName>Coverboards</fullName>
            </value>
            <value>
                <fullName>Felts</fullName>
            </value>
            <value>
                <fullName>ISO</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Mod Bit</fullName>
            </value>
            <value>
                <fullName>Vapour Retarders</fullName>
            </value>
            <value>
                <fullName>Category 1</fullName>
                <isActive>false</isActive>
                <label>Category 1</label>
            </value>
            <value>
                <fullName>Category 2</fullName>
                <isActive>false</isActive>
                <label>Category 2</label>
            </value>
            <value>
                <fullName>Category 3</fullName>
                <isActive>false</isActive>
                <label>Category 3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report__c/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <label>Colour</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report__c/fields/Producing_Plant__c.field-meta.xml
<CustomField>
    <fullName>Producing_Plant__c</fullName>
    <label>Producing Plant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Brampton</fullName>
            </value>
            <value>
                <fullName>Calgary</fullName>
            </value>
            <value>
                <fullName>Canroof</fullName>
            </value>
            <value>
                <fullName>CRC ISO</fullName>
            </value>
            <value>
                <fullName>Hawkesbury</fullName>
            </value>
            <value>
                <fullName>High River ISO</fullName>
            </value>
            <value>
                <fullName>Hillsboro</fullName>
            </value>
            <value>
                <fullName>IG East</fullName>
            </value>
            <value>
                <fullName>Kankakee</fullName>
            </value>
            <value>
                <fullName>Sumas</fullName>
            </value>
            <value>
                <fullName>Sylacauga</fullName>
            </value>
            <value>
                <fullName>Wilmington</fullName>
            </value>
            <value>
                <fullName>Plant 1</fullName>
                <isActive>false</isActive>
                <label>Plant 1</label>
            </value>
            <value>
                <fullName>Plant 2</fullName>
                <isActive>false</isActive>
                <label>Plant 2</label>
            </value>
            <value>
                <fullName>Plant 3</fullName>
                <isActive>false</isActive>
                <label>Plant 3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report__c/fields/Run_Tape_Code__c.field-meta.xml
<CustomField>
    <fullName>Run_Tape_Code__c</fullName>
    <label>Run #/Tape Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report_History__c/Intelligence_Report_History__c.object-meta.xml
<CustomObject>
    <description>Used to store the email that is sent out for audit reference</description>
    <label>Intelligence Report History</label>
    <nameField>
        <displayFormat>IntelAudit-{00000}</displayFormat>
        <label>Intelligence Report History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intelligence Report History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report_History__c/fields/Email_Body__c.field-meta.xml
<CustomField>
    <fullName>Email_Body__c</fullName>
    <description>Body of Email for Intelligence Report associated with this audit record.  Populated via Trigger when the Intel Report email is sent out</description>
    <label>Email Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report_History__c/fields/Email_Recipients__c.field-meta.xml
<CustomField>
    <fullName>Email_Recipients__c</fullName>
    <description>List of email recipients on Intelligence Report associated with this audit record.  Populated via Trigger when the Intel Report email is sent out</description>
    <label>Email Recipients</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report_History__c/fields/Email_Subject__c.field-meta.xml
<CustomField>
    <fullName>Email_Subject__c</fullName>
    <description>Subject from Email for Intelligence Report associated with this audit record.  Populated via Trigger when the Intel Report email is sent out</description>
    <label>Email Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report_History__c/fields/Intelligence_Report__c.field-meta.xml
<CustomField>
    <fullName>Intelligence_Report__c</fullName>
    <description>Intelligence Report associated with this audit record.  Populated via Trigger when the Intel Report email is sent out</description>
    <label>Intelligence Report</label>
    <referenceTo>Intelligence_Report__c</referenceTo>
    <relationshipLabel>Intelligence Report History</relationshipLabel>
    <relationshipName>Intelligence_Report_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report_Line_Item__c/Intelligence_Report_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Intelligence Report Line Item</label>
    <nameField>
        <displayFormat>IRLI-{000}</displayFormat>
        <label>Intelligence Report Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intelligence Report Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report_Line_Item__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report_Line_Item__c/fields/Intelligence_Report__c.field-meta.xml
<CustomField>
    <fullName>Intelligence_Report__c</fullName>
    <label>Intelligence Report</label>
    <referenceTo>Intelligence_Report__c</referenceTo>
    <relationshipLabel>Intelligence Report Line Items</relationshipLabel>
    <relationshipName>Intelligence_Report_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report_Line_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales Overview</fullName>
            </value>
            <value>
                <fullName>New Customer Activity</fullName>
            </value>
            <value>
                <fullName>Competitive Activity</fullName>
            </value>
            <value>
                <fullName>Design Community Activity</fullName>
            </value>
            <value>
                <fullName>Contractor Activity</fullName>
            </value>
            <value>
                <fullName>Competitive Market Activity</fullName>
            </value>
            <value>
                <fullName>Competitors Product Evaluation</fullName>
            </value>
            <value>
                <fullName>Target Account Info (Dealer/Roofer)</fullName>
            </value>
            <value>
                <fullName>Roofer Intel</fullName>
            </value>
            <value>
                <fullName>Dealer Intel</fullName>
            </value>
            <value>
                <fullName>IKO Product Intel</fullName>
            </value>
            <value>
                <fullName>Competitor Product Intel</fullName>
            </value>
            <value>
                <fullName>Recommendations</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Competitors Product Information</fullName>
                <isActive>false</isActive>
                <label>Competitors Product Information</label>
            </value>
            <value>
                <fullName>Product Quality Information</fullName>
                <isActive>false</isActive>
                <label>Product Quality Information</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Repository/Claims/force-app/main/default/classes/intelReportEmailController.cls
public class intelReportEmailController {
    Static public String emailVisualForce { get; set; }
    Static public void getEmailBodyPreview()
    {
        system.debug('Get userinfo');
        ID currentUserID = UserInfo.getUserId();
        system.debug('Get userinfo');
        String IntelUserName = UserInfo.getName();
        //get Manager's name in the roll hierarchy
        system.debug('Get manager');
        ID ManagerId = [Select ManagerId from User where ID =:currentUserID][0].ManagerId;
        String ManagerName;
        If(ManagerId != null)
        {
            ManagerName = [Select Name from User where ID =:ManagerId][0].Name;    
        }
        else
        {
            ManagerName = '--';
        }
        
        
        ID IntelRecordID = ApexPages.currentPage().getParameters().get('IRId');
        //get Record type ID 
        ID RecordTypeId = [Select RecordTypeId from Intelligence_Report__c where ID= :IntelRecordID].get(0).RecordTypeId; 
        //emailVisualForce=getEmailBody('hello', 'world', null, 'a01f0000006pVxDAAU', False, 'Full',null,null);
        intelEmailRecordType__mdt intelEmailRecordType = [Select label from intelEmailRecordType__mdt where RecordTypeId__c=:RecordTypeId][0];//'012f0000000FKLP'
        //compare against them
        //get the RecordTypename
        String recordTypeName = intelEmailRecordType.label;
        
        if(recordTypeName == 'Product Issues Report' )
        {
            system.debug('Its a product Issues report');
            emailVisualForce=getEmailBody(IntelUserName,
                                          ManagerName,
                                          null,
                                          IntelRecordID,
                                          False,
                                          'Product Issues',
                                          null,
                                          null);
        }else{
            emailVisualForce=getEmailBody(IntelUserName,
                                          ManagerName,
                                          null,
                                          IntelRecordID,
                                          False,
                                          'Full',
                                          null,
                                          null);    
        }
        
    }
    Static public String getEmailBody(String ReportFrom, String ReportTo, Id intelReportUser,Id intelligenceReport, Boolean send, String EmailType,List<String> addresses, String subject)
    {
        String emailBody ='';
        MAP<String,List<String>> mapEmailSections = new MAP<String,List<String>>();
        
        //add Report From and Report to 
        emailBody += '<p><strong><big>IKO Intelligence Reports</big></strong></p>';
        emailBody += '<p><strong>'+EmailType+' Intel Report</strong></p><br><br>';
        emailBody += '<p><strong>Submitted By: </strong>'+ReportFrom+'';
        emailBody += '<p><strong>Reports To: </strong>'+ReportTo+'</p><br><br>';
         
        
        // get all the Intelligence_Report_Line_Item__c of the Intelligence_Report__c ID to be considered for fetching the Attachments
        // Attachment of the Intelligence report is considered aswell
        List<ID> listIntelligenceReportsLineItemIDs = new List<ID>{intelligenceReport};
        //Can Fetch the list of sections in different Metadata Types in some custom meta data or ...
        //no filtering on EmailType 'Full'
        if(EmailType=='Full')
        {
            system.debug('Its a full email type');
            for (Intelligence_Report_Line_Item__c iRLI : [Select Id,Details__c,Type__c
                                                          From Intelligence_Report_Line_Item__c 
                                                          where Intelligence_Report__c=:intelligenceReport])
            {
                List<String> sections= new List<String>(mapEmailSections.get(iRLI.Type__c));
                sections.add(iRLI.Details__c);
                
                mapEmailSections.put(iRLI.Type__c,sections);
                listIntelligenceReportsLineItemIDs.add(iRLI.Id);
            }
        }else if(EmailType=='Residential Product')
        {
            system.debug('Its a Residential Product email type');
            
            List<String> AllowedTypes = new List<String>();
            For (intelEmailResidential__mdt iER : [ Select label from intelEmailResidential__mdt] )
            {
                AllowedTypes.add(iER.label);
            }
            system.debug(AllowedTypes);
            for (Intelligence_Report_Line_Item__c iRLI : [Select Id,Details__c,Type__c
                                                          From Intelligence_Report_Line_Item__c 
                                                          where Intelligence_Report__c=:intelligenceReport and Type__c IN :AllowedTypes])
            {
                List<String> sections= new List<String>(mapEmailSections.get(iRLI.Type__c));
                sections.add(iRLI.Details__c);
                mapEmailSections.put(iRLI.Type__c,sections);
                listIntelligenceReportsLineItemIDs.add(iRLI.Id);
            }
        }else if(EmailType=='Commercial Product')
        {
            system.debug('Its a Commercial Product email type');
            List<String> AllowedTypes = new List<String>();
            For (intelEmailCommercial__mdt iEC : [ Select label from intelEmailCommercial__mdt] )
            {
                system.debug(iEC);
                system.debug(iEC.label);
                AllowedTypes.add(iEC.label);
            }
            
            for (Intelligence_Report_Line_Item__c iRLI : [Select Id,Details__c,Type__c
                                                          From Intelligence_Report_Line_Item__c 
                                                          where Intelligence_Report__c=:intelligenceReport and Type__c IN :AllowedTypes])
            {
                List<String> sections= new List<String>(mapEmailSections.get(iRLI.Type__c));
                sections.add(iRLI.Details__c);
                mapEmailSections.put(iRLI.Type__c,sections);
                listIntelligenceReportsLineItemIDs.add(iRLI.Id);
            }
        }else if(EmailType=='Product Issues')
        {
            system.debug('Its a Product Issues email type');
            Intelligence_Report__c IR =[Select ID , Producing_Plant__c, Product__c ,Colour__c, Category__c, Description__c, Run_Tape_Code__c
                                        From Intelligence_Report__c
                                        Where ID = : intelligenceReport].get(0);
            mapEmailSections.put('Producing Plant',new List<String>{IR.Producing_Plant__c});
            mapEmailSections.put('Run number or Tape Code',new List<String>{IR.Run_Tape_Code__c});
            mapEmailSections.put('Product',new List<String>{IR.Product__c});                                 
            mapEmailSections.put('Colour ',new List<String>{IR.Colour__c});                                 
            mapEmailSections.put('Category',new List<String>{IR.Category__c});
            mapEmailSections.put('Description',new List<String>{IR.Description__c});              
        }
        system.debug('done with metadata');
        
        List<String> emailSections = new List<String>(mapEmailSections.keySet());
        if(emailSections.size()==0)
        {
            return null;
        }
        Boolean Attachments = False;
        List<ID> conVersions = new List<ID>();
        
        if (EmailType == 'Product Issues')
        {
            for( String section: emailSections)
            {
                emailBody += '<strong>'+section+':</strong>';
                
                for (String description : mapEmailSections.get(section))
                {
                    emailBody+=description+';';
                }
                emailBody +='<br>';
            }
        }else
        {
            for( String section: emailSections)
            {
                emailBody += '<p><strong>'+section+':</strong></p>';
                emailBody += '<ul>';
                for (String description : mapEmailSections.get(section))
                {
                    emailBody+='<li>'+description+'</li>';
                }
                emailBody +='</ul><br>';
                //use section name to get the content documents titles, ..
            }
        }
            
        //get IDs of Content Documents and versions
        List<ID> listContentDocumentIDs = new List<ID>();
        for (ContentDocumentLink cdl : [Select  Id, LinkedEntityId,ContentDocumentId from ContentDocumentLink where LinkedEntityId IN :listIntelligenceReportsLineItemIDs])
        {
            listContentDocumentIDs.add(cdl.ContentDocumentId);
        }
        
        Map <Id,ContentDocumentLink> mapContentDocumentLinks = new Map <Id,ContentDocumentLink>([Select  Id, LinkedEntityId,ContentDocumentId from ContentDocumentLink where LinkedEntityId IN :listIntelligenceReportsLineItemIDs]);
        
        
        for (ContentVersion cv: [select ID from ContentVersion where ContentDocumentId IN :listContentDocumentIDs])
        {
            conVersions.add(cv.Id);
        }
        
        system.debug('List of document IDs');
        system.debug(listContentDocumentIDs);
        
        //get size of the Content Documents
        List<ContentDocument> listContentDocuments= new List<ContentDocument>([Select Id, ContentSize, Title,FileType 
                                                                               From ContentDocument 
                                                                               WHERE Id in :listContentDocumentIDs]);
        //system.debug('List of Content Documents');
        //system.debug(listContentDocuments);
        //get total size of the documents
        Decimal totalAttachmentSizeMB= 0;
        for (ContentDocument cd : listContentDocuments)
        {
            totalAttachmentSizeMB += (Integer)cd.get('ContentSize')/math.pow(10,6); 
        }
        
        //if larger than 3MB append get links of each of the objects and store them and append them into the string 
        // should make this a config variable
         //Below conditions were changed by VL dd. 14 Nov 2018: Change from "3" to "100", so attachments would never be transformed into Salesforce links, but (default behaviour) into content delivery links
          //Content Delivery can be accessed also by non-Salesforce users. They receive a link that - when clicked on - lets them view attachments and download them without having to login to Salesforce. 
        
        if(totalAttachmentSizeMB > 0)
        {
            if (totalAttachmentSizeMB < 100)
            {
                //this message should be a lable to be translated
                Attachments= True;
                emailBody += '<p>Please check the attachments<p><br><ul>';
                for (ContentDocument contentdoc: listContentDocuments)
                {   
                    emailBody += '<li><strong>Attachment:</strong>'+ contentdoc.Title+'.'+contentdoc.FileType.toLowerCase()+'</li>';
                }
                emailBody += '</ul>';
            }
            else
            {
                emailBody += '<p>Attachments are Larger than 3MB <p><br><ul>';
                for (ContentDocument contentdoc: listContentDocuments)
                {   
                    emailBody += '<li><strong>Attachment:</strong><a href="'+ URL.getSalesforceBaseUrl().toExternalForm() +'/' + contentdoc.Id+'">'+contentdoc.Id+'</a></li>';
                }
                emailBody += '</ul>';
            }
        }
        
        //If In preview mode
        if(send == False)
        {
            return emailBody;
        }
        else
        {
            system.debug('creating email class');
            Messaging.SingleEmailMessage [] emails = new Messaging.SingleEmailMessage[]{};
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setSubject(subject);
            if(addresses.size()==0)
            {
                throw new intelReportEmailException('There are no recipients for "'+ subject +'" email');
            }
            email.setToAddresses(addresses );
            If (Attachments)
            {
                email.setEntityAttachments(conVersions);
            }
            email.setHtmlBody(emailBody);
            emails.add(email);
            if(Test.isRunningTest()){
                system.debug('@test: returning email body');
                return (emailBody);
            }
            Messaging.SendEmailResult[] emailresults = Messaging.sendEmail(emails);
            if (emailresults[0].success) {
                //Create an Intelligence_Report_History__c 
                {
                    insert new Intelligence_Report_History__c(Email_Recipients__c=string.join(addresses,','),Email_Subject__c = subject, Email_Body__c = emailBody, Intelligence_Report__c = intelligenceReport);
                }
                return('The email was sent successfully.');
            } else {
                return ('The email failed to send: '
                      + emailresults[0].errors[0].message);
            }            
        }
    }
    
}