ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/SendCertificate__e/SendCertificate__e.object-meta.xml
<CustomObject>
    <description>Event using to generate VF PDF and send email with certification</description>
    <label>Send Certificate</label>
    <pluralLabel>Send Certificates</pluralLabel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/SendCertificate__e/fields/AchievementAssignmentId__c.field-meta.xml
<CustomField>
    <fullName>AchievementAssignmentId__c</fullName>
    <label>Achievement Assignment Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/SendCertificate__e/fields/AchievementId__c.field-meta.xml
<CustomField>
    <fullName>AchievementId__c</fullName>
    <label>Achievement Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/SendCertificateEventTriggerHandler.cls
public class SendCertificateEventTriggerHandler extends TriggerHandlerFramework  {
    
    protected override void afterInsert() {
        List<SendCertificate__e> sendCertificateEvents = (List<SendCertificate__e>) Trigger.new;

        for (SendCertificate__e sendCertificate : sendCertificateEvents) {
            IKOCertificateCompletionEmail.sendCertificateByEmail(sendCertificate.AchievementId__c, sendCertificate.AchievementAssignmentId__c);
        }
    }
}