ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/EU_Open_Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>OI-{YYYY}-{0000000}</displayFormat>
        <label>Open Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Account__c.field-meta.xml
<CustomField>
    <fullName>EU_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Open_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Open_Invoice__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Invoice__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Invoice Paid</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/EU_Open_Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>OIL-{YYYY}-{0000000}</displayFormat>
        <label>Open Invoice Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Account__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Open_Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Open_Invoice__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Invoice__c</fullName>
    <label>Open Invoice</label>
    <referenceTo>EU_Open_Invoice__c</referenceTo>
    <relationshipName>Open_Invoice_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Open_Invoice_Line__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Invoice_Line__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Invoice Line Paid</label>
    <type>Checkbox</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/InvoiceLineService.cls
/**
 * Created by Gerard van Kempen on 2019-12-06.
 * 2019 (C) 4C NV, Mechelen Belgium.
 * Last modified as part of project 'IKO SFDC'.
 */

/**
* @author Gerard van Kempen, 4C NV
* @date 2019
*
* @group Integration Services
*
* @description InvoiceLineService provides methods to link Invoices and Invoice Lines.
*/

public class InvoiceLineService {

    /*******************************************************************************************************************
    * @description Link Open Invoice Lines to the appropriate Open Invoices with normal matching rules.
    * @param invoices a List of EU_Open_Invoice__c objects to be referenced
    * @param invoiceLines a List of EU_Open_Invoice_Line__c objects to be linked
    * @return a Boolean indicating whether or not all Invoice Lines have been linked correctly (true), or not (false)
    * @example
    * Boolean invoiceLinesLinkedOK = (new InvoiceLineService()).relateInvoicesToInvoiceLines(invoices, invoiceLines);
    */

    public Boolean relateInvoicesToInvoiceLines(List<EU_Open_Invoice__c> invoices, List<EU_Open_Invoice_Line__c> invoiceLines) {
        Integer matches = 0;
        // TODO: optimize algorithm
        for(EU_Open_Invoice__c invoice : invoices) {
            for(EU_Open_Invoice_Line__c invoiceLine : invoiceLines) {
                if(
                    invoice.EU_Invoice_Number__c == invoiceLine.EU_Header_Invoice_Number__c
                    && invoice.EU_Account__c == invoiceLine.EU_Header_Account__c
                ) {
                    invoiceLine.EU_Open_Invoice__c = invoice.Id;
                    matches++;
                }
            }
        }

        final Boolean allInvoiceLinesHandled = (matches == invoiceLines.size());
        if(!allInvoiceLinesHandled) {
            System.debug(LoggingLevel.ERROR, 'could not link all invoice lines to an invoice, or an invoice line has been multi-assigned');
        }

        return allInvoiceLinesHandled;
    }
}