ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/EU_Open_Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>OI-{YYYY}-{0000000}</displayFormat>
        <label>Open Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Open_Invoice__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Invoice__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Invoice Paid</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/EU_Open_Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>OIL-{YYYY}-{0000000}</displayFormat>
        <label>Open Invoice Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Open_Invoice__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Invoice__c</fullName>
    <label>Open Invoice</label>
    <referenceTo>EU_Open_Invoice__c</referenceTo>
    <relationshipName>Open_Invoice_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Open_Invoice_Line__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Invoice_Line__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Invoice Line Paid</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/InvoiceLineTriggerHandler.cls
/**
 * Created by Gerard van Kempen on 2019-12-06.
 * 2019 (C) 4C NV, Mechelen Belgium.
 * Last modified as part of project 'IKO SFDC'.
 */

public with sharing class InvoiceLineTriggerHandler extends TriggerHandler {

    protected override void onBeforeInsert(List<SObject> newList) {
        List<EU_Open_Invoice_Line__c> newInvoiceLines = (List<EU_Open_Invoice_Line__c>)newList;

        InvoiceLineTriggerHandlerFunctions.mapInvoiceLinesToInvoices(newInvoiceLines);
    }

    protected override void onBeforeUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
        Map<Id, EU_Open_Invoice_Line__c> newInvoiceLines = (Map<Id, EU_Open_Invoice_Line__c>)newMap;
        Map<Id, EU_Open_Invoice_Line__c> oldInvoiceLines = (Map<Id, EU_Open_Invoice_Line__c>)oldMap;

        List<EU_Open_Invoice_Line__c> invoiceLinesToBeMatched = InvoiceLineTriggerHandlerFunctions.filterInvoiceLinesToMap(newInvoiceLines, oldInvoiceLines);

        InvoiceLineTriggerHandlerFunctions.mapInvoiceLinesToInvoices(invoiceLinesToBeMatched);
    }

    protected override void onAfterUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
        Map<Id, EU_Open_Invoice_Line__c> newInvoiceLineMap = (Map<Id, EU_Open_Invoice_Line__c>)newMap;
        Map<Id, EU_Open_Invoice_Line__c> oldInvoiceLineMap = (Map<Id, EU_Open_Invoice_Line__c>)oldMap;

        List<EU_Open_Invoice__c> invoicesToClose = InvoiceLineTriggerHandlerFunctions.updateInvoiceRecord(newInvoiceLineMap);

        // update the queued orders if there are any
        if(invoicesToClose.size() > 0) {
            update invoicesToClose;
        }
    }

}