ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/EU_Open_Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>OI-{YYYY}-{0000000}</displayFormat>
        <label>Open Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Account__c.field-meta.xml
<CustomField>
    <fullName>EU_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Open_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Inv_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>EU_Inv_Due_Date__c</fullName>
    <label>Inv Due Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>EU_Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>EU_Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_JDE_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>EU_JDE_Customer_No__c</fullName>
    <label>JDE Customer No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Mapics_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>EU_Mapics_Customer_No__c</fullName>
    <label>Mapics Customer No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Open_Invoice__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Invoice__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Invoice Paid</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Purchase_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Purchase_Order_Number__c</fullName>
    <label>Purchase Order Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Terms_code__c.field-meta.xml
<CustomField>
    <fullName>EU_Terms_code__c</fullName>
    <label>Terms code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Terms_Description__c.field-meta.xml
<CustomField>
    <fullName>EU_Terms_Description__c</fullName>
    <label>Terms Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Total_Invoice_Value__c.field-meta.xml
<CustomField>
    <fullName>EU_Total_Invoice_Value__c</fullName>
    <label>Total Invoice Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/InvoiceSelector.cls
/**
 * Created by Gerard van Kempen on 2019-12-06.
 * 2019 (C) 4C NV, Mechelen Belgium.
 * Last modified as part of project 'IKO SFDC'.
 */

/**
* @author Gerard van Kempen, 4C NV
* @date 2019
*
* @group Integration Services
*
* @description InvoiceSelector provides methods to retrieve EU_Open_Invoice__c objects based on parameters.
*/

public class InvoiceSelector {

    /*******************************************************************************************************************
    * @description Retrieve Open Invoices for given Invoice Numbers.
    * @param invoiceNumbers a Set of Strings containing Invoice Numbers
    * @return a List of Open Invoices with matching Invoice Numbers
    * @example
    * List<EU_Open_Invoice__c> matchingInvoices = (new InvoiceSelector()).getInvoicesForInvoiceNumbers(invoiceNumbers);
    */

    public List<EU_Open_Invoice__c> getInvoicesForInvoiceNumbers(Set<String> invoiceNumbers, Set<Id> accountIds) {
        List<EU_Open_Invoice__c> invoicesForInvoiceNumbers = null;
        try {
            invoicesForInvoiceNumbers = [
                    SELECT EU_Account__c, EU_Amount_Due_Value__c, CreatedById, CurrencyIsoCode,
                            EU_Inv_Due_Date__c, EU_Invoice_Date__c, EU_Invoice_Number__c, EU_Invoice_Type__c,
                            EU_JDE_Customer_No__c, LastModifiedById, EU_Mapics_Customer_No__c, EU_Open_Invoice__c,
                            Name, EU_Order_number_Reference__c, EU_Purchase_Order_Number__c, EU_Terms_code__c,
                            EU_Terms_Description__c, EU_Total_Invoice_Value__c
                    FROM EU_Open_Invoice__c
                    WHERE EU_Invoice_Number__c IN :invoiceNumbers AND EU_Account__c IN :accountIds
            ];
        } catch (Exception e) {
            System.debug(LoggingLevel.WARN, e.getMessage());
            invoicesForInvoiceNumbers = new List<EU_Open_Invoice__c>();
        }

        if(invoiceNumbers.isEmpty()) {System.debug(LoggingLevel.WARN, 'could not find any invoices');}

        return invoicesForInvoiceNumbers;
    }

}