ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/EU_Open_Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>OI-{YYYY}-{0000000}</displayFormat>
        <label>Open Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Account__c.field-meta.xml
<CustomField>
    <fullName>EU_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Open_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Inv_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>EU_Inv_Due_Date__c</fullName>
    <label>Inv Due Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>EU_Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>EU_Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_JDE_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>EU_JDE_Customer_No__c</fullName>
    <label>JDE Customer No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Mapics_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>EU_Mapics_Customer_No__c</fullName>
    <label>Mapics Customer No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Open_Invoice__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Invoice__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Invoice Paid</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Purchase_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Purchase_Order_Number__c</fullName>
    <label>Purchase Order Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Terms_code__c.field-meta.xml
<CustomField>
    <fullName>EU_Terms_code__c</fullName>
    <label>Terms code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Terms_Description__c.field-meta.xml
<CustomField>
    <fullName>EU_Terms_Description__c</fullName>
    <label>Terms Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Total_Invoice_Value__c.field-meta.xml
<CustomField>
    <fullName>EU_Total_Invoice_Value__c</fullName>
    <label>Total Invoice Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/EU_Open_Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>OIL-{YYYY}-{0000000}</displayFormat>
        <label>Open Invoice Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Account__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Open_Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Inv_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Inv_Due_Date__c</fullName>
    <label>Invoice Due Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_JDE_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_JDE_Customer_No__c</fullName>
    <label>JDE Customer No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Mapics_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Mapics_Customer_No__c</fullName>
    <label>Mapics Customer No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Open_Invoice__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Open_Invoice__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Invoice Paid</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Order_number_Reference__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Order_number_Reference__c</fullName>
    <label>Order number Reference</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Purchase_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Purchase_Order_Number__c</fullName>
    <label>Purchase Order Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Terms_code__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Terms_code__c</fullName>
    <label>Terms code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Terms_Description__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Terms_Description__c</fullName>
    <label>Terms Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Total_Invoice_Value__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Total_Invoice_Value__c</fullName>
    <label>Total Invoice Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Open_Invoice__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Invoice__c</fullName>
    <label>Open Invoice</label>
    <referenceTo>EU_Open_Invoice__c</referenceTo>
    <relationshipName>Open_Invoice_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Open_Invoice_Line__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Invoice_Line__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Invoice Line Paid</label>
    <type>Checkbox</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/InvoiceService.cls
/**
 * Created by Gerard van Kempen on 2019-12-06.
 * 2019 (C) 4C NV, Mechelen Belgium.
 * Last modified as part of project 'IKO SFDC'.
 */

/**
* @author Gerard van Kempen, 4C NV
* @date 2019
*
* @group Integration Services
*
* @description InvoiceService provides two methods which can be used to create new EU_Open_Invoice__c objects
* based on data from existing EU_Open_Invoice_Line__c objects.
*/

public class InvoiceService {

    /*******************************************************************************************************************
    * @description Generate Open Invoices for Open Invoice Lines. Prevents duplicate Open Invoices from being generated
    * for similar Open Invoice Lines.
    * @param invoiceLines a List of Open Invoice Lines for which to generate Open Invoices
    * @return a List of Open Invoices
    * @example
    * List<EU_Open_Invoice__c> newInvoices = (new InvoiceService()).createNewInvoicesForInvoiceLines(invoiceLines);
    */

    public List<EU_Open_Invoice__c> createNewInvoicesForInvoiceLines(List<EU_Open_Invoice_Line__c> invoiceLines) {
        Map<String, EU_Open_Invoice__c> newInvoicesByInvoiceNumber = new Map<String, EU_Open_Invoice__c>();

        for(EU_Open_Invoice_Line__c invoiceLine : invoiceLines) {
            try {
                EU_Open_Invoice__c currentInvoice = new EU_Open_Invoice__c();
                if (newInvoicesByInvoiceNumber.containsKey(invoiceLine.EU_Header_Invoice_Number__c + invoiceLine.EU_Header_Account__c)) {
                    currentInvoice = newInvoicesByInvoiceNumber.get(invoiceLine.EU_Header_Invoice_Number__c + invoiceLine.EU_Header_Account__c);
                } else {
                    this.relateHeaderFieldsToInvoiceRecord(currentInvoice, invoiceLine);
                }
                currentInvoice.EU_Account__c = invoiceLine.EU_Header_Account__c;

                newInvoicesByInvoiceNumber.put(currentInvoice.EU_Invoice_Number__c + currentInvoice.EU_Account__c, currentInvoice);
            } catch(Exception e) {
                System.debug(LoggingLevel.WARN, e.getMessage());
                System.debug(LoggingLevel.WARN, 'could not generate invoice for invoice line due to NULL-reference');
            }
        }

        return newInvoicesByInvoiceNumber.values();
    }

    public void relateHeaderFieldsToInvoiceRecord(EU_Open_Invoice__c invoice, EU_Open_Invoice_Line__c invoiceLine) {
        invoice.CurrencyIsoCode = invoiceLine.CurrencyIsoCode;
        invoice.EU_Inv_Due_Date__c = invoiceLine.EU_Header_Inv_Due_Date__c;
        invoice.EU_Invoice_Date__c = invoiceLine.EU_Header_Invoice_Date__c;
        invoice.EU_Invoice_Number__c = invoiceLine.EU_Header_Invoice_Number__c;
        invoice.EU_Invoice_Type__c = invoiceLine.EU_Header_Invoice_Type__c;
        invoice.EU_JDE_Customer_No__c = invoiceLine.EU_Header_JDE_Customer_No__c;
        invoice.EU_Mapics_Customer_No__c = invoiceLine.EU_Header_Mapics_Customer_No__c;
        invoice.EU_Open_Invoice__c = invoiceLine.EU_Header_Open_Invoice__c;
        invoice.EU_Order_number_Reference__c = invoiceLine.EU_Header_Order_number_Reference__c;
        invoice.EU_Purchase_Order_Number__c = invoiceLine.EU_Header_Purchase_Order_Number__c;
        invoice.EU_Terms_code__c = invoiceLine.EU_Header_Terms_code__c;
        invoice.EU_Terms_Description__c = invoiceLine.EU_Header_Terms_Description__c;
        invoice.EU_Total_Invoice_Value__c = invoiceLine.EU_Header_Total_Invoice_Value__c;
    }
}