ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <description>Object to manage credit notes or check requests to pay home owner, customer (dealer), or a third party.</description>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Payment_Request__c/fields/Case_Closed__c.field-meta.xml
<CustomField>
    <fullName>Case_Closed__c</fullName>
    <description>Indicate whether the Payment Request is associated with Closed Cases.
True if it is, otherwise, is false.</description>
    <formula>TEXT( Case__r.Claim_Stage__c ) == &apos;Closed&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Closed?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Payment_Request__c/fields/Payment_Request_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request Line Item</label>
    <referenceTo>Payment_Request_Line_Item__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Payment_Request_Line_Item__c/Payment_Request_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Request Line Item</label>
    <nameField>
        <displayFormat>PRLI-{00000}</displayFormat>
        <label>Payment Request Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Payment_Request_Line_Item__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Payment Request Line Items</relationshipLabel>
    <relationshipName>Payment_Request_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/PaymentRequestLineItemService.cls
/**
 * @description Trigger Handler for the Payment Request Line Item object
 * @author Sinan Bunni
 * @date 02/05/2019
 */
public with sharing class PaymentRequestLineItemService {

	Private static User runningUser;
	public static User getRunningUser() {
		if (runningUser == NULL) {
			runningUser = [SELECT Id, Profile.Name FROM User WHERE Id = :UserInfo.getUserId()];
		}
		return runningUser;
	}

	public static void blockEditPaymentRequestLineItemOnClosedCases(List<Payment_Request_Line_Item__c> paymentRequestLineItems) {

		User runningUser = getRunningUser();

		Set<Id> paymentRequestIds = new Set<Id>();
		for (Payment_Request_Line_Item__c paymentRequestLineItem : paymentRequestLineItems) {
			paymentRequestIds.add(paymentRequestLineItem.Payment_Request__c);
		}

		Map<Id, Payment_Request__c> paymentRequestMap = new Map<Id, Payment_Request__c>(
		[
				SELECT Id, Case_Closed__c
				FROM Payment_Request__c
				WHERE Id IN:paymentRequestIds AND
				Case_Closed__c = true
		]
		);

		for (Payment_Request_Line_Item__c paymentRequestLineItem : paymentRequestLineItems) {
			if (paymentRequestMap.containsKey(paymentRequestLineItem.Payment_Request__c) &&
					runningUser.Profile.Name != 'System Administrator') {
				paymentRequestLineItem.addError('Users cannot edit the payment request line item for closed cases.');
			}
		}
	} // end blockEditPaymentRequestLineItemOnClosedCases method

} // end PaymentRequestLineItemService class