ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IMT_Invoice_Log__c/IMT_Invoice_Log__c.object-meta.xml
<CustomObject>
    <label>IMT Invoice Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>IMT Invoice Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IMT Invoice Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IMT_Invoice_Log__c/fields/JSON_Object__c.field-meta.xml
<CustomField>
    <fullName>JSON_Object__c</fullName>
    <label>JSON Object</label>
    <length>15000</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IMT_Invoice_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>15000</length>
    <type>LongTextArea</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/icTestREPOErrorLog.cls
/**
 * Created by Andrea Pissinis on 2018-09-12.
 */
@isTest
public with sharing class icTestREPOErrorLog {

    public static testMethod void test_createErrorLog(){
    	IMT_Invoice_Log__c newErrorLog = new IMT_Invoice_Log__c(
		Class_Name__c = 'className'
		,Method_Name__c = 'methodName'
		,Stack_Trace__c = 'stackTrace'
		,Error_Message__c = 'errorMessage'
		,JSON_Object__c = 'jsonObject');

		IMT_Invoice_Log__c newErrorLogForList = new IMT_Invoice_Log__c(
		Class_Name__c = 'className'
		,Method_Name__c = 'methodName'
		,Stack_Trace__c = 'stackTrace'
		,Error_Message__c = 'errorMessage'
		,JSON_Object__c = 'jsonObject');
		
		icRepoErrorLog.IClass repository = (icRepoErrorLog.IClass) icObjectFactory.GetSingletonInstance('icRepoErrorLog');
		repository.createErrorLog(newErrorLog);
		repository.createErrorLogs(new List<IMT_Invoice_Log__c>{newErrorLogForList});
    }

}