ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/What_s_Happening__c/What_s_Happening__c.object-meta.xml
<CustomObject>
    <description>This object contains content to generate quick view cards of current events and activities within the community.</description>
    <label>What&apos;s Happening</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>What&apos;s Happening</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/What_s_Happening__c/fields/Content_Language__c.field-meta.xml
<CustomField>
    <fullName>Content_Language__c</fullName>
    <label>Content Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Operating_Languages</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/What_s_Happening__c/fields/Image_Id__c.field-meta.xml
<CustomField>
    <fullName>Image_Id__c</fullName>
    <label>Image Id</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/What_s_Happening__c/fields/Link_Type__c.field-meta.xml
<CustomField>
    <fullName>Link_Type__c</fullName>
    <label>Link Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Email To</fullName>
            </value>
            <value>
                <fullName>No Link</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
                <isActive>false</isActive>
                <label>Document</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/What_s_Happening__c/fields/Publish_in__c.field-meta.xml
<CustomField>
    <fullName>Publish_in__c</fullName>
    <description>This field allowes to the user to select in which communities he wants the what&apos;s happening publication to be published</description>
    <inlineHelpText>Please select in which community you want to publish your &quot;what&apos;s happening&quot; publication. Multi selection is alowed.</inlineHelpText>
    <label>Publish in</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CommunityName</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icTestLogicWhatsHappening.cls
@isTest
public with sharing class icTestLogicWhatsHappening {

	static List<What_s_Happening__c> mockListWhatsHappening {get;set;}

	static void initSetup(){
		icTestMockUtilities.Mocker.SetMockSingletonInstance('icRepoWhatsHappening', new icRepoWhatsHappeningMock());

		What_s_Happening__c newWhatHappening = new What_s_Happening__c(Name = 'new name'
			,Image_Id__c = 'new image ref'
			,Title__c = 'new title'
			,Description__c = 'new desc'
			,Link_Type__c = 'Internal'
			,Active__c = true
			,Content_Language__c = 'English'
			,Order__c = 0
			,Publish_in__c = 'IKOROOFPRO_C');

		mockListWhatsHappening = new List<What_s_Happening__c>{newWhatHappening};

		icTestMockUtilities.Tracer.SetReturnValue('icRepoWhatsHappeningMock', 'getActiveWhatHappeningByLanguageAndCommunityName', mockListWhatsHappening);
	}

	public static testMethod void test_getActiveWhatHappeningByLanguageAndCommunityName(){
		initSetup();
		
		icLogicWhatsHappening.IClass logic = (icLogicWhatsHappening.IClass) icObjectFactory.GetSingletonInstance('icLogicWhatsHappening');

		List<What_s_Happening__c> result = logic.getActiveWhatHappeningByLanguageAndCommunityName('English','IKOROOFPRO_C');
		System.assertEquals(result.size(), 1);
	}

	public static testMethod void test_getListDTOFromWhatHappening(){
		initSetup();
		
		icLogicWhatsHappening.IClass logic = (icLogicWhatsHappening.IClass) icObjectFactory.GetSingletonInstance('icLogicWhatsHappening');

		List<icDTOWhatsHappening> result = logic.getListDTOFromWhatHappening(mockListWhatsHappening);
		System.assertEquals(result.size(), 1);
	}
}