ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/Account_Tier_Movement__c.object-meta.xml
<CustomObject>
    <label>Account Tier Movement</label>
    <nameField>
        <displayFormat>ATM - {0}</displayFormat>
        <label>Account Tier Movement name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Tier Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Applicable_Invoice_Year__c.field-meta.xml
<CustomField>
    <fullName>ATM_Applicable_Invoice_Year__c</fullName>
    <label>Applicable Invoice Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Applied_Benchmark_Value_Tier_1_High__c.field-meta.xml
<CustomField>
    <fullName>ATM_Applied_Benchmark_Value_Tier_1_High__c</fullName>
    <label>Applied Benchmark Value - Tier 1 - High</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Applied_Benchmark_Value_Tier_2_High__c.field-meta.xml
<CustomField>
    <fullName>ATM_Applied_Benchmark_Value_Tier_2_High__c</fullName>
    <label>Applied Benchmark Value - Tier 2 - High</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Applied_Benchmark_Value_Tier_2_Low__c.field-meta.xml
<CustomField>
    <fullName>ATM_Applied_Benchmark_Value_Tier_2_Low__c</fullName>
    <label>Applied Benchmark Value - Tier 2 - Low</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Applied_Benchmark_Value_Tier_3_Low__c.field-meta.xml
<CustomField>
    <fullName>ATM_Applied_Benchmark_Value_Tier_3_Low__c</fullName>
    <label>Applied Benchmark Value - Tier 3 - Low</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Business_Fundamentals_Completed__c.field-meta.xml
<CustomField>
    <fullName>ATM_Business_Fundamentals_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Business Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Contractor__c.field-meta.xml
<CustomField>
    <fullName>ATM_Contractor__c</fullName>
    <label>Contractor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Tier Movements</relationshipLabel>
    <relationshipName>Account_Tier_Trackings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Contractor_Email__c.field-meta.xml
<CustomField>
    <fullName>ATM_Contractor_Email__c</fullName>
    <description>Email of Contractor to receive emails</description>
    <label>Contractor Email</label>
    <type>Email</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Date_Present_Tier__c.field-meta.xml
<CustomField>
    <fullName>ATM_Date_Present_Tier__c</fullName>
    <label>Date Present Tier</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Installation_Fundamentals_Completed__c.field-meta.xml
<CustomField>
    <fullName>ATM_Installation_Fundamentals_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Member_Since_Months__c.field-meta.xml
<CustomField>
    <fullName>ATM_Member_Since_Months__c</fullName>
    <label>Member Since (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Performance_Fundamentals_Completed__c.field-meta.xml
<CustomField>
    <fullName>ATM_Performance_Fundamentals_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Performance Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Present_Tier__c.field-meta.xml
<CustomField>
    <fullName>ATM_Present_Tier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eligible Present Tier</label>
    <referenceTo>Tier__c</referenceTo>
    <relationshipLabel>Account Tier Movements</relationshipLabel>
    <relationshipName>ATM_Present_Tier_Tier</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Prior_Tier__c.field-meta.xml
<CustomField>
    <fullName>ATM_Prior_Tier__c</fullName>
    <label>Prior Tier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Purchase_Square_Volume__c.field-meta.xml
<CustomField>
    <fullName>ATM_Purchase_Square_Volume__c</fullName>
    <description>Purchase Square Volume (from Member Start Date)</description>
    <label>Purchase Square Volume</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Safety_Fundamentals_Completed__c.field-meta.xml
<CustomField>
    <fullName>ATM_Safety_Fundamentals_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Safety Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Sign_Up_Year__c.field-meta.xml
<CustomField>
    <fullName>ATM_Sign_Up_Year__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sign-Up Year</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Tier_Movement_Decision__c.field-meta.xml
<CustomField>
    <fullName>ATM_Tier_Movement_Decision__c</fullName>
    <label>Tier Movement Decision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exceeded Sq. Purchase Volume</fullName>
            </value>
            <value>
                <fullName>Did Not Meet Minimum Sq. Purchase Volume</fullName>
            </value>
            <value>
                <fullName>Manual Tier Adjustment</fullName>
            </value>
            <value>
                <fullName>Maintained Sq. Purchase Volume</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_TSR_Email__c.field-meta.xml
<CustomField>
    <fullName>ATM_TSR_Email__c</fullName>
    <description>Email Id of TSR to receive emails.</description>
    <label>TSR Email</label>
    <type>Email</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icTestRepoTierMovementLog.cls
@isTest
public with sharing class icTestRepoTierMovementLog {

    public static testMethod void test_getAllTiers(){
    	icRepoTierMovementLog.IClass repository = (icRepoTierMovementLog.IClass) icObjectFactory.GetSingletonInstance('icRepoTierMovementLog');

    	List<Account_Tier_Movement__c> tierMovementLog = new List<Account_Tier_Movement__c>();
    	
    	Account_Tier_Movement__c newTierMovementLog = new Account_Tier_Movement__c();
		//newTierMovementLog.ATM_Contractor__c = contractor.Id;
		newTierMovementLog.ATM_Member_Since_Months__c = 12;
		newTierMovementLog.ATM_Applicable_Invoice_Year__c = '2019';
		newTierMovementLog.ATM_Purchase_Square_Volume__c = 100;
		newTierMovementLog.ATM_Sign_Up_Year__c = false;
		newTierMovementLog.ATM_Tier_Movement_Decision__c = 'Maintained Sq. Purchase Volume';
		newTierMovementLog.ATM_Business_Fundamentals_Completed__c = true;
		newTierMovementLog.ATM_Installation_Fundamentals_Completed__c = true;
		newTierMovementLog.ATM_Performance_Fundamentals_Completed__c = true;
		newTierMovementLog.ATM_Safety_Fundamentals_Completed__c = true;
		newTierMovementLog.ATM_Applied_Benchmark_Value_Tier_1_High__c = 5;
		newTierMovementLog.ATM_Applied_Benchmark_Value_Tier_2_Low__c = 6;
		newTierMovementLog.ATM_Applied_Benchmark_Value_Tier_2_High__c = 10;
		newTierMovementLog.ATM_Applied_Benchmark_Value_Tier_3_Low__c = 11;
		newTierMovementLog.ATM_Date_Present_Tier__c = Date.today();
		//newTierMovementLog.ATM_Present_Tier__c = contractor.Present_Tier_Lookup__c;
		//newTierMovementLog.ATM_Prior_Tier__c = contractor.Prior_Tier__c;
		//newTierMovementLog.ATM_TSR_Email__c = contractor.Owner.Email;
		//newTierMovementLog.ATM_Contractor_Email__c = contractor.Admin_Email_Address__c;
		tierMovementLog.add(newTierMovementLog);

        List<Database.SaveResult> testResult = repository.saveTierMovementLog(tierMovementLog);
    }
}