ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/Tier_Movement_Setup__c.object-meta.xml
<CustomObject>
    <description>This object holds the configuration for the Account Tier Movement for IKOROOFPRO Loyalty Project.</description>
    <label>Tier Movement Setup</label>
    <nameField>
        <displayFormat>TMS - {0}</displayFormat>
        <label>Tier Movement Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tier Movement Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/fields/Admin_Email__c.field-meta.xml
<CustomField>
    <fullName>Admin_Email__c</fullName>
    <label>Admin Email</label>
    <type>Email</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/fields/Simulation__c.field-meta.xml
<CustomField>
    <fullName>Simulation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Simulation</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/fields/Tier_Advancement_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Tier_Advancement_End_Date__c</fullName>
    <description>This is the end date for Tier Advancement Process.</description>
    <label>Tier Advancement End Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/fields/Tier_Advancement_Invoice_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_Advancement_Invoice_Year__c</fullName>
    <label>Tier Advancement Invoice Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/fields/Tier_Advancement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Tier_Advancement_Start_Date__c</fullName>
    <description>This is the start date of Tier Advancement Process.</description>
    <label>Tier Advancement Start Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/fields/Tier_Maintenance_Descend_Date__c.field-meta.xml
<CustomField>
    <fullName>Tier_Maintenance_Descend_Date__c</fullName>
    <description>This is the date to run the Tier Maintenance and Descend Process.</description>
    <label>Tier Maintenance/Descend Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/fields/Tier_Maintenance_Descend_Invoice_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_Maintenance_Descend_Invoice_Year__c</fullName>
    <description>This is the year for which we have to run Tier Maintain/Descend process.</description>
    <label>Tier Maintenance/Descend Invoice Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icRepoTierMovementSetup.cls
public class icRepoTierMovementSetup implements icIClass {

	public Object GetInstance() {
		return new Impl();
	}

	public Interface IClass {
		Tier_Movement_Setup__c getTierMovementSetup();
	}

	public class Impl implements IClass {

		public Tier_Movement_Setup__c getTierMovementSetup() {
			Tier_Movement_Setup__c returnTierMovementSetup;
			List<Tier_Movement_Setup__c> listTierMovementSetup =
					[SELECT	Id
							,Name
							,Admin_Email__c
							,Simulation__c
							,Tier_Advancement_Start_Date__c
							,Tier_Advancement_End_Date__c
							,Tier_Advancement_Invoice_Year__c
							,Tier_Maintenance_Descend_Date__c
							,Tier_Maintenance_Descend_Invoice_Year__c
					FROM	Tier_Movement_Setup__c LIMIT 1];

			if(listTierMovementSetup.size() > 0) {
				returnTierMovementSetup = listTierMovementSetup[0];
			}
			return returnTierMovementSetup;
		}
	}
}