ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/Tier_Movement_Setup__c.object-meta.xml
<CustomObject>
    <description>This object holds the configuration for the Account Tier Movement for IKOROOFPRO Loyalty Project.</description>
    <label>Tier Movement Setup</label>
    <nameField>
        <displayFormat>TMS - {0}</displayFormat>
        <label>Tier Movement Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tier Movement Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/fields/Admin_Email__c.field-meta.xml
<CustomField>
    <fullName>Admin_Email__c</fullName>
    <label>Admin Email</label>
    <type>Email</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/fields/Simulation__c.field-meta.xml
<CustomField>
    <fullName>Simulation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Simulation</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/fields/Tier_Advancement_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Tier_Advancement_End_Date__c</fullName>
    <description>This is the end date for Tier Advancement Process.</description>
    <label>Tier Advancement End Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/fields/Tier_Advancement_Invoice_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_Advancement_Invoice_Year__c</fullName>
    <label>Tier Advancement Invoice Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/fields/Tier_Advancement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Tier_Advancement_Start_Date__c</fullName>
    <description>This is the start date of Tier Advancement Process.</description>
    <label>Tier Advancement Start Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/fields/Tier_Maintenance_Descend_Date__c.field-meta.xml
<CustomField>
    <fullName>Tier_Maintenance_Descend_Date__c</fullName>
    <description>This is the date to run the Tier Maintenance and Descend Process.</description>
    <label>Tier Maintenance/Descend Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/fields/Tier_Maintenance_Descend_Invoice_Year__c.field-meta.xml
<CustomField>
    <fullName>Tier_Maintenance_Descend_Invoice_Year__c</fullName>
    <description>This is the year for which we have to run Tier Maintain/Descend process.</description>
    <label>Tier Maintenance/Descend Invoice Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/icLogicTierMovementSetup.cls
public class icLogicTierMovementSetup implements icIClass {

	public Object GetInstance() {
		return new Impl();
	}

	public Interface IClass {
		Tier_Movement_Setup__c getTierMovementSetup();
		icDtoTierMovementConfig getTierMovementConfigDto(Tier_Movement_Setup__c tierMovementSetup);
	}

	public class Impl implements IClass {

		icRepoTierMovementSetup.IClass repository = (icRepoTierMovementSetup.IClass) icObjectFactory.GetSingletonInstance('icRepoTierMovementSetup');

		public Tier_Movement_Setup__c getTierMovementSetup() {
			return repository.getTierMovementSetup();
		}

		public icDtoTierMovementConfig getTierMovementConfigDto(Tier_Movement_Setup__c tierMovementSetup) {
			icDtoTierMovementConfig returnConfig = new icDtoTierMovementConfig();

			returnConfig.sfId = tierMovementSetup.Id;
			returnConfig.adminEmail = tierMovementSetup.Admin_Email__c;
			returnConfig.runProcess = false;
			returnConfig.isSimulation = tierMovementSetup.Simulation__c;

			Date dateToday = Date.today();
			Datetime dateTimeToday = DateTime.newInstance(dateToday.year(), dateToday.month(), dateToday.day());
			String dayOfWeekToday =  dateTimeToday.format('EEEE');

			Datetime dateTimeAscendDate = DateTime.newInstance(tierMovementSetup.Tier_Advancement_Start_Date__c.year(), tierMovementSetup.Tier_Advancement_Start_Date__c.month(), tierMovementSetup.Tier_Advancement_Start_Date__c.day());
			String dayOfWeekAscend =  dateTimeAscendDate.format('EEEE');

			if(tierMovementSetup.Tier_Maintenance_Descend_Date__c == dateToday) {
				returnConfig.runProcess = true;
				returnConfig.processMode = 'DESCEND';
				returnConfig.rebateYear = tierMovementSetup.Tier_Maintenance_Descend_Invoice_Year__c;
			} else if(tierMovementSetup.Tier_Advancement_Start_Date__c == dateToday 
			|| tierMovementSetup.Tier_Advancement_End_Date__c == dateToday
			|| (tierMovementSetup.Tier_Advancement_Start_Date__c < dateToday && tierMovementSetup.Tier_Advancement_End_Date__c > dateToday && dayOfWeekToday.equals(dayOfWeekAscend))) {
				returnConfig.runProcess = true;
				returnConfig.processMode = 'ASCEND';
				returnConfig.rebateYear = tierMovementSetup.Tier_Advancement_Invoice_Year__c;
				returnConfig.startDate = tierMovementSetup.Tier_Advancement_Start_Date__c;
				returnConfig.endDate = tierMovementSetup.Tier_Advancement_End_Date__c;
			}

			return returnConfig;
		}
	}
}