ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/Tier_Movement_Setup__c.object-meta.xml
<CustomObject>
    <description>This object holds the configuration for the Account Tier Movement for IKOROOFPRO Loyalty Project.</description>
    <label>Tier Movement Setup</label>
    <nameField>
        <displayFormat>TMS - {0}</displayFormat>
        <label>Tier Movement Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tier Movement Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/fields/Tier_Advancement_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Tier_Advancement_End_Date__c</fullName>
    <description>This is the end date for Tier Advancement Process.</description>
    <label>Tier Advancement End Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/fields/Tier_Advancement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Tier_Advancement_Start_Date__c</fullName>
    <description>This is the start date of Tier Advancement Process.</description>
    <label>Tier Advancement Start Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/fields/Tier_Maintenance_Descend_Date__c.field-meta.xml
<CustomField>
    <fullName>Tier_Maintenance_Descend_Date__c</fullName>
    <description>This is the date to run the Tier Maintenance and Descend Process.</description>
    <label>Tier Maintenance/Descend Date</label>
    <type>Date</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/icTestLogicTierMovementSetup.cls
@isTest
public with sharing class icTestLogicTierMovementSetup {

	static void setup() {
        icTestMockUtilities.Mocker.SetMockSingletonInstance('icRepoTierMovementSetup', new icRepoTierMovementSetupMock());
        icTestMockUtilities.Tracer.SetReturnValue('icRepoTierMovementSetupMock', 'getTierMovementSetup', new Tier_Movement_Setup__c());
    }

    public static testMethod void test_getTierMovementSetup(){
    	setup();

    	icLogicTierMovementSetup.IClass logic = (icLogicTierMovementSetup.IClass) icObjectFactory.GetSingletonInstance('icLogicTierMovementSetup');

        Tier_Movement_Setup__c testResult = logic.getTierMovementSetup();
    }

    public static testMethod void test_getTierMovementConfigDto_Weekly_byStart() {
    	icLogicTierMovementSetup.IClass logic = (icLogicTierMovementSetup.IClass) icObjectFactory.GetSingletonInstance('icLogicTierMovementSetup');

    	Date dateToday = Date.today();

    	Tier_Movement_Setup__c tierMovementSetup = new Tier_Movement_Setup__c(
    		Id = icTestHelperUtility.getFakeId(Tier_Movement_Setup__c.SObjectType)
    		,Tier_Advancement_Start_Date__c = dateToday
    		,Tier_Advancement_End_Date__c = dateToday.addMonths(9)
    		,Tier_Maintenance_Descend_Date__c = dateToday.addDays(7));

    	icDtoTierMovementConfig testResult = logic.getTierMovementConfigDto(tierMovementSetup);
    }

    public static testMethod void test_getTierMovementConfigDto_Weekly_byEnd() {
    	icLogicTierMovementSetup.IClass logic = (icLogicTierMovementSetup.IClass) icObjectFactory.GetSingletonInstance('icLogicTierMovementSetup');

    	Date dateToday = Date.today();

    	Tier_Movement_Setup__c tierMovementSetup = new Tier_Movement_Setup__c(
    		Id = icTestHelperUtility.getFakeId(Tier_Movement_Setup__c.SObjectType)
    		,Tier_Advancement_Start_Date__c = dateToday.addMonths(-9)
    		,Tier_Advancement_End_Date__c = dateToday
    		,Tier_Maintenance_Descend_Date__c = dateToday.addDays(7));

    	icDtoTierMovementConfig testResult = logic.getTierMovementConfigDto(tierMovementSetup);
    }

    public static testMethod void test_getTierMovementConfigDto_Weekly_byDOW() {
    	icLogicTierMovementSetup.IClass logic = (icLogicTierMovementSetup.IClass) icObjectFactory.GetSingletonInstance('icLogicTierMovementSetup');

    	Date dateToday = Date.today();

    	Tier_Movement_Setup__c tierMovementSetup = new Tier_Movement_Setup__c(
    		Id = icTestHelperUtility.getFakeId(Tier_Movement_Setup__c.SObjectType)
    		,Tier_Advancement_Start_Date__c = dateToday.addDays(-7)
    		,Tier_Advancement_End_Date__c = dateToday.addMonths(9)
    		,Tier_Maintenance_Descend_Date__c = dateToday.addDays(7));

    	icDtoTierMovementConfig testResult = logic.getTierMovementConfigDto(tierMovementSetup);
    }

    public static testMethod void test_getTierMovementConfigDto_Yearly() {
    	icLogicTierMovementSetup.IClass logic = (icLogicTierMovementSetup.IClass) icObjectFactory.GetSingletonInstance('icLogicTierMovementSetup');

    	Date dateToday = Date.today();

    	Tier_Movement_Setup__c tierMovementSetup = new Tier_Movement_Setup__c(
    		Id = icTestHelperUtility.getFakeId(Tier_Movement_Setup__c.SObjectType)
    		,Tier_Advancement_Start_Date__c = dateToday.addDays(7)
    		,Tier_Advancement_End_Date__c = dateToday.addMonths(9)
    		,Tier_Maintenance_Descend_Date__c = dateToday);

    	icDtoTierMovementConfig testResult = logic.getTierMovementConfigDto(tierMovementSetup);
    }
}