ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/Lab_Sample__c.object-meta.xml
<CustomObject>
    <label>Lab Sample</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Samples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A link to the Claim this lab sample is related to. Lab Samples with no links to a Claim have been received but not properly connected to a cliam.</description>
    <inlineHelpText>The Claim this Lab Sample relates to.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Lab Samples</relationshipLabel>
    <relationshipName>Lab_Samples</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Case_Description__c.field-meta.xml
<CustomField>
    <fullName>Case_Description__c</fullName>
    <description>CLAIMS - 77. Field to hold the related case description</description>
    <inlineHelpText>Related Case&apos;s description</inlineHelpText>
    <label>Case Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Id of record from legacy (WCMS) system</inlineHelpText>
    <label>Legacy Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Repository/Claims/force-app/main/default/classes/UpdateLegacyLabSampleRecords.cls
global class UpdateLegacyLabSampleRecords implements Database.Batchable<sObject>{

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT ID, Case__c,  Legacy_Id__c, Case_Subject__c, Case_Description__c FROM Lab_Sample__c ' + 
            'WHERE Legacy_Id__c != NULL'
        );
    }
    global void execute(Database.BatchableContext bc, List<Lab_Sample__c> records){
        // process each batch of records
        Set<Id> relatedCases = new Set<Id>();
        for (Lab_Sample__c labSample : records) {
            relatedCases.add(labSample.Case__c);
        }

        Map<Id, Case> cases = new Map<Id, Case>([SELECT Id, Description, Subject FROM Case WHERE Id IN :relatedCases]);

        for (Lab_Sample__c labSample : records) {
            Case c = cases.get(labSample.Case__c);
            if (c.Description != NULL && c.Description != '' ) {
              labSample.Case_Description__c = c.Description;
            }
        }
        update records;
    } 
    
    global void finish(Database.BatchableContext bc){
    	// VOID
    }    
}