ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/Contractor_Invoice__c.object-meta.xml
<CustomObject>
    <label>Uploaded Invoice</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Uploaded Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Uploaded_Files_Long__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_Files_Long__c</fullName>
    <label>Uploaded Files</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/icTestHandlerContentDocument.cls
/**
 * Created by Francois Poirier on 2018-10-10.
 */

@isTest
public with sharing class icTestHandlerContentDocument {

    @isTest
    public static void testOnBeforeDelete(){


        ContentDocument testDoc = new ContentDocument();
        ContentVersion testVersion = new ContentVersion();

        testVersion.Title = 'TestOnBeforeDeleteDoc';
        testVersion.PathOnClient = 'testBeforeDelete.jpg';
        testVersion.VersionData = Blob.valueOf('test content Data');
        testVersion.IsMajorVersion = true;

        insert testVersion;

        ContentVersion testVersion2 = new ContentVersion();

        testVersion2 = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE id = :testVersion.Id];

        testDoc.Id = testVersion2.ContentDocumentId;

        Contractor_Invoice__c newUploadedInvoice = new Contractor_Invoice__c(Uploaded_Files_Long__c = 'test');
        insert newUploadedInvoice;
        ContentDocumentLink docLink = new ContentDocumentLink(ContentDocumentId=testVersion2.ContentDocumentId,LINKEDENTITYID = newUploadedInvoice.Id,SHARETYPE='V');
        insert docLink;

        delete testDoc;
        
    }
}