ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/Contractor_Invoice__c.object-meta.xml
<CustomObject>
    <label>Uploaded Invoice</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Uploaded Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>IKOPRO Contractor, IKOPRO Contractor HA OK</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Uploaded Invoices</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <label>Date of Upload</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Action Required</label>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Upload Failed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Ready for Upload</fullName>
            </value>
            <value>
                <fullName>DO NOT PAY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Uploaded_Files_Long__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_Files_Long__c</fullName>
    <label>Uploaded Files</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Rebate Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>IKOPRO Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/fields/COOP_Amount__c.field-meta.xml
<CustomField>
    <fullName>COOP_Amount__c</fullName>
    <label>COOP Amount</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/fields/Invoice_Year__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Year__c</fullName>
    <externalId>true</externalId>
    <label>Invoice Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/fields/Total_Actual_Squares__c.field-meta.xml
<CustomField>
    <fullName>Total_Actual_Squares__c</fullName>
    <label>Total Actual Squares</label>
    <summarizedField>Invoice_Line__c.ActualSquares__c</summarizedField>
    <summaryForeignKey>Invoice_Line__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/fields/Total_Bundles__c.field-meta.xml
<CustomField>
    <fullName>Total_Bundles__c</fullName>
    <description>Total bundles sold based on IMT Invoice Lines.</description>
    <label>Bundles</label>
    <summarizedField>Invoice_Line__c.Bundles__c</summarizedField>
    <summaryFilterItems>
        <field>Invoice_Line__c.Is_Used_To_Calculate_Square__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Invoice_Line__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/fields/Total_Rebate_Squares__c.field-meta.xml
<CustomField>
    <fullName>Total_Rebate_Squares__c</fullName>
    <label>Rebate Squares</label>
    <summarizedField>Invoice_Line__c.RebateSquares__c</summarizedField>
    <summaryFilterItems>
        <field>Invoice_Line__c.Is_Used_To_Calculate_Square__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Invoice_Line__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/fields/Total_Rebates__c.field-meta.xml
<CustomField>
    <fullName>Total_Rebates__c</fullName>
    <label>Rebates</label>
    <summarizedField>Invoice_Line__c.Dollars__c</summarizedField>
    <summaryForeignKey>Invoice_Line__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icRepoInvoice.cls
public class icRepoInvoice implements icIClass {

	public Object GetInstance() {
		return new Impl();
	}

	public Interface IClass {
		List<Invoice__c> getAllInvoicesByAccountIdAndDate(String recordId, String strYear);
		List<Invoice__c> getAllInvoicesByAccountIdsAndRebateYear(List<String> recordIds, String rebateYear);
		List<Contractor_Invoice__c> getUploadedInvoiceById(List<String> recordIds);
		void updateInvoices(List<Contractor_Invoice__c> invoices);

	}

	public class Impl implements IClass {

		public List<Invoice__c> getAllInvoicesByAccountIdAndDate(String recordId, String strYear) {
			List<Invoice__c> listInvoices = new List<Invoice__c>();
			listInvoices =
					[SELECT	Id
							,Coop_Amount__c
							,Name
							,Total_Bundles__c
							,Invoice_Amount__c
							,Total_Rebates__c
							,Total_Rebate_Squares__c
							,Total_Actual_Squares__c
					FROM	Invoice__c
					WHERE	Contractor__c = :recordId
					AND		Invoice_Year__c = :strYear];
			return listInvoices;
		}

		public List<Invoice__c> getAllInvoicesByAccountIdsAndRebateYear(List<String> recordIds, String rebateYear) {
			List<Invoice__c> listInvoices = 
					[SELECT	Id
							,Contractor__c
							,Name
							,Total_Rebate_Squares__c
							,Invoice_Date__c
					FROM	Invoice__c
					WHERE	Contractor__c IN :recordIds
					AND		Invoice_Year__c = :rebateYear];
			return listInvoices;
		}

		public List<Contractor_Invoice__c> getUploadedInvoiceById(List<String> recordIds) {
			return [SELECT Id, Name, Status__c, Uploaded_Files_Long__c FROM Contractor_Invoice__c WHERE Id IN :recordIds];
		}

		public void updateInvoices(List<Contractor_Invoice__c> invoices) {
			update invoices;
		}
	}
}