ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/Contractor_Invoice__c.object-meta.xml
<CustomObject>
    <label>Uploaded Invoice</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Uploaded Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>IKOPRO Contractor, IKOPRO Contractor HA OK</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Uploaded Invoices</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <label>Date of Upload</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Rebate Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>IKOPRO Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/fields/COOP_Amount__c.field-meta.xml
<CustomField>
    <fullName>COOP_Amount__c</fullName>
    <label>COOP Amount</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/fields/Total_Bundles__c.field-meta.xml
<CustomField>
    <fullName>Total_Bundles__c</fullName>
    <description>Total bundles sold based on IMT Invoice Lines.</description>
    <label>Bundles</label>
    <summarizedField>Invoice_Line__c.Bundles__c</summarizedField>
    <summaryFilterItems>
        <field>Invoice_Line__c.Is_Used_To_Calculate_Square__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Invoice_Line__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/fields/Total_Rebate_Squares__c.field-meta.xml
<CustomField>
    <fullName>Total_Rebate_Squares__c</fullName>
    <label>Rebate Squares</label>
    <summarizedField>Invoice_Line__c.RebateSquares__c</summarizedField>
    <summaryFilterItems>
        <field>Invoice_Line__c.Is_Used_To_Calculate_Square__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Invoice_Line__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/fields/Total_Rebates__c.field-meta.xml
<CustomField>
    <fullName>Total_Rebates__c</fullName>
    <label>Rebates</label>
    <summarizedField>Invoice_Line__c.Dollars__c</summarizedField>
    <summaryForeignKey>Invoice_Line__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/icLogicInvoice.cls
public class icLogicInvoice implements icIClass {

	public Object GetInstance() {
		return new Impl();
	}

	public Interface IClass {
		List<Invoice__c> getAllYTDInvoicesByAccountId(String recordId);
		List<Invoice__c> getAllInvoicesByAccountIdsAndRebateYear(List<String> recordIds, String rebateYear);
		Map<String, List<Invoice__c>> getMapInvoicesByAccount(List<Invoice__c> invoices);
		List<Contractor_Invoice__c> getUploadedInvoiceById(List<String> recordIds);
		Double getSquaresFromInvoices(List<Invoice__c> invoices, Boolean isProrated, Date startDate);
		Double getPro4RewardsFromInvoices(List<Invoice__c> invoices);
		Double getCoopRewardsFromInvoices(List<Invoice__c> invoices);
		Double getUpcomingCoopRewardsFromInvoices(List<Invoice__c> invoices);
		void updateInvoices(List<Contractor_Invoice__c> invoices);
	}

	public class Impl implements IClass {

		icRepoInvoice.IClass repository = (icRepoInvoice.IClass) icObjectFactory.GetSingletonInstance('icRepoInvoice');

		public List<Invoice__c> getAllYTDInvoicesByAccountId(String recordId) {
			Date fromDate = Date.today();
			String strYear = String.valueOf(fromDate.year());

			List<Invoice__c> listInvoices = repository.getAllInvoicesByAccountIdAndDate(recordId, strYear);
			return listInvoices;
		}

		public List<Invoice__c> getAllInvoicesByAccountIdsAndRebateYear(List<String> recordIds, String rebateYear) {
			return repository.getAllInvoicesByAccountIdsAndRebateYear(recordIds, rebateYear);
		}

		public Map<String, List<Invoice__c>> getMapInvoicesByAccount(List<Invoice__c> invoices) {
			Map<String, List<Invoice__c>> returnMap = new Map<String, List<Invoice__c>>();

			for(Invoice__c thisInvoice : invoices) {
				List<Invoice__c> thisAccountInvoices = returnMap.get(thisInvoice.Contractor__c);
				if(thisAccountInvoices == null) {
					thisAccountInvoices = new List<Invoice__c>();
				}
				thisAccountInvoices.add(thisInvoice);
				returnMap.put(thisInvoice.Contractor__c, thisAccountInvoices);
			}

			return returnMap;
		}

		public List<Contractor_Invoice__c> getUploadedInvoiceById(List<String> recordIds) {
			return repository.getUploadedInvoiceById(recordIds);
		}

		public Double getSquaresFromInvoices(List<Invoice__c> invoices, Boolean isProrated, Date startDate) {
			Double returnTotal = 0;
			for(Invoice__c thisInvoice : invoices) {
				if(!isProrated || thisInvoice.Invoice_Date__c >= startDate) {
					returnTotal += thisInvoice.Total_Rebate_Squares__c;
				}
			}
			return returnTotal;
		}

		public Double getPro4RewardsFromInvoices(List<Invoice__c> invoices) {
			Double returnTotal = 0;
			for(Invoice__c thisInvoice : invoices) {
				returnTotal += thisInvoice.Total_Rebates__c;
			}
			return returnTotal;
		}

		public Double getCoopRewardsFromInvoices(List<Invoice__c> invoices) {
			Invoice__c temp;
			if(invoices.size() > 0) {
				temp = invoices[0];
			}
			return temp.Total_Bundles__c;
		}

		public Double getUpcomingCoopRewardsFromInvoices(List<Invoice__c> invoices){

			Double returnTotal = 0;
			for(Invoice__c thisInvoice : invoices) {
				if(thisInvoice.Coop_Amount__c != null) {
					returnTotal += thisInvoice.Coop_Amount__c;
				}
			}
			return returnTotal;

		}

		public void updateInvoices(List<Contractor_Invoice__c> invoices) {
			repository.updateInvoices(invoices);
		}
	}
}