ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/Contractor_Invoice__c.object-meta.xml
<CustomObject>
    <label>Uploaded Invoice</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Uploaded Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Rebate_Program_CRC_c__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Program_CRC_c__c</fullName>
    <label>Rebate_Program_CRC_c</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rebate_Program_CRC_c</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Rebate_Program_US__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Program_US__c</fullName>
    <label>Rebate Program (US)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2021BONUSREWARDS</fullName>
            </value>
            <value>
                <fullName>2018CONTRACTOR</fullName>
                <isActive>false</isActive>
                <label>2018CONTRACTOR</label>
            </value>
            <value>
                <fullName>2018PRO4-US</fullName>
                <isActive>false</isActive>
                <label>2018PRO4-US</label>
            </value>
            <value>
                <fullName>2019CONTRACTOR</fullName>
                <isActive>false</isActive>
                <label>2019CONTRACTOR</label>
            </value>
            <value>
                <fullName>2019PRO4-US</fullName>
                <isActive>false</isActive>
                <label>2019PRO4-US</label>
            </value>
            <value>
                <fullName>2019SPIFF</fullName>
                <isActive>false</isActive>
                <label>2019SPIFF</label>
            </value>
            <value>
                <fullName>2020BONUSREWARDSUS</fullName>
                <isActive>false</isActive>
                <label>2020BONUSREWARDSUS</label>
            </value>
            <value>
                <fullName>250WRAPREBATE2019</fullName>
                <isActive>false</isActive>
                <label>250WRAPREBATE2019</label>
            </value>
            <value>
                <fullName>500WRAPREBATE2019</fullName>
                <isActive>false</isActive>
                <label>500WRAPREBATE2019</label>
            </value>
            <value>
                <fullName>NOT A VALID CODE</fullName>
                <isActive>false</isActive>
                <label>NOT A VALID CODE</label>
            </value>
            <value>
                <fullName>SALUTEMILITARY2019</fullName>
                <isActive>false</isActive>
                <label>SALUTEMILITARY2019</label>
            </value>
            <value>
                <fullName>SALUTEMILITARY2019-D</fullName>
                <isActive>false</isActive>
                <label>SALUTEMILITARY2019-D</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icTestCtrlInvoiceUpload.cls
@isTest
public class icTestCtrlInvoiceUpload {

    public static testMethod void test_newContractorInvoice(){

        Test.startTest();
        
        icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicContractorInvoice', new icLogicContractorInvoiceMock());
        icTestMockUtilities.Tracer.SetReturnValue('icLogicContractorInvoiceMock', 'newContractorInvoice', new Contractor_Invoice__c());
        String rebateProgram = getActiveRebateProgram();
        icCTRLinvoiceUpload.newContractorInvoice(rebateProgram, new Contractor_Invoice__c());
        Test.stopTest();
    }

    public static testMethod void test_saveInvoice(){

        Test.startTest();
        icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicContractorInvoice', new icLogicContractorInvoiceMock());
        icTestMockUtilities.Tracer.SetReturnValue('icLogicContractorInvoiceMock', 'newContractorInvoice', new Contractor_Invoice__c());
        icTestMockUtilities.Tracer.SetReturnValue('icLogicContractorInvoiceMock', 'saveContractorInvoice', new Contractor_Invoice__c());
        String rebateProgram = getActiveRebateProgram();
        Contractor_Invoice__c contractObj = icCTRLinvoiceUpload.newContractorInvoice(rebateProgram, new Contractor_Invoice__c());
        icCTRLinvoiceUpload.saveInvoice(contractObj);
        Test.stopTest();
    }


    public static testMethod void test_getRebatePrograms(){
        icCTRLinvoiceUpload.getRebatePrograms();
    }

    public static testMethod void test_getComponentDetails()
    {
        String rebateProgram = getActiveRebateProgramCRC();
        Contractor_Invoice__c contractObj = icCTRLinvoiceUpload.newContractorInvoice(rebateProgram, new Contractor_Invoice__c());
        icCTRLinvoiceUpload.getComponentDetails(contractObj.Id);
    }

    public static testMethod void test_deleteUploadedFiles(){

        Test.startTest();

        String rebateProgram = getActiveRebateProgramCRC();
        Contractor_Invoice__c contractObj = icCTRLinvoiceUpload.newContractorInvoice(rebateProgram, new Contractor_Invoice__c());
        icCTRLinvoiceUpload.deleteUploadedFiles(new List<String>(), contractObj.Id);

        Test.stopTest();

    }

    public static testMethod void test_deleteContractInvoice(){

        Test.startTest();

        String rebateProgram = getActiveRebateProgramCRC();
        Contractor_Invoice__c contractObj = icCTRLinvoiceUpload.newContractorInvoice(rebateProgram, new Contractor_Invoice__c());
        icCTRLinvoiceUpload.deleteContractInvoice(contractObj.Id);

        Test.stopTest();

    }

    static String getActiveRebateProgram(){
        String rebateProgram = '';
        Schema.DescribeFieldResult fieldResult =
            Contractor_Invoice__c.Rebate_Program_US__c .getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        for( Schema.PicklistEntry f : ple)
        {
            if(f.isActive()){
                rebateProgram = f.getValue();
                break;
            }
            
        } 
        return rebateProgram;
        
    }
    
     static String getActiveRebateProgramCRC(){
        String rebateProgram = '';
        Schema.DescribeFieldResult fieldResult =
            Contractor_Invoice__c.Rebate_Program_CRC_c__c .getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        for( Schema.PicklistEntry f : ple)
        {
            if(f.isActive()){
                rebateProgram = f.getValue();
                break;
            }
            
        } 
        return rebateProgram;
        
    }
                
}