ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/Contractor_Invoice__c.object-meta.xml
<CustomObject>
    <label>Uploaded Invoice</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Uploaded Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/ACTUAL_FILE_IDS__c.field-meta.xml
<CustomField>
    <fullName>ACTUAL_FILE_IDS__c</fullName>
    <description>TEMP</description>
    <label>ACTUAL FILE IDS</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/DELTA_FILE_IDS__c.field-meta.xml
<CustomField>
    <fullName>DELTA_FILE_IDS__c</fullName>
    <label>DELTA FILE IDS</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/File_Mistmatch__c.field-meta.xml
<CustomField>
    <fullName>File_Mistmatch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>File Mismatch</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Action Required</label>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Upload Failed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Ready for Upload</fullName>
            </value>
            <value>
                <fullName>DO NOT PAY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Uploaded_Files_Long__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_Files_Long__c</fullName>
    <label>Uploaded Files</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/icBatchContractorInvoices.cls
global class icBatchContractorInvoices implements Database.Batchable<sObject> {

	icLogicAttachment.IClass documentLogic = (icLogicAttachment.IClass) icObjectFactory.GetSingletonInstance('icLogicAttachment');
	icLogicInvoice.IClass invoiceLogic = (icLogicInvoice.IClass) icObjectFactory.GetSingletonInstance('icLogicInvoice');

	global Database.QueryLocator start(Database.BatchableContext context) {

		return Database.getQueryLocator('SELECT Id, File_Mistmatch__c, Uploaded_Files_Long__c, Status__c FROM Contractor_Invoice__c ');
	}

	global void execute(Database.BatchableContext context, List<Contractor_Invoice__c> scope) {
		List<String> listInvoiceIds = new List<String>();

		for(Contractor_Invoice__c thisInvoice : scope) {
			listInvoiceIds.add(thisInvoice.Id);
		}

		List<ContentDocumentLink> relatedDocuments = documentLogic.getContentDocumentByRelatedRecordIds(listInvoiceIds);
		Map<String, List<ContentDocumentLink>> mapListDocumentsByInvoiceId = documentLogic.getMapListDocumentsByInvoiceId(relatedDocuments);

		system.debug('invoices ===> ' + scope);

		for(Contractor_Invoice__c thisInvoice : scope) {
			String actualFileIds = '';
			String deltaFileIds = '';

			thisInvoice.File_Mistmatch__c = false;

			system.debug('thisInvoice ===> ' + thisInvoice);

			List<ContentDocumentLink> thisInvoiceRelatedDocs = mapListDocumentsByInvoiceId.get(thisInvoice.Id);
			system.debug('thisInvoiceRelatedDocs ===> ' + thisInvoiceRelatedDocs);

			if(thisInvoiceRelatedDocs == null) {
				system.debug('thisInvoiceRelatedDocs is null');

				if(thisInvoice.Uploaded_Files_Long__c != null) {
					thisInvoice.File_Mistmatch__c = true;
				}
			}
			else
			{

				system.debug('thisInvoiceRelatedDocs is not null');

				if(thisInvoice.Uploaded_Files_Long__c == null) {
					thisInvoice.File_Mistmatch__c = true;
				} /*else {*/

				Set<Id> thisInvoiceRelatedDocIds = new Set<Id>();
				List<String> thisInvoiceRelatedDocStrings = new List<String>();

				if(thisInvoice.Uploaded_Files_Long__c != null){
					thisInvoice.Uploaded_Files_Long__c = thisInvoice.Uploaded_Files_Long__c.replaceAll(' ', '');
					thisInvoiceRelatedDocStrings = thisInvoice.Uploaded_Files_Long__c.split(',');
				}

				for(String tmpStrId : thisInvoiceRelatedDocStrings ){
					//try {
						Id tmpId = tmpStrId;
						thisInvoiceRelatedDocIds.add(tmpId);
					/*}
					catch (Exception ex){
						system.debug('Error processin id ===> ' + tmpStrId);
					}*/
				}

				for(ContentDocumentLink thisDoc : thisInvoiceRelatedDocs) {
					actualFileIds += thisDoc.ContentDocumentId + ', ';
					if(!thisInvoiceRelatedDocIds.contains(thisDoc.ContentDocumentId)) {
						thisInvoice.File_Mistmatch__c = true;
						deltaFileIds += thisDoc.ContentDocumentId + ', ';
					}
				}

			}

			if(thisInvoice.Status__c == 'Uploaded' || thisInvoice.Status__c == 'Ready for Upload' || thisInvoice.Status__c == 'Draft' ){
				system.debug('invoice in status uploaded or ready for upload');
				thisInvoice.File_Mistmatch__c = false;
				thisInvoice.Uploaded_Files_Long__c = actualFileIds;
				thisInvoice.ACTUAL_FILE_IDS__c = actualFileIds;
				thisInvoice.DELTA_FILE_IDS__c = '';
			}
			else {
				thisInvoice.ACTUAL_FILE_IDS__c = actualFileIds;
				thisInvoice.DELTA_FILE_IDS__c = deltaFileIds;
			}

		}

		invoiceLogic.updateInvoices(scope);
	}

	global void finish(Database.BatchableContext context) {
	}
}