ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/Contractor_Invoice__c.object-meta.xml
<CustomObject>
    <label>Uploaded Invoice</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Uploaded Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <label>Date of Upload</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Name/Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Rebate_Program_Formula__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Program_Formula__c</fullName>
    <formula>IF( NOT(ISBLANK(TEXT(Rebate_Program_CA__c))), TEXT(Rebate_Program_CA__c),
IF(NOT(ISBLANK(TEXT(Rebate_Program_US__c))), TEXT(Rebate_Program_US__c),
IF(NOT(ISBLANK(TEXT(Rebate_Program_CRC_c__c))), TEXT( Rebate_Program_CRC_c__c), NULL)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rebate Program</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Contractor_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Action Required</label>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Upload Failed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Ready for Upload</fullName>
            </value>
            <value>
                <fullName>DO NOT PAY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Repository/Claims/force-app/main/default/classes/icRepoContractorInvoice.cls
/**
* Created by Francois Poirier on 2019-11-18.
*/

public with sharing class icRepoContractorInvoice implements icIClass {
    
    public Object GetInstance() {
        return new Impl();
    }
    
    public Interface IClass {
        void saveContractorInvoice(Contractor_Invoice__c invoice);
        Contractor_Invoice__c getContractorInvoiceById(Id contractorInvoiceId);
    }
    
    public class Impl implements IClass {
        
        public void saveContractorInvoice(Contractor_Invoice__c invoice){
            upsert invoice;
        }
        
        public Contractor_Invoice__c getContractorInvoiceById(Id contractorInvoiceId){
            Contractor_Invoice__c invoice = new Contractor_Invoice__c();
            invoice = [
                SELECT  Id,
                Name,
                Status__c,
                Invoice_Date__c,
                Invoice_Number__c,
                Rebate_Program_Formula__c
                FROM    Contractor_Invoice__c
                WHERE   Id =: contractorInvoiceId
                LIMIT   1
            ];
            
            return invoice;
        }
    }   
}