ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/EU_Price_Agreement__c.object-meta.xml
<CustomObject>
    <label>Price Header</label>
    <nameField>
        <displayFormat>PA-{YY}-{0000000}</displayFormat>
        <label>Price Header ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Price_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/EU_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Contract_Number__c</fullName>
    <externalId>true</externalId>
    <label>Contract Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Item__c/EU_Price_Item__c.object-meta.xml
<CustomObject>
    <label>Price Line</label>
    <nameField>
        <displayFormat>PI-{YY}-{0000000}</displayFormat>
        <label>Price Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Item__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Price_List_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Item__c/fields/EU_Header_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Contract_Number__c</fullName>
    <label>Contract Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Item__c/fields/EU_Pricing_Agreement__c.field-meta.xml
<CustomField>
    <fullName>EU_Pricing_Agreement__c</fullName>
    <label>Price Header</label>
    <referenceTo>EU_Price_Agreement__c</referenceTo>
    <relationshipLabel>Price Lines</relationshipLabel>
    <relationshipName>Price_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/PriceItemService.cls
/**
 * Created by Gerard van Kempen on 2019-12-23.
 * 2019 (C) 4C NV, Mechelen Belgium.
 * Last modified as part of project 'IKO SFDC'.
 */

/**
* @author Gerard van Kempen, 4C NV
* @date 2019
*
* @group Integration Services
*
* @description PriceItemService provides methods to link Pricing Agreements and Price Items.
*/

public class PriceItemService {

    /*******************************************************************************************************************
    * @description Link Price Items to the appropriate Pricing Agreements with normal matching rules.
    * @param pricingAgreements a List of EU_Price_Agreement__c objects to be referenced
    * @param priceItems a List of EU_Price_Item__c objects to be linked
    * @return a Boolean indicating whether or not all Invoice Lines have been linked correctly (true), or not (false)
    * @example
    * Boolean priceItemsLinkedOK = (new PriceItemService()).relatePriceItemsToPricingAgreements(pricingAgreements, priceItems);
    */

    public Boolean relatePriceItemsToPricingAgreements(List<EU_Price_Agreement__c> pricingAgreements, List<EU_Price_Item__c> priceItems) {
        Integer matches = 0;
        // TODO: optimize algorithm
        for(EU_Price_Agreement__c pricingAgreement : pricingAgreements) {
            for(EU_Price_Item__c priceItem : priceItems) {
                if(
                    pricingAgreement.EU_Contract_Number__c == priceItem.EU_Header_Contract_Number__c
                    && pricingAgreement.AccountId__c == priceItem.AccountId__c
                ) {
                    system.debug('Matched record: ' + pricingAgreement.Id);
                    priceItem.EU_Pricing_Agreement__c = pricingAgreement.Id;
                    matches++;
                }
            }
        }

        final Boolean allPriceItemsHandled = (matches == priceItems.size());
        if(!allPriceItemsHandled) {
            System.debug(LoggingLevel.ERROR, 'could not link all price items to an agreement, or a price item has been multi-assigned');
        }

        return allPriceItemsHandled;
    }
}