ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intel_Report_Role__c/Intel_Report_Role__c.object-meta.xml
<CustomObject>
    <label>Intel Report Role</label>
    <nameField>
        <label>Intel Report Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intel Report Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intel_Report_Role__c/fields/Parent_Role__c.field-meta.xml
<CustomField>
    <fullName>Parent_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Role</label>
    <referenceTo>Intel_Report_Role__c</referenceTo>
    <relationshipLabel>Child Roles</relationshipLabel>
    <relationshipName>Intel_Report_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intel_Report_User__c/Intel_Report_User__c.object-meta.xml
<CustomObject>
    <label>Intel Report User</label>
    <nameField>
        <label>Intel Report User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intel Report Users</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intel_Report_User__c/fields/IKO_User__c.field-meta.xml
<CustomField>
    <fullName>IKO_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Only Salesforce users can create Intel reports, but other IKO employees may receive the email distribution.  This lookup will help set the Intel User field based on the user who is creating the record</description>
    <label>IKO User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Intel_Report_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intel_Report_Users_by_Role__c/Intel_Report_Users_by_Role__c.object-meta.xml
<CustomObject>
    <label>Intel Report User by Role</label>
    <nameField>
        <displayFormat>IRUR-{000}</displayFormat>
        <label>Intel Report User by Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intel Report Users by Role</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intel_Report_Users_by_Role__c/fields/Intel_Report_Role__c.field-meta.xml
<CustomField>
    <fullName>Intel_Report_Role__c</fullName>
    <label>Intel Report Role</label>
    <referenceTo>Intel_Report_Role__c</referenceTo>
    <relationshipLabel>Intel Report Users by Role</relationshipLabel>
    <relationshipName>Intel_Report_Users_by_Role</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intel_Report_Users_by_Role__c/fields/Intel_Report_User__c.field-meta.xml
<CustomField>
    <fullName>Intel_Report_User__c</fullName>
    <label>Intel Report User</label>
    <referenceTo>Intel_Report_User__c</referenceTo>
    <relationshipLabel>Intel Report Users by Role</relationshipLabel>
    <relationshipName>Intel_Report_Users_by_Role</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intel_Report_Users_by_Role__c/fields/Role_Type__c.field-meta.xml
<CustomField>
    <fullName>Role_Type__c</fullName>
    <inlineHelpText>Sales Reps will be able to send reports, but only those listed as Managers will receive distribution</inlineHelpText>
    <label>Role Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Rep</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/intelEmailRecordType__mdt/intelEmailRecordType__mdt.object-meta.xml
<CustomObject>
    <label>intelEmailRecordType</label>
    <pluralLabel>intelEmailRecordTypes</pluralLabel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/intelEmailRecordType__mdt/fields/RecordTypeId__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>RecordTypeId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report__c/Intelligence_Report__c.object-meta.xml
<CustomObject>
    <label>Intelligence Report</label>
    <nameField>
        <displayFormat>Intel-{000}</displayFormat>
        <label>Intelligence Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intelligence Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report__c/fields/Intel_Report_User__c.field-meta.xml
<CustomField>
    <fullName>Intel_Report_User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Intel Report User</label>
    <referenceTo>Intel_Report_User__c</referenceTo>
    <relationshipLabel>Intelligence Reports</relationshipLabel>
    <relationshipName>Intelligence_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report__c/fields/Report_Type__c.field-meta.xml
<CustomField>
    <fullName>Report_Type__c</fullName>
    <description>Only used for Product Issues reports</description>
    <label>Report Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report_Line_Item__c/Intelligence_Report_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Intelligence Report Line Item</label>
    <nameField>
        <displayFormat>IRLI-{000}</displayFormat>
        <label>Intelligence Report Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intelligence Report Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report_Line_Item__c/fields/Intelligence_Report__c.field-meta.xml
<CustomField>
    <fullName>Intelligence_Report__c</fullName>
    <label>Intelligence Report</label>
    <referenceTo>Intelligence_Report__c</referenceTo>
    <relationshipLabel>Intelligence Report Line Items</relationshipLabel>
    <relationshipName>Intelligence_Report_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Intelligence_Report_Line_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales Overview</fullName>
            </value>
            <value>
                <fullName>New Customer Activity</fullName>
            </value>
            <value>
                <fullName>Competitive Activity</fullName>
            </value>
            <value>
                <fullName>Design Community Activity</fullName>
            </value>
            <value>
                <fullName>Contractor Activity</fullName>
            </value>
            <value>
                <fullName>Competitive Market Activity</fullName>
            </value>
            <value>
                <fullName>Competitors Product Evaluation</fullName>
            </value>
            <value>
                <fullName>Target Account Info (Dealer/Roofer)</fullName>
            </value>
            <value>
                <fullName>Roofer Intel</fullName>
            </value>
            <value>
                <fullName>Dealer Intel</fullName>
            </value>
            <value>
                <fullName>IKO Product Intel</fullName>
            </value>
            <value>
                <fullName>Competitor Product Intel</fullName>
            </value>
            <value>
                <fullName>Recommendations</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Competitors Product Information</fullName>
                <isActive>false</isActive>
                <label>Competitors Product Information</label>
            </value>
            <value>
                <fullName>Product Quality Information</fullName>
                <isActive>false</isActive>
                <label>Product Quality Information</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
	public static Intel_Report_User__c createIntelReportUser(String Name, String Email, Id IKOuser)
    {
        Intel_Report_User__c IRU = new Intel_Report_User__c(
            Name=Name,
            Email_Address__c=Email,
            IKO_User__c=IKOuser
        );
        Insert IRU;
        return IRU;
    }
    static public Intel_Report_Role__c createIntelReportRole(String Name, ID ParentId)
    {
        Intel_Report_Role__c IRR = new Intel_Report_Role__c(
            Name = Name,
            Parent_Role__c = ParentId
        );
        insert IRR;
        return IRR;
    }
    public static Intelligence_Report__c createIntelligenceReport(String RecordTypeName,ID IntelReportUser, String ReportType,String Product)
    {
        system.debug([Select ID, RecordTypeId__c from intelEmailRecordType__mdt].size());
        ID RecordTypeID = [Select ID, RecordTypeId__c from intelEmailRecordType__mdt where Label=:RecordTypeName].get(0).RecordTypeId__c;
        Intelligence_Report__c IR = new Intelligence_Report__c(Intel_Report_User__c=IntelReportUser,
                                                              Product__c='Test Product',
                                                              Report_Type__c=ReportType,
                                                              RecordTypeId=RecordTypeID);
        insert IR;
        system.debug('IR was created');
        system.debug(IR.Id);
        return IR;
    }
    public static User createUser(String ProfileName, String LastName, String Email, Id ManagersId)
    {
        String alias = String.valueOf(System.currentTimeMillis());
        alias = alias.substring(alias.length() - 8,alias.length());
        User u = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = :ProfileName].Id,
            LastName = LastName,
            Email = Email,
            Username = 'puser000@amamama.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = alias,
            ManagerId = ManagersId,
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
        );
        Insert u;
        return u;
    }
    public static Intel_Report_Users_by_Role__c createIntelReportUsersbyRole(ID IntelReportRole, ID IntelReportUser, String RoleType)
    {
        Intel_Report_Users_by_Role__c IRUR = new Intel_Report_Users_by_Role__c(Intel_Report_Role__c = IntelReportRole,
                                                                               Intel_Report_User__c = IntelReportUser,
                                                                               Role_Type__c = RoleType);
        insert IRUR;
        return IRUR;
    }
    public static Intelligence_Report_Line_Item__c createIntelligenceReportLineItem(ID IntelligenceReportId, String LineItemType)
    {
		Intelligence_Report_Line_Item__c IRLI = new Intelligence_Report_Line_Item__c(Intelligence_Report__c=IntelligenceReportId,Type__c=LineItemType);
        insert IRLI;
        return IRLI;
    }
    
    public static ContentDocument getContentDocument()
    {
        ContentDocument CD ;
        Integer sizeList = [Select ID from ContentDocument].size();
        system.debug(sizeList);
        return CD;
    }
    
    public static ContentVersion createContentVersion()
    {
        ContentVersion CV = new ContentVersion(Title = 'Penguins',
                                               PathOnClient = 'Penguins.jpg',
                                               VersionData = Blob.valueOf('Test Content'),
                                               IsMajorVersion = true);
        insert CV;
        return CV;
    }
    public static Attachment createAttachment(ID objectId)
    {
        
        Attachment attach=new Attachment(   	
            Name='Unit Test Attachment',
            body=Blob.valueOf('Unit Test Attachment Body'),
            parentId=objectId);
        insert attach;
        return attach;
    }
        
    public static ContentDocumentLink createContentDocumentLink(ID IntelligenceReportId, Id ContentDocumentId )
    {
		ContentDocumentLink CDL = new ContentDocumentLink();
        insert CDL;
        return CDL;
    }
}