ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/CalendarEvent__c.object-meta.xml
<CustomObject>
    <label>Calendar Event</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Calendar Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calendar Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/ContentLanguage__c.field-meta.xml
<CustomField>
    <fullName>ContentLanguage__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Operating_Languages</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/Description_Long_Txt_Area__c.field-meta.xml
<CustomField>
    <fullName>Description_Long_Txt_Area__c</fullName>
    <label>Description</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/Publish_in__c.field-meta.xml
<CustomField>
    <fullName>Publish_in__c</fullName>
    <description>This field is use to filter the calendar event shown in the Calendar , Calendar list Lighning compoments  on communities portal of the logued user.</description>
    <inlineHelpText>Please Select in which community you want to publish your calendar event. Multi selection is alowed.</inlineHelpText>
    <label>Publish in</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CommunityName</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tiers</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CommunitySiteNameConfiguration__mdt/CommunitySiteNameConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>This metadata contains the information related to the Site Name Community and help to bind the value to the CommunityName global setvalue used in Calendar event and Whatshappening configuration.</description>
    <label>Community Site Name Configuration</label>
    <pluralLabel>Community Site Name Configurations</pluralLabel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CommunitySiteNameConfiguration__mdt/fields/CommunityNameGlobalSetValue__c.field-meta.xml
<CustomField>
    <fullName>CommunityNameGlobalSetValue__c</fullName>
    <description>This value must match the API NAME Value of the corresponding Picklist list Item in the global value set named CommunityName</description>
    <label>CommunityNameGlobalSetValue</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/Tier__c.object-meta.xml
<CustomObject>
    <description>Object to manage Tier information (e.g. maximum &amp; minimum amount of squares before Tier change).</description>
    <label>Tier</label>
    <nameField>
        <displayFormat>Tier {0}</displayFormat>
        <label>Tier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icTestCtrlUiCalendarEvent.cls
/**
 * Created by Francois Poirier on 2019-04-17.
 */

@isTest
public with sharing class icTestCtrlUiCalendarEvent {
    static String descriptionEvent;
    static String descriptionMajorEvent;

    static void InitTestWithoutData(){

        List<CalendarEvent__c> newEvents = new List<CalendarEvent__c>();
        List<CalendarEvent__c> newMajorEvents = new List<CalendarEvent__c>();
        
        CommunitySiteNameConfiguration__mdt config = new CommunitySiteNameConfiguration__mdt();
        config.CommunityNameGlobalSetValue__c = 'IKOROOFPRO_C';

        icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicEventCalendar', new icLogicEventCalendarMock());
        icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicConfig', new icLogicConfigMock());
        icTestMockUtilities.Tracer.SetReturnValue('icLogicEventCalendarMock', 'getActiveCalendarEventsByDateRangeTierCommunityName', newEvents);
        icTestMockUtilities.Tracer.SetReturnValue('icLogicEventCalendarMock', 'getTopEventsByLanguageAndTier', newMajorEvents);
        icTestMockUtilities.Tracer.SetReturnValue('icLogicEventCalendarMock', 'getNext3EventsForTier', newEvents);
        icTestMockUtilities.Tracer.SetReturnValue('icLogicConfigMock', 'getCommunitySiteNameConfigByName', config);
    }

    static void InitTestWithData(){
        CalendarEvent__c newEvent = new CalendarEvent__c();
        CalendarEvent__c newMajorEvent = new CalendarEvent__c();
        List<CalendarEvent__c> newEvents = new List<CalendarEvent__c>();
        List<CalendarEvent__c> newMajorEvents = new List<CalendarEvent__c>();

        newEvent.Active__c = true;
        newEvent.Tier__c = '1';
        newEvent.ContentLanguage__c = 'English';
        newEvent.Publish_in__c = 'IKOROOFPRO_C';
        newEvent.Description_Long_Txt_Area__c = icTestHelperUtility.generateRandomString(100);
        descriptionEvent = newEvent.Description_Long_Txt_Area__c;
        newEvent.EventDate__c = Date.today();

        newEvents.add(newEvent);

        newMajorEvent.Active__c = true;
        newMajorEvent.Tier__c = '1';
        newMajorEvent.ContentLanguage__c = 'English';
        newMajorEvent.Publish_in__c = 'IKOROOFPRO_C';
        newMajorEvent.Description_Long_Txt_Area__c = icTestHelperUtility.generateRandomString(100);
        descriptionMajorEvent = newMajorEvent.Description_Long_Txt_Area__c;
        newMajorEvent.EventDate__c = Date.today();

        newMajorEvents.add(newMajorEvent);
        CommunitySiteNameConfiguration__mdt config = new CommunitySiteNameConfiguration__mdt();
        config.CommunityNameGlobalSetValue__c = 'IKOROOFPRO_C';

        icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicEventCalendar', new icLogicEventCalendarMock());
        icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicConfig', new icLogicConfigMock());
        icTestMockUtilities.Tracer.SetReturnValue('icLogicEventCalendarMock', 'getActiveCalendarEventsByDateRangeTierCommunityName', newEvents);
        icTestMockUtilities.Tracer.SetReturnValue('icLogicEventCalendarMock', 'getTopEventsByLanguageAndTier', newMajorEvents);
        icTestMockUtilities.Tracer.SetReturnValue('icLogicEventCalendarMock', 'getNext3EventsForTier', newEvents);
        icTestMockUtilities.Tracer.SetReturnValue('icLogicConfigMock', 'getCommunitySiteNameConfigByName', config);
    }

    @isTest
    static void testgetEventsByDateRange_WhitoutData(){
        InitTestWithoutData();
        Map<String, List<icDtoCalendarEvent>> eventsEmpty = icCtrlUiCalendarEvent.getEventsByDateRange(String.valueOf(Date.today()), String.valueOf(Date.today()));
    }

    @isTest
    static void testgetEventsByDateRange_WithData(){
        InitTestWithData();
        Map<String, List<icDtoCalendarEvent>> events = icCtrlUiCalendarEvent.getEventsByDateRange(String.valueOf(Date.today()), String.valueOf(Date.today()));
    }

    @isTest
    static void testGetMonthNamesArray(){
        icCtrlUiCalendarEvent.getMonthNamesArray();
    }

}