ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/CalendarEvent__c.object-meta.xml
<CustomObject>
    <label>Calendar Event</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Calendar Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calendar Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/ContentLanguage__c.field-meta.xml
<CustomField>
    <fullName>ContentLanguage__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Operating_Languages</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/Description_Long_Txt_Area__c.field-meta.xml
<CustomField>
    <fullName>Description_Long_Txt_Area__c</fullName>
    <label>Description</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/External_Link__c.field-meta.xml
<CustomField>
    <fullName>External_Link__c</fullName>
    <label>External Link</label>
    <type>Url</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/Internal_Community_Link__c.field-meta.xml
<CustomField>
    <fullName>Internal_Community_Link__c</fullName>
    <label>Internal Community Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/Internal_Mobile_Link__c.field-meta.xml
<CustomField>
    <fullName>Internal_Mobile_Link__c</fullName>
    <label>Internal Mobile Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/Link_Type__c.field-meta.xml
<CustomField>
    <fullName>Link_Type__c</fullName>
    <label>Link Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>icLinkTypes</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/Publish_in__c.field-meta.xml
<CustomField>
    <fullName>Publish_in__c</fullName>
    <description>This field is use to filter the calendar event shown in the Calendar , Calendar list Lighning compoments  on communities portal of the logued user.</description>
    <inlineHelpText>Please Select in which community you want to publish your calendar event. Multi selection is alowed.</inlineHelpText>
    <label>Publish in</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CommunityName</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tiers</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/Tier__c.object-meta.xml
<CustomObject>
    <description>Object to manage Tier information (e.g. maximum &amp; minimum amount of squares before Tier change).</description>
    <label>Tier</label>
    <nameField>
        <displayFormat>Tier {0}</displayFormat>
        <label>Tier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icRepoEventCalendar.cls
/**
 * Created by Francois Poirier on 2019-04-10.
 */

public with sharing class icRepoEventCalendar implements icIClass {

    public Object GetInstance() {
        return new Impl();
    }

    public Interface IClass {
        List<CalendarEvent__c> getActiveCalendarEventsByDateRangeTierCommunityName(Date startDate, Date endDate, String language, String tier, String communityName);
    }

    public class Impl implements IClass {

        public List<CalendarEvent__c> getActiveCalendarEventsByDateRangeTierCommunityName(Date startDate, Date endDate, String language, String tier, String communityName){

            List<CalendarEvent__c> calendarEvents = new List<CalendarEvent__c>();

            calendarEvents = [
                    SELECT  Id,
                            Active__c,
                            ContentLanguage__c,
                            //Description__c,
                            Description_Long_Txt_Area__c,
                            Email_Recipient__c,
                            EventDate__c,
                            External_Link__c,
                            Internal_Community_Link__c,
                            Internal_Mobile_Link__c,
                            Link_Label__c,
                            Link_Type__c,
                            Tier__c,
                            Title__c
                    FROM    CalendarEvent__c
                    WHERE   EventDate__c >= :startDate
                    AND     EventDate__c <= :endDate
                    AND     Active__c = true
                    AND     ContentLanguage__c = :language
                    AND     Tier__c INCLUDES(:tier)
                    AND     Publish_in__c INCLUDES(:communityName)
                    ORDER BY EventDate__c ASC
            ];

            return calendarEvents;
        }
    }
}