ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/CalendarEvent__c.object-meta.xml
<CustomObject>
    <label>Calendar Event</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Calendar Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calendar Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/Description_Long_Txt_Area__c.field-meta.xml
<CustomField>
    <fullName>Description_Long_Txt_Area__c</fullName>
    <label>Description</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/icTestMapCalendarEvent.cls
/**
 * Created by Francois Poirier on 2019-04-17.
 */

@isTest
public with sharing class icTestMapCalendarEvent {

    @isTest
    static void testMapToDto(){

        icMapCalendarEvent.IClass mapper = (icMapCalendarEvent.IClass) icObjectFactory.GetSingletonInstance('icMapCalendarEvent');

        CalendarEvent__c calendarEvent = new CalendarEvent__c();
        List<CalendarEvent__c> calendarEvents = new List<CalendarEvent__c>();
        List<icDtoCalendarEvent> dtoCalendarEvents = new List<icDtoCalendarEvent>();

        calendarEvent.Id = icTestHelperUtility.getFakeId(CalendarEvent__c.SObjectType);
        calendarEvent.EventDate__c = Date.today();
        calendarEvent.Description_Long_Txt_Area__c = icTestHelperUtility.generateRandomString(100);


        calendarEvents.add(calendarEvent);

        dtoCalendarEvents = mapper.mapToDto(calendarEvents);

        system.assertEquals(calendarEvents.size(), dtoCalendarEvents.size());
        system.assertEquals(calendarEvents[0].Description_Long_Txt_Area__c, dtoCalendarEvents[0].Description);

    }
}