ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/CalendarEvent__c.object-meta.xml
<CustomObject>
    <label>Calendar Event</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Calendar Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calendar Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/ContentLanguage__c.field-meta.xml
<CustomField>
    <fullName>ContentLanguage__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Operating_Languages</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/Description_Long_Txt_Area__c.field-meta.xml
<CustomField>
    <fullName>Description_Long_Txt_Area__c</fullName>
    <label>Description</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/Publish_in__c.field-meta.xml
<CustomField>
    <fullName>Publish_in__c</fullName>
    <description>This field is use to filter the calendar event shown in the Calendar , Calendar list Lighning compoments  on communities portal of the logued user.</description>
    <inlineHelpText>Please Select in which community you want to publish your calendar event. Multi selection is alowed.</inlineHelpText>
    <label>Publish in</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CommunityName</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tiers</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/Tier__c.object-meta.xml
<CustomObject>
    <description>Object to manage Tier information (e.g. maximum &amp; minimum amount of squares before Tier change).</description>
    <label>Tier</label>
    <nameField>
        <displayFormat>Tier {0}</displayFormat>
        <label>Tier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Repository/Claims/force-app/main/default/classes/icTestLogicEventCalendar.cls
/**
 * Created by Francois Poirier on 2019-04-17.
 */

@isTest
public with sharing class icTestLogicEventCalendar {

    static String descriptionEvent;
    static String descriptionMajorEvent;

    static void setup(){

        CalendarEvent__c newEvent = new CalendarEvent__c();
        CalendarEvent__c newMajorEvent = new CalendarEvent__c();
        List<CalendarEvent__c> newEvents = new List<CalendarEvent__c>();
        List<CalendarEvent__c> newMajorEvents = new List<CalendarEvent__c>();

        newEvent.Active__c = true;
        newEvent.Tier__c = '1';
        newEvent.ContentLanguage__c = 'English';
        newEvent.Publish_in__c = 'IKOROOFPRO_C';
        newEvent.Description_Long_Txt_Area__c = icTestHelperUtility.generateRandomString(100);
        descriptionEvent = newEvent.Description_Long_Txt_Area__c;
        newEvent.EventDate__c = Date.today().addDays(1);

        newEvents.add(newEvent);

        newMajorEvent.Active__c = true;
        newMajorEvent.Tier__c = '1';
        newMajorEvent.ContentLanguage__c = 'English';
        newEvent.Publish_in__c = 'IKOROOFPRO_C';
        newMajorEvent.Description_Long_Txt_Area__c = icTestHelperUtility.generateRandomString(100);
        descriptionMajorEvent = newMajorEvent.Description_Long_Txt_Area__c;
        newMajorEvent.EventDate__c = Date.today();

        newMajorEvents.add(newMajorEvent);


        icTestMockUtilities.Mocker.SetMockSingletonInstance('icRepoEventCalendar', new icRepoEventCalendarMock());
        icTestMockUtilities.Tracer.SetReturnValue('icRepoEventCalendarMock', 'getActiveCalendarEventsByDateRangeTierCommunityName', newEvents);
        icTestMockUtilities.Tracer.SetReturnValue('icRepoEventCalendarMock', 'getNext3EventsForTier', newEvents);
        icTestMockUtilities.Tracer.SetReturnValue('icRepoEventCalendarMock', 'getTopEventsByLanguageAndTier', newMajorEvents);

    }

    @isTest
    static void testgetActiveCalendarEventsByDateRangeTierCommunityName(){

        setup();
        icLogicEventCalendar.IClass logic = (icLogicEventCalendar.IClass) icObjectFactory.GetSingletonInstance('icLogicEventCalendar');
        List<CalendarEvent__c> eventsFromLogic = new List<CalendarEvent__c>();
        eventsFromLogic = logic.getActiveCalendarEventsByDateRangeTierCommunityName(Date.today(), Date.today(), 'English', '1', 'IKOROOFPRO_C');

        system.assertEquals(descriptionEvent, eventsFromLogic[0].Description_Long_Txt_Area__c);
    }
   
}