ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/CalendarEvent__c.object-meta.xml
<CustomObject>
    <label>Calendar Event</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Calendar Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calendar Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/ContentLanguage__c.field-meta.xml
<CustomField>
    <fullName>ContentLanguage__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Operating_Languages</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/Description_Long_Txt_Area__c.field-meta.xml
<CustomField>
    <fullName>Description_Long_Txt_Area__c</fullName>
    <label>Description</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/Link_Type__c.field-meta.xml
<CustomField>
    <fullName>Link_Type__c</fullName>
    <label>Link Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>icLinkTypes</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/Publish_in__c.field-meta.xml
<CustomField>
    <fullName>Publish_in__c</fullName>
    <description>This field is use to filter the calendar event shown in the Calendar , Calendar list Lighning compoments  on communities portal of the logued user.</description>
    <inlineHelpText>Please Select in which community you want to publish your calendar event. Multi selection is alowed.</inlineHelpText>
    <label>Publish in</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CommunityName</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tiers</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/Tier__c.object-meta.xml
<CustomObject>
    <description>Object to manage Tier information (e.g. maximum &amp; minimum amount of squares before Tier change).</description>
    <label>Tier</label>
    <nameField>
        <displayFormat>Tier {0}</displayFormat>
        <label>Tier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Repository/Claims/force-app/main/default/classes/icTestRepoEventCalendar.cls
/**
 * Created by Francois Poirier on 2019-04-17.
 */

@isTest
public with sharing class icTestRepoEventCalendar {

    static icRepoEventCalendar.IClass repo = (icRepoEventCalendar.IClass) icObjectFactory.GetSingletonInstance('icRepoEventCalendar');

    @isTest
    static void testgetActiveCalendarEventsByDateRangeTierCommunityName(){

        CalendarEvent__c testEvent = new CalendarEvent__c();
        testEvent.EventDate__c = Date.today();
        testEvent.Description_Long_Txt_Area__c = 'test event';
        testEvent.Active__c = true;
        testEvent.ContentLanguage__c = 'English';
        testEvent.Tier__c = '1';
        testEvent.Link_Type__c = 'No Link';
        testEvent.Title__c = 'test Event';
        testEvent.Publish_in__C = 'IKOROOFPRO_C';
        
        insert testEvent;


        List<CalendarEvent__c> testEventsFromRepoWithResult  = repo.getActiveCalendarEventsByDateRangeTierCommunityName(Date.today(), Date.today(), 'English', '1','IKOROOFPRO_C');
        List<CalendarEvent__c> testEventsFromRepoWithout  = repo.getActiveCalendarEventsByDateRangeTierCommunityName(Date.today(), Date.today(), 'English', '1','FORCE_NO_RESULT');
        
        system.assert(testEventsFromRepoWithResult.size()>0);
        system.assertEquals(testEventsFromRepoWithout.size(), 0);

    }

}