ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Account_Owner_Region__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_Region__c</fullName>
    <formula>IF(AND(BEGINS(Owner.Profile.Name, &apos;USRS&apos;), CONTAINS( Owner.UserRole.Name , &apos;Midstates&apos;)), &quot;Midstates&quot;,
IF(AND(BEGINS(Owner.Profile.Name, &apos;USRS&apos;), CONTAINS( Owner.UserRole.Name , &apos;West&apos;)), &quot;West&quot;,
IF(AND(BEGINS(Owner.Profile.Name, &apos;USRS&apos;), CONTAINS( Owner.UserRole.Name , &apos;North&apos;)), &quot;North&quot;,
IF(AND(BEGINS(Owner.Profile.Name, &apos;USRS&apos;), CONTAINS( Owner.UserRole.Name , &apos;South&apos;)), &quot;South&quot;,
IF(AND(BEGINS(Owner.Profile.Name, &apos;USRS&apos;), CONTAINS( Owner.UserRole.Name , &apos;Leetland&apos;)), &quot;Leetland&quot;,
IF(OR( TEXT(BillingCountryCode) = &apos;US&apos;, BEGINS(Owner.Profile.Name, &apos;USRS&apos;)), &quot;US&quot;,
&quot;&quot;))))))</formula>
    <label>Account Owner Region</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Contractor.recordType-meta.xml
<RecordType>
    <fullName>Contractor</fullName>
    <active>true</active>
    <label>Contractor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Account_Owner_Region__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_Region__c</fullName>
    <description>Populated by flow with the Region for the owner of the Account (= part of the User&apos;s role name).</description>
    <label>Account Owner Region</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>Used to track the high level stages of the Claim</description>
    <label>Claim Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting Docs</fullName>
            </value>
            <value>
                <fullName>In Kankakee</fullName>
            </value>
            <value>
                <fullName>In Lab</fullName>
            </value>
            <value>
                <fullName>File Preparation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contractor Account which a Residential or Commercial Claim is related to</description>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.
(Should be of Record Type - Contractor / US Contractor / Residential Account, with Legacy Claim Account False)</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contractor, US Contractor, Residential Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Legacy_Claim_Account__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contractor Cases</relationshipLabel>
    <relationshipName>ContractorCases</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Contractor_Owner_Region__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Owner_Region__c</fullName>
    <description>Populated by flow with the Region for the owner of the Contractor Account (= part of the User&apos;s role name).</description>
    <label>Contractor Owner Region</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Distributor for a Residential or Commercial Claim</description>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Residential Account, Distributor, US Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Legacy_Claim_Account__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Distributor Cases</relationshipLabel>
    <relationshipName>DistributorCases</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Distributor_Owner_Region__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Owner_Region__c</fullName>
    <description>Populated by flow with the Region for the owner of the Distributor Account (= part of the User&apos;s role name).</description>
    <label>Distributor Owner Region</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <description>This field captures the language for the case. The documents generated for cases will be based on this language field.</description>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Operating_Languages</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warranty_and_Claim_Sectors</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Settlement_Type__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Type__c</fullName>
    <description>Indicates what type of Settlement this will be, which will have downstream impact on calclulations</description>
    <label>Settlement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>Default</label>
            </value>
            <value>
                <fullName>Hand Seal</fullName>
            </value>
            <value>
                <fullName>Cash Settlement</fullName>
            </value>
            <value>
                <fullName>Cash Settlement - Material Only</fullName>
            </value>
            <value>
                <fullName>Goodwill</fullName>
            </value>
            <value>
                <fullName>Money or Material Offer</fullName>
            </value>
            <value>
                <fullName>Manual Calculation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <description>This field displays the unit of measure of the product.</description>
    <formula>TEXT( Product__r.Unit_of_Measure__c )</formula>
    <label>Unit of Measure</label>
    <type>Text</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/CaseSharingRulesUtility_Test.cls
@isTest
public class CaseSharingRulesUtility_Test {
	
    @testSetup static void setupTestData() {
        initData();
        initUser();
    }

    @future
    private static void initUser() {
        User salesManagerUser = TestFactory.createUser('Unit', 'Tests', 'salesrsmmgr@iko.com', 'salesrsmmgr@iko.com', 'USRS Manager',
                'RSM West', 'salesmgr', 'GMT', 'en_US', 'UTF-8', 'en_US', null, null, false);
        insert salesManagerUser;
    }
    
    private static void initData() {

        Id baRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Building Location').getRecordTypeId();
        Id conRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Contractor').getRecordTypeId();
        Id disRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Distributor').getRecordTypeId();
        //Id ccRt = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Claim').getRecordTypeId();
        List<Account> toInsertAccounts = new List<Account>();

        toInsertAccounts.addAll(TestFactory.createAccounts(baRt, 'AccountCA', '9 King St E', 'Toronto', 'ON', 'CA', 'M4S 2H4',
                'Verified', UserInfo.getUserId(), TRUE, TRUE, 1, false));
        //insert toInsertAccounts;

        toInsertAccounts.addAll(TestFactory.createAccounts(conRt, 'AccountQC', '9 King St E', 'Toronto', 'QC', 'CA', 'M4S 2H4',
                'Verified', UserInfo.getUserId(), TRUE, TRUE, 1, false));
        
		toInsertAccounts.addAll(TestFactory.createAccounts(disRt, 'AccountQC', '9 King St E', 'Toronto', 'QC', 'CA', 'M4S 2H4',
                'Verified', UserInfo.getUserId(), TRUE, TRUE, 1, false));        
        
        insert toInsertAccounts;
        
        Product2 p = new Product2(
        	Name = 'IKO CAMBRIDGE',
            Sectors__c = 'CA',
            Is_Legacy__c = false,
            Unit_of_Measure__c = 'BD'
        );
        insert p;
        
        
        //create contact
        List<Contact> con = TestFactory.createContacts(toInsertAccounts[0].Id, 'ClaimTypeServiceTest', UserInfo.getUserId(), 1, false);
        insert con;

        
    }
    
    @isTest static void testCaseRegionFields() {
        Id baRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Building Location').getRecordTypeId();
        Id conRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Contractor').getRecordTypeId();
        Id disRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Distributor').getRecordTypeId();
        Set<Id> recordTypeSet = new Set<Id>();    
        recordTypeSet.add (baRt);
        recordTypeSet.add (conRt);
        recordTypeSet.add (disRt);
        Account accountBuilding = [select Id, Account_Owner_Region__c from Account where RecordTypeId = : baRt limit 1];
        Account accountContractor = [select Id, Account_Owner_Region__c from Account where RecordTypeId = : conRt limit 1];
        Account accountDistributor = [select Id, Account_Owner_Region__c from Account where RecordTypeId = : disRt limit 1];
        /*
        List<Account> allAccounts = new List<Account>([SELECT Id, RecordTypeId, Account_Owner_Region__c FROM Account WHERE RecordTypeId IN :recordTypeSet]);
        Map<Id, Account> accountsByAccountRecordTypeId = new Map<Id, Account>();
        for(Account a : allAccounts) {
            accountsByAccountRecordTypeId.put(a.RecordTypeId, a);
        }
		*/	
		Contact contact = [select Id from Contact limit 1];        
        Case c1 = new Case(
            Description = 'Residential Claim created by Test Case',
        	RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Residential Claim').getRecordTypeId(),
            Claim_Stage__c = 'Assessment',
            Settlement_Type__c = 'Manual Calculation',
            Preferred_Language__c = 'English', 
            AccountId = accountBuilding.Id,  // accountsByAccountRecordTypeId.get(baRt).Id,
            Contractor__c = accountContractor.Id,  //accountsByAccountRecordTypeId.get(conRt).Id,
            Distributor__c =  accountDistributor.Id, //accountsByAccountRecordTypeId.get(disRt).Id,
            ContactId = contact.Id,
            Sector__c = 'CA'
        );
        //system.debug('c1: ' + c1);
        insert c1;
        
        Case cCheck		= [select Id, Account_Owner_Region__c, Contractor_Owner_Region__c, Distributor_Owner_Region__c from Case where Id = :c1.Id limit 1];
        System.assertEquals( accountBuilding.Account_Owner_Region__c, cCheck.Account_Owner_Region__c ); 
        System.assertEquals( accountContractor.Account_Owner_Region__c, cCheck.Contractor_Owner_Region__c ); 
        System.assertEquals( accountDistributor.Account_Owner_Region__c, cCheck.Distributor_Owner_Region__c ); 
        system.debug('case info: ' + cCheck);
        System.debug ('account building: ' + accountBuilding.Account_Owner_Region__c);
        System.debug ('contractor: ' + accountContractor.Account_Owner_Region__c);
        System.debug ('distributor: ' + accountDistributor.Account_Owner_Region__c);
        /*
        System.assertEquals( accountsByAccountRecordTypeId.get(baRt).Account_Owner_Region__c, cCheck.Account_Owner_Region__c ); 
        System.assertEquals( accountsByAccountRecordTypeId.get(conRt).Account_Owner_Region__c, cCheck.Contractor_Owner_Region__c ); 
        System.assertEquals( accountsByAccountRecordTypeId.get(disRt).Account_Owner_Region__c, cCheck.Distributor_Owner_Region__c ); 
        system.debug('c1: ' + cCheck);
        system.debug('account: ' + accountsByAccountRecordTypeId.get(baRt).Account_Owner_Region__c);
        system.debug('contractor: ' + accountsByAccountRecordTypeId.get(conRt).Account_Owner_Region__c);
        system.debug('distributor: ' + accountsByAccountRecordTypeId.get(disRt).Account_Owner_Region__c);
		*/
    }
    
}