ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account ID</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/EU_Company_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Company_Number__c</fullName>
    <label>Company Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/EU_Price_Agreement__c.object-meta.xml
<CustomObject>
    <label>Price Header</label>
    <nameField>
        <displayFormat>PA-{YY}-{0000000}</displayFormat>
        <label>Price Header ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Price_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/Buying_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Buying_Group_ID__c</fullName>
    <label>Buying Group ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/Category_code_4_ID__c.field-meta.xml
<CustomField>
    <fullName>Category_code_4_ID__c</fullName>
    <label>Category code 4 ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/EU_Adjustment_Detail__c.field-meta.xml
<CustomField>
    <fullName>EU_Adjustment_Detail__c</fullName>
    <label>Adjustment Detail</label>
    <type>TextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/EU_Adjustment_Detail_ID__c.field-meta.xml
<CustomField>
    <fullName>EU_Adjustment_Detail_ID__c</fullName>
    <label>Adjustment Detail ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/EU_Base_Price__c.field-meta.xml
<CustomField>
    <fullName>EU_Base_Price__c</fullName>
    <label>Base Price</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/EU_Base_Price_ID__c.field-meta.xml
<CustomField>
    <fullName>EU_Base_Price_ID__c</fullName>
    <label>Base Price ID</label>
    <type>TextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/EU_Buying_Group__c.field-meta.xml
<CustomField>
    <fullName>EU_Buying_Group__c</fullName>
    <label>Buying Group</label>
    <type>TextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/EU_Category_Code_4__c.field-meta.xml
<CustomField>
    <fullName>EU_Category_Code_4__c</fullName>
    <label>Category Code 4</label>
    <type>TextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/EU_Company_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Company_Number__c</fullName>
    <label>Company Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/EU_Company_pricing__c.field-meta.xml
<CustomField>
    <fullName>EU_Company_pricing__c</fullName>
    <label>Company Pricing</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/EU_Company_Pricing_ID__c.field-meta.xml
<CustomField>
    <fullName>EU_Company_Pricing_ID__c</fullName>
    <label>Company Pricing ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/EU_Contract_Description__c.field-meta.xml
<CustomField>
    <fullName>EU_Contract_Description__c</fullName>
    <label>Contract Description</label>
    <type>TextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/EU_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Contract_Number__c</fullName>
    <externalId>true</externalId>
    <label>Contract Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/EU_Discount__c.field-meta.xml
<CustomField>
    <fullName>EU_Discount__c</fullName>
    <label>Discount</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/EU_Discount_ID__c.field-meta.xml
<CustomField>
    <fullName>EU_Discount_ID__c</fullName>
    <label>Discount ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Price_Agreement__c/fields/EU_Price_Type__c.field-meta.xml
<CustomField>
    <fullName>EU_Price_Type__c</fullName>
    <label>Price Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/PricingAgreementSelector.cls
/**
 * Created by Gerard van Kempen on 2019-12-23.
 * 2019 (C) 4C NV, Mechelen Belgium.
 * Last modified as part of project 'IKO SFDC'.
 */

/**
* @author Gerard van Kempen, 4C NV
* @date 2019
*
* @group Integration Services
*
* @description PricingAgreementSelector provides methods to retrieve EU_Price_Agreement__c objects based on parameters.
*/

public with sharing class PricingAgreementSelector {

    /*******************************************************************************************************************
    * @description Retrieve Pricing Agreements for given Contract Numbers.
    * @param contractNumbers a Set of Strings containing Contract Numbers
    * @param accountIds a Set of Ids containing Account Ids
    * @return a List of Pricing Agreements with matching Contract Numbers
    * @example
    * List<EU_Price_Agreement__c> matchingAgreements = (new PricingAgreementSelector()).getAgreementsForContractNumbers(contractNumbers, accountIds);
    */

    public List<EU_Price_Agreement__c> getAgreementsForContractNumbers(Set<String> contractNumbers, Set<Id> accountIds) {
        List<EU_Price_Agreement__c> agreementsForContractNumbers = null;
        try {
            agreementsForContractNumbers = [
                    SELECT AccountId__c, EU_Adjustment_Detail__c, EU_Adjustment_Detail_ID__c, EU_Base_Price__c,
                            EU_Base_Price_ID__c, EU_Buying_Group__c, Buying_Group_ID__c, EU_Category_Code_4__c,
                            Category_code_4_ID__c, EU_Company_Number__c, EU_Company_pricing__c, EU_Company_Pricing_ID__c,
                            EU_Contract_Description__c, EU_Contract_Number__c, CreatedById, CurrencyIsoCode,
                            EU_Discount__c, EU_Discount_ID__c, LastModifiedById, Name, EU_Price_Type__c
                    FROM EU_Price_Agreement__c
                    WHERE EU_Contract_Number__c IN :contractNumbers AND AccountId__c IN :accountIds
            ];
        } catch (Exception e) {
            System.debug(LoggingLevel.WARN, e.getMessage());
            agreementsForContractNumbers = new List<EU_Price_Agreement__c>();
        }

        if(contractNumbers.isEmpty()) {System.debug(LoggingLevel.WARN, 'could not find any agreements');}

        return agreementsForContractNumbers;
    }
}