ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Address_Verification_Status__c.field-meta.xml
<CustomField>
    <fullName>Address_Verification_Status__c</fullName>
    <description>Indicate that the address validated by Melissa Data&apos;s service, reviewed by a Manager, or imported from the WCMS system (marked as &quot;Verified&quot;); &quot;In Approval&quot; denotes awaiting manager approval. &quot;Pending&quot; is while MelissaData is initializing record</description>
    <inlineHelpText>Indicate that the address validated by Melissa Data&apos;s service, reviewed by a Manager, or imported from the WCMS system (marked as &quot;Verified&quot;); &quot;In Approval&quot; denotes awaiting manager approval. &quot;Pending&quot; is while MelissaData is initializing record</inlineHelpText>
    <label>Address Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Verification</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/All_Claim_Photos_Attached__c.field-meta.xml
<CustomField>
    <fullName>All_Claim_Photos_Attached__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that all photos required for the Claim are attached</description>
    <inlineHelpText>By checking this, you are confirming that all necessary photos for submitting this claim are attached to the Case</inlineHelpText>
    <label>All Claim Photos Attached?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Courier__c.field-meta.xml
<CustomField>
    <fullName>Courier__c</fullName>
    <description>Courer company used for tracking</description>
    <label>Courier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Courier</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Iko_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Iko_Product_Family__c</fullName>
    <description>Surfaces the Iko Product Famliy from the Product, to be used in Lookup filters</description>
    <formula>Product__r.Iko_Product_Family__c</formula>
    <label>Iko Product Family</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product related to the Residential/Commercial Claim</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Is_Legacy__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Product2.Sectors_Text__c</field>
            <operation>contains</operation>
            <valueField>$Source.Sector__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Samples_Collected__c.field-meta.xml
<CustomField>
    <fullName>Samples_Collected__c</fullName>
    <description>Used to indicate if Samples were collected for a Claim; using a Yes/No picklist instead of Boolean to make this field required</description>
    <label>Samples Collected?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Samples_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Samples_Ship_Date__c</fullName>
    <description>Ship Date of Samples for Claaim</description>
    <label>Samples Ship Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <description>Courier Tracking Number</description>
    <label>Tracking Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Type_of_Structure__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Structure__c</fullName>
    <inlineHelpText>Type of Structure/Building where the product is installed</inlineHelpText>
    <label>Type of Structure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Barn</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Garage</fullName>
            </value>
            <value>
                <fullName>Manufact Home</fullName>
            </value>
            <value>
                <fullName>Multi-Unit</fullName>
            </value>
            <value>
                <fullName>Residence</fullName>
            </value>
            <value>
                <fullName>Shed</fullName>
            </value>
            <value>
                <fullName>(none)</fullName>
                <isActive>false</isActive>
                <label>(none)</label>
            </value>
            <value>
                <fullName>Residence Shed</fullName>
                <isActive>false</isActive>
                <label>Residence Shed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/Claim_Type__c.object-meta.xml
<CustomObject>
    <description>Used to capture the Primary and Secondary reason for the Claim Case</description>
    <label>Claim Type</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Claim Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Related Claim Case</description>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Related Case must be a Residential or Commercial Claim</errorMessage>
        <filterItems>
            <field>Case.RecordType.Name</field>
            <operation>contains</operation>
            <value>Claim</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Claim Types</relationshipLabel>
    <relationshipName>Claim_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Concern__c.field-meta.xml
<CustomField>
    <fullName>Concern__c</fullName>
    <label>Concern</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Claim_Type_Reason</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this the Primary Claim Type?</description>
    <label>Is Primary?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claim_Type__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>(none)</fullName>
            </value>
            <value>
                <fullName>A Organic</fullName>
            </value>
            <value>
                <fullName>B Glass</fullName>
            </value>
            <value>
                <fullName>C Lam/Org</fullName>
            </value>
            <value>
                <fullName>D Lam/Glass</fullName>
            </value>
            <value>
                <fullName>E Coated Rolls</fullName>
            </value>
            <value>
                <fullName>F Mod Bit</fullName>
            </value>
            <value>
                <fullName>G Felt</fullName>
            </value>
            <value>
                <fullName>H Asphalt</fullName>
            </value>
            <value>
                <fullName>I Fibrebrd</fullName>
            </value>
            <value>
                <fullName>J Total</fullName>
            </value>
            <value>
                <fullName>K Lock</fullName>
            </value>
            <value>
                <fullName>L ArmourGd</fullName>
            </value>
            <value>
                <fullName>M Protecbrd</fullName>
            </value>
            <value>
                <fullName>N Poly ISO</fullName>
            </value>
            <value>
                <fullName>P Roof-Fast</fullName>
            </value>
            <value>
                <fullName>Q Gold Shield</fullName>
            </value>
            <value>
                <fullName>R Adhs/Ctgs</fullName>
            </value>
            <value>
                <fullName>Z Not IKO</fullName>
            </value>
            <value>
                <fullName>Valley Cap</fullName>
            </value>
            <value>
                <fullName>Panels</fullName>
            </value>
            <value>
                <fullName>Hip &amp; Ridge</fullName>
            </value>
            <value>
                <fullName>Valley</fullName>
            </value>
            <value>
                <fullName>Touch up kit</fullName>
            </value>
            <value>
                <fullName>Screws</fullName>
            </value>
            <value>
                <fullName>Starter w drip</fullName>
            </value>
            <value>
                <fullName>Side</fullName>
            </value>
            <value>
                <fullName>Rake</fullName>
            </value>
            <value>
                <fullName>XD Channel</fullName>
            </value>
            <value>
                <fullName>Debris guard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claims_Config__c/Claims_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to store values for the Claims team app configurations</description>
    <label>Claims Config</label>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claims_Config__c/fields/SharinPix_Annotate_Permission_Id__c.field-meta.xml
<CustomField>
    <fullName>SharinPix_Annotate_Permission_Id__c</fullName>
    <inlineHelpText>Allows end user to upload images, annotate, crop, resize</inlineHelpText>
    <label>SharinPix Annotate Permission Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Claims_Config__c/fields/SharinPix_Read_Only_Permission__c.field-meta.xml
<CustomField>
    <fullName>SharinPix_Read_Only_Permission__c</fullName>
    <inlineHelpText>Used in Lightning Pages to apply a read-only permission</inlineHelpText>
    <label>SharinPix Read Only Permission</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/Lab_Sample__c.object-meta.xml
<CustomObject>
    <label>Lab Sample</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Samples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A link to the Claim this lab sample is related to. Lab Samples with no links to a Claim have been received but not properly connected to a cliam.</description>
    <inlineHelpText>The Claim this Lab Sample relates to.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Lab Samples</relationshipLabel>
    <relationshipName>Lab_Samples</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Courier__c.field-meta.xml
<CustomField>
    <fullName>Courier__c</fullName>
    <defaultValue>&quot;Purolator&quot;</defaultValue>
    <label>Courier for Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Courier</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <description>Tracking details for the shipping of the sample.</description>
    <label>Tracking Number for Disposition</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/SharinPixPermissionsControllerTest.cls
/**
 * Created by sinan.bunni on 2019-09-17.
 */
@IsTest
public with sharing class SharinPixPermissionsControllerTest {

    private static void createUsers() {

        List<User> toInsertUsers = new List<User>();

        toInsertUsers.add(TestFactory.createUser('UnitClaim', 'TestsClaim', 'claimsManagerUsr@iko.com', 'claimsManagerUsr@iko.com', 'Claims Manager',
                'Claims Manager', 'tclu', 'GMT', 'en_US', 'UTF-8', 'en_US', 'United States', null, false));
        toInsertUsers.add(TestFactory.createUser('UnitClaim3', 'TestsClaim', 'labTechnicianUsr@iko.com', 'labTechnicianUsr@iko.com', 'Lab Technician',
                'Lab Tech', 'tsAUr', 'GMT', 'en_US', 'UTF-8', 'en_US', 'United States', null, false));
        toInsertUsers.add(TestFactory.createUser('Unit', 'Tests', 'salesrep@iko1.com', 'salesrep@iko.com',
                'USRS Sales Rep', 'RSM West', 'salesrep', 'GMT', 'en_US', 'UTF-8', 'en_US', null, null, false));

        insert toInsertUsers;
    }

    @TestSetup
    private static void setupTestData() {
        initTestData();
    }

    private static void initTestData() {
        Id baRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Building Location').getRecordTypeId();
        Id ccRt = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Claim').getRecordTypeId();
        List<Account> toInsertAccounts = new List<Account>();

        toInsertAccounts.addAll(TestFactory.createAccounts(baRt, 'CaseServiceTest', '9 King St E', 'Toronto', 'ON', 'CA', 'M4S 2H4',
                'Verified', UserInfo.getUserId(), TRUE, TRUE, 1, false));
        insert toInsertAccounts;

        //create contact
        List<Contact> con = TestFactory.createContacts(toInsertAccounts[0].Id, 'LabSampleTapeCodeServiceTest', UserInfo.getUserId(), 1, false);
        insert con;

        //create Cases
        List<Case> toInsertCases = new List<Case>();

        toInsertCases.addAll(TestFactory.createCases(ccRt, toInsertAccounts[0].Id, con[0].Id, 'Owner', 'CaseServiceTest1', null, 'Commercial', 'Draft', 1, false));
        Insert toInsertCases;

        Product2 prod = new Product2(IsActive = true, Name = 'IkoSampleProduct', ProductCode = 'IkoSampleProduct', Sectors__c = 'US;CA;Commercial;Blair');
        Product2 prod00270021 = new Product2(Iko_Product_Family__c = '0270000', IsActive = true, Name = 'Iko270000', ProductCode = 'Iko270000', Sectors__c = 'US;CA;Commercial;Blair');
        Product2 prod0900055 = new Product2(Iko_Product_Family__c = '0900000', IsActive = true, Name = 'Iko900000', ProductCode = 'Iko900000', Sectors__c = 'US;CA;Commercial;Blair');
        Product2 prod0070020 = new Product2(Iko_Product_Family__c = '0070000', IsActive = true, Name = 'Iko70000', ProductCode = 'Iko70000', Sectors__c = 'US;CA;Commercial;Blair');
        Product2 prod580000 = new Product2(Iko_Product_Family__c = '0580000', IsActive = true, Name = 'Iko580000', ProductCode = 'Iko580000', Sectors__c = 'US;CA;Commercial;Blair');
        Product2 prodNoFamily = new Product2(IsActive = true, Name = 'NoFamily', ProductCode = 'NoFamily', Sectors__c = 'US;CA;Commercial;Blair');
        insert new List<Product2>{
                prod, prod00270021, prod0900055, prod0070020, prod580000, prodNoFamily
        };

    }

    private static testMethod void getSharinPixPermissions_ClaimWithDraftStage_ReturnedAnnotatePermissionId() {

        //Prepare the data
        Case testCase = getTestCase('Draft', NULL);

        //Test the data
        Test.startTest();
        update testCase;
        Test.stopTest();

        //Assert the data
        System.assertEquals(
                SharinPixPermissionsController.getSharinPixPermissions(testCase.Id, 'Case'),
                Claims_Config__c.getOrgDefaults().SharinPix_Annotate_Permission_Id__c
        );
    }

    private static testMethod void getSharinPixPermissions_ClaimWithSubmittedStageAndSalesProfile_ReturnedReadPermissionId() {

        Case testCase = getTestCase('Submitted', NULL);
        //Prepare the data

        //Test the data
        Test.startTest();
        update testCase;
        Test.stopTest();

        //Assert the data
        System.assertEquals(
                SharinPixPermissionsController.getSharinPixPermissions(testCase.Id, 'Case'),
                Claims_Config__c.getOrgDefaults().SharinPix_Read_Only_Permission__c
        );

    }

    private static testMethod void getSharinPixPermissions_ClaimWithAssessmentStageAndSalesUser_ReturnedReadPermissionId() {

        //Prepare the data
        Case testCase = getTestCase('Assessment', NULL);

        //Test the data
        Test.startTest();
        update testCase;
        Test.stopTest();

        //Assert the data
        System.assertEquals(
                SharinPixPermissionsController.getSharinPixPermissions(testCase.Id, 'Case'),
                Claims_Config__c.getOrgDefaults().SharinPix_Read_Only_Permission__c
        );

    }

    private static testMethod void getSharinPixPermissions_ClaimWithClosedStageAndSalesUser_ReturnedReadPermissionId() {

        //Prepare the data
        Case testCase = getTestCase('Closed', NULL);

        //Test the data
        Test.startTest();
        update testCase;
        Test.stopTest();

        //Assert the data
        System.assertEquals(
                SharinPixPermissionsController.getSharinPixPermissions(testCase.Id, 'Case'),
                Claims_Config__c.getOrgDefaults().SharinPix_Read_Only_Permission__c
        );
    }

    private static testMethod void getSharinPixPermissions_ClaimWithDraftStageOnLabSample_ReturnedAnnotatePermissionId() {

        //Prepare the data
        Case testCase = getTestCase('Draft', NULL);

        //Test the data
        Test.startTest();
        update testCase;
        Test.stopTest();

        //Assert the data
        Lab_Sample__c labSample = [SELECT Id FROM Lab_Sample__c LIMIT 1];
        System.assertEquals(
                SharinPixPermissionsController.getSharinPixPermissions(labSample.Id, 'Lab_Sample__c'),
                Claims_Config__c.getOrgDefaults().SharinPix_Annotate_Permission_Id__c
        );
    }

    private static Case getTestCase(final String claimStage, final String claimSubStage) {

        Product2 testProduct = [SELECT Id FROM Product2 WHERE Name = 'Iko270000'];
        Case testCase = [SELECT Id, AccountId FROM Case WHERE Subject = 'CaseServiceTest1'];

        Claim_Type__c claimType = new Claim_Type__c(Case__c = testCase.Id, Concern__c = 'Asphalt bleedthrough', Product_Type__c = 'B Glass',Is_Primary__c = TRUE);
        insert claimType;

        Lab_Sample__c labSample = new Lab_Sample__c(Case__c = testCase.Id);
        insert labSample;

        Account testAccount = new Account(Id = testCase.AccountId, Address_Verification_Status__c = 'Verified');
        update testAccount;

        testCase.Origin = 'Owner';
        testCase.All_Claim_Photos_Attached__c = true;
        testCase.Product__c = testProduct.Id;
        testCase.Samples_Collected__c = 'Yes';
        testCase.Courier__c = 'USPS';
        testCase.Tracking_Number__c = 'abcdefg';
        testCase.Samples_Ship_Date__c = Date.today().addDays(1);
        testCase.Type_of_Structure__c = 'Barn';
        testCase.Pitch__c = '5/12';
        testCase.Sector__c = 'CA';
        testCase.Claim_Stage__c = claimStage;
        testCase.Claim_Sub_Stage__c = claimSubStage;
        testCase.Installation_Date__c = Date.newInstance(2007, 6, 6);
        testCase.Bundles_Causing_Concern__c = 26;
        testCase.Call_Received_Date__c = Date.newInstance(2018, 05, 08);

        return testCase;
    } // end getTestCase method

    @isTest
    private static void testGetCaseIdByLabSampleIdNullLabSampleId(){
        Test.startTest();
        String strResult = SharinPixPermissionsController.getCaseIdByLabSampleId(null);
        Test.stopTest();
        System.assertEquals(strResult,'');
    }

    @isTest
    private static void testGetCaseIdByLabSampleIdWithValidLabSampleId(){
        Test.startTest();
        Id ccRt = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Claim').getRecordTypeId();
        Id baRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Building Location').getRecordTypeId();

        Id accountId = TestFactory.createAccounts(baRt,'CaseServiceTest','99876 King St E','Toronto','ON','CA','M4S 2H4',
                'Verified',UserInfo.getUserId(),TRUE,TRUE,1,true)[0].Id;
        Id contactId = TestFactory.createContacts(accountId,'CaseServiceTest',UserInfo.getUserId(),1,true)[0].Id;
        Id caseId = TestFactory.createCases(ccRt,accountId,contactId,'Distributor','CaseServiceTest1',null,'Commercial','Draft',1,true)[0].Id;

        Lab_Sample__c ls = new Lab_Sample__c(Case__c = caseId);
        insert ls;

        String strResult = SharinPixPermissionsController.getCaseIdByLabSampleId(ls.Id);
        Test.stopTest();

        System.assertEquals(String.valueOf(caseId),strResult);
    }

    @isTest
    private static void testGetSharinPixPermissionIdByLabTech() {
        createUsers();
        List<Case> toInsertCases = new List<Case>();

        Id ccRt = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Commercial Claim').getRecordTypeId();
        Id baRt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Building Location').getRecordTypeId();
        User u = [SELECT Id FROM User WHERE Username = 'labTechnicianUsr@iko.com'];

        Test.startTest();
        System.runAs(u) {
            Id accountId = TestFactory.createAccounts(baRt, 'CaseServiceTest', '976 King St E', 'Toronto', 'ON', 'CA', 'M4S 2H4',
                    'Verified', UserInfo.getUserId(), TRUE, TRUE, 1, true)[0].Id;
            Id contactId = TestFactory.createContacts(accountId, 'CaseServiceTest', UserInfo.getUserId(), 1, true)[0].Id;

            toInsertCases = TestFactory.createCases(ccRt, accountId, contactId, 'Distributor', 'CaseServiceTestLabTech', null, 'Commercial', 'In Lab', 1, true);

            Claim_Type__c ct = new Claim_Type__c(Case__c = toInsertCases[0].Id);
            insert ct;
        }
        Test.stopTest();

        System.assertEquals(SharinPixPermissionsController.getSharinPixPermissions(toInsertCases[0].Id, 'Case'), Claims_Config__c.getOrgDefaults().SharinPix_Annotate_Permission_Id__c);

    }

} // end SharinPixPermissionsControllerTest method