ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Admin_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Admin_Email_Address__c</fullName>
    <description>Generic email address for company</description>
    <inlineHelpText>Generic email address for company</inlineHelpText>
    <label>Admin Email Address</label>
    <type>Email</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Business_Fundamentals_Completed__c.field-meta.xml
<CustomField>
    <fullName>Business_Fundamentals_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Business Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Date_Present_Tier__c.field-meta.xml
<CustomField>
    <fullName>Date_Present_Tier__c</fullName>
    <description>The Date stamp the present Tier was added.</description>
    <label>Date Present Tier</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IF_Course_Affirmation__c.field-meta.xml
<CustomField>
    <fullName>IF_Course_Affirmation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Performance_Fundamentals_Completed__c.field-meta.xml
<CustomField>
    <fullName>Performance_Fundamentals_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Performance Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Present_Tier_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Present_Tier_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Tier object to select present tier. Upon selection, flow will change benefits triggered by process builder and the latter will fill prior Tier field.</description>
    <label>Present Tier</label>
    <referenceTo>Tier__c</referenceTo>
    <relationshipLabel>Contractor Accounts with this Tier</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Prior_Tier__c.field-meta.xml
<CustomField>
    <fullName>Prior_Tier__c</fullName>
    <defaultValue>&quot;No Prior Tier&quot;</defaultValue>
    <description>Process Builder fills in the prior tier after tier change for this partner account.</description>
    <label>Prior Tier</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Safety_Fundamentals_Completed__c.field-meta.xml
<CustomField>
    <fullName>Safety_Fundamentals_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Safety Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Contractor.recordType-meta.xml
<RecordType>
    <fullName>Contractor</fullName>
    <active>true</active>
    <label>Contractor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/Account_Tier_Movement__c.object-meta.xml
<CustomObject>
    <label>Account Tier Movement</label>
    <nameField>
        <displayFormat>ATM - {0}</displayFormat>
        <label>Account Tier Movement name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Tier Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Applicable_Invoice_Year__c.field-meta.xml
<CustomField>
    <fullName>ATM_Applicable_Invoice_Year__c</fullName>
    <label>Applicable Invoice Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Applied_Benchmark_Value_Tier_1_High__c.field-meta.xml
<CustomField>
    <fullName>ATM_Applied_Benchmark_Value_Tier_1_High__c</fullName>
    <label>Applied Benchmark Value - Tier 1 - High</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Applied_Benchmark_Value_Tier_2_High__c.field-meta.xml
<CustomField>
    <fullName>ATM_Applied_Benchmark_Value_Tier_2_High__c</fullName>
    <label>Applied Benchmark Value - Tier 2 - High</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Applied_Benchmark_Value_Tier_2_Low__c.field-meta.xml
<CustomField>
    <fullName>ATM_Applied_Benchmark_Value_Tier_2_Low__c</fullName>
    <label>Applied Benchmark Value - Tier 2 - Low</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Applied_Benchmark_Value_Tier_3_Low__c.field-meta.xml
<CustomField>
    <fullName>ATM_Applied_Benchmark_Value_Tier_3_Low__c</fullName>
    <label>Applied Benchmark Value - Tier 3 - Low</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Business_Fundamentals_Completed__c.field-meta.xml
<CustomField>
    <fullName>ATM_Business_Fundamentals_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Business Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>ATM_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Account Tier Movements</relationshipLabel>
    <relationshipName>ATM_Account_Tier_Movements_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Contractor__c.field-meta.xml
<CustomField>
    <fullName>ATM_Contractor__c</fullName>
    <label>Contractor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Tier Movements</relationshipLabel>
    <relationshipName>Account_Tier_Trackings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Contractor_Email__c.field-meta.xml
<CustomField>
    <fullName>ATM_Contractor_Email__c</fullName>
    <description>Email of Contractor to receive emails</description>
    <label>Contractor Email</label>
    <type>Email</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Date_Present_Tier__c.field-meta.xml
<CustomField>
    <fullName>ATM_Date_Present_Tier__c</fullName>
    <label>Date Present Tier</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Installation_Fundamentals_Completed__c.field-meta.xml
<CustomField>
    <fullName>ATM_Installation_Fundamentals_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Member_Since_Months__c.field-meta.xml
<CustomField>
    <fullName>ATM_Member_Since_Months__c</fullName>
    <label>Member Since (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Performance_Fundamentals_Completed__c.field-meta.xml
<CustomField>
    <fullName>ATM_Performance_Fundamentals_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Performance Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Present_Tier__c.field-meta.xml
<CustomField>
    <fullName>ATM_Present_Tier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eligible Present Tier</label>
    <referenceTo>Tier__c</referenceTo>
    <relationshipLabel>Account Tier Movements</relationshipLabel>
    <relationshipName>ATM_Present_Tier_Tier</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Prior_Tier__c.field-meta.xml
<CustomField>
    <fullName>ATM_Prior_Tier__c</fullName>
    <label>Prior Tier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Purchase_Square_Volume__c.field-meta.xml
<CustomField>
    <fullName>ATM_Purchase_Square_Volume__c</fullName>
    <description>Purchase Square Volume (from Member Start Date)</description>
    <label>Purchase Square Volume</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Safety_Fundamentals_Completed__c.field-meta.xml
<CustomField>
    <fullName>ATM_Safety_Fundamentals_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Safety Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Sign_Up_Year__c.field-meta.xml
<CustomField>
    <fullName>ATM_Sign_Up_Year__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sign-Up Year</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Simulation__c.field-meta.xml
<CustomField>
    <fullName>ATM_Simulation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Simulation</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_Tier_Movement_Decision__c.field-meta.xml
<CustomField>
    <fullName>ATM_Tier_Movement_Decision__c</fullName>
    <label>Tier Movement Decision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exceeded Sq. Purchase Volume</fullName>
            </value>
            <value>
                <fullName>Did Not Meet Minimum Sq. Purchase Volume</fullName>
            </value>
            <value>
                <fullName>Manual Tier Adjustment</fullName>
            </value>
            <value>
                <fullName>Maintained Sq. Purchase Volume</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/fields/ATM_TSR_Email__c.field-meta.xml
<CustomField>
    <fullName>ATM_TSR_Email__c</fullName>
    <description>Email Id of TSR to receive emails.</description>
    <label>TSR Email</label>
    <type>Email</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/icLogicTierMovementLog.cls
public class icLogicTierMovementLog implements icIClass {

	public Object GetInstance() {
		return new Impl();
	}

	public Interface IClass {
		Account_Tier_Movement__c createNewTierMovementLog(icDtoTierMovementConfig processConfig, Account contractor, Contact primaryContact, Integer calculatedMonth, Double calculatedSqares, Boolean isSignupYear, String tierMovement, Double tier1High, Double tier2Low, Double tier2High, Double tier3Low);
		void saveTierMovementLog(List<Account_Tier_Movement__c> tierMovementLogs);
	}

	public class Impl implements IClass {

		icRepoTierMovementLog.IClass repo = (icRepoTierMovementLog.IClass) icObjectFactory.GetSingletonInstance('icRepoTierMovementLog');

		Map<String, String> mapMovementDecision {
			get {
				if(mapMovementDecision == null) {
					mapMovementDecision = new Map<String, String>();
					mapMovementDecision.put('MAINTAIN', 'Maintained Sq. Purchase Volume');
					mapMovementDecision.put('ASCEND', 'Exceeded Sq. Purchase Volume');
					mapMovementDecision.put('DESCEND', 'Did Not Meet Minimum Sq. Purchase Volume');
				}
				return mapMovementDecision;
			}
			set;
		}

		public Account_Tier_Movement__c createNewTierMovementLog(icDtoTierMovementConfig processConfig, Account contractor, Contact primaryContact, Integer calculatedMonth, Double calculatedSqares, Boolean isSignupYear, String tierMovement, Double tier1High, Double tier2Low, Double tier2High, Double tier3Low) {

			System.debug('mapMovementDecision : ' + mapMovementDecision);
			System.debug('tierMovement : ' + tierMovement);

			Account_Tier_Movement__c newTierMovementLog = new Account_Tier_Movement__c();
			newTierMovementLog.ATM_Simulation__c = processConfig.isSimulation;
			newTierMovementLog.ATM_Contractor__c = contractor.Id;
			newTierMovementLog.ATM_Member_Since_Months__c = calculatedMonth;
			newTierMovementLog.ATM_Applicable_Invoice_Year__c = processConfig.rebateYear;
			newTierMovementLog.ATM_Purchase_Square_Volume__c = calculatedSqares;
			newTierMovementLog.ATM_Sign_Up_Year__c = isSignupYear;
			newTierMovementLog.ATM_Tier_Movement_Decision__c = mapMovementDecision.get(tierMovement);
			newTierMovementLog.ATM_Business_Fundamentals_Completed__c = contractor.Business_Fundamentals_Completed__c;
			newTierMovementLog.ATM_Installation_Fundamentals_Completed__c = contractor.IF_Course_Affirmation__c;
			newTierMovementLog.ATM_Performance_Fundamentals_Completed__c = contractor.Performance_Fundamentals_Completed__c;
			newTierMovementLog.ATM_Safety_Fundamentals_Completed__c = contractor.Safety_Fundamentals_Completed__c;
			newTierMovementLog.ATM_Applied_Benchmark_Value_Tier_1_High__c = tier1High;
			newTierMovementLog.ATM_Applied_Benchmark_Value_Tier_2_Low__c = tier2Low;
			newTierMovementLog.ATM_Applied_Benchmark_Value_Tier_2_High__c = tier2High;
			newTierMovementLog.ATM_Applied_Benchmark_Value_Tier_3_Low__c = tier3Low;
			newTierMovementLog.ATM_Date_Present_Tier__c = contractor.Date_Present_Tier__c;
			newTierMovementLog.ATM_Present_Tier__c = contractor.Present_Tier_Lookup__c;
			newTierMovementLog.ATM_Prior_Tier__c = contractor.Prior_Tier__c;
			newTierMovementLog.ATM_TSR_Email__c = contractor.Owner.Email;
			newTierMovementLog.ATM_Contractor_Email__c = contractor.Admin_Email_Address__c;
			if(primaryContact != null) {
				newTierMovementLog.ATM_Contact_Name__c = primaryContact.Id;
			}
			return newTierMovementLog;
		}

		public void saveTierMovementLog(List<Account_Tier_Movement__c> tierMovementLogs) {
            List<Database.SaveResult> saveResults = repo.saveTierMovementLog(tierMovementLogs);
            icServiceErrorHandler.handleDatabaseSaveResult(tierMovementLogs, saveResults, 'icLogicTierMovementLog', 'saveTierMovementLog');
        }
	}
}