ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Admin_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Admin_Email_Address__c</fullName>
    <description>Generic email address for company</description>
    <inlineHelpText>Generic email address for company</inlineHelpText>
    <label>Admin Email Address</label>
    <type>Email</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Applicant_Information__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Information</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Available_COOP_Funds__c.field-meta.xml
<CustomField>
    <fullName>Available_COOP_Funds__c</fullName>
    <formula>if(AND((COOP_Funds_Credit__c &gt; COOP_Funds_Debit__c),  Present_Tier_Lookup__r.Name &lt;&gt;&quot;Tier 0&quot;),COOP_Funds_Credit__c - COOP_Funds_Debit__c,0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Co-Op Funds</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Available_Premium_COOP_Funds__c.field-meta.xml
<CustomField>
    <fullName>Available_Premium_COOP_Funds__c</fullName>
    <formula>if(AND((Premium_COOP_Funds_Credit__c &gt; Premium_COOP_Funds_Debit__c),Present_Tier_Lookup__r.Name &lt;&gt;&quot;Tier 0&quot;),Premium_COOP_Funds_Credit__c - Premium_COOP_Funds_Debit__c ,0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Premium Cap (Swag)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/BillingStateCode__c.field-meta.xml
<CustomField>
    <fullName>BillingStateCode__c</fullName>
    <formula>TEXT(BillingStateCode)</formula>
    <label>BillingStateCode</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Business_Operating_Language_ROOFPRO__c.field-meta.xml
<CustomField>
    <fullName>Business_Operating_Language_ROOFPRO__c</fullName>
    <defaultValue>&quot;English&quot;</defaultValue>
    <inlineHelpText>Language for communications (emails) you receive regarding the ROOFPRO Portal.</inlineHelpText>
    <label>Business Operating Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Operating_Languages</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Central_Station_Short_URL__c.field-meta.xml
<CustomField>
    <fullName>Central_Station_Short_URL__c</fullName>
    <label>Central Station Short URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Contractor_ID__c.field-meta.xml
<CustomField>
    <fullName>Contractor_ID__c</fullName>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ROOFPRO Contractor ID</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Contractor_Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Name_Formula__c</fullName>
    <description>Displays name of the contractor account without the &quot;(ROOFPRO)&quot; appended.</description>
    <formula>IF(RIGHT(Name, 10) = &quot; (ROOFPRO)&quot;, 
LEFT( Name , LEN(Name) - 10 ), 
IF(RIGHT(Name, 14) = &quot; (CRC RoofPRO)&quot;, 
LEFT( Name , LEN(Name) - 14 ), 
Name))</formula>
    <label>Contractor</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/DBA_Account__c.field-meta.xml
<CustomField>
    <fullName>DBA_Account__c</fullName>
    <description>Populated with Provision Access flow for non-SPP ROOFPRO Accounts</description>
    <label>DBA (Doing Business As)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Hide_Upcoming_Coop_Rewards__c.field-meta.xml
<CustomField>
    <fullName>Hide_Upcoming_Coop_Rewards__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox is for Loyalty Admins to hide the next year Upcoming Coop Rewards present in the six box tracker.</description>
    <label>Hide Next Year&apos;s Coop Rewards</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IKO_com__c.field-meta.xml
<CustomField>
    <fullName>IKO_com__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field with initial value taken from the ROOFPRO Applicant. 
Used for Data sync with IKO.com.</description>
    <label>I want to be listed on IKO.com</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IKOPRO_Approved_On__c.field-meta.xml
<CustomField>
    <fullName>IKOPRO_Approved_On__c</fullName>
    <description>Filled with process builder (upon enabling partner)</description>
    <label>Activated On</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IKOPRO_QueueID__c.field-meta.xml
<CustomField>
    <fullName>IKOPRO_QueueID__c</fullName>
    <description>ID for Queue created upon enabling Contractor as Partner Account. This ID will be used to assign all incoming leads from the partner&apos;s web form to the Queue as Lead Owner.
The Queue ID is populated upon creation of the Queue via Flow.</description>
    <externalId>true</externalId>
    <label>IKOPRO_QueueID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IsPartner__c.field-meta.xml
<CustomField>
    <fullName>IsPartner__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to capture the value of the &apos;IsPartner&apos; system field, because this one cannot be used within validation rules.</description>
    <label>IsPartner</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Language_Preferences__c.field-meta.xml
<CustomField>
    <fullName>Language_Preferences__c</fullName>
    <label>Language Preference(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Operating_Languages</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Mapics_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Mapics_ERP_ID__c</fullName>
    <description>The account&apos;s ID in the Mapics ERP. We use this to match data when we sync it back and forth.</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter the customer&apos;s ID from the Mapics ERP. Be very careful to make sure this is correct. Enter any leading zeroes--Mapics IDs are exactly 8 digits long.</inlineHelpText>
    <label>Mapics ERP ID</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Present_Tier_Formula__c.field-meta.xml
<CustomField>
    <fullName>Present_Tier_Formula__c</fullName>
    <formula>Present_Tier_Lookup__r.Tier_Label__c</formula>
    <label>Present Tier Formula</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Quote_Logo__c.field-meta.xml
<CustomField>
    <fullName>Quote_Logo__c</fullName>
    <label>Quote Logo</label>
    <length>500</length>
    <type>Html</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Sales_Rep_Info__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Info__c</fullName>
    <formula>&quot;Phone: &quot; &amp;  Owner.Phone &amp; BR() &amp;
&quot;Mobile: &quot; &amp;  Owner.MobilePhone &amp; BR() &amp;
&quot;Email: &quot; &amp;  Owner.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Rep Info</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Tier_Prozone__c.field-meta.xml
<CustomField>
    <fullName>Tier_Prozone__c</fullName>
    <description>Field used for Sync Fields functionality (API Call) with PROZONE (ROOFPRO).</description>
    <formula>CASE(Present_Tier_Lookup__r.Name,
&quot;Tier 1&quot;, &quot;ROOFPRO PREFERRED&quot;,
&quot;Tier 2&quot;, &quot;ROOFPRO SELECT&quot;,
&quot;Tier 3&quot;, &quot;ROOFPRO CRAFTSMAN PREMIER&quot;,
&quot;Tier 0&quot;, &quot;Advantage&quot;,
&quot;No Tier Chosen&quot;)

/*Old Formula
CASE(Present_Tier_Lookup__r.Name,
&quot;Tier 1&quot;, &quot;ROOFPRO PREFERRED&quot;,
&quot;Tier 2&quot;, &quot;ROOFPRO SELECT&quot;,
&quot;Tier 3&quot;, &quot;ROOFPRO CRAFTSMAN PREMIER&quot;,
&quot;No Tier Chosen&quot;)*/</formula>
    <label>Tier (Prozone)</label>
    <type>Text</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/icRepoAccount.cls
public class icRepoAccount implements icIClass {

	public Object GetInstance() {
		return new Impl();
	}

	public Interface IClass {
		Contact getPersonAcountInfoById(String recordId);
		Account getAcountInfoById(String recordId);
		List<Account> getAcountsInfoByIds(List<Id> accountIds);
		Account getAcountByHARefKey(String haRefKey);
		Account getContractorContactUsInfo(String customerId);
		List<Account> getContractorsWithExpiringFunds();
		Account saveAccount(Account record);
		List<Database.SaveResult> saveAccounts(List<Account> accounts);
		List<Account> getAccountsByMapicsExternalId(Set<String> externalId);
	}

	public class Impl implements IClass {

		public Contact getPersonAcountInfoById(String recordId) {
			List<Contact> listContact = [SELECT	Id
							,FirstName
							,LastName
							,Email
					FROM	Contact
					WHERE	AccountId = :recordId
					LIMIT	1];
			if(listContact.size() == 1) {
				return listContact[0];
			}
			return null;
		}

		public Account getAcountInfoById(String recordId) {
			List<Account> listAccount = [SELECT	Id
							,Name
							,IKOPRO_Approved_On__c
							,Quote_Logo__c
							,BillingStreet
							,BillingCity
							,BillingState
							,BillingCountry
							,BillingPostalCode
							,IKOPRO_QueueID__c
							,Available_COOP_Funds__c
							,Central_Station_Short_URL__c
							,Hide_Upcoming_Coop_Rewards__c
							,Present_Tier_Formula__c
					FROM	Account
					WHERE	Id = :recordId
					LIMIT	1];
			if(listAccount.size() == 1) {
				return listAccount[0];
			}
			return null;
		}

		public List<Account> getAcountsInfoByIds(List<Id> accountIds){

			List<Account> listAccount = new List<Account>();
			listAccount =
				[SELECT	Id,
						Name,
						DBA_Account__c,
						Website,
						Contractor_ID__c,
						Contractor_Name_Formula__c,
						IKOPRO_QueueID__c,
						Phone,
						Fax,
						BillingStreet,
						BillingCity,
						BillingState,
						BillingStateCode__c,
						BillingPostalCode,
						BillingCountry,
						IsPartner__c,
						IsPartner,
						IKO_com__c,
						Applicant_Information__r.Wants_To_Be_Listed_On_IKO_com__c,
						Tier_Prozone__c,
                        Admin_Email_Address__c,
						Language_Preferences__c,
						Business_Operating_Language_ROOFPRO__c
				FROM	Account
				WHERE	Id IN: accountIds];

			return listAccount;
		}

		public Account getAcountByHARefKey(String haRefKey) {
			List<Account> listAccount = [SELECT	Id
							,Name
					FROM	Account
					WHERE	IKOPRO_QueueID__c = :haRefKey
					LIMIT	1];
			if(listAccount.size() == 1) {
				return listAccount[0];
			}
			return null;
		}

		public Account getContractorContactUsInfo(String customerId) {
			List<Account> listAccount = [SELECT	Id
							,Name
							,Sales_Rep_Info__c
							,Owner.Name
							,Owner.Phone
							,Owner.MobilePhone
							,Owner.Email
					FROM	Account
					WHERE	Id = :customerId
					LIMIT	1];
			if(listAccount.size() == 1) {
				return listAccount[0];
			}
			return null;
		}

		public List<Account> getContractorsWithExpiringFunds() {
			return [SELECT Id, Name, Available_COOP_Funds__c, Available_Premium_COOP_Funds__c FROM Account WHERE Available_COOP_Funds__c > 0 OR Available_Premium_COOP_Funds__c > 0];
		}

		public Account saveAccount(Account reccord){
			upsert reccord;
			return reccord;
		}

		public List<Database.SaveResult> saveAccounts(List<Account> accounts){
			return Database.update(accounts, false);
		}

		/**
         * Query salesforce for a list of Account by Mapics external Id
         *
         * @param   externalId  a unique list of Mapics external ids
         * @return  a list of accounts
         */
		public List<Account> getAccountsByMapicsExternalId(Set<String> externalId) {
			return [SELECT Id, Name, OwnerId, Mapics_ERP_ID__c FROM Account WHERE Mapics_ERP_ID__c IN :externalId];
		}
	}
}