ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Admin_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Admin_Email_Address__c</fullName>
    <description>Generic email address for company</description>
    <inlineHelpText>Generic email address for company</inlineHelpText>
    <label>Admin Email Address</label>
    <type>Email</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Business_Fundamentals_Completed__c.field-meta.xml
<CustomField>
    <fullName>Business_Fundamentals_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Business Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Date_Present_Tier__c.field-meta.xml
<CustomField>
    <fullName>Date_Present_Tier__c</fullName>
    <description>The Date stamp the present Tier was added.</description>
    <label>Date Present Tier</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IF_Course_Affirmation__c.field-meta.xml
<CustomField>
    <fullName>IF_Course_Affirmation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IKOPRO_Approved_On__c.field-meta.xml
<CustomField>
    <fullName>IKOPRO_Approved_On__c</fullName>
    <description>Filled with process builder (upon enabling partner)</description>
    <label>Activated On</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IsPartner__c.field-meta.xml
<CustomField>
    <fullName>IsPartner__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to capture the value of the &apos;IsPartner&apos; system field, because this one cannot be used within validation rules.</description>
    <label>IsPartner</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Override_Tier_Movement__c.field-meta.xml
<CustomField>
    <fullName>Override_Tier_Movement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The automatic tier movement is restricted when loyalty admins will check this box while changing the contractor tier manually.</description>
    <inlineHelpText>When this checkbox is ticked the automatic tier movement is restricted and the tier will remain the same until the Current Cutoff Date (Maintenance/Descend).</inlineHelpText>
    <label>Override Tier Movement</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Performance_Fundamentals_Completed__c.field-meta.xml
<CustomField>
    <fullName>Performance_Fundamentals_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Performance Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Present_Tier_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Present_Tier_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Tier object to select present tier. Upon selection, flow will change benefits triggered by process builder and the latter will fill prior Tier field.</description>
    <label>Present Tier</label>
    <referenceTo>Tier__c</referenceTo>
    <relationshipLabel>Contractor Accounts with this Tier</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Present_Tier_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Present_Tier_Percentage__c</fullName>
    <formula>Present_Tier_Lookup__r.Percentage_Tier_Invoices__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Present Tier Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Prior_Tier__c.field-meta.xml
<CustomField>
    <fullName>Prior_Tier__c</fullName>
    <defaultValue>&quot;No Prior Tier&quot;</defaultValue>
    <description>Process Builder fills in the prior tier after tier change for this partner account.</description>
    <label>Prior Tier</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Prior_Tier_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Prior_Tier_Percentage__c</fullName>
    <description>Populated with Process Builder upon Tier change &amp; used to calculate COOP Amount on the Rebate Invoice Records (upon creation).</description>
    <label>Prior Tier Percentage</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Safety_Fundamentals_Completed__c.field-meta.xml
<CustomField>
    <fullName>Safety_Fundamentals_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Safety Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Contractor.recordType-meta.xml
<RecordType>
    <fullName>Contractor</fullName>
    <active>true</active>
    <label>Contractor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/IKOPRO_Contractor.recordType-meta.xml
<RecordType>
    <fullName>IKOPRO_Contractor</fullName>
    <active>true</active>
    <description>Used for Contractors who have access to the ROOFPRO Community</description>
    <label>IKOPRO Contractor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/IKOPRO_Contractor_HA_OK.recordType-meta.xml
<RecordType>
    <fullName>IKOPRO_Contractor_HA_OK</fullName>
    <active>true</active>
    <description>For Contractor Layout where Home Advisor Subscription is already active.</description>
    <label>IKOPRO Contractor HA OK</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account_Tier_Movement__c/Account_Tier_Movement__c.object-meta.xml
<CustomObject>
    <label>Account Tier Movement</label>
    <nameField>
        <displayFormat>ATM - {0}</displayFormat>
        <label>Account Tier Movement name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Tier Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/IKOPRO_Account_Payment__c.object-meta.xml
<CustomObject>
    <label>Contractor Payment</label>
    <nameField>
        <displayFormat>INV - {00000}</displayFormat>
        <label>PaymentID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contractor Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Rebate Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/Tier__c.object-meta.xml
<CustomObject>
    <description>Object to manage Tier information (e.g. maximum &amp; minimum amount of squares before Tier change).</description>
    <label>Tier</label>
    <nameField>
        <displayFormat>Tier {0}</displayFormat>
        <label>Tier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/fields/Maximum_Squares__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Squares__c</fullName>
    <label>Maximum Squares</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/fields/Minimum_Squares__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Squares__c</fullName>
    <label>Minimum Squares</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/fields/Tier_Label__c.field-meta.xml
<CustomField>
    <fullName>Tier_Label__c</fullName>
    <label>Tier</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icBatchTierMovementProcess.cls
global class icBatchTierMovementProcess implements Database.Batchable<sObject>, Database.Stateful {

	icLogicAccount.IClass logicAccount = (icLogicAccount.IClass) icObjectFactory.GetSingletonInstance('icLogicAccount');
	icLogicAccountPayment.IClass logicAccountPayment = (icLogicAccountPayment.IClass) icObjectFactory.GetSingletonInstance('icLogicAccountPayment');
	icLogicContact.IClass logicContact = (icLogicContact.IClass) icObjectFactory.GetSingletonInstance('icLogicContact');
	icLogicInvoice.IClass logicInvoice = (icLogicInvoice.IClass) icObjectFactory.GetSingletonInstance('icLogicInvoice');
	icLogicTierMovementLog.IClass logicTierMovement = (icLogicTierMovementLog.IClass) icObjectFactory.GetSingletonInstance('icLogicTierMovementLog');

	global icDtoTierMovementConfig processConfig {get; set;}
	global Map<String, Tier__c> mapTiers {get;set;}

	global Tier__c tier1 {get;set;}
	global Tier__c tier2 {get;set;}
	global Tier__c tier3 {get;set;}
    global Tier__c tier0 {get;set;}

	global Integer intRebateYear {get;set;}
	global Double tier1High {get;set;}
	global Double tier2Low {get;set;}
	global Double tier2High {get;set;}
	global Double tier3Low {get;set;}

	global Date processDate = Date.today();

	global Map<String, List<String>> processLogs = new Map<String, List<String>>();
	global Integer totalAccountsProcessed = 0;
	
	global icBatchTierMovementProcess(icDtoTierMovementConfig processConfig, Map<String, Tier__c> mapTiers) {
		this.processConfig = processConfig;
		this.mapTiers = mapTiers;

		for(Tier__c thisTier : mapTiers.values()) {
			if(thisTier.Tier_Label__c == '1') {
				tier1 = thisTier;
				tier1High = thisTier.Maximum_Squares__c;
			}
			if(thisTier.Tier_Label__c == '2') {
				tier2 = thisTier;
				tier2Low = thisTier.Minimum_Squares__c;
				tier2High = thisTier.Maximum_Squares__c;
			}
			if(thisTier.Tier_Label__c == '3') {
				tier3 = thisTier;
				tier3Low = thisTier.Minimum_Squares__c;
			}
            if(thisTier.Tier_Label__c == '0') {
				tier0 = thisTier;
			}
		}

		this.intRebateYear = Integer.valueOf(processConfig.rebateYear);
	}

	global Database.QueryLocator start(Database.BatchableContext context) {
		Map<String, Schema.RecordTypeInfo> mapContractorRecordTypes = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();
		Id contractorRecordTypeId = mapContractorRecordTypes.get('IKOPRO_Contractor').getRecordTypeId();
		Id contractorHAOKRecordTypeId = mapContractorRecordTypes.get('IKOPRO_Contractor_HA_OK').getRecordTypeId();

		return Database.getQueryLocator('SELECT Id, Name, IKOPRO_Approved_On__c, Present_Tier_Lookup__c, Present_Tier_Percentage__c, Prior_Tier__c, Prior_Tier_Percentage__c, Date_Present_Tier__c, Override_Tier_Movement__c, Owner.Email, Admin_Email_Address__c, Business_Fundamentals_Completed__c, IF_Course_Affirmation__c, Performance_Fundamentals_Completed__c, Safety_Fundamentals_Completed__c FROM Account WHERE IsPartner__c = true AND RecordTypeId IN (\'' + contractorRecordTypeId + '\',\'' + contractorHAOKRecordTypeId + '\')');
	}

	global void execute(Database.BatchableContext context, List<Account> scope) {
		totalAccountsProcessed += scope.size();

		System.debug('scope.size > ' + scope.size());
		
		List<Account> finalScope = new List<Account>();
		List<Account> updateAccounts = new List<Account>();
		// get all accountIds in scope
		// evaluate exclusions
		List<String> accountIds = new List<String>();
		for(Account thisAccount : scope) {
			Boolean isAccountInScope = true;

			if(thisAccount.Override_Tier_Movement__c) {
				isAccountInScope = false;
				addProcessLog(thisAccount, 'Omitted by manual override', 'Override_Tier_Movement__c');
			} else if(thisAccount.Present_Tier_Lookup__c == null) {
				isAccountInScope = false;
				addProcessLog(thisAccount, 'Omitted by invalid present tier', 'Present Tier is null ');
			} else if(thisAccount.IKOPRO_Approved_On__c == null || thisAccount.IKOPRO_Approved_On__c.year() > intRebateYear) {
				isAccountInScope = false;
				addProcessLog(thisAccount, 'Omitted by activation date', 'Activated on ' + thisAccount.IKOPRO_Approved_On__c);
            }else if(thisAccount.Present_Tier_Lookup__c == tier0.Id){
                isAccountInScope = false;
				addProcessLog(thisAccount, 'Omitted by Tier 1Minus', 'Excluded from movement');
            }
            else {
				
				// always check ASCEND on weekly process mode
				// TO DO: remap ASCEND mode with WEEKLY
				if(processConfig.processMode == 'ASCEND') {
					if(mapTiers.get(thisAccount.Present_Tier_Lookup__c).Tier_Label__c == '3') {
						isAccountInScope = false;
						addProcessLog(thisAccount, 'Omitted can not ascend', 'Present Tier is Tier 3, can not ascend further.');
					}
				}
			}

			if(isAccountInScope) {
				accountIds.add(thisAccount.Id);
				finalScope.add(thisAccount);
			}
		}

		System.debug('finalScope.size > ' + finalScope.size());

		//get primary admin contacts by contractor
		List<Contact> allContactsInScope = logicContact.getPrimaryAdminContactsByContractorIds(accountIds);
		Map<String, Contact> mapAdminContactByContractor = logicContact.getMapPrimaryAdminContactByContractorId(allContactsInScope);

		String strPaymentYear = processConfig.rebateYear;
		if(processConfig.processMode == 'DESCEND') {
			strPaymentYear = String.valueOf(intRebateYear + 1);
		}
		//get all paid account payments for process year
		List<IKOPRO_Account_Payment__c> allPaidRenewals = logicAccountPayment.getPaidAccountPaymentByYearAndContractorIds(strPaymentYear, accountIds);
		Map<String, IKOPRO_Account_Payment__c> mapPaidRenewalsByContractorId = logicAccountPayment.getMapPaidRenewalByContractorId(allPaidRenewals);

		//get all rebate invoices
		List<Invoice__c> scopeInvoices = logicInvoice.getAllInvoicesByAccountIdsAndRebateYear(accountIds, processConfig.rebateYear);
		Map<String, List<Invoice__c>> mapInvoicesByAccount = logicInvoice.getMapInvoicesByAccount(scopeInvoices);

		List<Account_Tier_Movement__c> listTierMovementLogs = new List<Account_Tier_Movement__c>();
		for(Account thisAccount : finalScope) {
			//validate renewal
			IKOPRO_Account_Payment__c renewalPayment = mapPaidRenewalsByContractorId.get(thisAccount.Id);
			if(renewalPayment == null) {
				addProcessLog(thisAccount, 'Omitted not renewed', 'No paid Payment for ' + strPaymentYear);
				continue;
			}
			
			Tier__c presentTier = mapTiers.get(thisAccount.Present_Tier_Lookup__c);
			Integer intPresentTier = Integer.valueOf(presentTier.Tier_Label__c);

			Double calculatedTier1High = tier1High;
			Double calculatedTier2Low = tier2Low;
			Double calculatedTier2High = tier2High;
			Double calculatedTier3Low = tier3Low;

			Boolean isProratedYear = logicAccount.evaluateIsProratedYear(thisAccount, intRebateYear);
			Integer calculatedMonth = 12;
			if(isProratedYear) {
				calculatedMonth -= thisAccount.IKOPRO_Approved_On__c.month();
				if(calculatedMonth < 3) {
					calculatedMonth = 3;
				}

				calculatedTier1High = (calculatedTier1High / 12) * calculatedMonth;
				calculatedTier2Low = (calculatedTier2Low / 12) * calculatedMonth;
				calculatedTier2High = (calculatedTier2High / 12) * calculatedMonth;
				calculatedTier3Low = (calculatedTier3Low / 12) * calculatedMonth;
			}

			//calculate total squares
			List<Invoice__c> thisAccountInvoices = mapInvoicesByAccount.get(thisAccount.Id);			
			Double totalSquares = 0;
			if(thisAccountInvoices != null) {
				totalSquares = logicInvoice.getSquaresFromInvoices(thisAccountInvoices, isProratedYear, thisAccount.IKOPRO_Approved_On__c);
			}

			Integer intTierBySquare;
			String tierBySquareId;
			if(totalSquares <= calculatedTier1High) {
				intTierBySquare = 1;
				tierBySquareId = tier1.Id;
			}
			if(totalSquares >= calculatedTier2Low && totalSquares <= calculatedTier2High) {
				intTierBySquare = 2;
				tierBySquareId = tier2.Id;
			}
			if(totalSquares >= calculatedTier3Low) {
				intTierBySquare = 3;
				tierBySquareId = tier3.Id;
			}

			Boolean logTierMovement = false;
			String tierMovement = 'MAINTAIN';
			if(intPresentTier > intTierBySquare && processConfig.processMode == 'DESCEND') {
				tierMovement = 'DESCEND';
				logTierMovement = true;
				addProcessLog(thisAccount, 'Moved', 'Descended');
			}
			// always check ASCEND
			if(intPresentTier < intTierBySquare) { // && processConfig.processMode == 'ASCEND') {
				if(((intPresentTier == 1 && intTierBySquare == 2) && (thisAccount.Safety_Fundamentals_Completed__c && thisAccount.IF_Course_Affirmation__c)) ||
                   ((intPresentTier == 2 && intTierBySquare == 3) && (thisAccount.Safety_Fundamentals_Completed__c && thisAccount.IF_Course_Affirmation__c && thisAccount.Business_Fundamentals_Completed__c && thisAccount.Performance_Fundamentals_Completed__c))||
                  ((intPresentTier == 1 && intTierBySquare == 3) && (thisAccount.Safety_Fundamentals_Completed__c && thisAccount.IF_Course_Affirmation__c))){
					
					tierMovement = 'ASCEND';
					logTierMovement = true;
					addProcessLog(thisAccount, 'Volume & Education Criteria Met', 'Ascended');
					
				}
				else{

					tierMovement = 'MAINTAIN';
					logTierMovement = false;
					addProcessLog(thisAccount, 'Educationnal Criteria Failed', 'No tier movement');
				}
				
			}
			if(tierMovement == 'MAINTAIN') {
				addProcessLog(thisAccount, 'Maintainted', 'Maintainted');
				if(processConfig.processMode == 'DESCEND') {
					logTierMovement = true;
				}
			}

			if(logTierMovement) {
				// get primary admin contact for this contractor
				Contact primaryAdmin = mapAdminContactByContractor.get(thisAccount.Id);

				thisAccount.Present_Tier_Lookup__c = tierBySquareId;
				thisAccount.Prior_Tier__c = presentTier.Tier_Label__c;
				thisAccount.Prior_Tier_Percentage__c = thisAccount.Present_Tier_Percentage__c;
				ThisAccount.Date_Present_Tier__c = processDate;
				updateAccounts.add(thisAccount);

				listTierMovementLogs.add(logicTierMovement.createNewTierMovementLog(processConfig, thisAccount, primaryAdmin, calculatedMonth, totalSquares, isProratedYear, tierMovement, calculatedTier1High, calculatedTier2Low, calculatedTier2High, calculatedTier3Low));
			}
		}

		if(updateAccounts.size() > 0 && !processConfig.isSimulation) {
			logicAccount.saveAccounts(updateAccounts);
		}

		if(listTierMovementLogs.size() > 0 ) {
			logicTierMovement.saveTierMovementLog(listTierMovementLogs);
		}

	}

	global void finish(Database.BatchableContext context) {
		String emailBodyHTML = 'Tier Movement Process ran and completed at : ' + icUtilDatetime.getLocalDateTime(Datetime.now()) + ' <br><br>';
		emailBodyHTML += '<br> Total account processed : ' + totalAccountsProcessed + ' <br><br>';
		
		for(String thisKey : processLogs.keySet()) {
			List<String> processTypeLogs = processLogs.get(thisKey);
			emailBodyHTML += 'Total account ' + thisKey + ' : ' + processTypeLogs.size() + '<br>';

			processTypeLogs.sort();
			for(String thisLog : processTypeLogs) {
				emailBodyHTML += thisLog + '<br>';
			}
			emailBodyHTML += '<br>';
		}

		Messaging.SingleEmailMessage emailOut = new Messaging.SingleEmailMessage(); 

		emailOut.setSubject('Tier Movement Process Results');
		emailOut.setSenderDisplayName('Automated Process');
		emailOut.setToAddresses(new String[] {processConfig.adminEmail});
		emailOut.setHTMLBody(emailBodyHTML);        

		Messaging.sendEmail(new List<Messaging.Email>{emailOut});
	}

	private void addProcessLog(Account relatedAccount, String logType, String logMessage) {
		List<String> logTypeMessages = processLogs.get(logType);

		if(logTypeMessages == null) {
			logTypeMessages = new List<String>();
		}
		logTypeMessages.add(relatedAccount.Name + ' (' + relatedAccount.Id + ') : ' + logMessage);

		processLogs.put(logType, logTypeMessages);
	}
}