ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Admin_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Admin_Email_Address__c</fullName>
    <description>Generic email address for company</description>
    <inlineHelpText>Generic email address for company</inlineHelpText>
    <label>Admin Email Address</label>
    <type>Email</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Applicant_Information__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Information</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
            <value>
                <fullName>Key Customer</fullName>
            </value>
            <value>
                <fullName>Key Target</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Present_Tier__c.field-meta.xml
<CustomField>
    <fullName>Present_Tier__c</fullName>
    <label>Present Tier (picklist)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
                <label>ROOFPRO Preferred</label>
            </value>
            <value>
                <fullName>Tier 2</fullName>
                <label>ROOFPRO Select</label>
            </value>
            <value>
                <fullName>Tier 3</fullName>
                <label>ROOFPRO Craftsman Premier</label>
            </value>
            <value>
                <fullName>Tier 0</fullName>
                <label>Advantage</label>
            </value>
            <value>
                <fullName>Tier 1 - Shield</fullName>
                <isActive>false</isActive>
                <label>Tier 1 - Shield</label>
            </value>
            <value>
                <fullName>Tier 2 - ShieldPRO Plus</fullName>
                <isActive>false</isActive>
                <label>Tier 2 - ShieldPRO Plus</label>
            </value>
            <value>
                <fullName>Tier 3 - ShieldPRO Premier</fullName>
                <isActive>false</isActive>
                <label>Tier 3 - ShieldPRO Premier</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Present_Tier_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Present_Tier_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Tier object to select present tier. Upon selection, flow will change benefits triggered by process builder and the latter will fill prior Tier field.</description>
    <label>Present Tier</label>
    <referenceTo>Tier__c</referenceTo>
    <relationshipLabel>Contractor Accounts with this Tier</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Contractor.recordType-meta.xml
<RecordType>
    <fullName>Contractor</fullName>
    <active>true</active>
    <label>Contractor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <label>Other</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/Bidder__c.object-meta.xml
<CustomObject>
    <description>This object is a junction object between Opportinity, Account and Account, where Account references are of record type US Distributor  and record type US Contractor.</description>
    <label>Bidder</label>
    <nameField>
        <displayFormat>Bid-{000000}</displayFormat>
        <label>Bidder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Contractor_Account__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the Contractorfield must be of type Contractor or  type US Contractor.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bidders (Contractor)</relationshipLabel>
    <relationshipName>Opportunity_Distributor_Contractor</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Distributor_Account__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the Distributor field must be of type Distributor or  type US Distributor.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Distributor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bidders (Distributor)</relationshipLabel>
    <relationshipName>Opportunity_Distributor_Contractor1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Opportunity Record Type should be US Sales Bid</errorMessage>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Sales Bid</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bidders</relationshipLabel>
    <relationshipName>Opportunity_Distributor_Contractor</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Contains the status of Opportunity Won or Loss to this Pair of Opportunity and Distributor</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <description>Is the combination of the Opportunity ID + DistributorID + Contractor ID This field is not visible.</description>
    <label>Unique ID</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/Tier__c.object-meta.xml
<CustomObject>
    <description>Object to manage Tier information (e.g. maximum &amp; minimum amount of squares before Tier change).</description>
    <label>Tier</label>
    <nameField>
        <displayFormat>Tier {0}</displayFormat>
        <label>Tier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/fields/Maximum_Squares__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Squares__c</fullName>
    <label>Maximum Squares</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/fields/Minimum_Squares__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Squares__c</fullName>
    <label>Minimum Squares</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/fields/Percentage_Tier_Invoices__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Tier_Invoices__c</fullName>
    <description>(temp) field to calculate rebate invoice amounts....</description>
    <label>Percentage</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/fields/Tier_Evaluation_Date__c.field-meta.xml
<CustomField>
    <fullName>Tier_Evaluation_Date__c</fullName>
    <defaultValue>TODAY() + 365</defaultValue>
    <label>Tier Evaluation Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/fields/Tier_Label__c.field-meta.xml
<CustomField>
    <fullName>Tier_Label__c</fullName>
    <label>Tier</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icTestHelperDataCreator.cls
/***********
 * Test Class Created to regroup all data creation in test classes. 
 * Creator : Dominic Boivin 
 * Creation Date : 2020-08-18
 ***********/
public with sharing class icTestHelperDataCreator {
    //Method moved from icTestHelperUtility
    public static Account generateAccount() {

		Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('IKO ROOFPRO APPLICANTS').getRecordTypeId();
		Account newAccount = new Account(Name = 'Account Name');
		newAccount.RecordTypeId = recordTypeId;
		newAccount.BillingPostalCode = 'H3X2K8';
		//newAccount.Applicant_Information__c = newContact.Id;
		return newAccount;
    }
    //Method moved from icTestHelperUtility
	public static Account generateOtherAccount() {

		Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('IKO ROOFPRO APPLICANTS').getRecordTypeId();
		Account newAccount = new Account();
		newAccount.Name = icTestHelperUtility.generateRandomString(14);
		newAccount.Customer_Type__c = 'Customer';
		newAccount.Admin_Email_Address__c = icTestHelperUtility.generateRandomString(5) + '@' + icTestHelperUtility.generateRandomString(10) + '.com';
		newAccount.BillingCountryCode = 'CA';
		newAccount.BillingCity = icTestHelperUtility.generateRandomString(10);
		newAccount.BillingStateCode = 'QC';
		newAccount.BillingStreet = '123 street';
		newAccount.BillingPostalCode = 'H3X2K8';
		newAccount.Present_Tier__c = 'Tier 1';
		newAccount.Type = 'Other';
		newAccount.Phone = '555-555-5555';
		newAccount.RecordTypeId = recordTypeId;
		//newAccount.Applicant_Information__c = newContact.Id;
		return newAccount;

	}
    //Method moved from icTestHelperUtility
	public static Account generateContractorAccount(){
		Account applicantAccount = generateAccount();
		insert applicantAccount;

		Contact newContact = new Contact();
		newContact.FirstName = 'Applicant';
		newContact.LastName = 'Contact';
		newContact.AccountId = applicantAccount.Id;
		insert newContact;

		Tier__c accountTier = createTestTier();

		Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('IKOPRO Contractor').getRecordTypeId();

		Account newAccount = new Account(Name = 'Account Name');
		newAccount.RecordTypeId = recordTypeId;
		newAccount.Applicant_Information__c = newContact.Id;
		newAccount.Present_Tier_Lookup__c = accountTier.Id;
		
		return newAccount;
	}

	public static Opportunity generateOpportunityByRecordType(String recordTypeName,Id OpportunityAccountId){
		Id recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
		Opportunity newOpportunity = new Opportunity();
		if (recordTypeName == 'US Sales Bid'){
			newOpportunity.Name = 'Test Name' ;
			newOpportunity.RecordTypeId = recordTypeId;
			newOpportunity.CloseDate = Date.today()+90;
			newOpportunity.AccountId = OpportunityAccountId;
            newOpportunity.StageName = 'Preparing Quotes';	
            newOpportunity.Quote_Approved__c = false; 
		}
		else {
			newOpportunity = null;
		}
		return newOpportunity;        
	}

	public static Account generateAccountByRecordType(String recordTypeName){
		
		Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
		Account newAccount = new Account();
		newAccount.RecordTypeId = recordTypeId;
		String randomName = icTestHelperUtility.generateRandomString(10);
		if (recordTypeName == 'US Contractor'){
			newAccount.Name = 'Unit Test US Contractor ' + randomName;
			newAccount.BillingPostalCode = 'H3X2K8';
		}
		else if (recordTypeName == 'US Distributor'){
			newAccount.Name = 'Unit Test US Distributor' + randomName;
			newAccount.BillingPostalCode = 'H3P2K8';
		}
		else if (recordTypeName == 'Building Location'){
			newAccount.Name = 'Unit Test Building Location' +  randomName;
			newAccount.BillingPostalCode = 'H3P2P8';
		}
		else {
			newAccount = null;
		}
		return newAccount;        
	}

	public static Bidder__c generateBidder(Opportunity opportunity, Account distributor, Account contractor, String status) {
		Bidder__c newBidder = new Bidder__c();
		newBidder.Opportunity__c	= opportunity.Id;
        newBidder.Distributor_Account__c = distributor.Id;
        newBidder.Contractor_Account__c = contractor.Id;
        newBidder.Unique_ID__c = opportunity.Id + '' + distributor.Id + '' + contractor.Id;
        newBidder.Status__c = status;
		return newBidder;
	}

	public static Tier__c createTestTier(){

		Tier__c testTier = new Tier__c();
		testTier.Maximum_Squares__c = 2499;
		testTier.Minimum_Squares__c = 1;
		testTier.Percentage_Tier_Invoices__c = 20.0;
		testTier.Tier_Label__c = 'Test Tier';
		testTier.Tier_Evaluation_Date__c = Date.today().addDays(30);
		insert testTier;
		return testTier;
	}
    
    public static OpportunityLineItem createOpportunityLineItemWithoutPriceStructure(Opportunity opportunity, Boolean insertData){
        Pricebook2 priceBook = createPricebook('Example Price Book', 'This is the Price Book description.', true, true);
		opportunity.Pricebook2Id = priceBook.id;
		update Opportunity;
		Product2 product = createProduct2('Example Product', 'This is the Product description.','Product Code', true,true); 
        // Get the Standard Price Book ID
        Id StandardPriceBookId =  Test.getStandardPricebookId(); 
        // Insert the Product in the Standard Price Book (if necessary)
        PricebookEntry standardPriceBookEntry = createPriceBookEntry(StandardPriceBookId,product.Id, 0.0,false,true,true);
		// Insert the Product in the New Price Book
		
        PricebookEntry priceBookEntry = createPriceBookEntry(priceBook.Id,product.Id, 100.0,false,true,true);
        OpportunityLineItem opportunityLineItem = createOpportunityLineItem(opportunity.Id, product ,priceBookEntry.Id,3,3.50,insertData);
        return opportunityLineItem;
    }

    public static Pricebook2 createPricebook(String name, String description,Boolean isActive, Boolean insertData) {
        Pricebook2 priceBook = new Pricebook2(
            Name = name,
            Description = description,
            IsActive = isActive
        );

        if (insertData){
            insert priceBook;    
        }
        return priceBook;
    }

    public static Product2  createProduct2(String name, String description, String productCode, Boolean isActive, Boolean insertData){
        // Create a Product
        Product2 product = new Product2(
            Name =name,
            Description = description,
            ProductCode = productCode,
            Unit_of_Measure__c = 'BD',
            IsActive = true
        );
        if (insertData){
            insert product;
        }
        return product;
    }

    public static PricebookEntry createPriceBookEntry(Id priceBook2Id, Id productId, Decimal unitPrice, Boolean useStandardPrice,Boolean isActive,Boolean insertData){
         PricebookEntry priceBookEntry = new PricebookEntry(
            Pricebook2Id = priceBook2Id,
            Product2Id =productId,
            UnitPrice = unitPrice,
            UseStandardPrice = useStandardPrice,
            IsActive = isActive
        );
        if (insertData){
            insert priceBookEntry;
        }
        return priceBookEntry;
    }

    public static OpportunityLineItem createOpportunityLineItem(Id opportunityId, Product2 product, Id priceBookEntryId, Integer quantity, Decimal unitPrice, Boolean insertData ){
        //Create the LineItem for the opportunity
        OpportunityLineItem newOpportunityLineItem = new OpportunityLineItem(
            OpportunityId = opportunityId,
            PricebookEntryId = priceBookEntryId,
            Product2Id = product.Id,
            Quantity = quantity,
            UnitPrice = unitPrice
        );
        if (insertData){
            insert newOpportunityLineItem;
        }
        return newOpportunityLineItem;
    }
}