ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Admin_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Admin_Email_Address__c</fullName>
    <description>Generic email address for company</description>
    <inlineHelpText>Generic email address for company</inlineHelpText>
    <label>Admin Email Address</label>
    <type>Email</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/BillingStateCode__c.field-meta.xml
<CustomField>
    <fullName>BillingStateCode__c</fullName>
    <formula>TEXT(BillingStateCode)</formula>
    <label>BillingStateCode</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Business_Operating_Language_ROOFPRO__c.field-meta.xml
<CustomField>
    <fullName>Business_Operating_Language_ROOFPRO__c</fullName>
    <defaultValue>&quot;English&quot;</defaultValue>
    <inlineHelpText>Language for communications (emails) you receive regarding the ROOFPRO Portal.</inlineHelpText>
    <label>Business Operating Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Operating_Languages</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Contractor_Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Name_Formula__c</fullName>
    <description>Displays name of the contractor account without the &quot;(ROOFPRO)&quot; appended.</description>
    <formula>IF(RIGHT(Name, 10) = &quot; (ROOFPRO)&quot;, 
LEFT( Name , LEN(Name) - 10 ), 
IF(RIGHT(Name, 14) = &quot; (CRC RoofPRO)&quot;, 
LEFT( Name , LEN(Name) - 14 ), 
Name))</formula>
    <label>Contractor</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/CS_Sync_Required__c.field-meta.xml
<CustomField>
    <fullName>CS_Sync_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CS Sync Required</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/DBA_Account__c.field-meta.xml
<CustomField>
    <fullName>DBA_Account__c</fullName>
    <description>Populated with Provision Access flow for non-SPP ROOFPRO Accounts</description>
    <label>DBA (Doing Business As)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IKO_com__c.field-meta.xml
<CustomField>
    <fullName>IKO_com__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field with initial value taken from the ROOFPRO Applicant. 
Used for Data sync with IKO.com.</description>
    <label>I want to be listed on IKO.com</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IKOPRO_QueueID__c.field-meta.xml
<CustomField>
    <fullName>IKOPRO_QueueID__c</fullName>
    <description>ID for Queue created upon enabling Contractor as Partner Account. This ID will be used to assign all incoming leads from the partner&apos;s web form to the Queue as Lead Owner.
The Queue ID is populated upon creation of the Queue via Flow.</description>
    <externalId>true</externalId>
    <label>IKOPRO_QueueID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Tier_Prozone__c.field-meta.xml
<CustomField>
    <fullName>Tier_Prozone__c</fullName>
    <description>Field used for Sync Fields functionality (API Call) with PROZONE (ROOFPRO).</description>
    <formula>CASE(Present_Tier_Lookup__r.Name,
&quot;Tier 1&quot;, &quot;ROOFPRO PREFERRED&quot;,
&quot;Tier 2&quot;, &quot;ROOFPRO SELECT&quot;,
&quot;Tier 3&quot;, &quot;ROOFPRO CRAFTSMAN PREMIER&quot;,
&quot;Tier 0&quot;, &quot;Advantage&quot;,
&quot;No Tier Chosen&quot;)

/*Old Formula
CASE(Present_Tier_Lookup__r.Name,
&quot;Tier 1&quot;, &quot;ROOFPRO PREFERRED&quot;,
&quot;Tier 2&quot;, &quot;ROOFPRO SELECT&quot;,
&quot;Tier 3&quot;, &quot;ROOFPRO CRAFTSMAN PREMIER&quot;,
&quot;No Tier Chosen&quot;)*/</formula>
    <label>Tier (Prozone)</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icBatchCSSyncProcess.cls
global class icBatchCSSyncProcess implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts  {

	
	icServiceCentralStation.IClass csService = (icServiceCentralStation.IClass) icObjectFactory.GetSingletonInstance('icServiceCentralStation');
	icLogicAccount.IClass logicAccount = (icLogicAccount.IClass) icObjectFactory.GetSingletonInstance('icLogicAccount');

	global Integer totalAccountsProcessed = 0;
	global Integer totalFailedSync = 0;

	global Database.QueryLocator start(Database.BatchableContext context) {
		return Database.getQueryLocator('SELECT Id, IKOPRO_QueueID__c, Contractor_Name_Formula__c, Phone, BillingStreet, BillingCity, BillingState, BillingStateCode__c, BillingPostalCode, BillingCountry, Tier_Prozone__c, Admin_Email_Address__c, DBA_Account__c, Website, Fax, Business_Operating_Language_ROOFPRO__c, IsPartner, IKO_com__c, CS_Sync_Required__c FROM Account WHERE CS_Sync_Required__c = true');
	}

	global void execute(Database.BatchableContext context, List<Account> scope) {
		totalAccountsProcessed += scope.size();

		for(Account thisAccount : scope) {
			String jsonAccont = logicAccount.serializeAccount(thisAccount);
			Boolean syncSuccessful = csService.syncAccount(thisAccount.Id, jsonAccont);
			if(syncSuccessful) {
				thisAccount.CS_Sync_Required__c = false;
				logicAccount.saveAccount(thisAccount);
			} else {
				totalFailedSync++;
			}
		}
	}

	global void finish(Database.BatchableContext context) {
		String emailBodyHTML = 'Central Station Sync Process ran and completed at : ' + icUtilDatetime.getLocalDateTime(Datetime.now()) + ' <br><br>';
		emailBodyHTML += '<br> Total account sync\'d : ' + totalAccountsProcessed + ' <br><br>';
		emailBodyHTML += '<br> Total failed sync\'d : ' + totalFailedSync + ' <br><br>';
		emailBodyHTML += '<br> Review the error logs for more information (IMT_Incoice_Log) <br><br>';

		Messaging.SingleEmailMessage emailOut = new Messaging.SingleEmailMessage(); 

		emailOut.setSubject('Central Station Sync Process Results');
		emailOut.setSenderDisplayName('Automated Process');
		emailOut.setToAddresses(new String[] {'ROOFPROIT@iko.com'});
		emailOut.setHTMLBody(emailBodyHTML);        

		Messaging.sendEmail(new List<Messaging.Email>{emailOut});
	}
}