ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Annual_Insurance_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Annual_Insurance_Renewal__c</fullName>
    <label>IAAP Annual Hot Works Insurance Renewal</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IAAP_Registered_Highlight__c.field-meta.xml
<CustomField>
    <fullName>IAAP_Registered_Highlight__c</fullName>
    <label>IAAP Registered</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IAAP Registered</fullName>
            </value>
            <value>
                <fullName>IAAP Diamond Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IAP_Registered_Date__c.field-meta.xml
<CustomField>
    <fullName>IAP_Registered_Date__c</fullName>
    <label>IAAP Registered Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IAP_Registration_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>IAP_Registration_Expiry_Date__c</fullName>
    <label>IAAP Registration Expiry Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration #</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Registration_Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Sequence_Number__c</fullName>
    <description>Used to track the sequence number to apply to the Registeration # field; should be read-only to all users by system users</description>
    <label>Registration Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Warranty__c.field-meta.xml
<CustomField>
    <fullName>Warranty__c</fullName>
    <label>Warranty</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Labour &amp; Materials</fullName>
            </value>
            <value>
                <fullName>Diamond Shield</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Contractor.recordType-meta.xml
<RecordType>
    <fullName>Contractor</fullName>
    <active>true</active>
    <label>Contractor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/Warranty__c.object-meta.xml
<CustomObject>
    <description>Used to track Warranties for Residential and Commercial installations</description>
    <label>Warranty</label>
    <nameField>
        <label>Warranty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warranties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Building where the product is installed</description>
    <label>Building</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Account must be of Record Type Building Location</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Building Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Warranties (Building)</relationshipLabel>
    <relationshipName>BuildingWarranties</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.
(Contractor should be Record Type of Contractor / US Contractor / IKOPRO Contractor / Residential Account Record Type and Legacy Claim Account = False)</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contractor, US Contractor, IKOPRO Contractor, IKOPRO Contractor, Residential Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Legacy_Claim_Account__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Warranties</relationshipLabel>
    <relationshipName>Warranties</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <inlineHelpText>To track if the Warranty has expired; used as part of duplciate matching rules</inlineHelpText>
    <label>Expired?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Installation_Deficiency_Status__c.field-meta.xml
<CustomField>
    <fullName>Installation_Deficiency_Status__c</fullName>
    <description>CLAIMSV2-38 Deficiencies are noted and must be reporated. You can&apos;t go from &quot;repairs required&quot; to &quot;no deficiencies&quot; because that makes no sense.</description>
    <inlineHelpText>The current status of the deficiencies, if any.</inlineHelpText>
    <label>Installation Deficiency Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Installation_Deficiency_Status</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Registration_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Registration_Prefix__c</fullName>
    <inlineHelpText>Stores the prefix (e.g. 2-char province code) for the Registraiton Number. Used for aggregation when determining next sequence number</inlineHelpText>
    <label>Registration Prefix</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <inlineHelpText>Sequence number for province of the Contractor; leveraged for the Registration # field</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Warranty</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Labor &amp; Membrane</fullName>
            </value>
            <value>
                <fullName>Diamond Shield</fullName>
            </value>
            <value>
                <fullName>ShieldPRO plus+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Warranty_Expired_Date__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Expired_Date__c</fullName>
    <description>This field contains the date time the warranty is switched to Expired.</description>
    <inlineHelpText>This field contains the date time the warranty is switched to Expired.</inlineHelpText>
    <label>Warranty Expired Date</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Warranty_Registration_Id__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Registration_Id__c</fullName>
    <inlineHelpText>Auto-generated registration number based on Province Code (2 char), 5 digit unique numeric (per province) and full year. E.g. ON-10001-2019</inlineHelpText>
    <label>Warranty Registration Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Warranty_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Start_Date__c</fullName>
    <description>This is the start of the warranty period</description>
    <label>Warranty Start Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Warranty_Status__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Status__c</fullName>
    <description>Status of the Warranty</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Expired</fullName>
                <isActive>false</isActive>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Not Issued</fullName>
                <isActive>false</isActive>
                <label>Not Issued</label>
            </value>
            <value>
                <fullName>Registered</fullName>
                <isActive>false</isActive>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Unregistered</fullName>
                <isActive>false</isActive>
                <label>Unregistered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Warranty_Substatus__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Substatus__c</fullName>
    <label>Substatus</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Warranty_Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting documentation</fullName>
            </value>
            <value>
                <fullName>Need Insurance</fullName>
            </value>
            <value>
                <fullName>With Sales</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Invoice Sent</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Not Issued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Warranty_Term__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Term__c</fullName>
    <description>This is the warranty term. 
Numeric values are in years
LT = Life Time
NW = No Warranty</description>
    <label>Warranty Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/WarrantyServiceTest.cls
@isTest
private class WarrantyServiceTest {
	


	@isTest static void testThatRegistrationPrefixSet() {
		Id rt 	= Schema.SObjectType.Account.getRecordTypeInfosByName().get('Contractor').getRecordTypeId();

		Account a1 		= new Account(RecordTypeId = rt, Name = 'Test1', IAAP_Registered_Highlight__c = 'IAAP Registered', Registration__c = 'ON/2010', Registration_Sequence_Number__c = 2010, BillingStateCode = 'ON', BillingCountryCode = 'CA', IAP_Registered_Date__c = date.today(), IAP_Registration_Expiry_Date__c = date.today().addYears(3));
		Account a2 		= new Account(RecordTypeId = rt, Name = 'Test1', IAAP_Registered_Highlight__c = 'IAAP Registered', Registration__c = 'ON/2010', Registration_Sequence_Number__c = 2010, BillingStateCode = 'AB', BillingCountryCode = 'CA', IAP_Registered_Date__c = date.today(), IAP_Registration_Expiry_Date__c = date.today().addYears(3));
		Account a3 		= new Account(RecordTypeId = rt, Name = 'Test1', IAAP_Registered_Highlight__c = 'IAAP Registered', Registration__c = 'ON/2010', Registration_Sequence_Number__c = 2010, BillingStateCode = 'QC', BillingCountryCode = 'CA', IAP_Registered_Date__c = date.today(), IAP_Registration_Expiry_Date__c = date.today().addYears(3));
		insert new List<Account> { a1, a2, a3}; 

		Test.startTest();
		Warranty__c w1  = new Warranty__c(Sequence_Number__c = 10002, Warranty_Registration_Id__c = 'Golden1234', Warranty_Term__c = '10', Contractor__c = a1.Id);
		Warranty__c w2  = new Warranty__c(Sequence_Number__c = 10003, Registration_Prefix__c='AB', Warranty_Registration_Id__c = 'ON-10002-2018', Warranty_Term__c = '10', Contractor__c = a1.Id);
		insert new List<Warranty__c> {w1,w2};

		Warranty__c w1Check 		= [select Id, Registration_Prefix__c from Warranty__c where Id = :w1.Id];
		Warranty__c w2Check 		= [select Id, Registration_Prefix__c from Warranty__c where Id = :w2.Id];

		System.assertEquals(w1Check.Registration_Prefix__c, 'ON', 'Prefix not set correctly on insert');			
		System.assertEquals(w2Check.Registration_Prefix__c, 'AB', 'Trigger should not have overwritten value set');			

		w2.Registration_Prefix__c	= null;
		update w2;


		w2Check 		= [select Id, Registration_Prefix__c from Warranty__c where Id = :w2.Id];
		System.assertEquals(w2Check.Registration_Prefix__c, 'ON', 'Prefix not set correctly on update');			
		Test.stopTest();
	}



	@isTest static void testThatSequenceNumberSetCorrectly() {
		/* initialize some Accounts, Warranties and Sequence Numbers */

		Id rt 	= Schema.SObjectType.Account.getRecordTypeInfosByName().get('Contractor').getRecordTypeId();

		Account a1 		= new Account(RecordTypeId = rt, Name = 'Test1', IAAP_Registered_Highlight__c = 'IAAP Registered', Registration__c = 'ON/2010', Registration_Sequence_Number__c = 2010, BillingStateCode = 'ON', BillingCountryCode = 'CA', IAP_Registered_Date__c = date.today(), IAP_Registration_Expiry_Date__c = date.today().addYears(3));
		Account a2 		= new Account(RecordTypeId = rt, Name = 'Test1', IAAP_Registered_Highlight__c = 'IAAP Registered', Registration__c = 'ON/2010', Registration_Sequence_Number__c = 2010, BillingStateCode = 'AB', BillingCountryCode = 'CA', IAP_Registered_Date__c = date.today(), IAP_Registration_Expiry_Date__c = date.today().addYears(3));
		Account a3 		= new Account(RecordTypeId = rt, Name = 'Test1', IAAP_Registered_Highlight__c = 'IAAP Registered', Registration__c = 'ON/2010', Registration_Sequence_Number__c = 2010, BillingStateCode = 'QC', BillingCountryCode = 'CA', IAP_Registered_Date__c = date.today(), IAP_Registration_Expiry_Date__c = date.today().addYears(3));
		insert new List<Account> { a1, a2, a3}; 

		Test.startTest();
		Warranty__c w1  = new Warranty__c(Sequence_Number__c = 10002, Registration_Prefix__c='ON', Warranty_Registration_Id__c = 'Golden1234', Warranty_Term__c = '10', Contractor__c = a1.Id);
		Warranty__c w2  = new Warranty__c(Sequence_Number__c = 10003, Registration_Prefix__c='ON', Warranty_Registration_Id__c = 'ON-10002-2018', Warranty_Term__c = '10', Contractor__c = a1.Id);
		insert new List<Warranty__c> {w1,w2};


		Warranty__c w3 	= new Warranty__c(Warranty_Term__c = '10', Contractor__c = a2.Id);
		Warranty__c w4 	= new Warranty__c(Warranty_Term__c = '10', Contractor__c = a3.Id);
		Warranty__c w5 	= new Warranty__c(Warranty_Term__c = '10', Contractor__c = a3.Id);
		Warranty__c w6 	= new Warranty__c(Warranty_Term__c = '10', Contractor__c = a1.Id);

		upsert new List<Warranty__c> {w1, w2, w3, w4, w5, w6};


		List<Warranty__c> wCheck 		= [select Id, Warranty_Registration_Id__c from Warranty__c where Id iN : new List<Warranty__c> { w1, w2, w3, w4, w5, w6}];

		for(Warranty__c w : wCheck) {
			if(w.Id == w1.Id) 
				System.assertEquals(w.Warranty_Registration_Id__c, 'Golden1234', 'Warranty should have retained registration number');		
			if(w.Id == w2.Id) 
				System.assertEquals(w.Warranty_Registration_Id__c, 'ON-10002-2018', 'Warranty should have retained registration number');		
			if(w.Id == w3.Id) 
				System.assertEquals(w.Warranty_Registration_Id__c, 'AB-10000-'+date.today().year(), 'First AB Warranty should start at 10000');		
			if(w.Id == w4.Id) 
				System.assertEquals(w.Warranty_Registration_Id__c, 'QC-10000-'+date.today().year(), 'First QC Warranty should start at 10000');		
			if(w.Id == w5.Id) 
				System.assertEquals(w.Warranty_Registration_Id__c, 'QC-10001-'+date.today().year(), 'Second QC Warranty should be 10001');		
			if(w.Id == w6.Id) 
				System.assertEquals(w.Warranty_Registration_Id__c, 'ON-10004-'+date.today().year(), 'Third ON Warranty should increment sequence');		

		}
		Test.stopTest();
	}
	

    /* Ticket CLAIMSV2-624
     * Added condition to display error Message when submitting record for Approval,
     * By: Anil Mannem (Incloud) on 13-May-2020
     */
    @isTest static void testvalidateApprovalSubmission() {

        Id rt1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Contractor').getRecordTypeId();
		Id rt2 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Building Location').getRecordTypeId();

		Account a1 = new Account(RecordTypeId = rt1, Name = 'Test1', IAAP_Registered_Highlight__c = 'IAAP Registered', Registration__c = 'ON/2010', Registration_Sequence_Number__c = 2010, BillingStateCode = 'ON', BillingCountryCode = 'CA', IAP_Registered_Date__c = date.today(), Annual_Insurance_Renewal__c = date.today().addYears(1), IAP_Registration_Expiry_Date__c = date.today().addYears(3));
		Account a2 = new Account(RecordTypeId = rt2, Name = 'Test2', CurrencyIsoCode = 'CAD');
		insert new List<Account> { a1, a2};

		Warranty__c w1 = new Warranty__c(Name = 'Test1', Warranty_Status__c = 'Draft', Warranty_Term__c = '5', Contractor__c = a1.Id, Building__c = a2.Id, Type__c = 'Labor & Membrane');
        Warranty__c w2 = new Warranty__c(Name = 'Test2', Warranty_Status__c = 'Draft', Warranty_Term__c = '5', Contractor__c = a1.Id, Building__c = a2.Id, Type__c = 'Diamond Shield');
		insert new List<Warranty__c> {w1, w2};

        w1.Warranty_Status__c = 'In Progress';
        w1.Warranty_Substatus__c = 'In Review';
		w2.Warranty_Status__c = 'In Progress';
        w2.Warranty_Substatus__c = 'Payment Received';
        w2.Installation_Deficiency_Status__c = 'No Deficiencies';
        try {
	        update new List<Warranty__c> {w1, w2};
        } catch (Exception e) {
            Boolean expectedExceptionThrown =  e.getMessage().contains(System.Label.Approval_Warranty_StartDate) ? true : false;
        	//System.AssertEquals(expectedExceptionThrown, true);
		}
    } //end of testvalidateApprovalSubmission
    
    @isTest static void testUpdateWarrantyExpired() {
        Id rt      = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Contractor').getRecordTypeId();
        
        Account a1                  = new Account(RecordTypeId = rt, Name = 'Test1', IAAP_Registered_Highlight__c = 'IAAP Registered', Registration__c = 'ON/2010', Registration_Sequence_Number__c = 2010, BillingStateCode = 'ON', BillingCountryCode = 'CA', IAP_Registered_Date__c = date.today(), IAP_Registration_Expiry_Date__c = date.today().addYears(3));
        //Account a2                = new Account(RecordTypeId = rt, Name = 'Test1', IAAP_Registered_Highlight__c = 'IAAP Registered', Registration__c = 'ON/2010', Registration_Sequence_Number__c = 2010, BillingStateCode = 'AB', BillingCountryCode = 'CA', IAP_Registered_Date__c = date.today(), IAP_Registration_Expiry_Date__c = date.today().addYears(3));
        //Account a3                = new Account(RecordTypeId = rt, Name = 'Test1', IAAP_Registered_Highlight__c = 'IAAP Registered', Registration__c = 'ON/2010', Registration_Sequence_Number__c = 2010, BillingStateCode = 'QC', BillingCountryCode = 'CA', IAP_Registered_Date__c = date.today(), IAP_Registration_Expiry_Date__c = date.today().addYears(3));
        insert new List<Account> { a1}; 
            
        //Test.startTest();
        Warranty__c w1  = new Warranty__c(Sequence_Number__c = 10002, Registration_Prefix__c='ON', Warranty_Registration_Id__c = 'Golden1234', Warranty_Term__c = '10', Contractor__c = a1.Id, Warranty_Substatus__c = 'Not Issued');
        Warranty__c w2  = new Warranty__c(Sequence_Number__c = 10003, Registration_Prefix__c='ON', Warranty_Registration_Id__c = 'ON-10002-2018', Warranty_Term__c = '10', Contractor__c = a1.Id, Warranty_Start_Date__c = Date.newInstance(2010, 7, 14));
        Warranty__c w3  = new Warranty__c(Name = 'Test1', Warranty_Status__c = 'Draft', Warranty_Term__c = '5', Contractor__c = a1.Id, Type__c = 'Diamond Shield', Warranty_Start_Date__c = null, Warranty_Substatus__c = 'Awaiting documentation');
        insert new List<Warranty__c> {w1,w2,w3};
            
            List<Warranty__c> wCheck  = [select Id, Warranty_Registration_Id__c, Expired__c, Warranty_Expired_Date__c from Warranty__c where Id iN : new List<Warranty__c> { w1, w2, w3 }];
        
        for(Warranty__c w : wCheck) {
            if(w.Id == w1.Id) 
            {
                //System.Debug ('Warranty Expired Date is w1 ' + w.Warranty_Expired_Date__c);
                System.assertEquals(w.Expired__c, 'Yes');
                        System.assertEquals(String.isEmpty(w.Warranty_Expired_Date__c), false);
                
            }
            if(w.Id == w2.Id) 
            {    
                //System.Debug ('Warranty Expired Date is w2 ' + w.Warranty_Expired_Date__c);
                System.assertEquals(w.Expired__c, 'Yes');
                        System.assertEquals(String.isEmpty(w.Warranty_Expired_Date__c), false);
                        
            }
            if(w.Id == w3.Id) 
            {
                //System.Debug ('Warranty Expired Date is w3 ' + w.Warranty_Expired_Date__c);
                System.assertEquals(w.Expired__c, 'No');
                        System.assertEquals(w.Warranty_Expired_Date__c, null);
            }
        }
        //Test.stopTest();
    }
    
}