ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Available_COOP_Funds__c.field-meta.xml
<CustomField>
    <fullName>Available_COOP_Funds__c</fullName>
    <formula>if(AND((COOP_Funds_Credit__c &gt; COOP_Funds_Debit__c),  Present_Tier_Lookup__r.Name &lt;&gt;&quot;Tier 0&quot;),COOP_Funds_Credit__c - COOP_Funds_Debit__c,0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Co-Op Funds</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Available_Premium_COOP_Funds__c.field-meta.xml
<CustomField>
    <fullName>Available_Premium_COOP_Funds__c</fullName>
    <formula>if(AND((Premium_COOP_Funds_Credit__c &gt; Premium_COOP_Funds_Debit__c),Present_Tier_Lookup__r.Name &lt;&gt;&quot;Tier 0&quot;),Premium_COOP_Funds_Credit__c - Premium_COOP_Funds_Debit__c ,0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Premium Cap (Swag)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Expired_Co_Op_Funds__c.field-meta.xml
<CustomField>
    <fullName>Expired_Co_Op_Funds__c</fullName>
    <label>Prior Year Co-Op Funds</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Expired_Premium_Cap__c.field-meta.xml
<CustomField>
    <fullName>Expired_Premium_Cap__c</fullName>
    <label>Prior Year Premium Cap</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Prior_Year_Co_Op_Funds_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Prior_Year_Co_Op_Funds_Remaining__c</fullName>
    <description>This field will hold the last year Coop funds and this amount will decrease as Loyalty Admins will keep approving the last year Reimbursement Claims. This field is populated by batch class icBatchExpireCoopFunds.</description>
    <label>Prior Year Co-Op Funds (Remaining)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Prior_Year_Premium_Cap_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Prior_Year_Premium_Cap_Remaining__c</fullName>
    <description>This field will hold the last year Coop premium cap and this amount will decrease as Loyalty Admins will keep approving the last year Reimbursement Claims. This field is populated by batch class icBatchExpireCoopFunds.</description>
    <label>Prior Year Premium Cap (Remaining)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <label>Account ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Currency_Used__c.field-meta.xml
<CustomField>
    <fullName>Currency_Used__c</fullName>
    <label>Currency Used</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Reason_for_Co_op_Entry__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Co_op_Entry__c</fullName>
    <description>This field needs to be filled by Loyalty Admins when they do a manual entry in the Transaction object.</description>
    <label>Reason for Co-Op Adjustment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Transaction_Sources__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Sources__c</fullName>
    <inlineHelpText>For Coop adjustments, only select &quot;Loyalty Admins&quot; as Transaction Source.</inlineHelpText>
    <label>Sources</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Transaction_Sources</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debit</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Repository/Claims/force-app/main/default/classes/icBatchExpireCoopFunds.cls
global class icBatchExpireCoopFunds implements Database.Batchable<sObject> {

    icLogicAccount.IClass logicAccount = (icLogicAccount.IClass) icObjectFactory.GetSingletonInstance('icLogicAccount');
    icLogicTransaction.IClass logicTransaction = (icLogicTransaction.IClass) icObjectFactory.GetSingletonInstance('icLogicTransaction');
   
    
    global Database.QueryLocator start(Database.BatchableContext context){
        return Database.getQueryLocator('SELECT Id, Name, Available_COOP_Funds__c, Available_Premium_COOP_Funds__c FROM Account LIMIT 2');
    }

    global void execute(Database.BatchableContext context, List<Account> scope){
         List<Transaction__c> listExpiryTransactions = new List<Transaction__c>();

        System.debug('execute Batch with ' + scope.size() + ' records');

        Date dateToday = Date.today();

        for(Account thisAccount : scope) {
            thisAccount.Expired_Co_Op_Funds__c = thisAccount.Available_COOP_Funds__c;
            thisAccount.Expired_Premium_Cap__c = thisAccount.Available_Premium_COOP_Funds__c;
            thisAccount.Prior_Year_Co_Op_Funds_Remaining__c = thisAccount.Available_COOP_Funds__c;
            thisAccount.Prior_Year_Premium_Cap_Remaining__c = thisAccount.Available_Premium_COOP_Funds__c;

            listExpiryTransactions.add(new Transaction__c(
                Account_ID__c = thisAccount.Id,
                Transaction_Date__c = dateToday,
                Transaction_Sources__c = 'Expired Funds',
                Transaction_Type__c = 'Debit',
                Amount__c = thisAccount.Available_COOP_Funds__c,
                Currency_Used__c = 'Co-op $',
                Reason_for_Co_op_Entry__c = 'End of Year: funds expired'));
            listExpiryTransactions.add(new Transaction__c(
                Account_ID__c = thisAccount.Id,
                Transaction_Date__c = dateToday,
                Transaction_Sources__c = 'Expired Funds',
                Transaction_Type__c = 'Debit',
                Amount__c = thisAccount.Available_Premium_COOP_Funds__c,
                Currency_Used__c = 'Premium Co-op $',
                Reason_for_Co_op_Entry__c = 'End of Year: funds expired'));
        }

        System.debug('create ' + listExpiryTransactions.size() + ' expired transactions');

        logicAccount.saveAccounts(scope);
        logicTransaction.createTransactions(listExpiryTransactions);
    }

    global void finish(Database.BatchableContext context){
              
    }
}