ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Available_COOP_Funds__c.field-meta.xml
<CustomField>
    <fullName>Available_COOP_Funds__c</fullName>
    <formula>if(AND((COOP_Funds_Credit__c &gt; COOP_Funds_Debit__c),  Present_Tier_Lookup__r.Name &lt;&gt;&quot;Tier 0&quot;),COOP_Funds_Credit__c - COOP_Funds_Debit__c,0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Co-Op Funds</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Hide_Upcoming_Coop_Rewards__c.field-meta.xml
<CustomField>
    <fullName>Hide_Upcoming_Coop_Rewards__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox is for Loyalty Admins to hide the next year Upcoming Coop Rewards present in the six box tracker.</description>
    <label>Hide Next Year&apos;s Coop Rewards</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IKOPRO_Approved_On__c.field-meta.xml
<CustomField>
    <fullName>IKOPRO_Approved_On__c</fullName>
    <description>Filled with process builder (upon enabling partner)</description>
    <label>Activated On</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IKOPRO_QueueID__c.field-meta.xml
<CustomField>
    <fullName>IKOPRO_QueueID__c</fullName>
    <description>ID for Queue created upon enabling Contractor as Partner Account. This ID will be used to assign all incoming leads from the partner&apos;s web form to the Queue as Lead Owner.
The Queue ID is populated upon creation of the Queue via Flow.</description>
    <externalId>true</externalId>
    <label>IKOPRO_QueueID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Present_Tier_Formula__c.field-meta.xml
<CustomField>
    <fullName>Present_Tier_Formula__c</fullName>
    <formula>Present_Tier_Lookup__r.Tier_Label__c</formula>
    <label>Present Tier Formula</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Rebate Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Repository/Claims/force-app/main/default/classes/icCTRLQuickShot.cls
global with sharing class icCTRLQuickShot {

	static icLogicUser.IClass logicUser = (icLogicUser.IClass) icObjectFactory.GetSingletonInstance('icLogicUser');
	static icLogicAccount.IClass logicAccount = (icLogicAccount.IClass) icObjectFactory.GetSingletonInstance('icLogicAccount');	
	static icLogicLead.IClass logicLead = (icLogicLead.IClass) icObjectFactory.GetSingletonInstance('icLogicLead');
	static icLogicOpportunity.IClass logicOpportunity = (icLogicOpportunity.IClass) icObjectFactory.GetSingletonInstance('icLogicOpportunity');
	static icLogicInvoice.IClass logicInvoice = (icLogicInvoice.IClass) icObjectFactory.GetSingletonInstance('icLogicInvoice');

	@AuraEnabled
	global static icDTOQuickShotInfo getQuickShotInfo(){
		icDTOQuickShotInfo info = new icDTOQuickShotInfo();

		String customerId = logicUser.getAccountIdFromPartnerUser(UserInfo.getUserId());
		Account customer = logicAccount.getAcountInfoById(customerId);
		if(String.isNotBlank(customerId)) {
			info.newLeads = logicLead.getNewLeadsCountByAccountId(customerId, customer.IKOPRO_QueueID__c);
			info.currentOpportunities = logicOpportunity.getCurrentOpportunitiesCountByAccountId(customerId);

			List<Invoice__c> ytdInvoices = logicInvoice.getAllYTDInvoicesByAccountId(customerId);

			info.squaresYTD = logicInvoice.getSquaresFromInvoices(ytdInvoices, false, customer.IKOPRO_Approved_On__c);
			info.pro4Rewards = logicInvoice.getPro4RewardsFromInvoices(ytdInvoices);

			info.coopRewards = customer.Available_COOP_Funds__c == null ? 0 : customer.Available_COOP_Funds__c;
			info.tierLevel = customer.Present_Tier_Formula__c == null ? 0 : Integer.valueOf(customer.Present_Tier_Formula__c);

			info.hideUpcomingCoopRewards = customer.Hide_Upcoming_Coop_Rewards__c;
			info.upcomingCoopRewards = logicInvoice.getUpcomingCoopRewardsFromInvoices(ytdInvoices);
		}

		
		return info;
	}

}