ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Business_Fundamentals_Completed__c.field-meta.xml
<CustomField>
    <fullName>Business_Fundamentals_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Business Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IF_Course_Affirmation__c.field-meta.xml
<CustomField>
    <fullName>IF_Course_Affirmation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Installation Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IKOPRO_Approved_On__c.field-meta.xml
<CustomField>
    <fullName>IKOPRO_Approved_On__c</fullName>
    <description>Filled with process builder (upon enabling partner)</description>
    <label>Activated On</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IsPartner__c.field-meta.xml
<CustomField>
    <fullName>IsPartner__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to capture the value of the &apos;IsPartner&apos; system field, because this one cannot be used within validation rules.</description>
    <label>IsPartner</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Override_Tier_Movement__c.field-meta.xml
<CustomField>
    <fullName>Override_Tier_Movement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The automatic tier movement is restricted when loyalty admins will check this box while changing the contractor tier manually.</description>
    <inlineHelpText>When this checkbox is ticked the automatic tier movement is restricted and the tier will remain the same until the Current Cutoff Date (Maintenance/Descend).</inlineHelpText>
    <label>Override Tier Movement</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Performance_Fundamentals_Completed__c.field-meta.xml
<CustomField>
    <fullName>Performance_Fundamentals_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Performance Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Present_Tier_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Present_Tier_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Tier object to select present tier. Upon selection, flow will change benefits triggered by process builder and the latter will fill prior Tier field.</description>
    <label>Present Tier</label>
    <referenceTo>Tier__c</referenceTo>
    <relationshipLabel>Contractor Accounts with this Tier</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Safety_Fundamentals_Completed__c.field-meta.xml
<CustomField>
    <fullName>Safety_Fundamentals_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Safety Fundamentals Completed</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/IKOPRO_Contractor.recordType-meta.xml
<RecordType>
    <fullName>IKOPRO_Contractor</fullName>
    <active>true</active>
    <description>Used for Contractors who have access to the ROOFPRO Community</description>
    <label>IKOPRO Contractor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/IKOPRO_Contractor_HA_OK.recordType-meta.xml
<RecordType>
    <fullName>IKOPRO_Contractor_HA_OK</fullName>
    <active>true</active>
    <description>For Contractor Layout where Home Advisor Subscription is already active.</description>
    <label>IKOPRO Contractor HA OK</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Account_Payment__c/IKOPRO_Account_Payment__c.object-meta.xml
<CustomObject>
    <label>Contractor Payment</label>
    <nameField>
        <displayFormat>INV - {00000}</displayFormat>
        <label>PaymentID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contractor Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Rebate Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/Tier__c.object-meta.xml
<CustomObject>
    <description>Object to manage Tier information (e.g. maximum &amp; minimum amount of squares before Tier change).</description>
    <label>Tier</label>
    <nameField>
        <displayFormat>Tier {0}</displayFormat>
        <label>Tier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/fields/Maximum_Squares__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Squares__c</fullName>
    <label>Maximum Squares</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/fields/Minimum_Squares__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Squares__c</fullName>
    <label>Minimum Squares</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/fields/Tier_Label__c.field-meta.xml
<CustomField>
    <fullName>Tier_Label__c</fullName>
    <label>Tier</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier_Movement_Setup__c/Tier_Movement_Setup__c.object-meta.xml
<CustomObject>
    <description>This object holds the configuration for the Account Tier Movement for IKOROOFPRO Loyalty Project.</description>
    <label>Tier Movement Setup</label>
    <nameField>
        <displayFormat>TMS - {0}</displayFormat>
        <label>Tier Movement Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tier Movement Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Repository/Claims/force-app/main/default/classes/icTestBatchTierMovementProcess.cls
@isTest
public with sharing class icTestBatchTierMovementProcess {

    public static void initTest() {
        icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicAccount', new icLogicAccountMock());

        icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicAccountPayment', new icLogicAccountPaymentMock());
        icTestMockUtilities.Tracer.SetReturnValue('icLogicAccountPaymentMock', 'getPaidAccountPaymentByYearAndContractorIds', new List<IKOPRO_Account_Payment__c>());

        icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicContact', new icLogicContactMock());
        icTestMockUtilities.Tracer.SetReturnValue('icLogicContactMock', 'getPrimaryAdminContactsByContractorIds', new List<Contact>());
        icTestMockUtilities.Tracer.SetReturnValue('icLogicContactMock', 'getMapPrimaryAdminContactByContractorId', new Map<String, Contact>());

        icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicInvoice', new icLogicInvoiceMock());
        icLogicInvoice.IClass logicInvoice = (icLogicInvoice.IClass) icObjectFactory.GetSingletonInstance('icLogicInvoice');
        icTestMockUtilities.Tracer.SetReturnValue('icLogicInvoiceMock', 'getAllInvoicesByAccountIdsAndRebateYear', new List<Invoice__c>());

        icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicTierMovementLog', new icLogicTierMovementLogMock());

        icTestMockUtilities.Mocker.SetMockSingletonInstance('icHandlerAccount', new icHandlerAccountMock());

        icTestMockUtilities.Tracer.SetReturnValue('icLogicTierMovementSetupMock', 'getTierMovementSetup', new Tier_Movement_Setup__c());
    }

    static testMethod void test_batchDescend_maintain() {
        initTest();

        Date mockDate = Date.newInstance(2020, 03, 24);

        icDtoTierMovementConfig processConfig = new icDtoTierMovementConfig();
        processConfig.sfId = 'configId';
        processConfig.runProcess = true;
        processConfig.isSimulation = false;
        processConfig.processMode = 'DESCEND';
        processConfig.rebateYear = '2019';
        processConfig.adminEmail = 'test@test.com';
        processConfig.startDate = mockDate;
        processConfig.endDate = mockDate;

        Map<String, Tier__c> mapTiers = new Map<String, Tier__c>();
        Tier__c tier1 = new Tier__c();
        //tier1.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier1.Tier_Label__c = '1';
        tier1.Minimum_Squares__c = 0;
        tier1.Maximum_Squares__c = 2999;
        
        Tier__c tier2 = new Tier__c();
        //tier2.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier2.Tier_Label__c = '2';
        tier2.Minimum_Squares__c = 3000;
        tier2.Maximum_Squares__c = 5999;
        
        Tier__c tier3 = new Tier__c();
        //tier3.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier3.Tier_Label__c = '3';
        tier3.Minimum_Squares__c = 6000;
        tier3.Maximum_Squares__c = 1000000;
        
        Tier__c tier0 = new Tier__c();
        //tier3.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier3.Tier_Label__c = '0';
        tier3.Minimum_Squares__c = 0;
        tier3.Maximum_Squares__c = 0;
        
        insert new List<Tier__c> {tier1, tier2, tier3, tier0};
        mapTiers.put(tier1.Id, tier1);
        mapTiers.put(tier2.Id, tier2);
        mapTiers.put(tier3.Id, tier3);
        mapTiers.put(tier0.Id, tier0);

        System.debug('tier1 : ' + tier1.id);
        System.debug('tier2 : ' + tier2.id);
        System.debug('tier3 : ' + tier3.id);

        Map<String, Schema.RecordTypeInfo> mapContractorRecordTypes = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();
        Id contractorRecordTypeId = mapContractorRecordTypes.get('IKOPRO_Contractor').getRecordTypeId();
        Id contractorHAOKRecordTypeId = mapContractorRecordTypes.get('IKOPRO_Contractor_HA_OK').getRecordTypeId();

        Account maintain = new Account(Name = 'maintain'
            ,IKOPRO_Approved_On__c = Date.newInstance(2019, 11, 24)
            ,Override_Tier_Movement__c = false
            ,Present_Tier_Lookup__c = tier2.Id
            ,IsPartner__c = true
            ,RecordTypeId = contractorRecordTypeId
            ,BillingPostalCode = 'h0h 0h0');
        insert new List<Account>{maintain};
            maintain.IsPartner = true;
        update maintain;

        icTestMockUtilities.Tracer.SetReturnValue('icLogicAccountMock', 'evaluateIsProratedYear', false);

        Map<String, IKOPRO_Account_Payment__c> mapPaidRenewalsByContractorIdMock = new Map<String, IKOPRO_Account_Payment__c>();
        mapPaidRenewalsByContractorIdMock.put(maintain.Id, new IKOPRO_Account_Payment__c());
        icTestMockUtilities.Tracer.SetReturnValue('icLogicAccountPaymentMock', 'getMapPaidRenewalByContractorId', mapPaidRenewalsByContractorIdMock);

        Map<String, List<Invoice__c>> mapInvoicesByAccountMock = new Map<String, List<Invoice__c>>();
        Invoice__c invoiceMock = new Invoice__c();
        mapInvoicesByAccountMock.put(maintain.Id, new List<Invoice__c>{invoiceMock});
        icTestMockUtilities.Tracer.SetReturnValue('icLogicInvoiceMock', 'getMapInvoicesByAccount', mapInvoicesByAccountMock);
        icTestMockUtilities.Tracer.SetReturnValue('icLogicInvoiceMock', 'getSquaresFromInvoices', 4000);

        icBatchTierMovementProcess batchClass = new icBatchTierMovementProcess(processConfig, mapTiers);
        Database.executebatch(batchClass);
    }

    static testMethod void test_batchDescend_descend_prorated() {
        initTest();

        Date mockDate = Date.newInstance(2020, 03, 24);

        icDtoTierMovementConfig processConfig = new icDtoTierMovementConfig();
        processConfig.sfId = 'configId';
        processConfig.runProcess = true;
        processConfig.isSimulation = false;
        processConfig.processMode = 'DESCEND';
        processConfig.rebateYear = '2019';
        processConfig.adminEmail = 'test@test.com';
        processConfig.startDate = mockDate;
        processConfig.endDate = mockDate;

        Map<String, Tier__c> mapTiers = new Map<String, Tier__c>();
        Tier__c tier1 = new Tier__c();
        //tier1.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier1.Tier_Label__c = '1';
        tier1.Minimum_Squares__c = 0;
        tier1.Maximum_Squares__c = 2999;
        
        Tier__c tier2 = new Tier__c();
        //tier2.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier2.Tier_Label__c = '2';
        tier2.Minimum_Squares__c = 3000;
        tier2.Maximum_Squares__c = 5999;
        
        Tier__c tier3 = new Tier__c();
        //tier3.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier3.Tier_Label__c = '3';
        tier3.Minimum_Squares__c = 6000;
        tier3.Maximum_Squares__c = 1000000;
        
        Tier__c tier0 = new Tier__c();
        //tier3.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier3.Tier_Label__c = '0';
        tier3.Minimum_Squares__c = 0;
        tier3.Maximum_Squares__c = 0;
        
        insert new List<Tier__c> {tier1, tier2, tier3, tier0};
        mapTiers.put(tier1.Id, tier1);
        mapTiers.put(tier2.Id, tier2);
        mapTiers.put(tier3.Id, tier3);
        mapTiers.put(tier0.Id, tier0);

        Map<String, Schema.RecordTypeInfo> mapContractorRecordTypes = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();
        Id contractorRecordTypeId = mapContractorRecordTypes.get('IKOPRO_Contractor').getRecordTypeId();
        Id contractorHAOKRecordTypeId = mapContractorRecordTypes.get('IKOPRO_Contractor_HA_OK').getRecordTypeId();

        Account prorated = new Account(Name = 'prorated'
            ,IKOPRO_Approved_On__c = Date.newInstance(2019, 11, 24)
            ,Override_Tier_Movement__c = false
            ,Present_Tier_Lookup__c = tier3.Id
            ,IsPartner__c = true
            ,RecordTypeId = contractorRecordTypeId
            ,BillingPostalCode = 'h0h 0h0');
        insert new List<Account>{prorated};
            prorated.IsPartner = true;
        update prorated;

        icTestMockUtilities.Tracer.SetReturnValue('icLogicAccountMock', 'evaluateIsProratedYear', true);

        Map<String, IKOPRO_Account_Payment__c> mapPaidRenewalsByContractorIdMock = new Map<String, IKOPRO_Account_Payment__c>();
        mapPaidRenewalsByContractorIdMock.put(prorated.Id, new IKOPRO_Account_Payment__c());
        icTestMockUtilities.Tracer.SetReturnValue('icLogicAccountPaymentMock', 'getMapPaidRenewalByContractorId', mapPaidRenewalsByContractorIdMock);

        Map<String, List<Invoice__c>> mapInvoicesByAccountMock = new Map<String, List<Invoice__c>>();
        Invoice__c invoiceMock = new Invoice__c();
        mapInvoicesByAccountMock.put(prorated.Id, new List<Invoice__c>{invoiceMock});
        icTestMockUtilities.Tracer.SetReturnValue('icLogicInvoiceMock', 'getMapInvoicesByAccount', mapInvoicesByAccountMock);
        icTestMockUtilities.Tracer.SetReturnValue('icLogicInvoiceMock', 'getSquaresFromInvoices', 10);

        icBatchTierMovementProcess batchClass = new icBatchTierMovementProcess(processConfig, mapTiers);
        Database.executebatch(batchClass);
    }

    static testMethod void test_batchDescend_ommitted() {
        initTest();

        Date mockDate = Date.newInstance(2020, 03, 24);

        icDtoTierMovementConfig processConfig = new icDtoTierMovementConfig();
        processConfig.sfId = 'configId';
        processConfig.runProcess = true;
        processConfig.isSimulation = false;
        processConfig.processMode = 'DESCEND';
        processConfig.rebateYear = '2019';
        processConfig.adminEmail = 'test@test.com';
        processConfig.startDate = mockDate;
        processConfig.endDate = mockDate;

        Map<String, Tier__c> mapTiers = new Map<String, Tier__c>();
        Tier__c tier1 = new Tier__c();
        //tier1.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier1.Tier_Label__c = '1';
        tier1.Minimum_Squares__c = 0;
        tier1.Maximum_Squares__c = 2999;
        
        Tier__c tier2 = new Tier__c();
        //tier2.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier2.Tier_Label__c = '2';
        tier2.Minimum_Squares__c = 3000;
        tier2.Maximum_Squares__c = 5999;
        
        Tier__c tier3 = new Tier__c();
        //tier3.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier3.Tier_Label__c = '3';
        tier3.Minimum_Squares__c = 6000;
        tier3.Maximum_Squares__c = 1000000;
        
        insert new List<Tier__c> {tier1, tier2, tier3};
        mapTiers.put(tier1.Id, tier1);
        mapTiers.put(tier2.Id, tier2);
        mapTiers.put(tier3.Id, tier3);

        Map<String, Schema.RecordTypeInfo> mapContractorRecordTypes = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();
        Id contractorRecordTypeId = mapContractorRecordTypes.get('IKOPRO_Contractor').getRecordTypeId();
        Id contractorHAOKRecordTypeId = mapContractorRecordTypes.get('IKOPRO_Contractor_HA_OK').getRecordTypeId();

        Account ommitActivatedOn = new Account(Name = 'ommitActivatedOn'
            ,IKOPRO_Approved_On__c = Date.newInstance(2020, 03, 24)
            ,Override_Tier_Movement__c = false
            ,Present_Tier_Lookup__c = tier2.Id
            ,IsPartner__c = true
            ,RecordTypeId = contractorRecordTypeId
            ,BillingPostalCode = 'h0h 0h0');
        Account manualOverride = new Account(Name = 'manualOverride'
            ,IKOPRO_Approved_On__c = Date.newInstance(2018, 03, 24)
            ,Override_Tier_Movement__c = true
            ,Present_Tier_Lookup__c = tier2.Id
            ,IsPartner__c = true
            ,RecordTypeId = contractorRecordTypeId
            ,BillingPostalCode = 'h0h 0h0');
        Account noPresentTier = new Account(Name = 'noPresentTier'
            ,IKOPRO_Approved_On__c = Date.newInstance(2018, 03, 24)
            ,Override_Tier_Movement__c = false
            ,IsPartner__c = true
            ,RecordTypeId = contractorRecordTypeId
            ,BillingPostalCode = 'h0h 0h0');
        Account canNotDescend = new Account(Name = 'canNotDescend'
            ,IKOPRO_Approved_On__c = Date.newInstance(2018, 03, 24)
            ,Override_Tier_Movement__c = false
            ,Present_Tier_Lookup__c = tier1.Id
            ,IsPartner__c = true
            ,RecordTypeId = contractorRecordTypeId
            ,BillingPostalCode = 'h0h 0h0');
        Account notRenewed = new Account(Name = 'notRenewed'
            ,IKOPRO_Approved_On__c = Date.newInstance(2019, 11, 24)
            ,Override_Tier_Movement__c = false
            ,Present_Tier_Lookup__c = tier2.Id
            ,IsPartner__c = true
            ,RecordTypeId = contractorRecordTypeId
            ,BillingPostalCode = 'h0h 0h0');        
        insert new List<Account>{ommitActivatedOn, manualOverride, noPresentTier, canNotDescend, notRenewed};

        icTestMockUtilities.Tracer.SetReturnValue('icLogicAccountPaymentMock', 'getMapPaidRenewalByContractorId', new Map<String, IKOPRO_Account_Payment__c>());

        icBatchTierMovementProcess batchClass = new icBatchTierMovementProcess(processConfig, mapTiers);
        Database.executebatch(batchClass);
    }

    static testMethod void test_batchAscend_ascend() {
        initTest();

        Date mockDate = Date.newInstance(2020, 03, 24);

        icDtoTierMovementConfig processConfig = new icDtoTierMovementConfig();
        processConfig.sfId = 'configId';
        processConfig.runProcess = true;
        processConfig.isSimulation = false;
        processConfig.processMode = 'ASCEND';
        processConfig.rebateYear = '2020';
        processConfig.adminEmail = 'test@test.com';
        processConfig.startDate = mockDate;
        processConfig.endDate = mockDate;

        Map<String, Tier__c> mapTiers = new Map<String, Tier__c>();
        Tier__c tier1 = new Tier__c();
        //tier1.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier1.Tier_Label__c = '1';
        tier1.Minimum_Squares__c = 0;
        tier1.Maximum_Squares__c = 2999;
        
        Tier__c tier2 = new Tier__c();
        //tier2.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier2.Tier_Label__c = '2';
        tier2.Minimum_Squares__c = 3000;
        tier2.Maximum_Squares__c = 5999;
        
        Tier__c tier3 = new Tier__c();
        //tier3.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier3.Tier_Label__c = '3';
        tier3.Minimum_Squares__c = 6000;
        tier3.Maximum_Squares__c = 1000000;
        
        Tier__c tier0 = new Tier__c();
        //tier3.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier3.Tier_Label__c = '0';
        tier3.Minimum_Squares__c = 0;
        tier3.Maximum_Squares__c = 0;
        
        insert new List<Tier__c> {tier1, tier2, tier3, tier0};
        mapTiers.put(tier1.Id, tier1);
        mapTiers.put(tier2.Id, tier2);
        mapTiers.put(tier3.Id, tier3);
        mapTiers.put(tier0.Id, tier0);

        Map<String, Schema.RecordTypeInfo> mapContractorRecordTypes = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();
        Id contractorRecordTypeId = mapContractorRecordTypes.get('IKOPRO_Contractor').getRecordTypeId();
        Id contractorHAOKRecordTypeId = mapContractorRecordTypes.get('IKOPRO_Contractor_HA_OK').getRecordTypeId();

        Account ascend = new Account(Name = 'ascend'
            ,IKOPRO_Approved_On__c = Date.newInstance(2019, 11, 24)
            ,Override_Tier_Movement__c = false
            ,Present_Tier_Lookup__c = tier2.Id
            ,IsPartner__c = true
            ,RecordTypeId = contractorRecordTypeId
            ,BillingPostalCode = 'h0h 0h0');
        insert new List<Account>{ascend};
            ascend.IsPartner = true;
            ascend.Safety_Fundamentals_Completed__c = true;
            ascend.IF_Course_Affirmation__c = true;
            ascend.Performance_Fundamentals_Completed__c = true;
            ascend.Business_Fundamentals_Completed__c = true;
        update ascend;

        icTestMockUtilities.Tracer.SetReturnValue('icLogicAccountMock', 'evaluateIsProratedYear', false);

        Map<String, IKOPRO_Account_Payment__c> mapPaidRenewalsByContractorIdMock = new Map<String, IKOPRO_Account_Payment__c>();
        mapPaidRenewalsByContractorIdMock.put(ascend.Id, new IKOPRO_Account_Payment__c());
        icTestMockUtilities.Tracer.SetReturnValue('icLogicAccountPaymentMock', 'getMapPaidRenewalByContractorId', mapPaidRenewalsByContractorIdMock);

        Map<String, List<Invoice__c>> mapInvoicesByAccountMock = new Map<String, List<Invoice__c>>();
        Invoice__c invoiceMock = new Invoice__c();
        mapInvoicesByAccountMock.put(ascend.Id, new List<Invoice__c>{invoiceMock});
        icTestMockUtilities.Tracer.SetReturnValue('icLogicInvoiceMock', 'getMapInvoicesByAccount', mapInvoicesByAccountMock);
        icTestMockUtilities.Tracer.SetReturnValue('icLogicInvoiceMock', 'getSquaresFromInvoices', 9000);

        icBatchTierMovementProcess batchClass = new icBatchTierMovementProcess(processConfig, mapTiers);
        Database.executebatch(batchClass);
    }

    static testMethod void test_batchAscend_ommitted() {
        initTest();

        Date mockDate = Date.newInstance(2020, 03, 24);

        icDtoTierMovementConfig processConfig = new icDtoTierMovementConfig();
        processConfig.sfId = 'configId';
        processConfig.runProcess = true;
        processConfig.isSimulation = false;
        processConfig.processMode = 'ASCEND';
        processConfig.rebateYear = '2020';
        processConfig.adminEmail = 'test@test.com';
        processConfig.startDate = mockDate;
        processConfig.endDate = mockDate;

        Map<String, Tier__c> mapTiers = new Map<String, Tier__c>();
        Tier__c tier1 = new Tier__c();
        //tier1.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier1.Tier_Label__c = '1';
        tier1.Minimum_Squares__c = 0;
        tier1.Maximum_Squares__c = 2999;
        
        Tier__c tier2 = new Tier__c();
        //tier2.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier2.Tier_Label__c = '2';
        tier2.Minimum_Squares__c = 3000;
        tier2.Maximum_Squares__c = 5999;
        
        Tier__c tier3 = new Tier__c();
        //tier3.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier3.Tier_Label__c = '3';
        tier3.Minimum_Squares__c = 6000;
        tier3.Maximum_Squares__c = 1000000;
        
        insert new List<Tier__c> {tier1, tier2, tier3};
        mapTiers.put(tier1.Id, tier1);
        mapTiers.put(tier2.Id, tier2);
        mapTiers.put(tier3.Id, tier3);

        Map<String, Schema.RecordTypeInfo> mapContractorRecordTypes = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();
        Id contractorRecordTypeId = mapContractorRecordTypes.get('IKOPRO_Contractor').getRecordTypeId();
        Id contractorHAOKRecordTypeId = mapContractorRecordTypes.get('IKOPRO_Contractor_HA_OK').getRecordTypeId();

        Account canNotAscend = new Account(Name = 'canNotAscend'
            ,IKOPRO_Approved_On__c = Date.newInstance(2018, 03, 24)
            ,Override_Tier_Movement__c = false
            ,Present_Tier_Lookup__c = tier3.Id
            ,IsPartner__c = true
            ,RecordTypeId = contractorRecordTypeId
            ,BillingPostalCode = 'h0h 0h0');        
        insert new List<Account>{canNotAscend};

        icBatchTierMovementProcess batchClass = new icBatchTierMovementProcess(processConfig, mapTiers);
        Database.executebatch(batchClass);
    }
}