ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Central_Station_Short_URL__c.field-meta.xml
<CustomField>
    <fullName>Central_Station_Short_URL__c</fullName>
    <label>Central Station Short URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IKOPRO_QueueID__c.field-meta.xml
<CustomField>
    <fullName>IKOPRO_QueueID__c</fullName>
    <description>ID for Queue created upon enabling Contractor as Partner Account. This ID will be used to assign all incoming leads from the partner&apos;s web form to the Queue as Lead Owner.
The Queue ID is populated upon creation of the Queue via Flow.</description>
    <externalId>true</externalId>
    <label>IKOPRO_QueueID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icCtrlShortUrl.cls
global with sharing class icCtrlShortUrl {

	static icLogicAccount.IClass logicAccount = (icLogicAccount.IClass) icObjectFactory.GetSingletonInstance('icLogicAccount');
	static icLogicUser.IClass logicUser = (icLogicUser.IClass) icObjectFactory.GetSingletonInstance('icLogicUser');
	static icServiceCentralStation.IClass csService = (icServiceCentralStation.IClass) icObjectFactory.GetSingletonInstance('icServiceCentralStation');

	@AuraEnabled
	global static String getShortUrlFromAccount() {

		String contractorId = logicUser.getAccountIdFromPartnerUser(UserInfo.getUserId());
		Account contractorAccount = logicAccount.getAcountInfoById(contractorId);

		String shortURL;
		if(String.isNotBlank(contractorAccount.Central_Station_Short_URL__c)) {
			shortURL = contractorAccount.Central_Station_Short_URL__c;
		}

		return shortURL;
	}

	@AuraEnabled
	global static String getShortUrl() {

		String contractorId = logicUser.getAccountIdFromPartnerUser(UserInfo.getUserId());
		Account contractorAccount = logicAccount.getAcountInfoById(contractorId);

		String shortURL = csService.getShortUrl(contractorId, contractorAccount.IKOPRO_QueueID__c);

		if(shortURL.startsWith('https://')) {
			contractorAccount.Central_Station_Short_URL__c = shortURL;
			logicAccount.saveAccount(contractorAccount);
		}

		return shortURL;
	}
}