ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/EU_Terms_Code__c.field-meta.xml
<CustomField>
    <fullName>EU_Terms_Code__c</fullName>
    <label>Terms Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/EU_Open_Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>OI-{YYYY}-{0000000}</displayFormat>
        <label>Open Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Account__c.field-meta.xml
<CustomField>
    <fullName>EU_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Open_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Inv_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>EU_Inv_Due_Date__c</fullName>
    <label>Inv Due Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>EU_Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>EU_Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_JDE_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>EU_JDE_Customer_No__c</fullName>
    <label>JDE Customer No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Mapics_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>EU_Mapics_Customer_No__c</fullName>
    <label>Mapics Customer No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Open_Invoice__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Invoice__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Invoice Paid</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Purchase_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Purchase_Order_Number__c</fullName>
    <label>Purchase Order Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Terms_code__c.field-meta.xml
<CustomField>
    <fullName>EU_Terms_code__c</fullName>
    <label>Terms code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Terms_Description__c.field-meta.xml
<CustomField>
    <fullName>EU_Terms_Description__c</fullName>
    <label>Terms Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice__c/fields/EU_Total_Invoice_Value__c.field-meta.xml
<CustomField>
    <fullName>EU_Total_Invoice_Value__c</fullName>
    <label>Total Invoice Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/EU_Open_Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>OIL-{YYYY}-{0000000}</displayFormat>
        <label>Open Invoice Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Amount_Due_Value__c.field-meta.xml
<CustomField>
    <fullName>EU_Amount_Due_Value__c</fullName>
    <label>Amount Due Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Days_Past_Due__c.field-meta.xml
<CustomField>
    <fullName>EU_Days_Past_Due__c</fullName>
    <label># Days Past Due</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Account__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Open_Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Inv_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Inv_Due_Date__c</fullName>
    <label>Invoice Due Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_JDE_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_JDE_Customer_No__c</fullName>
    <label>JDE Customer No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Mapics_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Mapics_Customer_No__c</fullName>
    <label>Mapics Customer No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Open_Invoice__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Open_Invoice__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Invoice Paid</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Order_number_Reference__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Order_number_Reference__c</fullName>
    <label>Order number Reference</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Purchase_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Purchase_Order_Number__c</fullName>
    <label>Purchase Order Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Terms_code__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Terms_code__c</fullName>
    <label>Terms code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Terms_Description__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Terms_Description__c</fullName>
    <label>Terms Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Header_Total_Invoice_Value__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Total_Invoice_Value__c</fullName>
    <label>Total Invoice Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Invoice_Line_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Invoice_Line_Number__c</fullName>
    <externalId>true</externalId>
    <label>Invoice Line Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Open_Invoice__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Invoice__c</fullName>
    <label>Open Invoice</label>
    <referenceTo>EU_Open_Invoice__c</referenceTo>
    <relationshipName>Open_Invoice_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Open_Invoice_Line__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Invoice_Line__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Invoice Line Paid</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Invoice_Line__c/fields/EU_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Order_Number__c</fullName>
    <label>Order Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/InvoiceServicesTestComponentFactory.cls
/**
 * Created by Gerard van Kempen on 2019-12-09.
 * 2019 (C) 4C NV, Mechelen Belgium.
 * Last modified as part of project 'IKO SFDC'.
 */

/**
* @author Gerard van Kempen, 4C NV
* @date 2019
*
* @group Integration Services
*
* @description InvoiceServicesTestComponentFactory aids in the generation of test objects.
*/

@IsTest
public class InvoiceServicesTestComponentFactory {
    public class InvoiceLineTestingTuple {
        public final EU_Open_Invoice_Line__c referenceInvoiceLine;
        public EU_Open_Invoice_Line__c workingInvoiceLine;
        public InvoiceLineTestingTuple(EU_Open_Invoice_Line__c invoiceLine) {
            this.referenceInvoiceLine = invoiceLine.clone();
            this.workingInvoiceLine = invoiceLine.clone();
        }
    }

    public class InvoiceTestingTuple {
        public final EU_Open_Invoice__c referenceInvoice;
        public EU_Open_Invoice__c workingInvoice;
        public InvoiceTestingTuple(EU_Open_Invoice__c invoice) {
            this.referenceInvoice = invoice.clone();
            this.workingInvoice = invoice.clone();
        }
    }

    private static String newRandomString(Integer length) {
        Blob blobKey = Crypto.generateAesKey(128);
        String key = EncodingUtil.convertToHex(blobKey);
        return key.substring(0,length);
    }

    /*******************************************************************************************************************
    * @description Generate a fully populated EU_Open_Invoice_Line__c object wrapped in a testing tuple.
    * @param invoiceNumber a dummy invoice number, not null
    * @param dueValue a dummy due value, not null
    * @param acct a dummy account (may be null)
    * @return an InvoiceLineTestingTuple setup using the provided values, and some random values as to avoid collisions
    * @example
    * InvoiceLineTestingTuple invoiceLineTT = InvoiceServicesTestComponentFactory.newInvoiceLineTestingTuple(invoiceNumber, dueValue, acct);
    */

    public static InvoiceLineTestingTuple newInvoiceLineTestingTuple(String invoiceNumber, Decimal dueValue, Account acct) {
        EU_Open_Invoice_Line__c invoiceLine = new EU_Open_Invoice_Line__c();
        invoiceLine.EU_Days_Past_Due__c = 0;
        if(acct != null) {
            invoiceLine.EU_Header_Account__c = acct.Id;
        }
//        invoiceLine_1.CreatedById; // automatically set
        invoiceLine.CurrencyIsoCode = 'EUR';
        invoiceLine.EU_Header_Inv_Due_Date__c = Date.today().addDays(7);
        invoiceLine.EU_Header_Invoice_Date__c = Date.today();
        invoiceLine.EU_Invoice_Line_Number__c = newRandomString(4);
        invoiceLine.EU_Header_Invoice_Number__c = invoiceNumber;
        invoiceLine.EU_Header_Invoice_Type__c = 'Invoice';
        invoiceLine.EU_Header_JDE_Customer_No__c = newRandomString(16);
//        invoiceLine_1.LastModifiedById; // automatically set
        invoiceLine.EU_Header_Mapics_Customer_No__c = newRandomString(16);
//        invoiceLine_1.EU_Open_Invoice__c; // related Invoice, cannot be set yet
        invoiceLine.EU_Header_Open_Invoice__c = true; // info: what does this field do?
        invoiceLine.EU_Open_Invoice_Line__c = true; // info: what does this field do?
//        invoiceLine_1.Name; // autonumber
        invoiceLine.EU_Order_Number__c = newRandomString(8);
        invoiceLine.EU_Header_Order_number_Reference__c = newRandomString(8);
        invoiceLine.EU_Header_Purchase_Order_Number__c = newRandomString(12);
        invoiceLine.EU_Header_Terms_code__c = newRandomString(5);
        invoiceLine.EU_Header_Terms_Description__c = newRandomString(32);
        invoiceLine.EU_Header_Total_Invoice_Value__c = dueValue * 2.1;
        return new InvoiceLineTestingTuple(invoiceLine);
    }

    /*******************************************************************************************************************
    * @description Generate a fully populated EU_Open_Invoice_Line__c object wrapped in a testing tuple.
    * @param dueValue a dummy due value, not null
    * @param acct a dummy account (may be null)
    * @return an InvoiceLineTestingTuple setup using the provided values, and some random values as to avoid collisions
    * @example
    * InvoiceLineTestingTuple invoiceLineTT = InvoiceServicesTestComponentFactory.newInvoiceLineTestingTuple(dueValue, acct);
    */

    public static InvoiceLineTestingTuple newInvoiceLineTestingTuple(Decimal dueValue, Account acct) {
        return newInvoiceLineTestingTuple(newRandomString(9), dueValue, acct);
    }

    /*******************************************************************************************************************
    * @description Generate a fully populated EU_Open_Invoice_Line__c object wrapped in a testing tuple.
    * @param acct a dummy account (may be null)
    * @return an InvoiceLineTestingTuple setup using the provided values, and some random values as to avoid collisions
    * @example
    * InvoiceLineTestingTuple invoiceLineTT = InvoiceServicesTestComponentFactory.newInvoiceLineTestingTuple(acct);
    */

    public static InvoiceLineTestingTuple newInvoiceLineTestingTuple(Account acct) {
        return newInvoiceLineTestingTuple(1324.65, acct);
    }

    /*******************************************************************************************************************
    * @description Generate a fully populated EU_Open_Invoice_Line__c object wrapped in a testing tuple.
    * @return an InvoiceLineTestingTuple setup using random values as to avoid collisions
    * @example
    * InvoiceLineTestingTuple invoiceLineTT = InvoiceServicesTestComponentFactory.newInvoiceLineTestingTuple();
    */

    public static InvoiceLineTestingTuple newInvoiceLineTestingTuple() {
        return newInvoiceLineTestingTuple(null);
    }

    /*******************************************************************************************************************
    * @description Generate a fully populated EU_Open_Invoice__c object wrapped in a testing tuple.
    * @param invoiceNumber a dummy invoice number, not null
    * @param dueValue a dummy due value, not null
    * @param acct a dummy account (may be null)
    * @return an InvoiceTestingTuple setup using the provided values, and some random values as to avoid collisions
    * @example
    * InvoiceTestingTuple invoiceLineTT = InvoiceServicesTestComponentFactory.InvoiceTestingTuple(invoiceNumber, dueValue, acct);
    */

    public static InvoiceTestingTuple newInvoiceTestingTuple(String invoiceNumber, Decimal dueValue, Account acct) {
        EU_Open_Invoice__c invoice = new EU_Open_Invoice__c();
        if(acct != null) {
            invoice.EU_Account__c = acct.Id;
        }
        invoice.EU_Amount_Due_Value__c = dueValue;
//        testingInvoice_1.CreatedById; // automatically set
        invoice.CurrencyIsoCode = 'EUR';
        invoice.EU_Inv_Due_Date__c = Date.today().addDays(7);
        invoice.EU_Invoice_Date__c = Date.today();
        invoice.EU_Invoice_Number__c = invoiceNumber;
        invoice.EU_Invoice_Type__c = 'Invoice';
        invoice.EU_JDE_Customer_No__c = newRandomString(16);
//        testingInvoice_1.LastModifiedById; // automatically set
        invoice.EU_Mapics_Customer_No__c = newRandomString(16);
//        testingInvoice_1.EU_Open_Invoice__c;
        invoice.EU_Open_Invoice__c = false; // info: what does this field do?
//        testingInvoice_1.Name; // autonumber
        invoice.EU_Order_number_Reference__c = newRandomString(8);
        invoice.EU_Purchase_Order_Number__c = newRandomString(12);
        invoice.EU_Terms_code__c = newRandomString(5);
        invoice.EU_Terms_Description__c = newRandomString(32);
        invoice.EU_Total_Invoice_Value__c = dueValue * 2.1;
        return new InvoiceTestingTuple(invoice);
    }

    /*******************************************************************************************************************
    * @description Generate a fully populated EU_Open_Invoice__c object wrapped in a testing tuple.
    * @param dueValue a dummy due value, not null
    * @param acct a dummy account (may be null)
    * @return an InvoiceTestingTuple setup using the provided values, and some random values as to avoid collisions
    * @example
    * InvoiceTestingTuple invoiceLineTT = InvoiceServicesTestComponentFactory.InvoiceTestingTuple(dueValue, acct);
    */

    public static InvoiceTestingTuple newInvoiceTestingTuple(Decimal dueValue, Account acct) {
        return newInvoiceTestingTuple(newRandomString(9), dueValue, acct);
    }

    /*******************************************************************************************************************
    * @description Generate a fully populated EU_Open_Invoice__c object wrapped in a testing tuple.
    * @param acct a dummy account (may be null)
    * @return an InvoiceTestingTuple setup using the provided values, and some random values as to avoid collisions
    * @example
    * InvoiceTestingTuple invoiceLineTT = InvoiceServicesTestComponentFactory.InvoiceTestingTuple(acct);
    */

    public static InvoiceTestingTuple newInvoiceTestingTuple(Account acct) {
        return newInvoiceTestingTuple(1324.65, acct);
    }

    /*******************************************************************************************************************
    * @description Generate a fully populated EU_Open_Invoice__c object wrapped in a testing tuple.
    * @return an InvoiceTestingTuple setup using random values as to avoid collisions
    * @example
    * InvoiceTestingTuple invoiceLineTT = InvoiceServicesTestComponentFactory.InvoiceTestingTuple();
    */

    public static InvoiceTestingTuple newInvoiceTestingTuple() {
        return newInvoiceTestingTuple(null);
    }
}