ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IKO_Division_Visible_to__c.field-meta.xml
<CustomField>
    <fullName>IKO_Division_Visible_to__c</fullName>
    <description>This field is to check if the created accounts are Decra.</description>
    <label>IKO Division Visible to</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warranty_and_Claim_Sectors</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Claim_Stage__c.field-meta.xml
<CustomField>
    <fullName>Claim_Stage__c</fullName>
    <description>Used to track the high level stages of the Claim</description>
    <label>Claim Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Awaiting Docs</fullName>
            </value>
            <value>
                <fullName>In Kankakee</fullName>
            </value>
            <value>
                <fullName>In Lab</fullName>
            </value>
            <value>
                <fullName>File Preparation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warranty_and_Claim_Sectors</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <description>Object to manage credit notes or check requests to pay home owner, customer (dealer), or a third party.</description>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Payment_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Payment_Request__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Payment_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Payment_Request__c/fields/Second_Payee__c.field-meta.xml
<CustomField>
    <fullName>Second_Payee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The second contact payee</description>
    <inlineHelpText>The second contact payee</inlineHelpText>
    <label>Second Payee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Requests (Second Payee)</relationshipLabel>
    <relationshipName>Second_Payee</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/PaymentRequestService.cls
public with sharing class PaymentRequestService {

	/*
		Block all updates for Case when the Claim_Stage__c is Closed, *unless* it is being re-opened
	*/
	public static void blockCreatedUpdateDelete(List<Payment_Request__c> records) {
		User runningUser = [SELECT Id, Profile.Name FROM User WHERE Id = :UserInfo.getUserId()];

		Map<Id, RecordType> claimRecordTypes = CaseService.getClaimRecordTypes();
		List<Id> caseIds = new List<Id>();

		for (Payment_Request__c rp : records)
			caseIds.add(rp.Case__c);

		Map<Id, Case> caseMap = new Map<Id, Case>([
				SELECT Id, RecordTypeId, Claim_Stage__c
				FROM Case
				WHERE Id IN :caseIds AND RecordTypeId IN :claimRecordTypes.keySet() AND Claim_Stage__c = 'Closed']);

		if (caseMap.isEmpty())
			return;

		for (Payment_Request__c rp : records) {
			if (caseMap.get(rp.Case__c) <> NULL && runningUser.Profile.Name != 'System Administrator') {
				rp.addError('Payment Requests cannot be modified for a closed case');
			}
		}
	}


	public static void checkValidationForDecra(List<Payment_Request__c> records, Map<Id, Payment_Request__c> oldMap){

		set<Id> accountIds = new Set<Id>();
		set<Id> contactIds = new Set<Id>();
		set<Id> caseIds = new Set<Id>();
        Map<Id, Account> accountsMap = new Map<Id, Account>();
		Map<Id, Contact> contactsMap = new Map<Id, Contact>();
		Map<Id, Case> caseMap = new Map<Id, Case>();
        List<Payment_Request__c> paymentsToProcess = new List<Payment_Request__c>();
        for(Payment_Request__c paymentRequestObj : records){
            
				System.debug('before if condition');
                if(oldMap == null || (oldMap.get(paymentRequestObj.Id).Second_Payee__C != paymentRequestObj.Second_Payee__C 
                                        || oldMap.get(paymentRequestObj.Id).Account__c != paymentRequestObj.Account__c 
                                        || oldMap.get(paymentRequestObj.Id).Contact__C != paymentRequestObj.Contact__C 
                                       ))
                {
					System.debug('coming till here in the if condition');
                    if(paymentRequestObj.Account__C != null){
                        accountIds.add(paymentRequestObj.Account__C);
                    }
    
                    if(paymentRequestObj.Contact__C != null){
                        contactIds.add(paymentRequestObj.Contact__C);
                    }
    
                    if(paymentRequestObj.Second_Payee__C != null){
                        contactIds.add(paymentRequestObj.Second_Payee__C);
                    }
    
                   
					paymentsToProcess.add(paymentRequestObj);
					caseIds.add(paymentRequestObj.Case__c);
                }
            
		}

		if(!accountIds.isEmpty()){
            accountsMap = new Map<Id, Account>([SELECT Id, Iko_Division_Visible_To__c FROM Account WHERE Id IN :accountIds]);
        }

        if(!contactIds.isEmpty()){
            contactsMap = new Map<Id, Contact>([SELECT Id, Account.Iko_Division_Visible_To__c, AccountId FROM Contact WHERE Id IN :contactIds]);
		}
		
		if(!caseIds.isEmpty()){
			caseMap = new Map<Id, Case>([SELECT Id, Payment_Request__c, Sector__C FROM  Case WHERE ID IN : caseIds]);
		}
		System.debug('accountsMap' + accountsMap);
		for(Payment_Request__c paymentRequestObj : paymentsToProcess){
        {
			if(paymentRequestObj.Case__c != null && caseMap.get(paymentRequestObj.Case__c).Sector__C == 'Decra' )
			{
           
                if(paymentRequestObj.Account__C != null){
					System.debug('coming till here');
                    if(accountsMap.get(paymentRequestObj.Account__C).Iko_Division_Visible_To__c != 'Decra'){
						System.debug('coming  not till here');
                        paymentRequestObj.addError('Please select decra account');
                    }
                }

                if(paymentRequestObj.Contact__C != null){
                    if(contactsMap.get(paymentRequestObj.Contact__C).AccountId != null && contactsMap.get(paymentRequestObj.Contact__C).Account.Iko_Division_Visible_To__c != 'Decra'){
                        paymentRequestObj.addError('Please select Decra contact');
                    }
                }

                if(paymentRequestObj.Second_Payee__C != null){
                    if(contactsMap.get(paymentRequestObj.Second_Payee__C).AccountId != null && contactsMap.get(paymentRequestObj.Second_Payee__C).Account.Iko_Division_Visible_To__c != 'Decra'){
                        paymentRequestObj.addError('Please select Decra  second payee');
                    }
                }

            }else{

                if(paymentRequestObj.Account__C != null){
                    if(accountsMap.get(paymentRequestObj.Account__C).Iko_Division_Visible_To__c == 'Decra'){
                        paymentRequestObj.addError('Please select non Decra account');
                    }
                }


                if(paymentRequestObj.Contact__c != null){
                    if(contactsMap.get(paymentRequestObj.Contact__C).AccountId != null && contactsMap.get(paymentRequestObj.Contact__C).Account.Iko_Division_Visible_To__c == 'Decra'){
                        paymentRequestObj.addError('Please select non Decra contact');
                    }
                }

                if(paymentRequestObj.Second_Payee__C != null){
                    if(contactsMap.get(paymentRequestObj.Second_Payee__C).AccountId != null && contactsMap.get(paymentRequestObj.Second_Payee__C).Account.Iko_Division_Visible_To__c == 'Decra'){
                        paymentRequestObj.addError('Please select non Decra second payee');
                    }
                }

               
            }

        }

	}
	}
}