ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IKOPRO_Approved_On__c.field-meta.xml
<CustomField>
    <fullName>IKOPRO_Approved_On__c</fullName>
    <description>Filled with process builder (upon enabling partner)</description>
    <label>Activated On</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/IsPartner__c.field-meta.xml
<CustomField>
    <fullName>IsPartner__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to capture the value of the &apos;IsPartner&apos; system field, because this one cannot be used within validation rules.</description>
    <label>IsPartner</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Override_Tier_Movement__c.field-meta.xml
<CustomField>
    <fullName>Override_Tier_Movement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The automatic tier movement is restricted when loyalty admins will check this box while changing the contractor tier manually.</description>
    <inlineHelpText>When this checkbox is ticked the automatic tier movement is restricted and the tier will remain the same until the Current Cutoff Date (Maintenance/Descend).</inlineHelpText>
    <label>Override Tier Movement</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Present_Tier_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Present_Tier_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Tier object to select present tier. Upon selection, flow will change benefits triggered by process builder and the latter will fill prior Tier field.</description>
    <label>Present Tier</label>
    <referenceTo>Tier__c</referenceTo>
    <relationshipLabel>Contractor Accounts with this Tier</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/IKOPRO_Contractor.recordType-meta.xml
<RecordType>
    <fullName>IKOPRO_Contractor</fullName>
    <active>true</active>
    <description>Used for Contractors who have access to the ROOFPRO Community</description>
    <label>IKOPRO Contractor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/Tier__c.object-meta.xml
<CustomObject>
    <description>Object to manage Tier information (e.g. maximum &amp; minimum amount of squares before Tier change).</description>
    <label>Tier</label>
    <nameField>
        <displayFormat>Tier {0}</displayFormat>
        <label>Tier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/fields/Maximum_Squares__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Squares__c</fullName>
    <label>Maximum Squares</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/fields/Minimum_Squares__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Squares__c</fullName>
    <label>Minimum Squares</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/fields/Tier_Label__c.field-meta.xml
<CustomField>
    <fullName>Tier_Label__c</fullName>
    <label>Tier</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icTestCTRLProzone.cls
/**
 * Created by Andrea Pissinis on 2018-09-13.
 */
@isTest
public with sharing class icTestCTRLProzone {

    public static testMethod void test_userCTRL(){
        Map<String, Schema.RecordTypeInfo> mapContractorRecordTypes = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();
        Id contractorRecordTypeId = mapContractorRecordTypes.get('IKOPRO_Contractor').getRecordTypeId();
        Tier__c tier3 = new Tier__c();
        //tier3.Id = icTestHelperUtility.getFakeId(Tier__c.SObjectType);
        tier3.Tier_Label__c = '3';
        tier3.Minimum_Squares__c = 6000;
        tier3.Maximum_Squares__c = 1000000;
        insert tier3;
        Account prorated = new Account(Name = 'prorated'
            ,IKOPRO_Approved_On__c = Date.newInstance(2019, 11, 24)
            ,Override_Tier_Movement__c = false
            ,Present_Tier_Lookup__c = tier3.Id
            ,IsPartner__c = true
            ,RecordTypeId = contractorRecordTypeId
            ,BillingPostalCode = 'h0h 0h0');
        insert new List<Account>{prorated};
            prorated.IsPartner = true;
        update prorated;
        icCTRLProzone.getCurrentTheme();
        icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicUser', new icLogicUserMock());
        icTestMockUtilities.Tracer.SetReturnValue('icLogicUserMock', 'getAccountIdFromPartnerUser', 'test');
		icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicAccount', new icLogicAccountMock());
        icTestMockUtilities.Tracer.SetReturnValue('icLogicAccountMock', 'getAcountInfoById', prorated);
        icCTRLProzone.getProzoneRemoteAuthDetails(prorated.Id);
    }

}