ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Last_Month_Dollars__c.field-meta.xml
<CustomField>
    <fullName>Last_Month_Dollars__c</fullName>
    <description>Order Summary roll up fields. Rolls up the dollar amount of the customer&apos;s Shipped Orders for the previous month.</description>
    <label>Last Month[$]</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Last_Year_Month_Dollars__c.field-meta.xml
<CustomField>
    <fullName>Last_Year_Month_Dollars__c</fullName>
    <inlineHelpText>The customer&apos;s order total for the previous month in the previous year. Useful for year over year comparisons.</inlineHelpText>
    <label>Last Year Month [$]</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Order_Summary_Bundles_Current_YTD__c.field-meta.xml
<CustomField>
    <fullName>Order_Summary_Bundles_Current_YTD__c</fullName>
    <label>Order Summary - Bundles Current YTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Order_Summary_Bundles_Previous_Year__c.field-meta.xml
<CustomField>
    <fullName>Order_Summary_Bundles_Previous_Year__c</fullName>
    <label>Order Summary - Bundles Previous Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Order_Summary_Bundles_Previous_YTD__c.field-meta.xml
<CustomField>
    <fullName>Order_Summary_Bundles_Previous_YTD__c</fullName>
    <label>Order Summary - Bundles Previous YTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Order_Summary_Last_Month_Qty__c.field-meta.xml
<CustomField>
    <fullName>Order_Summary_Last_Month_Qty__c</fullName>
    <description>The sum of the quantities on orders from the month prior to the current month&apos;s data upload. Note that that on the 1st of May this would still show data for MARCH since the APRIL upload would not be received until a few days into the month.</description>
    <inlineHelpText>The sum of the quantities on orders from the month prior to the current month&apos;s data upload. Note that that on the 1st of May this would still show data for MARCH since the APRIL upload would not be received until a few days into the month.</inlineHelpText>
    <label>Order Summary - Last Month Qty</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Order_Summary_Last_Month_Year_Qty__c.field-meta.xml
<CustomField>
    <fullName>Order_Summary_Last_Month_Year_Qty__c</fullName>
    <label>Order Summary - Last Month &amp; Year Qty</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Order_Summary_Month__c.field-meta.xml
<CustomField>
    <fullName>Order_Summary_Month__c</fullName>
    <description>The month which the order summary values apply to. This should help avoid confusion on, for example, the second day of March when the numbers are still for January because April&apos;s haven&apos;t been received yet.</description>
    <inlineHelpText>The month which the order summary values apply to.</inlineHelpText>
    <label>Order Summary: Month</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Order_Summary_Previous_Year_Full__c.field-meta.xml
<CustomField>
    <fullName>Order_Summary_Previous_Year_Full__c</fullName>
    <label>Order Summary - Previous Year (Full)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Order_Summary_Quantity_Previous_Year__c.field-meta.xml
<CustomField>
    <fullName>Order_Summary_Quantity_Previous_Year__c</fullName>
    <description>Calculated by batch class.</description>
    <inlineHelpText>Total quantity shipped for all units in the previous year.</inlineHelpText>
    <label>Order Summary - Quantity Previous Year</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Previous_Year_YTD_Dollars__c.field-meta.xml
<CustomField>
    <fullName>Previous_Year_YTD_Dollars__c</fullName>
    <inlineHelpText>Previous year&apos;s sales YTD. If it&apos;s August, September to December won&apos;t appear here.</inlineHelpText>
    <label>Previous Year YTD [$]</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Previous_Year_YTD_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Previous_Year_YTD_Quantity__c</fullName>
    <inlineHelpText>Rollup of the customer&apos;s shipped orders from the previous calendar year as measured by quantity.</inlineHelpText>
    <label>Previous Year YTD [QTY]</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/YTD_Dollars__c.field-meta.xml
<CustomField>
    <fullName>YTD_Dollars__c</fullName>
    <description>Order Summary year to date dollars total for all shipped orders.</description>
    <label>YTD[$]</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/YTD_Quantity__c.field-meta.xml
<CustomField>
    <fullName>YTD_Quantity__c</fullName>
    <description>Total of all quantities ordered year to date.</description>
    <label>YTD [QTY]</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/Batch_EraseGPSRollups.cls
/*
SF-91
- We need to erase all the values int he various account fields so that they're null
- If this isn't done, a value that was calculated will stay in perpetuity even if an account is no longer ordering
- It will also screw up the logic for the field (which depends on the null values)

Batch_EraseGPSRollups foo = new Batch_EraseGPSRollups();
Id batchId = Database.executeBatch(foo, 50);

This is called after the UpdateAccountStatistics method is finished
*/

global class Batch_EraseGPSRollups implements 
    Database.Batchable<sObject>, Database.Stateful {
    
    // instance member to retain state across transactions
    global Integer recordsProcessed = 0;
    global Database.QueryLocator start(Database.BatchableContext bc) {

		// In theory if the 
        String q;
        q = 'SELECT Id, Name ';
        q += 'FROM Account ';
        q += 'WHERE (';
        q += 'YTD_Dollars__c != null ';
        q += 'OR Order_Summary_Previous_Year_Full__c != null)';
        

        q += 'ORDER BY Name ASC';
		System.Debug(q);
        
        return Database.getQueryLocator( q );
    }

        
    global void execute(Database.BatchableContext bc, List<Account> scope){
		System.Debug('Size of List ' + scope.size());
        
		List<Account> accounts = new List<Account>();
        	accounts.addAll(scope);
        
        // Really straightforward: loop throug the list and set all the fields we care about to NULL
        // then update them
        for(Account a : accounts) {
            a.Order_Summary_Bundles_Current_YTD__c = null;
            a.Order_Summary_Bundles_Previous_Year__c = null;
            a.Order_Summary_Bundles_Previous_YTD__c = null;
            a.YTD_Dollars__c = null;
            a.Last_Month_Dollars__c = null;
            a.Last_Year_Month_Dollars__c = null;
            a.Order_Summary_Last_Month_Year_Qty__c = null;
            a.Order_Summary_Last_Month_Qty__c = null;
            a.Order_Summary_Previous_Year_Full__c = null;
            a.Previous_Year_YTD_Dollars__c = null;
            a.YTD_Quantity__c = null;
            a.Order_Summary_Quantity_Previous_Year__c = null;
            a.Previous_Year_YTD_Quantity__c = null;
            a.Order_Summary_Month__c = null;
        }
        
        update accounts;
    }
        
    global void finish(Database.BatchableContext bc){
        System.debug(recordsProcessed + ' records processed. Shazam!');
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];
        // call some utility to send email
        // EmailUtils.sendMessage(job, recordsProcessed);

        Database.executeBatch(new Batch_UpdateAccountOrderAmounts());

    }    
}