ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Lead_Administrator__c.field-meta.xml
<CustomField>
    <fullName>Lead_Administrator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Populated with Process Builder and taken from the same value on the Contractor Admin Profile page.</description>
    <label>Lead Administrator</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>IKOPRO Contractor</value>
        </filterItems>
        <filterItems>
            <field>User.Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Lead_Admin2</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Contractor.recordType-meta.xml
<RecordType>
    <fullName>Contractor</fullName>
    <active>true</active>
    <label>Contractor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Contractor_Subscription__c/IKOPRO_Contractor_Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Subscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Contractor_Subscription__c/fields/Contractor_Account__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>IKOPRO Contractor, IKOPRO Contractor HA OK</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions1</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/IKOPRO_Contractor_Subscription__c/recordTypes/EagleView.recordType-meta.xml
<RecordType>
    <fullName>EagleView</fullName>
    <active>true</active>
    <label>EagleView</label>
</RecordType>

Repository/Claims/force-app/main/default/classes/icTestREPOSubscription.cls
/**
 * Created by Andrea Pissinis on 2018-09-12.
 */
@isTest
public with sharing class icTestREPOSubscription {

    public static testMethod void test_getSubscriptionsByAccountIdAndRecordTypeId(){

        icRepoSubscription.IClass repository = (icRepoSubscription.IClass) icObjectFactory.GetSingletonInstance('icRepoSubscription');

        Account contractor = icTestHelperUtility.generateContractorAccount();
        insert contractor;

        IKOPRO_Contractor_Subscription__c s = new IKOPRO_Contractor_Subscription__c();
        s.Contractor_Account__c = contractor.Id;

        Id recTypeId = [SELECT id from RecordType where Name ='EagleView'].Id;

        repository.getSubscriptionsByAccountIdAndRecordTypeId(contractor.Id,recTypeId);

    }

    public static testMethod void test_createSubscription(){
        icRepoSubscription.IClass repository = (icRepoSubscription.IClass) icObjectFactory.GetSingletonInstance('icRepoSubscription');

        Account contractor = icTestHelperUtility.generateContractorAccount();
        contractor.Lead_Administrator__c = UserInfo.getUserId();
        contractor.BillingPostalCode = '10034';
        contractor.ShippingPostalCode = '10034';
        insert contractor;

        IKOPRO_Contractor_Subscription__c s = new IKOPRO_Contractor_Subscription__c();
        s.Contractor_Account__c = contractor.Id;

        repository.createSubscription(s);

    }

    public static testMethod void test_updateSubscription(){
        icRepoSubscription.IClass repository = (icRepoSubscription.IClass) icObjectFactory.GetSingletonInstance('icRepoSubscription');

        Account contractor = icTestHelperUtility.generateContractorAccount();
        contractor.Lead_Administrator__c = UserInfo.getUserId();
        contractor.BillingPostalCode = '10034';
        contractor.ShippingPostalCode = '10034';
        insert contractor;

        IKOPRO_Contractor_Subscription__c s = new IKOPRO_Contractor_Subscription__c();
        s.Contractor_Account__c = contractor.Id;

        insert s;

        repository.updateSubscription(s);

    }

}