ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Lead_Administrator__c.field-meta.xml
<CustomField>
    <fullName>Lead_Administrator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Populated with Process Builder and taken from the same value on the Contractor Admin Profile page.</description>
    <label>Lead Administrator</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>IKOPRO Contractor</value>
        </filterItems>
        <filterItems>
            <field>User.Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Lead_Admin2</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/EagleView_Report__c.object-meta.xml
<CustomObject>
    <label>EagleView Report</label>
    <nameField>
        <displayFormat>EVR-{0}</displayFormat>
        <label>EagleView Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EagleView Reports</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EagleView Reports</relationshipLabel>
    <relationshipName>EagleView_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Created</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>In Process</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/SubStatus__c.field-meta.xml
<CustomField>
    <fullName>SubStatus__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>29</fullName>
                <label>AddressVerified</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Canceled By Client</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Card Rejected</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>CreditCard Failure</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Customer</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Customer Response</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Duplicate</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Need To ID</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>No ID</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>No Images</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Other</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Poor Images</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Process Started</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>Ready To Send</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Report Type Change</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Sent</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Site Map</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>System</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Under Review</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Wrong House</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Sent_</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icTestHandlerEagleViewReport.cls
/**
 * Created by Andrea Pissinis on 2018-09-13.
 */
@isTest
public with sharing class icTestHandlerEagleViewReport {

    public static testMethod void EagleViewReport_Test(){

        icHandlerEagleViewReport.IClass hdl = (icHandlerEagleViewReport.IClass) icObjectFactory.GetSingletonInstance('icHandlerEagleViewReport');


        Account acc = icTestHelperUtility.generateAccount();
        acc.Lead_Administrator__c = UserInfo.getUserId();
        insert acc;

        EagleView_Report__c r = new EagleView_Report__c();
        r.Status__c = '1';
        r.Account__c = acc.Id;
        r.SubStatus__c = '11';
        insert r;

        r.SubStatus__c = '19';
        update r;

    }

}