ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Lead_Administrator__c.field-meta.xml
<CustomField>
    <fullName>Lead_Administrator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Populated with Process Builder and taken from the same value on the Contractor Admin Profile page.</description>
    <label>Lead Administrator</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>IKOPRO Contractor</value>
        </filterItems>
        <filterItems>
            <field>User.Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Lead_Admin2</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/EagleView_Report__c.object-meta.xml
<CustomObject>
    <label>EagleView Report</label>
    <nameField>
        <displayFormat>EVR-{0}</displayFormat>
        <label>EagleView Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EagleView Reports</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EagleView Reports</relationshipLabel>
    <relationshipName>EagleView_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EagleView_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Created</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>In Process</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icTestREPOEagleViewReport.cls
/**
 * Created by Andrea Pissinis on 2018-09-12.
 */
@isTest
public with sharing class icTestREPOEagleViewReport {

    public static testMethod void test_getEagleViewReportById(){
        icRepoEagleViewReport.IClass repository = (icRepoEagleViewReport.IClass) icObjectFactory.GetSingletonInstance('icRepoEagleViewReport');

        Account acc = icTestHelperUtility.generateAccount();
        acc.Lead_Administrator__c = UserInfo.getUserId();
        insert acc;

        EagleView_Report__c r = new EagleView_Report__c();
        r.Status__c = '1';
        r.Account__c = acc.Id;
        insert r;

        repository.getEagleViewReportById(r.Id);

    }

    public static testMethod void test_createEagleViewReport(){
        icRepoEagleViewReport.IClass repository = (icRepoEagleViewReport.IClass) icObjectFactory.GetSingletonInstance('icRepoEagleViewReport');

        Account acc = icTestHelperUtility.generateAccount();
        acc.Lead_Administrator__c = UserInfo.getUserId();
        insert acc;

        EagleView_Report__c r = new EagleView_Report__c();
        r.Status__c = '1';
        r.Account__c = acc.Id;

        repository.createEagleViewReport(r);

    }

    public static testMethod void test_updateEagleViewReport(){
        icRepoEagleViewReport.IClass repository = (icRepoEagleViewReport.IClass) icObjectFactory.GetSingletonInstance('icRepoEagleViewReport');

        Account acc = icTestHelperUtility.generateAccount();
        acc.Lead_Administrator__c = UserInfo.getUserId();
        insert acc;

        EagleView_Report__c r = new EagleView_Report__c();
        r.Status__c = '1';
        r.Account__c = acc.Id;
        insert r;

        repository.updateEagleViewReport(r);

    }

    public static testMethod void test_deleteEagleViewReport(){
        icRepoEagleViewReport.IClass repository = (icRepoEagleViewReport.IClass) icObjectFactory.GetSingletonInstance('icRepoEagleViewReport');

        Account acc = icTestHelperUtility.generateAccount();
        acc.Lead_Administrator__c = UserInfo.getUserId();
        insert acc;

        EagleView_Report__c r = new EagleView_Report__c();
        r.Status__c = '1';
        r.Account__c = acc.Id;
        insert r;

        repository.deleteEagleViewReport(r);
    }

}