ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Present_Tier_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Present_Tier_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Tier object to select present tier. Upon selection, flow will change benefits triggered by process builder and the latter will fill prior Tier field.</description>
    <label>Present Tier</label>
    <referenceTo>Tier__c</referenceTo>
    <relationshipLabel>Contractor Accounts with this Tier</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CalendarEvent__c/CalendarEvent__c.object-meta.xml
<CustomObject>
    <label>Calendar Event</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Calendar Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calendar Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CommunitySiteNameConfiguration__mdt/CommunitySiteNameConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>This metadata contains the information related to the Site Name Community and help to bind the value to the CommunityName global setvalue used in Calendar event and Whatshappening configuration.</description>
    <label>Community Site Name Configuration</label>
    <pluralLabel>Community Site Name Configurations</pluralLabel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/CommunitySiteNameConfiguration__mdt/fields/CommunityNameGlobalSetValue__c.field-meta.xml
<CustomField>
    <fullName>CommunityNameGlobalSetValue__c</fullName>
    <description>This value must match the API NAME Value of the corresponding Picklist list Item in the global value set named CommunityName</description>
    <label>CommunityNameGlobalSetValue</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/Tier__c.object-meta.xml
<CustomObject>
    <description>Object to manage Tier information (e.g. maximum &amp; minimum amount of squares before Tier change).</description>
    <label>Tier</label>
    <nameField>
        <displayFormat>Tier {0}</displayFormat>
        <label>Tier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/fields/Tier_Label__c.field-meta.xml
<CustomField>
    <fullName>Tier_Label__c</fullName>
    <label>Tier</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icCtrlUiCalendarEvent.cls
/**
 * Created by Francois Poirier on 2019-04-01.
 */

global with sharing class icCtrlUiCalendarEvent {

    static icLogicEventCalendar.IClass logicEventCalendar = (icLogicEventCalendar.IClass) icObjectFactory.GetSingletonInstance('icLogicEventCalendar');
    static icLogicUser.IClass logicUser = (icLogicUser.IClass) icObjectFactory.GetSingletonInstance('icLogicUser');
    static icMapCalendarEvent.IClass mapCalendarEvent = (icMapCalendarEvent.IClass) icObjectFactory.GetSingletonInstance('icMapCalendarEvent');
    static icLogicConfig.IClass logicConfig = (icLogicConfig.IClass) icObjectFactory.GetSingletonInstance('icLogicConfig');

    @AuraEnabled
    global static Map<String, List<icDtoCalendarEvent>> getEventsByDateRange(String fistDay, String lastDay){
        system.debug('fistDay ====> ' + fistDay);
        system.debug('lastDay ====> ' + lastDay);

        User currentUser = logicUser.getUserAndAccountFromPartnerUser(UserInfo.getUserId());
        
        system.debug('UserInfo.getUserId = ' + UserInfo.getUserId());

        //IKO-240 Use the CommunityName to filter Calendar Events
        String communityName = Site.getName();
        system.debug('Community Site Name ===> ' + communityName);
        CommunitySiteNameConfiguration__mdt communityConfig = logicConfig.getCommunitySiteNameConfigByName(communityName);

        String tierNumber = '';

        if(Test.isRunningTest()){
            tierNumber = '1';
        }
        else {
            tierNumber = currentUser.Contact.Account.Present_Tier_Lookup__r.Tier_Label__c;
        }

        system.debug('tierNumber current User ===> ' + currentUser.Contact.Account.Present_Tier_Lookup__r.Tier_Label__c);

        Map<String, List<icDtoCalendarEvent>> dateEventsMap = new Map<String, List<icDtoCalendarEvent>>();
        List<CalendarEvent__c> calendarEvents = new List<CalendarEvent__c>();
        List<CalendarEvent__c> mainCalendarEvents = new List<CalendarEvent__c>();
        Set<CalendarEvent__c> allEvents = new Set<CalendarEvent__c>();

        calendarEvents = logicEventCalendar.getActiveCalendarEventsByDateRangeTierCommunityName(Date.valueOf(fistDay),Date.valueOf(lastDay), currentUser.ROOFPRO_Portal_Language__c, tierNumber, communityConfig.CommunityNameGlobalSetValue__c	);
        system.debug('calendar events ===> ' + calendarEvents);

        allEvents.addAll(calendarEvents);
        system.debug('all events after add all calendarEvents ===> ' + allEvents);

        List<icDtoCalendarEvent> dtoCalendarEvents = mapCalendarEvent.mapToDto(allEvents);

        dateEventsMap.put('currentEvents', new List<icDtoCalendarEvent>());

        for(icDtoCalendarEvent calendarEvent : dtoCalendarEvents){

            String eventDateStr;

            eventDateStr = String.valueOf(calendarEvent.EventDate.year()) + String.valueOf(calendarEvent.EventDate.month()) + String.valueOf(calendarEvent.EventDate.day());

            if(!dateEventsMap.containsKey(eventDateStr)){
                List<icDtoCalendarEvent> events = new List<icDtoCalendarEvent>();
                dateEventsMap.put(eventDateStr, events);
            }

            dateEventsMap.get(eventDateStr).add(calendarEvent);
            dateEventsMap.get('currentEvents').add(calendarEvent);
        }

        system.debug('dateEventsMap ===> ' + dateEventsMap);

        return dateEventsMap;
    }
    @AuraEnabled
    global static Map<Integer, String> getMonthNamesArray(){

        return icServiceDate.getMonthArray();

    }
}