ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Present_Tier_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Present_Tier_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Tier object to select present tier. Upon selection, flow will change benefits triggered by process builder and the latter will fill prior Tier field.</description>
    <label>Present Tier</label>
    <referenceTo>Tier__c</referenceTo>
    <relationshipLabel>Contractor Accounts with this Tier</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Tier_Number__c.field-meta.xml
<CustomField>
    <fullName>Tier_Number__c</fullName>
    <formula>Present_Tier_Lookup__r.Tier_Label__c</formula>
    <label>Tier Number</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/Tier__c.object-meta.xml
<CustomObject>
    <description>Object to manage Tier information (e.g. maximum &amp; minimum amount of squares before Tier change).</description>
    <label>Tier</label>
    <nameField>
        <displayFormat>Tier {0}</displayFormat>
        <label>Tier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Tier__c/fields/Tier_Label__c.field-meta.xml
<CustomField>
    <fullName>Tier_Label__c</fullName>
    <label>Tier</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icRepoUser.cls
public with sharing class icRepoUser implements icIClass {

	public Object GetInstance() {
		return new Impl();
	}

	public Interface IClass {
		User getAccountInfoFromPartnerUser(String partnerUserId);
		User getLoggedInUserInfo(String userId);
		List<User> getOwnerManagerIdByOwnerID(Set<ID> ownerIds);
	}

	public class Impl implements IClass {
		public User getAccountInfoFromPartnerUser(String partnerUserId) {
			return [SELECT 	Id,
							ContactId,
							Contact.AccountId,
							Contact.Account.Tier_Number__c,
							Contact.Account.Present_Tier_Lookup__r.Tier_Label__c,
							Contact.Account.BillingCountry,
							LanguageLocaleKey,
							ROOFPRO_Portal_Language__c,
							Contact.FirstName,
							Contact.LastName,
							Contact.Email,
							Contact.MobilePhone,
							Contact.Phone
					FROM User
					WHERE Id =:partnerUserId];
		}

		public User getLoggedInUserInfo(String userId) {
			return  [SELECT Id,
							UserName,
							UserRole.Name,
							Profile.Name
					 FROM User
					 WHERE Id =:userId];
		}

		public List<User> getOwnerManagerIdByOwnerID(Set<ID> ownerIds) {
			return  [SELECT Id,
							ManagerId
					 FROM 	User
					 WHERE  Id in :ownerIds];
		}
	}
}