ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Warranty__c.field-meta.xml
<CustomField>
    <fullName>Warranty__c</fullName>
    <label>Warranty</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Labour &amp; Materials</fullName>
            </value>
            <value>
                <fullName>Diamond Shield</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Job_In_Progress__c.field-meta.xml
<CustomField>
    <fullName>Job_In_Progress__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Used to indicate that this claim is for a Job In Progress, to aid in setting priority</inlineHelpText>
    <label>Job In Progress</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Leaking__c.field-meta.xml
<CustomField>
    <fullName>Leaking__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates that this is related to a leaking issue, and will be used for prioritization</inlineHelpText>
    <label>Leaking?</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warranty_and_Claim_Sectors</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Warranty__c.field-meta.xml
<CustomField>
    <fullName>Warranty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Warranty for the installation related to this Claim</description>
    <label>Warranty</label>
    <referenceTo>Warranty__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Case/fields/Warranty_Status__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Status__c</fullName>
    <description>Formula field for the Warranty Status, to be referenced in Lightning App Builder for page messages</description>
    <formula>TEXT(Warranty__r.Warranty_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warranty Status</label>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/ClaimsFD__c/ClaimsFD__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Has settings related to the file downloads for a claim</description>
    <label>Claims File Download</label>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/ClaimsFD__c/fields/Download__c.field-meta.xml
<CustomField>
    <fullName>Download__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows multi-select download of files in the current page</description>
    <label>Download</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/Lab_Sample__c.object-meta.xml
<CustomObject>
    <label>Lab Sample</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab Samples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Lab_Sample__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A link to the Claim this lab sample is related to. Lab Samples with no links to a Claim have been received but not properly connected to a cliam.</description>
    <inlineHelpText>The Claim this Lab Sample relates to.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Lab Samples</relationshipLabel>
    <relationshipName>Lab_Samples</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/Warranty__c.object-meta.xml
<CustomObject>
    <description>Used to track Warranties for Residential and Commercial installations</description>
    <label>Warranty</label>
    <nameField>
        <label>Warranty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warranties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Building where the product is installed</description>
    <label>Building</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Account must be of Record Type Building Location</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Building Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Warranties (Building)</relationshipLabel>
    <relationshipName>BuildingWarranties</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Warranty</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Labor &amp; Membrane</fullName>
            </value>
            <value>
                <fullName>Diamond Shield</fullName>
            </value>
            <value>
                <fullName>ShieldPRO plus+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Warranty_Registration_Id__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Registration_Id__c</fullName>
    <inlineHelpText>Auto-generated registration number based on Province Code (2 char), 5 digit unique numeric (per province) and full year. E.g. ON-10001-2019</inlineHelpText>
    <label>Warranty Registration Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Warranty_Status__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Status__c</fullName>
    <description>Status of the Warranty</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Expired</fullName>
                <isActive>false</isActive>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Not Issued</fullName>
                <isActive>false</isActive>
                <label>Not Issued</label>
            </value>
            <value>
                <fullName>Registered</fullName>
                <isActive>false</isActive>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Unregistered</fullName>
                <isActive>false</isActive>
                <label>Unregistered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Warranty_Substatus__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Substatus__c</fullName>
    <label>Substatus</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Warranty_Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting documentation</fullName>
            </value>
            <value>
                <fullName>Need Insurance</fullName>
            </value>
            <value>
                <fullName>With Sales</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Invoice Sent</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Not Issued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/FileDataTableAuraControllerTest.cls
/**
 * @description Test Aura Controller for all operations related the Files Data Table Lightning Components
 * @author Sinan Bunni
 * @date 2019-80-80
 */
@IsTest
public class FileDataTableAuraControllerTest {

    private static void initFileDownloadCustomSettingsTestData() {
        ClaimsFD__c setting = new ClaimsFD__c();
        setting.Name = 'Test Setting';
        setting.Download__C = true;
        insert setting;
    }

    private static testMethod void getHierarchySettings()
    {
        ClaimsFD__c setting = FileDataTableAuraController.getHierarchySettings();
        System.assertEquals(setting.Name, 'Test Setting');
    }
    private static testMethod void getFiles_ValidCaseRecordId_ListOfFilesLinkedToCase() {
        // Prepare the data
        Case caseRecord = [SELECT Id FROM Case LIMIT 1];
        createTestFileRecord(caseRecord.Id);

        // Test the data
        Test.startTest();
        List<ContentVersion> contentVersions = FileDataTableAuraController.getFiles(caseRecord.Id, 'Case');
        Test.stopTest();

        // Assert the data
        System.assertEquals(1, contentVersions.size(), 'Expected number of files associated to the Case is 1');
    }

    private static testMethod void getFiles_ValidLabSampleId_ListOfFilesLinkedToCase() {

        // Prepare the data
        Lab_Sample__c labSampleRecord = [SELECT Id, Case__c FROM Lab_Sample__c LIMIT 1];
        createTestFileRecord(labSampleRecord.Case__c);

        // Test the data
        Test.startTest();
        List<ContentVersion> contentVersions = FileDataTableAuraController.getFiles(labSampleRecord.Id, 'Lab_Sample__c');
        Test.stopTest();

        // Assert the data
        System.assertEquals(1, contentVersions.size(), 'Expected number of files associated to the Case is 1');
    }

    private static testMethod void getFiles_ValidWarrantyId_ListOfFilesLinkedToWarranty() {

        // Prepare the data
        Warranty__c warrantyRecord = [SELECT Id FROM Warranty__c LIMIT 1];
        createTestFileRecord(warrantyRecord.Id);

        // Test the data
        Test.startTest();
        List<ContentVersion> contentVersions = FileDataTableAuraController.getFiles(warrantyRecord.Id, 'Warranty__c');
        Test.stopTest();

        // Assert the data
        System.assertEquals(1, contentVersions.size(), 'Expected number of files associated to the Warranty is 1');
    }

    private static testMethod void updateFiles_ValidCaseWithLinkedDocumentAndGeneralIKOType_FileTitleUpdatedSuccessfully() {

        // Prepare the data
        Case caseRecord = [SELECT Id, CaseNumber FROM Case LIMIT 1];
        createTestFileRecord(caseRecord.Id);

        // Test the data
        ContentVersion contentVersion = [SELECT Id, Title, ContentDocumentId FROM ContentVersion LIMIT 1];
        
        //Create File property Record

        Map<String, String> jsonObj = new Map<String, String>();
        jsonObj.put('name', 'IKO Test');
        jsonObj.put('documentId',contentVersion.ContentDocumentId );
        jsonObj.put('ikoFileType', 'APPT' );
        
        List<Map<String, String>> jsonObjList = new List<Map<String, String>>();
        
        jsonObjList.add(jsonObj);
        
        System.debug('JSON.serialize(jsonObjList): '+JSON.serialize(jsonObjList));
        Test.startTest();
        FileDataTableAuraController.updateFilesBulkified(JSON.serialize(jsonObjList),'Case',caseRecord.Id);
        Test.stopTest();

        // Assert the data
        
        //System.debug('contentDocumentLink: '+contentDocumentLink);
        ContentVersion modifiedContentVersion = [SELECT Id, Title FROM ContentVersion
                                                 LIMIT 1];
        System.debug('modifiedContentVersion: '+modifiedContentVersion);
        System.assertNotEquals(modifiedContentVersion.Title, contentVersion.Title, 'Expected modified content version title is different from original.');
        System.assert(modifiedContentVersion.Title.contains(caseRecord.CaseNumber), true);
        System.assert(modifiedContentVersion.Title.contains('APPT'), true);
        
        
        
    }

    private static testMethod void updateFiles_ValidLabSampleWithLinkedDocumentAndGeneralIKOType_FileTitleUpdatedSuccessfully(){
       	Case caseRecord = [SELECT Id, CaseNumber FROM Case LIMIT 1];
		Lab_Sample__c lbToTest = [Select Id, Case__c from Lab_Sample__c Where Case__c= :caseRecord.Id];		        
        
        Test.startTest();
        	createTestFileRecord(lbToTest.Id);
        	ContentVersion contentVersion = [SELECT Id, ContentDocumentId from ContentVersion LIMIT 1];
        
            Map<String, String> jsonObj = new Map<String, String>();
            jsonObj.put('name', 'IKO Test');
            jsonObj.put('documentId',contentVersion.ContentDocumentId );
            jsonObj.put('ikoFileType', 'APPT' );
            
            List<Map<String, String>> jsonObjList = new List<Map<String, String>>();
            
            jsonObjList.add(jsonObj);
        
        	FileDataTableAuraController.updateFilesBulkified(JSON.serialize(jsonObjList),'Lab_Sample__c', lbToTest.Id);
        Test.stopTest();
        
       	
        ContentVersion caseContentVersion = [SELECT Id, Title from ContentVersion LIMIT 1];
        System.debug('caseContentVersion: '+caseContentVersion);
        
        
    }
    private static testMethod void updateFiles_ValidWarrantyWithLinkedDocumentAndGeneralIKOType_FileTitleUpdatedSuccessfully() {

        // Prepare the data
        Warranty__c warrantyRecord = [SELECT Id, Warranty_Registration_Id__c FROM Warranty__c LIMIT 1];
        createTestFileRecord(warrantyRecord.Id);
        
        

        // Test the data
        ContentVersion contentVersion = [SELECT Id, Title, ContentDocumentId FROM ContentVersion LIMIT 1];
        Map<String, String> jsonObj = new Map<String, String>();
        jsonObj.put('name', 'IKO Test');
        jsonObj.put('documentId',contentVersion.ContentDocumentId );
        jsonObj.put('ikoFileType', 'APPT' );
        
        List<Map<String, String>> jsonObjList = new List<Map<String, String>>();
        jsonObjList.add(jsonObj);
        
        Test.startTest();
        FileDataTableAuraController.updateFilesBulkified(JSON.serialize(jsonObjList),'Warranty__c', warrantyRecord.Id);
        Test.stopTest();

        // Assert the data
        /*
        ContentVersion modifiedContentVersion = [SELECT Id, Title FROM ContentVersion LIMIT 1];
        System.assertNotEquals(modifiedContentVersion.Title, contentVersion.Title, 'Expected modified content version title is different from original.');
        System.assert(modifiedContentVersion.Title.contains(warrantyRecord.Warranty_Registration_Id__c), true);
        System.assert(modifiedContentVersion.Title.contains('General'), true);
		*/
    }

    private static testMethod void getListOfFileTypes_Void_MapOfLabelAndAbbreviateIKOFileTypes() {

        // Test the data
        Test.startTest();
        Map<String, String> ikoFileLabelToAbbreviateMap = FileDataTableAuraController.getListOfFileTypes();
        Test.stopTest();

        // Assert the data
        System.assert(ikoFileLabelToAbbreviateMap.size() > 0, true);
    }

    private static void createTestFileRecord(Id objectId) {

        ContentVersion contentVersion = new ContentVersion(Title = 'IKO Test',
                PathOnClient = 'IKOTest.png', VersionData = Blob.valueOf('IKO Test'), IsMajorVersion = true);
        insert contentVersion;

        List<ContentDocument> contentDocuments = [
                SELECT Id, Title, LatestPublishedVersionId
                FROM ContentDocument
                LIMIT 1
        ];

        ContentDocumentLink conenContentDocumentLink = new ContentDocumentLink(LinkedEntityId = objectId,
                ContentDocumentId = contentDocuments.get(0).Id, ShareType = 'V');
        insert conenContentDocumentLink;

    } // end createTestFileRecord method

    @testSetup
    private static void setupTestData() {

        initFileDownloadCustomSettingsTestData();

        Id baRtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Building Location').getRecordTypeId();

        Account accountRecord = new Account(RecordTypeId = baRtId, Name = 'ClaimNumber', BillingStreet = '19 King St E',
                BillingCity = 'Toronto', BillingStateCode = 'ON', BillingCountryCode = 'CA', BillingPostalCode = 'M4S 2H4');
        insert accountRecord;

        Contact contactRecord = new Contact(LastName = 'CaseServiceTest', AccountId = accountRecord.Id);
        insert contactRecord;

        Warranty__c warrantyRecord = new Warranty__c(Name = 'Test Warranty', Warranty_Registration_Id__c = '111111', Warranty_Status__c = 'Draft', Type__c = 'Labor & Membrane', Warranty_Substatus__c = 'With Sales', Building__c = accountRecord.Id);
        insert warrantyRecord;

        Case caseRecord = new Case(Origin = 'Owner', Leaking__c = true, Job_In_Progress__c = true, ContactId = contactRecord.Id, AccountId = accountRecord.Id, Sector__c = 'CA', Warranty__c = warrantyRecord.Id);
        insert caseRecord;

        Lab_Sample__c labSampleRecord = new Lab_Sample__c(Case__c = caseRecord.Id);
        insert labSampleRecord;
    }

} // end FileDataTableAuraControllerTest class