ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Warranty__c.field-meta.xml
<CustomField>
    <fullName>Warranty__c</fullName>
    <label>Warranty</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Labour &amp; Materials</fullName>
            </value>
            <value>
                <fullName>Diamond Shield</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/Warranty__c.object-meta.xml
<CustomObject>
    <description>Used to track Warranties for Residential and Commercial installations</description>
    <label>Warranty</label>
    <nameField>
        <label>Warranty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warranties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Architect__c.field-meta.xml
<CustomField>
    <fullName>Architect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Architect</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria. 
(Architect should be Record Type Designer and Legacy Claim Account = False)</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Designer</value>
        </filterItems>
        <filterItems>
            <field>Account.Legacy_Claim_Account__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Warranties (Architect)</relationshipLabel>
    <relationshipName>Warranties4</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultant</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.
(Consultant should be Record Type Designer / Other and Legacy Claim Account = False)</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Designer, Other</value>
        </filterItems>
        <filterItems>
            <field>Account.Legacy_Claim_Account__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Warranties (Consultant)</relationshipLabel>
    <relationshipName>Warranties3</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <inlineHelpText>To track if the Warranty has expired; used as part of duplciate matching rules</inlineHelpText>
    <label>Expired?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Warranty_Expired_Date__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Expired_Date__c</fullName>
    <description>This field contains the date time the warranty is switched to Expired.</description>
    <inlineHelpText>This field contains the date time the warranty is switched to Expired.</inlineHelpText>
    <label>Warranty Expired Date</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Warranty_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Expiry_Date__c</fullName>
    <formula>IF(
      AND(
        MONTH( Warranty_Start_Date__c ) = 2,
        DAY( Warranty_Start_Date__c ) = 29,
        NOT( 
          OR( 
            MOD( YEAR( Warranty_Start_Date__c ) + VALUE (TEXT (Warranty_Term__c)), 400 ) = 0, 
            AND( 
              MOD( YEAR( Warranty_Start_Date__c ) + VALUE (TEXT (Warranty_Term__c)), 4 ) = 0,
              MOD( YEAR( Warranty_Start_Date__c ) + VALUE (TEXT (Warranty_Term__c)), 100 ) != 0
            )
          )
        ) 
      ),
      DATE( YEAR( Warranty_Start_Date__c ) + VALUE (TEXT (Warranty_Term__c)), 3, 1),
      DATE( YEAR( Warranty_Start_Date__c ) + VALUE (TEXT (Warranty_Term__c)), MONTH( Warranty_Start_Date__c ), DAY( Warranty_Start_Date__c ) )
      )</formula>
    <label>Warranty Expiry Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Warranty_Substatus__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Substatus__c</fullName>
    <label>Substatus</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Warranty_Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting documentation</fullName>
            </value>
            <value>
                <fullName>Need Insurance</fullName>
            </value>
            <value>
                <fullName>With Sales</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Invoice Sent</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Not Issued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/Warranty_BatchUpdateExpired.cls
public class Warranty_BatchUpdateExpired implements Database.Batchable<sObject>, Schedulable {
	public String queryString = null;
	public Integer queryNumber = 0;
    public Map<String, Account> accountsByAccountId = new Map<String, Account>();
	
    public Warranty_BatchUpdateExpired()
    {
        
     
    }

    public Warranty_BatchUpdateExpired (Integer queryNum)
    {
        queryNumber = queryNum;
        
    }
    public Database.QueryLocator start(Database.BatchableContext bc) {
        
        Date todayDate = Date.today();
        
        switch on queryNumber
        {
            when 1
            {
                System.debug('First query.');
                return Database.getQueryLocator ('SELECT ID, Architect__c, Consultant__c, Warranty_Expiry_Date__c, Warranty_Substatus__c FROM Warranty__c where Expired__c = null') ;
            }
            when 2
            {
                System.debug('Second query.');
                return Database.getQueryLocator ('SELECT ID, Architect__c, Consultant__c, Warranty_Expiry_Date__c, Warranty_Substatus__c FROM Warranty__c where Warranty_Expired_Date__c = null and Expired__c = \'Yes\'') ;
            }
            when 3
            {
                System.debug('Third query.');
                return Database.getQueryLocator ('SELECT ID, Architect__c, Consultant__c, Warranty_Expiry_Date__c, Warranty_Substatus__c FROM Warranty__c where Warranty_Substatus__c = \'Not Issued\' and Expired__c = \'No\'') ;
            }
            when else
            {
                System.debug('Forth query.');
                return Database.getQueryLocator('SELECT ID, Architect__c, Consultant__c, Warranty_Expiry_Date__c, Warranty_Substatus__c FROM Warranty__c where Expired__c =  \'No\' and Warranty_Expiry_Date__c <: todayDate');                 
            	
            }
        }
        
    }
    public void execute(Database.BatchableContext bc, List<Warranty__c> scope){
        // process each batch of record
        try
        {
                
        List<Warranty__c> lstExpiredWarranty = new List<Warranty__c>();      
            
        if (accountsByAccountId.isEmpty())
            {
                String accountName = 'N/A';
                List<Account> allAccounts = new List<Account>([SELECT Id, Name FROM Account WHERE name =: accountName]);
        		for(Account a : allAccounts) {
            		accountsByAccountId.put(a.Id, a);
                }
        	}    
        Integer i = 0;
        for (Warranty__c w : scope) {
            
            i++;
            
            if(accountsByAccountId.containsKey(w.Architect__c) == true) {
             	w.Architect__c = null;
            }
            
            if(accountsByAccountId.containsKey(w.Consultant__c) == true) {
            	w.Consultant__c = null;
            }
            
            if (w.Warranty_Expiry_Date__c != null && w.Warranty_Expiry_Date__c < Date.today())
            {
                w.Expired__c = 'Yes';
                w.Warranty_Expired_Date__c = string.valueofGmt(DateTime.now()) + '_' + string.valueOf(i);
            }
            else if (w.Warranty_Substatus__c == 'Not Issued')
            {
                w.Expired__c = 'Yes';
                w.Warranty_Expired_Date__c = string.valueofGmt(DateTime.now()) + '_' + string.valueOf(i);
            }
            else 
            {
                w.Expired__c = 'No';
                w.Warranty_Expired_Date__c = null;
            }
			
            lstExpiredWarranty.add(w);  
                 
        }   
        	System.Debug('update list ' + lstExpiredWarranty);
        	List<Database.SaveResult> saveResults = Database.Update(lstExpiredWarranty,false);
            System.Debug('error  list ' + saveResults);
			icServiceErrorHandler.handleDatabaseSaveResult('Claims',lstExpiredWarranty, saveResults, 'Warranty_BatchUpdateExpired', 'execute query ' + queryNumber);
			
        }
        Catch (Exception ex)
        {
            System.debug(ex.getMessage() );
            icServiceErrorHandler.LogError('Claims', 'Warranty_BatchUpdateExpired','execute' , ex.getStackTraceString(), ex.getMessage(), '');        
        }
    }   
    public void finish(Database.BatchableContext bc){
        Id job= bc.getJobId();
        System.debug(job);
        
        
    }  
    
    public void execute(SchedulableContext sc){
        try
        {
            Database.executeBatch(new Warranty_BatchUpdateExpired (1));
            Database.executeBatch(new Warranty_BatchUpdateExpired (2));
            Database.executeBatch(new Warranty_BatchUpdateExpired (3));
            Database.executeBatch(new Warranty_BatchUpdateExpired (4));
            
        }
        catch(Exception ex)
        {
            System.debug(ex.getMessage() );
            icServiceErrorHandler.LogError('Claims', 'Warranty_BatchUpdateExpired','execute' , ex.getStackTraceString(), ex.getMessage(), '');     
        }
    
    
    }
}