ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/fields/Warranty__c.field-meta.xml
<CustomField>
    <fullName>Warranty__c</fullName>
    <label>Warranty</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Labour &amp; Materials</fullName>
            </value>
            <value>
                <fullName>Diamond Shield</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Account/recordTypes/Contractor.recordType-meta.xml
<RecordType>
    <fullName>Contractor</fullName>
    <active>true</active>
    <label>Contractor</label>
</RecordType>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/Warranty__c.object-meta.xml
<CustomObject>
    <description>Used to track Warranties for Residential and Commercial installations</description>
    <label>Warranty</label>
    <nameField>
        <label>Warranty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warranties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.
(Contractor should be Record Type of Contractor / US Contractor / IKOPRO Contractor / Residential Account Record Type and Legacy Claim Account = False)</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contractor, US Contractor, IKOPRO Contractor, IKOPRO Contractor, Residential Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Legacy_Claim_Account__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Warranties</relationshipLabel>
    <relationshipName>Warranties</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <inlineHelpText>To track if the Warranty has expired; used as part of duplciate matching rules</inlineHelpText>
    <label>Expired?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Installation_Deficiency_Status__c.field-meta.xml
<CustomField>
    <fullName>Installation_Deficiency_Status__c</fullName>
    <description>CLAIMSV2-38 Deficiencies are noted and must be reporated. You can&apos;t go from &quot;repairs required&quot; to &quot;no deficiencies&quot; because that makes no sense.</description>
    <inlineHelpText>The current status of the deficiencies, if any.</inlineHelpText>
    <label>Installation Deficiency Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Installation_Deficiency_Status</valueSetName>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Registration_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Registration_Prefix__c</fullName>
    <inlineHelpText>Stores the prefix (e.g. 2-char province code) for the Registraiton Number. Used for aggregation when determining next sequence number</inlineHelpText>
    <label>Registration Prefix</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <inlineHelpText>Sequence number for province of the Contractor; leveraged for the Registration # field</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Warranty</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Labor &amp; Membrane</fullName>
            </value>
            <value>
                <fullName>Diamond Shield</fullName>
            </value>
            <value>
                <fullName>ShieldPRO plus+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Warranty_Expired_Date__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Expired_Date__c</fullName>
    <description>This field contains the date time the warranty is switched to Expired.</description>
    <inlineHelpText>This field contains the date time the warranty is switched to Expired.</inlineHelpText>
    <label>Warranty Expired Date</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Warranty_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Expiry_Date__c</fullName>
    <formula>IF(
      AND(
        MONTH( Warranty_Start_Date__c ) = 2,
        DAY( Warranty_Start_Date__c ) = 29,
        NOT( 
          OR( 
            MOD( YEAR( Warranty_Start_Date__c ) + VALUE (TEXT (Warranty_Term__c)), 400 ) = 0, 
            AND( 
              MOD( YEAR( Warranty_Start_Date__c ) + VALUE (TEXT (Warranty_Term__c)), 4 ) = 0,
              MOD( YEAR( Warranty_Start_Date__c ) + VALUE (TEXT (Warranty_Term__c)), 100 ) != 0
            )
          )
        ) 
      ),
      DATE( YEAR( Warranty_Start_Date__c ) + VALUE (TEXT (Warranty_Term__c)), 3, 1),
      DATE( YEAR( Warranty_Start_Date__c ) + VALUE (TEXT (Warranty_Term__c)), MONTH( Warranty_Start_Date__c ), DAY( Warranty_Start_Date__c ) )
      )</formula>
    <label>Warranty Expiry Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Warranty_Registration_Id__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Registration_Id__c</fullName>
    <inlineHelpText>Auto-generated registration number based on Province Code (2 char), 5 digit unique numeric (per province) and full year. E.g. ON-10001-2019</inlineHelpText>
    <label>Warranty Registration Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Warranty_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Start_Date__c</fullName>
    <description>This is the start of the warranty period</description>
    <label>Warranty Start Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Warranty_Status__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Status__c</fullName>
    <description>Status of the Warranty</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Expired</fullName>
                <isActive>false</isActive>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Not Issued</fullName>
                <isActive>false</isActive>
                <label>Not Issued</label>
            </value>
            <value>
                <fullName>Registered</fullName>
                <isActive>false</isActive>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Unregistered</fullName>
                <isActive>false</isActive>
                <label>Unregistered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Warranty__c/fields/Warranty_Substatus__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Substatus__c</fullName>
    <label>Substatus</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Warranty_Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting documentation</fullName>
            </value>
            <value>
                <fullName>Need Insurance</fullName>
            </value>
            <value>
                <fullName>With Sales</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Invoice Sent</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Not Issued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Repository/Claims/force-app/main/default/classes/WarrantyService.cls
public with sharing class WarrantyService {
	public static final String LABORANDMEMBRANE_WARRANTYTYPE = 'Labor & Membrane';
    /*
        Used to generate a sequence number for the Warranty Registration Id value;
        uses the Contractor’s Billing Address State Code (e.g. “ON”, “AB”)
    */
    public static void setSequencePrefix(List<Warranty__c> records) {
        List<Id> accountIds = new List<Id>();

        for (Warranty__c w : records) {
			if (w.Registration_Prefix__c == null) {
				accountIds.add(w.Contractor__c);
			}
		}

        if (accountIds.isEmpty()) {
			return;
		}

        Map<Id, Account> accountMap = new Map<Id, Account>([select Id, BillingStateCode from Account where Id in :accountIds AND BillingStateCode <> null]);
        if (accountMap.isEmpty()) {
			return;
		}

        for (Warranty__c w : records) {
			if (w.Registration_Prefix__c == null) {
				w.Registration_Prefix__c = (accountMap.get(w.Contractor__c) <> null) ? accountMap.get(w.Contractor__c).BillingStateCode : null;
			}
		}
    } // end setSequencePrefix method

    /*
        Used to generate a Warranty Registration Id value,
        by determining a sequence number
        (based on the highest existing sequence for the Contractor’s Billing State Code)
        and generates a value in the format {Billing State Code}-{Sequence Number}-{YYYY},
        e.g.
        •	ON-10005-2019
        •	AB-10004-2019
        •	AB-10005-2019
    */
    public static Integer defaultRegistrationNumber = 10000;
    public static void generateRegistrationNumber(List<Warranty__c> records) {
        List<Warranty__c> registrationRecords = new List<Warranty__c>();
        List<Id> contractorIds = new List<Id>();

        for (Warranty__c w : records) {
            if (!String.isBlank(w.Contractor__c) && String.isBlank(w.Warranty_Registration_Id__c)) {
                registrationRecords.add(w);
                contractorIds.add(w.Contractor__c);
            }
        }

        if (registrationRecords.isEmpty()) {
			return;
		}

        Map<Id, Account> accountMap = new Map<Id, Account>([SELECT Id, BillingStateCode FROM Account WHERE Id IN :contractorIds]);

        Map<String, Integer> sequenceMap = new Map<String, Integer>();
        for (AggregateResult ar : [
				SELECT Registration_Prefix__c, MAX(Sequence_Number__c)
				FROM Warranty__c
				WHERE Registration_Prefix__c <> NULL
				GROUP BY Registration_Prefix__c]) {
			sequenceMap.put(String.valueOf(ar.get('Registration_Prefix__c')), Integer.valueOf(ar.get('expr0')));
		}

        for (Warranty__c w : registrationRecords) {
            if (accountMap.get(w.Contractor__c) <> null && accountMap.get(w.Contractor__c).BillingStateCode <> null) {
                Integer currentSequence = (sequenceMap.get(w.Registration_Prefix__c) <> null) ?
                        sequenceMap.get(w.Registration_Prefix__c) + 1 :
                        WarrantyService.defaultRegistrationNumber;

                w.Sequence_Number__c = currentSequence;
                w.Warranty_Registration_Id__c = w.Registration_Prefix__c + '-' + w.Sequence_Number__c + '-' + Date.today().year();
                sequenceMap.put(w.Registration_Prefix__c, currentSequence);

            }
        }
    } // end generateRegistrationNumber method
    
    /* Ticket CLAIMSV2-624
     * Added conditions to display error Message when submitting record for Approval,
     * By: Anil Mannem (Incloud) on 12-May-2020
     */
    public static void validateApprovalSubmission(List<Warranty__c> warrantyList, Map<Id, Warranty__c> warrantyOldMap) {
        String errMsg = '';
        for(Warranty__c thisWarranty : warrantyList) {
            Warranty__c oldWarranty = warrantyOldMap.get(thisWarranty.id);
            if(thisWarranty.Warranty_Substatus__c == 'In Approval') {
                if(thisWarranty.Warranty_Status__c != 'In Progress') {
                    errMsg += System.Label.Approval_Warranty_Status;
                }
                if(thisWarranty.Warranty_Start_Date__c == NULL) {
                    errMsg += System.Label.Approval_Warranty_StartDate;
                }
                if(thisWarranty.Type__c == 'Labor & Membrane') {
                    if(oldWarranty.Warranty_Substatus__c != 'In Review') {
                        errMsg += System.Label.Approval_Labor_Membrane_Warranty_Substatus; 
                    }    
                }
                if(thisWarranty.Type__c == 'Diamond Shield') {
                    if(oldWarranty.Warranty_Substatus__c != 'Payment Received') {
                        errMsg += System.Label.Approval_DiamondShield_Warranty_Substatus;
                    }                
                    if(thisWarranty.Installation_Deficiency_Status__c != 'No Deficiencies' && thisWarranty.Installation_Deficiency_Status__c != 'Repairs Completed') {
                        errMsg += System.Label.Approval_Warranty_InstallationDeficiencyStatus;
                    }
                }
            }
            if(String.isNotBlank(errMsg)) {
                thisWarranty.addError(errMsg);
            }
        }
    } // end of validateApprovalSubmission
    
    
    //ClaimsV2-786
    //By Vicki Tran on July 15, 2020
    public static void UpdateWarrantyExpired (List<Warranty__c> records, Map<Id, Warranty__c> oldRecords)
    {
        Integer i = 0;
        for (Warranty__c w : records) {
            i++;
            if (w.Warranty_Expiry_Date__c != null && w.Warranty_Expiry_Date__c < Date.today())
            {
                w.Expired__c = 'Yes';
                w.Warranty_Expired_Date__c = string.valueofGmt(DateTime.now()) + '_' + string.valueOf(i);
            }
            else if (w.Warranty_Substatus__c == 'Not Issued')
            {
                w.Expired__c = 'Yes';
                w.Warranty_Expired_Date__c = string.valueofGmt(DateTime.now()) + '_' + string.valueOf(i);
            }
            else 
            {
                w.Expired__c = 'No';
                w.Warranty_Expired_Date__c = null;
            }
        }
    }

    
    
    
}