ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/To_Merge__c/To_Merge__c.object-meta.xml
<CustomObject>
    <description>TEMPORARY object. This will be deleted. I&apos;m just trying to write a script that helps me automate merging of accounts when there are large quantities.

2019-12-04 Skooter</description>
    <label>To Merge</label>
    <nameField>
        <label>To Merge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To Merge</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/To_Merge__c/fields/Duplicates__c.field-meta.xml
<CustomField>
    <fullName>Duplicates__c</fullName>
    <inlineHelpText>Comma separated list of duplicates.</inlineHelpText>
    <label>Duplicates</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/To_Merge__c/fields/Master__c.field-meta.xml
<CustomField>
    <fullName>Master__c</fullName>
    <inlineHelpText>The master account ID</inlineHelpText>
    <label>Master</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/Batch_MergeAccounts.cls
/* To Run

Batch_MergeAccounts foo = new Batch_MergeAccounts();
Id batchId = Database.executeBatch(foo, 10);

*/

global class Batch_MergeAccounts implements
    Database.Batchable<sObject>, Database.Stateful {
        
        global Database.QueryLocator start(Database.BatchableContext bc) {
            String q = 'SELECT Id, Master__c, Duplicates__c FROM To_Merge__c';
            
            return Database.getQueryLocator(q);
        }
        
        global void execute(Database.BatchableContext bc, List<To_Merge__c> scope) {
        for(To_Merge__c m : scope) {
            
            Account master = new Account();
                master.Id = m.Master__c;
            
            Account duplicate = new Account();
                duplicate.Id = m.Duplicates__c.trim();
            
            merge master duplicate;
        }

		delete scope;
        }
	
        global void finish(Database.BatchableContext bc) {
            // do nothing
        }
        
    }