ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/Bidder__c.object-meta.xml
<CustomObject>
    <description>This object is a junction object between Opportinity, Account and Account, where Account references are of record type US Distributor  and record type US Contractor.</description>
    <label>Bidder</label>
    <nameField>
        <displayFormat>Bid-{000000}</displayFormat>
        <label>Bidder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <description>Is the combination of the Opportunity ID + DistributorID + Contractor ID This field is not visible.</description>
    <label>Unique ID</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icTestHandlerBidder.cls
/**
 * Created by Anil Mannem (Incloud) on 31-July-2020
 */
@isTest
public with sharing class icTestHandlerBidder {

    static void initTest() {
        icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicBidder', new icLogicBidderMock());
        icTestMockUtilities.Tracer.SetReturnValue('icLogicBidderMock', 'getBidderInfo', new List<Bidder__c>());
    }

    @isTest
    static void test_onBeforeInsert(){
        initTest();

        icHandlerBidder.IClass handler = (icHandlerBidder.IClass) icObjectFactory.GetSingletonInstance('icHandlerBidder');

        List<Bidder__c> bidderList = new List<Bidder__c>();
        Bidder__c newBidder = new Bidder__c();
        newBidder.Unique_ID__c = '1';
        bidderList.add(NewBidder);
        try {
	        handler.onBeforeInsert(bidderList);
        } catch (Exception e) {            
        }
    }

    @isTest
    static void test_onBeforeUpdate(){
        initTest();

        icHandlerBidder.IClass handler = (icHandlerBidder.IClass) icObjectFactory.GetSingletonInstance('icHandlerBidder');

        List<Bidder__c> oldBidderList = new List<Bidder__c>();
        List<Bidder__c> newBidderList = new List<Bidder__c>();

        Bidder__c oldBidder = new Bidder__c();
        oldBidder.Unique_ID__c = '1';
        oldBidderList.add(oldBidder);
        Bidder__c newBidder = new Bidder__c();
        newBidder.Unique_ID__c = '123';
        newBidderList.add(newBidder);
        
        try {
	        handler.onBeforeUpdate(oldBidderList, newBidderList, new Map<Id, Bidder__c>());
        } catch (Exception e) {
            
        }

    }
}