ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/Bidder__c.object-meta.xml
<CustomObject>
    <description>This object is a junction object between Opportinity, Account and Account, where Account references are of record type US Distributor  and record type US Contractor.</description>
    <label>Bidder</label>
    <nameField>
        <displayFormat>Bid-{000000}</displayFormat>
        <label>Bidder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Contractor_Account__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the Contractorfield must be of type Contractor or  type US Contractor.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bidders (Contractor)</relationshipLabel>
    <relationshipName>Opportunity_Distributor_Contractor</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Distributor_Account__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the Distributor field must be of type Distributor or  type US Distributor.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Distributor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bidders (Distributor)</relationshipLabel>
    <relationshipName>Opportunity_Distributor_Contractor1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Opportunity Record Type should be US Sales Bid</errorMessage>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Sales Bid</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bidders</relationshipLabel>
    <relationshipName>Opportunity_Distributor_Contractor</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Contains the status of Opportunity Won or Loss to this Pair of Opportunity and Distributor</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <description>Is the combination of the Opportunity ID + DistributorID + Contractor ID This field is not visible.</description>
    <label>Unique ID</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Repository/Claims/force-app/main/default/classes/icRepoOpportunity.cls
public class icRepoOpportunity implements icIClass {

	public Object GetInstance() {
		return new Impl();
	}

	public Interface IClass {
		List<Opportunity> getCurrentOpportunitiesByAccountId(String recordId);
		Opportunity getOpportunityDataForGreenSky(Id opportunityId);
		List<Opportunity> getApprovedOpportunitiesByListID(Set<Id> opportunityIds, Id recordTypeId);
		List<Opportunity> getBidderForOpportunity(List<Id> opportunityIdList);
		List<Opportunity> getOpportunityByAccountsIdsIsClosedAndRecordTypeId(Set<Id> accountIds,Boolean isClosed,Id recordTypeId);
	}

	public class Impl implements IClass {

		public List<Opportunity> getCurrentOpportunitiesByAccountId(String recordId) {
			List<Opportunity> listOpportunities = new List<Opportunity>();
			listOpportunities =
					[SELECT Id
							,Name
					FROM	Opportunity
					WHERE	Contractor__c = :recordId
					AND 	IsClosed = false];
			return listOpportunities;
		}

		public Opportunity getOpportunityDataForGreenSky(Id opportunityId){

			Opportunity myOpp = new Opportunity();

			List<Opportunity> myOpps = new List<Opportunity>();
			myOpps = [
					SELECT 	Id,
							AccountId,
							Amount
					FROM 	Opportunity
					WHERE  	Id = :opportunityId
					LIMIT   1
			];

			if(!myOpps.isEmpty()){
				myOpp = myOpps[0];
			}

			return myOpp;
		}
		public List<Opportunity> getApprovedOpportunitiesByListID(Set<Id> opportunityIds, Id recordTypeId){
			return [SELECT 	Id							
					FROM 	Opportunity
					WHERE  	Id in :opportunityIds
							AND Quote_Approved__c = true
							AND RecordTypeId = :recordTypeId];
		}
        
        // Added by Anil Mannem
        public List<Opportunity> getBidderForOpportunity(List<Id> opportunityIdList){
            return [SELECT Id,
                           Final_Distributor__c,
                           Final_Contractor__c,
                           StageName,
                           Quote_Approved__c,
                           (SELECT Id,
                                   Status__c,
                                   Opportunity__c,
                                   Opportunity__r.Name,
                                   Distributor_Account__r.Name,
                                   Contractor_Account__r.Name,
                                   Unique_ID__c
                            FROM Opportunity_Distributor_Contractor__r)
                    FROM Opportunity 
                    WHERE Id IN :opportunityIdList];
		}
		
		public List<Opportunity> getOpportunityByAccountsIdsIsClosedAndRecordTypeId(Set<Id> accountIds,Boolean isClosed,Id recordTypeId){
			
			return  [SELECT Id, 
			        	Name, 
			        	AccountId, 
						Account.BillingCity, 
						Account.Name 
	 		        	FROM Opportunity 
	 		        WHERE AccountId IN :accountIds and 
						isClosed = :isClosed and 
						recordTypeId = :recordtypeId];
		}
	}
}