ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/Bidder__c.object-meta.xml
<CustomObject>
    <description>This object is a junction object between Opportinity, Account and Account, where Account references are of record type US Distributor  and record type US Contractor.</description>
    <label>Bidder</label>
    <nameField>
        <displayFormat>Bid-{000000}</displayFormat>
        <label>Bidder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Contractor_Account__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the Contractorfield must be of type Contractor or  type US Contractor.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bidders (Contractor)</relationshipLabel>
    <relationshipName>Opportunity_Distributor_Contractor</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Distributor_Account__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the Distributor field must be of type Distributor or  type US Distributor.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Distributor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bidders (Distributor)</relationshipLabel>
    <relationshipName>Opportunity_Distributor_Contractor1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Opportunity Record Type should be US Sales Bid</errorMessage>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Sales Bid</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bidders</relationshipLabel>
    <relationshipName>Opportunity_Distributor_Contractor</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/icBidderGeneratePDF.cls
public with sharing class icBidderGeneratePDF {
    static icLogicAttachment.IClass logicAttachment = (icLogicAttachment.IClass) icObjectFactory.GetSingletonInstance('icLogicAttachment');
    static icLogicOpportunity.IClass logicOpportunity = (icLogicOpportunity.IClass) icObjectFactory.GetSingletonInstance('icLogicOpportunity');
    static icLogicBidder.IClass logicBidder = (icLogicBidder.IClass) icObjectFactory.GetSingletonInstance('icLogicBidder');
    static icLogicEmail.IClass logicEmail = (icLogicEmail.IClass) icObjectFactory.GetSingletonInstance('icLogicEmail');

    @future(callout = true)
    public static void bidderOpportunityGeneratePDF(List<Id> opportunityIdList){
        List<Opportunity> opportunityList = logicOpportunity.getBidderForOpportunity(opportunityIdList);
        Blob pdfContent; 
        for(Opportunity thisOpportunity : opportunityList){
            for(Bidder__c thisBidder : thisOpportunity.Opportunity_Distributor_Contractor__r){
                String recordId = thisBidder.Id;
                PageReference thisPageReference = Page.US_Sales_Quote_PDF;
                thisPageReference.getParameters().put('bidderID', recordId);
                String fileTitle = '';
                if(thisBidder.Contractor_Account__r.Name == NULL) {
                    fileTitle = thisBidder.Opportunity__r.Name+' - '+thisBidder.Distributor_Account__r.Name+' - Quote.pdf';
                } else {
                    fileTitle = thisBidder.Opportunity__r.Name+' - '+thisBidder.Distributor_Account__r.Name+' - '+thisBidder.Contractor_Account__r.Name+' - Quote.pdf';
                }
                
                if (Test.isRunningTest()) {
                    pdfContent= Blob.valueof('Quote PDF');
                }
                else {
                    pdfContent = thisPageReference.getContentAsPDF();
                }
                logicAttachment.createDocumentInObject(recordId, fileTitle, fileTitle, pdfContent);
                pdfContent = null;
            }
        }
    }

    @future(callout = true)
    public static void bidderGeneratePDF(List<Id> bidderIdList){
        List<Bidder__c> bidderList = logicBidder.getBidderDetailsforPDFAutomation(bidderIdList);
        for(Bidder__c thisBidder : bidderList) {
            if(thisBidder.Opportunity__r.Quote_Approved__c) {
                String recordId = thisBidder.Id;
                PageReference thisPageReference = Page.US_Sales_Quote_PDF;
                thisPageReference.getParameters().put('bidderID', recordId);
                String fileTitle = '';
                if(thisBidder.Contractor_Account__r.Name == NULL) {
                    fileTitle = thisBidder.Opportunity__r.Name+' - '+thisBidder.Distributor_Account__r.Name+' - Quote.pdf';
                } else {
                    fileTitle = thisBidder.Opportunity__r.Name+' - '+thisBidder.Distributor_Account__r.Name+' - '+thisBidder.Contractor_Account__r.Name+' - Quote.pdf';
                }
                logicAttachment.createDocumentInObject(recordId, fileTitle, fileTitle, (Test.isRunningTest() ? Blob.valueof('Quote PDF') : thisPageReference.getContentAsPDF()));    
            }
        }
    }
}