ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/Bidder__c.object-meta.xml
<CustomObject>
    <description>This object is a junction object between Opportinity, Account and Account, where Account references are of record type US Distributor  and record type US Contractor.</description>
    <label>Bidder</label>
    <nameField>
        <displayFormat>Bid-{000000}</displayFormat>
        <label>Bidder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Contractor_Account__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the Contractorfield must be of type Contractor or  type US Contractor.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bidders (Contractor)</relationshipLabel>
    <relationshipName>Opportunity_Distributor_Contractor</relationshipName>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Distributor_Account__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account selected in the Distributor field must be of type Distributor or  type US Distributor.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Distributor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bidders (Distributor)</relationshipLabel>
    <relationshipName>Opportunity_Distributor_Contractor1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Opportunity Record Type should be US Sales Bid</errorMessage>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Sales Bid</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bidders</relationshipLabel>
    <relationshipName>Opportunity_Distributor_Contractor</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Bidder__c/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <description>Is the combination of the Opportunity ID + DistributorID + Contractor ID This field is not visible.</description>
    <label>Unique ID</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Repository/Claims/force-app/main/default/classes/icHandlerBidder.cls
public class icHandlerBidder implements icIClass {

	public Object GetInstance() {
		return new Impl();
	}

	public Interface IClass {
        void onBeforeInsert(List<Bidder__c> newBidders);
        void onBeforeUpdate(List<Bidder__c> oldBidders, List<Bidder__c> newBidders, Map<Id, Bidder__c> biddersMap);
        void onAfterInsert(List<Bidder__c> newBidders, Map<Id, Bidder__c> biddersMap);
    }

	public class Impl implements IClass {

		icLogicBidder.IClass logicBidder = (icLogicBidder.IClass) icObjectFactory.GetSingletonInstance('icLogicBidder');

		public void onBeforeInsert(List<Bidder__c> newBidders) {
            List<Bidder__c> bidderList = logicBidder.getBidderInfo();
            List<String> uniqueIdList = new List<String>();
            for (Bidder__c thisBidder : bidderList) {
                uniqueIdList.add(thisBidder.Unique_ID__c);
            }
            for (Bidder__c thisBidder : newBidders) {
                thisBidder.Unique_ID__c = thisBidder.Opportunity__c + '' +thisBidder.Distributor_Account__c + '' + thisBidder.Contractor_Account__c;
                Boolean result = uniqueIdList.contains(thisBidder.Unique_ID__c);
                if(result) {
                    thisBidder.addError(System.Label.icBidderPair);
                }
            }
        }

        public void onBeforeUpdate(List<Bidder__c> oldBidders, List<Bidder__c> newBidders, Map<Id, Bidder__c> biddersOldMap) {
            List<Bidder__c> bidderList = logicBidder.getBidderInfo();
            for (Bidder__c thisBidder : newBidders) {
                Bidder__c oldBidder = biddersOldMap.get(thisBidder.ID);
                thisBidder.Unique_ID__c = thisBidder.Opportunity__c + '' +thisBidder.Distributor_Account__c + '' + thisBidder.Contractor_Account__c;
                if(oldBidder.Unique_ID__c != thisBidder.Unique_ID__c) {
                    List<String> uniqueIdList = new List<String>();
                    for (Bidder__c thisBidderList : bidderList) {
                        uniqueIdList.add(thisBidderList.Unique_ID__c);
                    }
                    Boolean result = uniqueIdList.contains(thisBidder.Unique_ID__c);
                    if(result) {
                        thisBidder.addError(System.Label.icBidderPair);
                    }
                }
            }
        }

        public void onAfterInsert(List<Bidder__c> newBidders, Map<Id, Bidder__c> biddersMap){
            List<Id> bidderIdList = new List<Id>();
            for(Bidder__c thisBidder : newBidders){
                bidderIdList.add(thisBidder.Id);
            }
            if(!bidderIdList.isEmpty()){
                icBidderGeneratePDF.bidderGeneratePDF(bidderIdList);
            }
        }
    }
}