ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/Popup_notification__c.object-meta.xml
<CustomObject>
    <label>Popup notification</label>
    <nameField>
        <displayFormat>pop-{000000}</displayFormat>
        <label>Popup notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Popup notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_Notification_view__c/Popup_Notification_view__c.object-meta.xml
<CustomObject>
    <label>Popup Notification view</label>
    <nameField>
        <displayFormat>popv-{000000}</displayFormat>
        <label>Popup Notification View Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Popup Notification views</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_Notification_view__c/fields/Popup_notification__c.field-meta.xml
<CustomField>
    <fullName>Popup_notification__c</fullName>
    <label>Popup Notification</label>
    <referenceTo>Popup_notification__c</referenceTo>
    <relationshipLabel>Popup Notification Views</relationshipLabel>
    <relationshipName>Popup_Notification_views</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_Notification_view__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Popup_Notification_views</relationshipName>
    <type>Lookup</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/icTestRepoPopupNotificationView.cls
/**
 * Created by Francois Poirier on 2019-12-02.
 */

@isTest
public with sharing class icTestRepoPopupNotificationView {

    static icRepoPopupNotificationView.IClass repoPopupView = (icRepoPopupNotificationView.IClass) icObjectFactory.GetSingletonInstance('icRepoPopupNotificationView');

    @isTest
    static void testRepo(){

        Popup_notification__c popup = new Popup_notification__c();
        popup.Start_Date__c = Date.today();
        popup.End_Date__c = Date.today();
        popup.Active__c = true;
        insert popup;

        Popup_Notification_view__c popupView = new Popup_Notification_view__c();
        popupView.Popup_notification__c = popup.Id;
        popupView.User__c = UserInfo.getUserId();

        repoPopupView.savePopupNotificationView(popupView);

        Popup_Notification_view__c popupViewFromRepo = new Popup_Notification_view__c();

        popupViewFromRepo = repoPopupView.getViewsByNotificationAndUserIds(popup.Id, UserInfo.getUserId());

        system.assertEquals(popupView.Id, popupViewFromRepo.Id);

    }
}