ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/Popup_notification__c.object-meta.xml
<CustomObject>
    <label>Popup notification</label>
    <nameField>
        <displayFormat>pop-{000000}</displayFormat>
        <label>Popup notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Popup notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_Notification_view__c/Popup_Notification_view__c.object-meta.xml
<CustomObject>
    <label>Popup Notification view</label>
    <nameField>
        <displayFormat>popv-{000000}</displayFormat>
        <label>Popup Notification View Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Popup Notification views</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_Notification_view__c/fields/Do_not_show_again__c.field-meta.xml
<CustomField>
    <fullName>Do_not_show_again__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Show Again</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_Notification_view__c/fields/Number_of_views__c.field-meta.xml
<CustomField>
    <fullName>Number_of_views__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Views</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_Notification_view__c/fields/Popup_notification__c.field-meta.xml
<CustomField>
    <fullName>Popup_notification__c</fullName>
    <label>Popup Notification</label>
    <referenceTo>Popup_notification__c</referenceTo>
    <relationshipLabel>Popup Notification Views</relationshipLabel>
    <relationshipName>Popup_Notification_views</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_Notification_view__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Popup_Notification_views</relationshipName>
    <type>Lookup</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/icRepoPopupNotificationView.cls
/**
 * Created by Francois Poirier on 2019-11-29.
 */

public with sharing class icRepoPopupNotificationView implements icIClass {

    public Object GetInstance() {
        return new Impl();
    }

    public Interface IClass {

        Popup_Notification_view__c getViewsByNotificationAndUserIds(Id popupId, Id userId);
        void savePopupNotificationView(Popup_Notification_view__c popupView);

    }

    public class Impl implements IClass {

        public Popup_Notification_view__c getViewsByNotificationAndUserIds(Id popupId, Id userId){

            Popup_Notification_view__c popupView = new Popup_Notification_view__c();
            List<Popup_Notification_view__c> popupViews = new List<Popup_Notification_view__c>();

            popupViews = [
                    SELECT  Id,
                            Do_not_show_again__c,
                            Number_of_views__c
                    FROM    Popup_Notification_view__c
                    WHERE   Popup_notification__c = :popupId
                    AND     User__c = :userId
            ];

            if(popupViews.size()>0){
                popupView = popupViews[0];
            }

            return popupView;

        }

        public void savePopupNotificationView(Popup_Notification_view__c popupView){

            upsert popupView;

        }
    }

}