ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/Popup_notification__c.object-meta.xml
<CustomObject>
    <label>Popup notification</label>
    <nameField>
        <displayFormat>pop-{000000}</displayFormat>
        <label>Popup notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Popup notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/fields/Current__c.field-meta.xml
<CustomField>
    <fullName>Current__c</fullName>
    <formula>AND( Active__c , Start_Date__c &lt;=  TODAY(),  End_Date__c &gt;=  TODAY() )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/fields/English_Message_Rich__c.field-meta.xml
<CustomField>
    <fullName>English_Message_Rich__c</fullName>
    <label>English</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/fields/French_Message_Rich__c.field-meta.xml
<CustomField>
    <fullName>French_Message_Rich__c</fullName>
    <label>French</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/fields/Number_of_time_to_display__c.field-meta.xml
<CustomField>
    <fullName>Number_of_time_to_display__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Display Frequency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/fields/Spanish_Message_Rich__c.field-meta.xml
<CustomField>
    <fullName>Spanish_Message_Rich__c</fullName>
    <label>Spanish</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/icRepoPopupNotification.cls
/**
 * Created by Francois Poirier on 2019-11-29.
 */

public with sharing class icRepoPopupNotification  implements icIClass {

    public Object GetInstance() {
        return new Impl();
    }

    public Interface IClass {

        Popup_notification__c getCurrentPopup();
        Popup_notification__c getCurrentPopupByTag(String tag);

    }

    public class Impl implements IClass {

        public Popup_notification__c getCurrentPopup(){

            List<Popup_notification__c> popupNotifications = new List<Popup_notification__c>();
            Popup_notification__c popupNotification = new Popup_notification__c();

            popupNotifications = [
                    SELECT  Id,
                            Active__c,
                            End_Date__c,
                            English_message_Rich__c,
                            French_message_Rich__c,
                            Number_of_time_to_display__c,
                            Start_Date__c,
                            Spanish_message_Rich__c
                    FROM    Popup_notification__c
                    WHERE   Current__c = true
            ];

            if(popupNotifications.size()>0){
                popupNotification = popupNotifications[0];
            }

            return popupNotification;

        }

        public Popup_notification__c getCurrentPopupByTag(String tag){

            List<Popup_notification__c> popupNotifications = new List<Popup_notification__c>();
            Popup_notification__c popupNotification = new Popup_notification__c();

            popupNotifications = [
                    SELECT  Id,
                            Active__c,
                            End_Date__c,
                            English_message_Rich__c,
                            French_message_Rich__c,
                            Number_of_time_to_display__c,
                            Start_Date__c,
                            Spanish_message_Rich__c
                    FROM    Popup_notification__c
                    WHERE   Current__c = true
                    AND     Tag__c = :tag
            ];

            if(popupNotifications.size()>0){
                popupNotification = popupNotifications[0];
            }

            return popupNotification;

        }
    }

}