ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/Popup_notification__c.object-meta.xml
<CustomObject>
    <label>Popup notification</label>
    <nameField>
        <displayFormat>pop-{000000}</displayFormat>
        <label>Popup notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Popup notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/fields/English_message__c.field-meta.xml
<CustomField>
    <fullName>English_message__c</fullName>
    <label>English message</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/fields/French_message__c.field-meta.xml
<CustomField>
    <fullName>French_message__c</fullName>
    <label>French message</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/fields/Number_of_time_to_display__c.field-meta.xml
<CustomField>
    <fullName>Number_of_time_to_display__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Display Frequency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/fields/Spanish_message__c.field-meta.xml
<CustomField>
    <fullName>Spanish_message__c</fullName>
    <label>Spanish message</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_Notification_view__c/Popup_Notification_view__c.object-meta.xml
<CustomObject>
    <label>Popup Notification view</label>
    <nameField>
        <displayFormat>popv-{000000}</displayFormat>
        <label>Popup Notification View Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Popup Notification views</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_Notification_view__c/fields/Number_of_views__c.field-meta.xml
<CustomField>
    <fullName>Number_of_views__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Views</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_Notification_view__c/fields/Popup_notification__c.field-meta.xml
<CustomField>
    <fullName>Popup_notification__c</fullName>
    <label>Popup Notification</label>
    <referenceTo>Popup_notification__c</referenceTo>
    <relationshipLabel>Popup Notification Views</relationshipLabel>
    <relationshipName>Popup_Notification_views</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

Repository/Claims/force-app/main/default/classes/icTestCtrlPopupNotification.cls
/**
 * Created by Francois Poirier on 2019-12-02.
 */

@isTest
public with sharing class icTestCtrlPopupNotification {

    @isTest
    static void testGetPopupNotification(){

        icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicPopupNotification', new icLogicPopupNotificationMock());
        icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicPopupNotificationView', new icLogicPopupNotificationViewMock());
        icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicUser', new icLogicUserMock());

        User testUser = new User();

        testUser.Id = icTestHelperUtility.getFakeId(User.SObjectType);

        icTestMockUtilities.Tracer.SetReturnValue('icLogicUserMock', 'getUserAndAccountFromPartnerUser', testUser);

        Popup_notification__c popup = new Popup_notification__c();
        popup.Start_Date__c = Date.today();
        popup.End_Date__c = Date.today();
        popup.Active__c = true;
        popup.Number_of_time_to_display__c = 10;
        popup.English_message__c = icTestHelperUtility.generateRandomString(20);
        popup.French_message__c = icTestHelperUtility.generateRandomString(20);
        popup.Spanish_message__c = icTestHelperUtility.generateRandomString(20);
        popup.Id = icTestHelperUtility.getFakeId(Popup_Notification__c.SObjectType);
        String myTag = icTestHelperUtility.generateRandomString(5);
        popup.Tag__c = myTag;


        icTestMockUtilities.Tracer.SetReturnValue('icLogicPopupNotificationMock', 'getCurrentPopup', popup);
        icTestMockUtilities.Tracer.SetReturnValue('icLogicPopupNotificationMock', 'getCurrentPopupByTag', popup);

        //test null number of views & English message
        icTestMockUtilities.Tracer.SetReturnValue('icLogicPopupNotificationViewMock', 'getViewsByNotificationAndUserIds', new Popup_Notification_view__c());
        testUser.ROOFPRO_Portal_Language__c = 'English';

        icCtrlPopupNotification.getPopupNotification();
        icCtrlPopupNotification.getPopupNotificationByTag(myTag);

        //test valid number pf views & French message
        Popup_Notification_view__c popupView = new Popup_Notification_view__c();
        popupView.Number_of_views__c = 1;

        icTestMockUtilities.Tracer.SetReturnValue('icLogicPopupNotificationViewMock', 'getViewsByNotificationAndUserIds', popupView);
        testUser.ROOFPRO_Portal_Language__c = 'Quebec French';
        icCtrlPopupNotification.getPopupNotification();

        //test Spanish message
        testUser.ROOFPRO_Portal_Language__c = 'Spanish';
        icCtrlPopupNotification.getPopupNotification();

    }

    @isTest
    static void testStopShowingPopupNotification(){

        icTestMockUtilities.Mocker.SetMockSingletonInstance('icLogicPopupNotificationView', new icLogicPopupNotificationViewMock());

        icCtrlPopupNotification.stopShowingPopupNotification(icTestHelperUtility.getFakeId(Popup_Notification_view__c.SObjectType));
        
    }

}