ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/Popup_notification__c.object-meta.xml
<CustomObject>
    <label>Popup notification</label>
    <nameField>
        <displayFormat>pop-{000000}</displayFormat>
        <label>Popup notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Popup notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/fields/English_Message_Rich__c.field-meta.xml
<CustomField>
    <fullName>English_Message_Rich__c</fullName>
    <label>English</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/fields/French_Message_Rich__c.field-meta.xml
<CustomField>
    <fullName>French_Message_Rich__c</fullName>
    <label>French</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/fields/Number_of_time_to_display__c.field-meta.xml
<CustomField>
    <fullName>Number_of_time_to_display__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Display Frequency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/fields/Spanish_Message_Rich__c.field-meta.xml
<CustomField>
    <fullName>Spanish_Message_Rich__c</fullName>
    <label>Spanish</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_Notification_view__c/Popup_Notification_view__c.object-meta.xml
<CustomObject>
    <label>Popup Notification view</label>
    <nameField>
        <displayFormat>popv-{000000}</displayFormat>
        <label>Popup Notification View Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Popup Notification views</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_Notification_view__c/fields/Do_not_show_again__c.field-meta.xml
<CustomField>
    <fullName>Do_not_show_again__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Show Again</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_Notification_view__c/fields/Number_of_views__c.field-meta.xml
<CustomField>
    <fullName>Number_of_views__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Views</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_Notification_view__c/fields/Popup_notification__c.field-meta.xml
<CustomField>
    <fullName>Popup_notification__c</fullName>
    <label>Popup Notification</label>
    <referenceTo>Popup_notification__c</referenceTo>
    <relationshipLabel>Popup Notification Views</relationshipLabel>
    <relationshipName>Popup_Notification_views</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_Notification_view__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Popup_Notification_views</relationshipName>
    <type>Lookup</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/icCtrlPopupNotification.cls
/**
 * Created by Francois Poirier on 2019-11-29.
 */

global with sharing class icCtrlPopupNotification {


    static icLogicPopupNotification.IClass logicPopupNotifcation = (icLogicPopupNotification.IClass) icObjectFactory.GetSingletonInstance('icLogicPopupNotification');
    static icLogicPopupNotificationView.IClass logicPopupNotifcationView = (icLogicPopupNotificationView.IClass) icObjectFactory.GetSingletonInstance('icLogicPopupNotificationView');
    static icLogicUser.IClass logicUser = (icLogicUser.IClass) icObjectFactory.GetSingletonInstance('icLogicUser');

    @AuraEnabled global static icDtoPopupNotification getPopupNotification(){

        icDtoPopupNotification dtoNotification = new icDtoPopupNotification();

        Popup_notification__c notification = new Popup_notification__c();

        notification = logicPopupNotifcation.getCurrentPopup();
        system.debug('notification ====> ' + notification);

        dtoNotification = validateNofication(notification);

        return dtoNotification;

    }

    @AuraEnabled global static icDtoPopupNotification getPopupNotificationByTag(String tag){

        icDtoPopupNotification dtoNotification = new icDtoPopupNotification();

        Popup_notification__c notification = new Popup_notification__c();

        system.debug('tag ===> ' + tag);
        notification = logicPopupNotifcation.getCurrentPopupByTag(tag);
        system.debug('notification ====> ' + notification);

        dtoNotification = validateNofication(notification);

        return dtoNotification;

    }

    @AuraEnabled global static void stopShowingPopupNotification(String notificationViewId){

        Popup_Notification_view__c popupNotificationView = new Popup_Notification_view__c();
        popupNotificationView.Id = notificationViewId;
        popupNotificationView.Do_not_show_again__c = true;
        logicPopupNotifcationView.savePopupNotificationView(popupNotificationView);

    }


    private static icDtoPopupNotification validateNofication(Popup_notification__c notification){
        icDtoPopupNotification dtoNotification = new icDtoPopupNotification();
        dtoNotification.showMessage = false;


        Popup_Notification_view__c notificationView = new Popup_Notification_view__c();
        User currentUser = new User();

        currentUser = logicUser.getUserAndAccountFromPartnerUser(UserInfo.getUserId());
        system.debug('current user ====> ' + currentUser);
        //currentUser = logicUser.getUserAndAccountFromPartnerUser('0051F000004sBhR');

        if(String.isNotBlank(notification.Id)){
            notificationView = logicPopupNotifcationView.getViewsByNotificationAndUserIds(notification.Id, currentUser.Id);
            if(notificationView.Number_of_views__c == null) {
                notificationView.Number_of_views__c = 0;
                notificationView.Popup_notification__c = notification.Id;
                notificationView.User__c = currentUser.Id;
                notificationView.Do_not_show_again__c = false;
            }
            notificationView.Number_of_views__c ++;

            if (notificationView.Number_of_views__c <= notification.Number_of_time_to_display__c && !notificationView.Do_not_show_again__c) {
                dtoNotification.showMessage = true;

                logicPopupNotifcationView.savePopupNotificationView(notificationView);

                dtoNotification.notificationViewId = notificationView.Id;

                if (currentUser.ROOFPRO_Portal_Language__c == 'English') {

                    dtoNotification.message = notification.English_Message_Rich__c;

                }
                if (currentUser.ROOFPRO_Portal_Language__c == 'Quebec French') {

                    dtoNotification.message = notification.French_Message_Rich__c;

                }

                if (currentUser.ROOFPRO_Portal_Language__c == 'Spanish') {

                    dtoNotification.message = notification.Spanish_Message_Rich__c;

                }

            }

        }

        return dtoNotification;
    }
}