ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_notification__c/Popup_notification__c.object-meta.xml
<CustomObject>
    <label>Popup notification</label>
    <nameField>
        <displayFormat>pop-{000000}</displayFormat>
        <label>Popup notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Popup notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_Notification_view__c/Popup_Notification_view__c.object-meta.xml
<CustomObject>
    <label>Popup Notification view</label>
    <nameField>
        <displayFormat>popv-{000000}</displayFormat>
        <label>Popup Notification View Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Popup Notification views</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/Popup_Notification_view__c/fields/Popup_notification__c.field-meta.xml
<CustomField>
    <fullName>Popup_notification__c</fullName>
    <label>Popup Notification</label>
    <referenceTo>Popup_notification__c</referenceTo>
    <relationshipLabel>Popup Notification Views</relationshipLabel>
    <relationshipName>Popup_Notification_views</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

Repository/Claims/force-app/main/default/classes/icTestLogicPopupNotificationView.cls
/**
 * Created by Francois Poirier on 2019-12-02.
 */

@isTest
public with sharing class icTestLogicPopupNotificationView {

    @isTest
    static void testGetViewsByNotificationAndUserIds(){

        icTestMockUtilities.Mocker.SetMockSingletonInstance('icRepoPopupNotificationView', new icRepoPopupNotificationViewMock());
        icLogicPopupNotificationView.IClass logicPopupView = (icLogicPopupNotificationView.IClass) icObjectFactory.GetSingletonInstance('icLogicPopupNotificationView');

        icTestMockUtilities.Tracer.SetReturnValue('icRepoPopupNotificationViewMock', 'getViewsByNotificationAndUserIds', new Popup_Notification_view__c());

        Popup_Notification_view__c popupView = new Popup_Notification_view__c();

        popupView = logicPopupView.getViewsByNotificationAndUserIds(icTestHelperUtility.getFakeId(Popup_Notification__c.SObjectType), UserInfo.getUserId());

    }

    @isTest
    static void testSavePopupNotificationView(){

        icTestMockUtilities.Mocker.SetMockSingletonInstance('icRepoPopupNotificationView', new icRepoPopupNotificationViewMock());
        icLogicPopupNotificationView.IClass logicPopupView = (icLogicPopupNotificationView.IClass) icObjectFactory.GetSingletonInstance('icLogicPopupNotificationView');
        Popup_Notification_view__c popupView = new Popup_Notification_view__c();

        logicPopupView.savePopupNotificationView(popupView);

    }
}