ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/EU_Open_Order__c.object-meta.xml
<CustomObject>
    <label>Open Order</label>
    <nameField>
        <displayFormat>OO-{YYYY}-{0000000}</displayFormat>
        <label>Open Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Open_Order__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Order__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Open Order</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/EU_Open_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Open Order Line</label>
    <nameField>
        <displayFormat>OOL-{YYYY}-{0000000}</displayFormat>
        <label>Open Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Open_Order__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Order__c</fullName>
    <label>Open Order</label>
    <referenceTo>EU_Open_Order__c</referenceTo>
    <relationshipLabel>Open Order Lines</relationshipLabel>
    <relationshipName>Open_Order_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/OrderLineTriggerHandler.cls
/**
 * Created by Gerard van Kempen on 2019-12-11.
 * 2019 (C) 4C NV, Mechelen Belgium.
 * Last modified as part of project 'IKO SFDC'.
 */

public with sharing class OrderLineTriggerHandler extends TriggerHandler {

    protected override void onBeforeInsert(List<SObject> newList) {
        List<EU_Open_Order_Line__c> newOrderLines = (List<EU_Open_Order_Line__c>)newList;

        OrderLineTriggerHandlerFunctions.mapOrderLinesToOrders(newOrderLines);
    }

    protected override void onBeforeUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
        Map<Id, EU_Open_Order_Line__c> newOrderLineMap = (Map<Id, EU_Open_Order_Line__c>)newMap;
        Map<Id, EU_Open_Order_Line__c> oldOrderLineMap = (Map<Id, EU_Open_Order_Line__c>)oldMap;

        List<EU_Open_Order_Line__c> orderLinesToBeMatched = OrderLineTriggerHandlerFunctions.filterOrderLinesToMap(newOrderLineMap, oldOrderLineMap);

        OrderLineTriggerHandlerFunctions.mapOrderLinesToOrders(orderLinesToBeMatched);
    }

    protected override void onAfterUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
        Map<Id, EU_Open_Order_Line__c> newOrderLineMap = (Map<Id, EU_Open_Order_Line__c>)newMap;
        Map<Id, EU_Open_Order_Line__c> oldOrderLineMap = (Map<Id, EU_Open_Order_Line__c>)oldMap;

        List<EU_Open_Order__c> ordersToClose = OrderLineTriggerHandlerFunctions.findOrdersToCloseBasedOnOrderLines(newOrderLineMap);

        // update the queued orders if there are any
        if(!ordersToClose.isEmpty()) {
            update ordersToClose;
        }
    }

}