ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/EU_Open_Order__c.object-meta.xml
<CustomObject>
    <label>Open Order</label>
    <nameField>
        <displayFormat>OO-{YYYY}-{0000000}</displayFormat>
        <label>Open Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Account__c.field-meta.xml
<CustomField>
    <fullName>EU_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Open Orders</relationshipLabel>
    <relationshipName>Open_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Open_Order__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Order__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Open Order</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Open_Order_Value__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Order_Value__c</fullName>
    <label>Open Order Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Order_number_Reference__c.field-meta.xml
<CustomField>
    <fullName>EU_Order_number_Reference__c</fullName>
    <label>Order number Reference</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>EU_Order_Type__c</fullName>
    <label>Order Type</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Project_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Project_Number__c</fullName>
    <label>Project Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Purchase_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Purchase_Order_Number__c</fullName>
    <label>Purchase Order Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Request_Date__c.field-meta.xml
<CustomField>
    <fullName>EU_Request_Date__c</fullName>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Total_Order_Value__c.field-meta.xml
<CustomField>
    <fullName>EU_Total_Order_Value__c</fullName>
    <label>Total Order Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/EU_Open_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Open Order Line</label>
    <nameField>
        <displayFormat>OOL-{YYYY}-{0000000}</displayFormat>
        <label>Open Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Account__c.field-meta.xml
<CustomField>
    <fullName>EU_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Open Order Lines</relationshipLabel>
    <relationshipName>Open_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Extended_Price__c.field-meta.xml
<CustomField>
    <fullName>EU_Extended_Price__c</fullName>
    <label>Extended Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Header_Open_Order__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Open_Order__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Open Order</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Header_Open_Order_Value__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Open_Order_Value__c</fullName>
    <label>Open Order Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Header_Order_Creation_Date__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Order_Creation_Date__c</fullName>
    <label>Order Creation Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Header_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Order_Number__c</fullName>
    <label>Order Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Header_Order_Number_Reference__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Order_Number_Reference__c</fullName>
    <label>Order Number Reference</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Header_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Order_Type__c</fullName>
    <label>Order Type</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Header_Project_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Project_Number__c</fullName>
    <label>Project Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Header_Purchase_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Purchase_Order_Number__c</fullName>
    <label>Purchase Order Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Header_Request_Date__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Request_Date__c</fullName>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Header_Total_Order_Value__c.field-meta.xml
<CustomField>
    <fullName>EU_Header_Total_Order_Value__c</fullName>
    <label>Total Order Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Item__c.field-meta.xml
<CustomField>
    <fullName>EU_Item__c</fullName>
    <label>Item</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Item_Description__c.field-meta.xml
<CustomField>
    <fullName>EU_Item_Description__c</fullName>
    <label>Item Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Open_Order__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Order__c</fullName>
    <label>Open Order</label>
    <referenceTo>EU_Open_Order__c</referenceTo>
    <relationshipLabel>Open Order Lines</relationshipLabel>
    <relationshipName>Open_Order_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Open_Order_Line_Numer__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Order_Line_Numer__c</fullName>
    <label>Open Order Line Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Open_Quantity__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Quantity__c</fullName>
    <label>Open Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>EU_Order_Line__c</fullName>
    <label>Order Line</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Order_UM__c.field-meta.xml
<CustomField>
    <fullName>EU_Order_UM__c</fullName>
    <label>Order UM</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Price_Order_UM__c.field-meta.xml
<CustomField>
    <fullName>EU_Price_Order_UM__c</fullName>
    <label>Price Order UM</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order_Line__c/fields/EU_Source_System__c.field-meta.xml
<CustomField>
    <fullName>EU_Source_System__c</fullName>
    <label>Source System</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/classes/OrderServicesTestComponentFactory.cls
/**
 * Created by Gerard van Kempen on 2019-12-11.
 * 2019 (C) 4C NV, Mechelen Belgium.
 * Last modified as part of project 'IKO SFDC'.
 * Modified by Rudi Vermeulen on 2020-12-03: Included new field EU_Header_Order_Creation_Date__c
 */

/**
* @author Gerard van Kempen, 4C NV
* @date 2019
*
* @group Integration Services
*
* @description OrderServicesTestComponentFactory aids in the generation of test objects.
*/

@IsTest
public with sharing class OrderServicesTestComponentFactory {
    public class OrderLineTestingTuple {
        public final EU_Open_Order_Line__c referenceOrderLine;
        public EU_Open_Order_Line__c workingOrderLine;
        public OrderLineTestingTuple(EU_Open_Order_Line__c orderLine) {
            this.referenceOrderLine = orderLine.clone();
            this.workingOrderLine = orderLine.clone();
        }
    }

    public class OrderTestingTuple {
        public final EU_Open_Order__c referenceOrder;
        public EU_Open_Order__c workingOrder;
        public OrderTestingTuple(EU_Open_Order__c order) {
            this.referenceOrder = order.clone();
            this.workingOrder = order.clone();
        }
    }

    private static String newRandomString(Integer length) {
        Blob blobKey = Crypto.generateAesKey(128);
        String key = EncodingUtil.convertToHex(blobKey);
        return key.substring(0,length);
    }

    /*******************************************************************************************************************
    * @description Generate a fully populated EU_Open_Order_Line__c object wrapped in a testing tuple.
    * @param invoiceNumber a dummy order number, not null
    * @param dueValue a dummy due value, not null
    * @param acct a dummy account (may be null)
    * @return an OrderLineTestingTuple setup using the provided values, and some random values as to avoid collisions
    * @example
    * orderLineTestingTuple orderLineTT = OrderServicesTestComponentFactory.newInvoiceLineTestingTuple(orderNumber, dueValue, acct);
    */

    public static OrderLineTestingTuple newOrderLineTestingTuple(String invoiceNumber, Decimal dueValue, Account acct) {
        EU_Open_Order_Line__c orderLine = new EU_Open_Order_Line__c();
        if(acct != null) {
            orderLine.EU_Account__c = acct.Id;
        }
        orderLine.CurrencyIsoCode = 'EUR';
//        orderLine.EU_ERP_External_Id__c = newRandomString(32);
        orderLine.EU_Extended_Price__c = Math.round(dueValue);
        orderLine.EU_Item__c = newRandomString(25);
        orderLine.EU_Item_Description__c = newRandomString(32);
        orderLine.EU_Header_Open_Order__c = true;
//        orderLine.EU_Open_Order__c = null;
        orderLine.EU_Open_Order_Line_Numer__c = newRandomString(10);
        orderLine.EU_Header_Open_Order_Value__c = Math.round(dueValue * 1.2);
        orderLine.EU_Open_Quantity__c = Math.round(dueValue * 0.7);
        orderLine.EU_Order_Line__c = newRandomString(5);
        orderLine.EU_Header_Order_Number__c = invoiceNumber;
        orderLine.EU_Header_Order_Number_Reference__c = newRandomString(15);
        orderLine.EU_Header_Order_Type__c = newRandomString(5);
        orderLine.EU_Order_UM__c = newRandomString(3);
        orderLine.EU_Price_Order_UM__c = Math.round(dueValue * 0.87);
        orderLine.EU_Header_Project_Number__c = newRandomString(15);
        orderLine.EU_Header_Purchase_Order_Number__c = newRandomString(25);
        orderLine.EU_Header_Request_Date__c = Date.today();
        orderLine.EU_Source_System__c = newRandomString(30);
        orderLine.EU_Header_Total_Order_Value__c = Math.round(dueValue * 2.1);
        orderLine.EU_Header_Order_Creation_Date__c = Date.today();
        
        return new OrderLineTestingTuple(orderLine);
    }

    /*******************************************************************************************************************
    * @description Generate a fully populated EU_Open_Order_Line__c object wrapped in a testing tuple.
    * @param dueValue a dummy due value, not null
    * @param acct a dummy account (may be null)
    * @return an OrderLineTestingTuple setup using the provided values, and some random values as to avoid collisions
    * @example
    * orderLineTestingTuple orderLineTT = OrderServicesTestComponentFactory.newInvoiceLineTestingTuple(orderNumber, dueValue, acct);
    */

    public static OrderLineTestingTuple newOrderLineTestingTuple(Decimal dueValue, Account acct) {
        return newOrderLineTestingTuple(newRandomString(9), dueValue, acct);
    }

    /*******************************************************************************************************************
    * @description Generate a fully populated EU_Open_Order_Line__c object wrapped in a testing tuple.
    * @param acct a dummy account (may be null)
    * @return an OrderLineTestingTuple setup using the provided values, and some random values as to avoid collisions
    * @example
    * orderLineTestingTuple orderLineTT = OrderServicesTestComponentFactory.newInvoiceLineTestingTuple(orderNumber, dueValue, acct);
    */

    public static OrderLineTestingTuple newOrderLineTestingTuple(Account acct) {
        return newOrderLineTestingTuple(1324.65, acct);
    }

    /*******************************************************************************************************************
    * @description Generate a fully populated EU_Open_Order_Line__c object wrapped in a testing tuple.
    * @return an OrderLineTestingTuple setup using the provided values, and some random values as to avoid collisions
    * @example
    * orderLineTestingTuple orderLineTT = OrderServicesTestComponentFactory.newInvoiceLineTestingTuple(orderNumber, dueValue, acct);
    */

    public static OrderLineTestingTuple newOrderLineTestingTuple() {
        return newOrderLineTestingTuple(null);
    }

    /*******************************************************************************************************************
    * @description Generate a fully populated EU_Open_Order__c object wrapped in a testing tuple.
    * @param orderNumber a dummy order number, not null
    * @param dueValue a dummy due value, not null
    * @param acct a dummy account (may be null)
    * @return an OrderTestingTuple setup using the provided values, and some random values as to avoid collisions
    * @example
    * OrderTestingTuple orderTT = OrderServicesTestComponentFactory.newOrderTestingTuple(orderNumber, dueValue, acct);
    */

    public static OrderTestingTuple newOrderTestingTuple(String orderNumber, Decimal dueValue, Account acct) {
        EU_Open_Order__c order = new EU_Open_Order__c();
        if(acct != null) {
            order.EU_Account__c = acct.Id;
        }
        order.CurrencyIsoCode = 'EUR';
        order.EU_Open_Order__c = true;
        order.EU_Open_Order_Value__c = Math.round(dueValue);
        order.EU_Order_Number__c = orderNumber;
        order.EU_Order_number_Reference__c = newRandomString(15);
        order.EU_Order_Type__c = newRandomString(5);
        order.EU_Project_Number__c = newRandomString(15);
        order.EU_Purchase_Order_Number__c = newRandomString(25);
        order.EU_Request_Date__c = Date.today();
        order.EU_Total_Order_Value__c = Math.round(dueValue * 2.1);

        return new OrderTestingTuple(order);
    }

    /*******************************************************************************************************************
    * @description Generate a fully populated EU_Open_Order__c object wrapped in a testing tuple.
    * @param dueValue a dummy due value, not null
    * @param acct a dummy account (may be null)
    * @return an OrderTestingTuple setup using the provided values, and some random values as to avoid collisions
    * @example
    * OrderTestingTuple orderTT = OrderServicesTestComponentFactory.newOrderTestingTuple(orderNumber, dueValue, acct);
    */

    public static OrderTestingTuple newOrderTestingTuple(Decimal dueValue, Account acct) {
        return newOrderTestingTuple(newRandomString(9), dueValue, acct);
    }

    /*******************************************************************************************************************
    * @description Generate a fully populated EU_Open_Order__c object wrapped in a testing tuple.
    * @param acct a dummy account (may be null)
    * @return an OrderTestingTuple setup using the provided values, and some random values as to avoid collisions
    * @example
    * OrderTestingTuple orderTT = OrderServicesTestComponentFactory.newOrderTestingTuple(orderNumber, dueValue, acct);
    */

    public static OrderTestingTuple newOrderTestingTuple(Account acct) {
        return newOrderTestingTuple(1324.65, acct);
    }

    /*******************************************************************************************************************
    * @description Generate a fully populated EU_Open_Order__c object wrapped in a testing tuple.
    * @return an OrderTestingTuple setup using the provided values, and some random values as to avoid collisions
    * @example
    * OrderTestingTuple orderTT = OrderServicesTestComponentFactory.newOrderTestingTuple(orderNumber, dueValue, acct);
    */

    public static OrderTestingTuple newOrderTestingTuple() {
        return newOrderTestingTuple(null);
    }
}