ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/EU_Open_Order__c.object-meta.xml
<CustomObject>
    <label>Open Order</label>
    <nameField>
        <displayFormat>OO-{YYYY}-{0000000}</displayFormat>
        <label>Open Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Account__c.field-meta.xml
<CustomField>
    <fullName>EU_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Open Orders</relationshipLabel>
    <relationshipName>Open_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Open_Order__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Order__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Open Order</label>
    <type>Checkbox</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Open_Order_Value__c.field-meta.xml
<CustomField>
    <fullName>EU_Open_Order_Value__c</fullName>
    <label>Open Order Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Order_number_Reference__c.field-meta.xml
<CustomField>
    <fullName>EU_Order_number_Reference__c</fullName>
    <label>Order number Reference</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>EU_Order_Type__c</fullName>
    <label>Order Type</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Project_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Project_Number__c</fullName>
    <label>Project Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Purchase_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>EU_Purchase_Order_Number__c</fullName>
    <label>Purchase Order Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Request_Date__c.field-meta.xml
<CustomField>
    <fullName>EU_Request_Date__c</fullName>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

ClaimsAndWarranty_ClaimsDev/WarrantyAndClaims_ClaimsDev/force-app/main/default/objects/EU_Open_Order__c/fields/EU_Total_Order_Value__c.field-meta.xml
<CustomField>
    <fullName>EU_Total_Order_Value__c</fullName>
    <label>Total Order Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Repository/Claims/force-app/main/default/classes/OrderSelector.cls
/**
 * Created by Gerard van Kempen on 2019-12-06.
 * 2019 (C) 4C NV, Mechelen Belgium.
 * Last modified as part of project 'IKO SFDC'.
 */

/**
* @author Gerard van Kempen, 4C NV
* @date 2019
*
* @group Integration Services
*
* @description OrderSelector provides methods to retrieve EU_Open_Order__c objects based on parameters.
*/

public class OrderSelector {

    /*******************************************************************************************************************
    * @description Retrieve Open Orders for given Order Numbers.
    * @param orderNumbers a Set of Strings containing Order Numbers
    * @return a List of Open Orders with matching Order Numbers
    * @example
    * List<EU_Open_Order__c> matchingOrders = (new OrderSelector()).getOrdersForOrderNumbers(orderNumbers);
    */

    public List<EU_Open_Order__c> getOrdersForOrderNumbers(Set<String> orderNumbers, Set<Id> accountIds) {
        List<EU_Open_Order__c> ordersForOrderNumbers = null;
        try {
            ordersForOrderNumbers = [
                    SELECT EU_Account__c, CreatedById, CurrencyIsoCode, LastModifiedById,
                            EU_Open_Order__c, Name, EU_Open_Order_Value__c, EU_Order_Number__c,
                            EU_Order_number_Reference__c, EU_Order_Type__c, EU_Project_Number__c,
                            EU_Purchase_Order_Number__c, EU_Request_Date__c, EU_Total_Order_Value__c
                    FROM EU_Open_Order__c
                    WHERE EU_Order_Number__c IN :orderNumbers AND EU_Account__c IN :accountIds
            ];
        } catch (Exception e) {
            System.debug(LoggingLevel.WARN, e.getMessage());
            ordersForOrderNumbers = new List<EU_Open_Order__c>();
        }

        if(ordersForOrderNumbers.isEmpty()) {System.debug(LoggingLevel.WARN, 'could not find any orders');}

        return ordersForOrderNumbers;
    }
}